### ISSUE TITLE
non-pointer struct kernel arguments fail due to varying ABIs

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#1]
pocl assumes the kernels arguments are mapped as they are in sources. Structs are problematic as different ABIs map them differently. E.g. on AMD64/Linux it seems to split the struct to two integers some times which causes the kernel launching to fail as it maps the arguments to wrong positions.

This is not trivial to fix. Some possibilities:
- force the kernel ABI to be fixed at Clang side
- create a more sophisticated work group launcher that converts from the pocl argument table to the correct types and then calls the kernel with the correct ABI

The first is cleaner but possibly hard to get through.

https://bugs.launchpad.net/pocl/+bug/987905

**Comment by pjaaskel** [comment]
libffi might be useful for this long standing issue.  https://github.com/atgreen/libffi/blob/master/doc/libffi.texi

**Comment by pjaaskel** [comment]
@inducer please try the Clang patch https://raw.githubusercontent.com/pocl/pocl/c9ae29f2268d3b92462d6ca97d1d596dae0d15a1/tools/patches/clang-3.9-always-spir-cc-for-kernels.patch which should fix the long standing issue of passing aggregates by value and see if it fixes any of the pyopencl regressions. Ping @tom-gall

**Comment by inducer** [comment]
cc @mattwala

**Comment by inducer** [comment]
This is fine now.

Test case (from PyOpenCL tests):
```
PYOPENCL_TEST=port python test_array.py 'test_custom_type_fill(cl._csc)'
```
(You will likely need to disable the skip clause)

[Updated patch for clang 4.0](https://gist.github.com/inducer/9ff6bc3b228f8e3566a0127c67a05ceb)

**Comment by pjaaskel** [comment]
Thanks. I will upstream the patch after the pocl 0.14 smoke settles.

**Comment by inducer** [comment]
@pjaaskel Is the patch upstream yet?

**Comment by inducer** [comment]
Updated for 4.0 release: https://github.com/inducer/clangdev-feedstock/blob/5401c899823c61b83357e5d23c0a335eb687df9d/recipe/clang-4.0-opencl-calling-conv.patch

**Comment by inducer** [comment]
Thanks!

**Comment by pjaaskel** [comment]
Submitted for review: https://reviews.llvm.org/D33639

**Comment by inducer** [comment]
Thanks!
