### ISSUE TITLE
Vector assigning with single values in conditional operator

### ISSUE THREAD

**Issue by maZZZu** [pocl/pocl#101]
I'm not sure if this is legal syntax but it works with AMD's OpenCL and not with POCL:
```c++
float4 foo = (float4){0.0f, 1.0f, 2.0f, 3.0f};
foo = foo > 1.0f ? 1.0f : 0.5f;
printf("%2.2v4hlf\n", foo);
//Should output:
//0.50,0.50,1.00,1.00
```
POCL kernel compiler gives this error:
```c++
error: assigning to 'float4' from incompatible type 'int __attribute__((ext_vector_type(4)))'
```
This works:
```c++
float4 foo = (float4){0.0f, 1.0f, 2.0f, 3.0f};
foo = foo > 1.0f ? (float4){1.0f, 1.0f, 1.0f, 1.0f} : 0.5f;
printf("%2.2v4hlf\n", foo);
//Output:
//0.50,0.50,1.00,1.00
```

**Comment by pjaaskel** [comment]
There have been patches going to the upcoming LLVM 3.7 that might fix this. However, Clang/LLVM issues should be reported there, but we can consider this as a missing OpenCL C frontend feature if it's not yet there.
