### ISSUE TITLE
lib/CL/devices/cuda/pocl-cuda failed to compile for arm architecture

### ISSUE THREAD

**Issue by terryfork** [pocl/pocl#1011]
#if defined __arm__ code is broken in multiple places

Failed to build working pocl for Nvidia Jetson Nano.

**Comment by pjaaskel** [comment]
Do our Arm maintainer @jianbinfang have an idea here?

**Comment by Muhammad-Yunus** [comment]
@terryfork try follow this tutorial if you eant to use PoCL CPU + CUDA in Jetson Nano https://yunusmuhammad007.medium.com/build-and-install-opencl-on-jetson-nano-10bf4a7f0e65

**Comment by terryfork** [comment]
@Muhammad-Yunus yes, it can be compiled for aarch64 but in this way it don't use code defined for arm and this cause error in runtime:
[2021-11-22 09:31:01.546385646473]POCL: in fn pocl_cuda_alloc_mem_obj at line 569:
  |      CUDA | Error during cuMemHostRegister
CUDA_ERROR_NOT_SUPPORTED: operation not supported

**Comment by isuruf** [comment]
For Jetson Nano, you need https://github.com/pocl/pocl/pull/890

**Comment by terryfork** [comment]
> For Jetson Nano, you need #890

Thanks for the link, but there is no solution here. Code is still unable to compile with that changes. I've tried to fix compilation errors, it compiles but don't work properly.
