### ISSUE TITLE
Help wanted make error on android after 99%

### ISSUE THREAD

**Issue by Saikatsaha1996** [pocl/pocl#1018]
Pocl Just awesome 😌
I am getting error after 99%
I installed with chroot Linux in android it successfully installed and showing (1 OpenCL CPU DEVICE) but with termux failed
So if any solution available please help..
![Screenshot_2021-12-13-10-49-57-681_com termux](https://user-images.githubusercontent.com/72664192/145757182-13eaa4f8-8091-4e89-9931-58f39274054c.jpg)

1) feature request
Please add support for adreno (Qualcomm Snapdragon) base gpu 
Because when I installed Pocl in chroot Linux it shown only cpu device!..
Please add support for adreno Qualcomm Snapdragon Gpu

**Comment by pjaaskel** [comment]
Dear @Saikatsaha1996,  we currently lack an Android maintainer, so unless you step up to be one or send a pull request we can test, it's unfortunately not very likely your support request will be actively picked by someone else.

Similarly, related to your feature request: PoCL doesn't have a support team waiting for features to implement for anyone who requests them. However, we promise to review any feature pull requests you send in a timely fashion, if you decide to contribute back to this awesome open source project. This could be a good reading for you: https://opensource.guide/how-to-contribute/

I'm keeping the issue open to track the Android problem in case an Android maintainer pops up.

**Comment by Saikatsaha1996** [comment]
> Dear @Saikatsaha1996, we currently lack an Android maintainer, so unless you step up to be one or send a pull request we can test, it's unfortunately not very likely your support request will be actively picked by someone else.
> 
> Similarly, related to your feature request: PoCL doesn't have a support team waiting for features to implement for anyone who requests them. However, we promise to review any feature pull requests you send in a timely fashion, if you decide to contribute back to this awesome open source project. This could be a good reading for you: https://opensource.guide/how-to-contribute/
> 
> I'm keeping the issue open to track the Android problem in case an Android maintainer pops up.

Done
![Screenshot_2021-12-13-12-11-22-421_com termux](https://user-images.githubusercontent.com/72664192/145764475-b314f3fa-4634-4101-b2a9-ed6f5ca1a9ec.jpg)
![Screenshot_2021-12-13-12-11-16-082_com termux](https://user-images.githubusercontent.com/72664192/145764482-b8b3f82d-38c8-4627-aeac-16e8e32b4b08.jpg)

**Comment by Saikatsaha1996** [comment]
I found solution from here !🙂
But want for GPU
#807
