### ISSUE TITLE
pocl_test_dlopen_device_pthread test fails

### ISSUE THREAD

**Issue by abbec** [pocl/pocl#1025]
When running the tests, `pocl_test_dlopen_device_pthread` fails with an error: `dlopen($ORIGIN/../../lib/CL/devices/pthread/libpocl-devices-pthread.so, RTLD_NOW) failed: libpocl-devices-basic.so: cannot open shared object file: No such file or directory`, which is true, since libpocl-devices-pthread.so does depend on libpocl-devices-basic.so and that lives in a separate device directory.

How is this supposed to work? I just ran `make check` after `make`?

**Comment by pjaaskel** [comment]
This is a very interesting and good question. It works for me in my various local test envs.

**Comment by pjaaskel** [comment]
```
ldd lib/CL/devices/pthread/libpocl-devices-pthread.so 
...
        libpocl-devices-basic.so => /home/visit0r/src/pocl/build/lib/CL/devices/basic/libpocl-devices-basic.so (0x00007f6d14453000)
...
```
A full path to the .so explains it. You probably have only the filename for some reason?

**Comment by abbec** [comment]
Yeah turned out to be The Nix CMake wrapping that told CMake to not use rpath during build which is why this works in the normal case.
