### ISSUE TITLE
Unknown Target HSAIL when Building CL to LLVM bitcode

### ISSUE THREAD

**Issue by AK2000** [pocl/pocl#1036]
When trying to compile POCL with the ENABLE_HSA=ON I get an error for an unknown target: `error: unknown target triple 'hsail64', please use -triple or -arch` during the build process. I am using POCL 1.8 with LLVM 13 on  RHEL. 

I think the error has to do with not setting up LLVM properly with the right targets enabled. I tried following the setup in the documentation, but I think it is out of date. In the documentation for the HSA target, the instructions say to build with a developmental version of LLVM 3.7 from this repository: https://github.com/HSAFoundation/HLC-HSAIL-Development-LLVM/ -b hsail-stable-3.7, then to use an upstream version of clang with a patch from POCL. However, POCL no longer supports LLVM 3.7, the developmental LLVM repo hasn't been updated in more than 5 years, and the patch pointed to by the documentation has been removed from the POCL repo. Maybe this is a simple fix, but if someone could point me in the right direction for using the HSA target and even update the documentation, that would be much appreciated!

**Comment by woachk** [comment]
HSAIL no longer exists. It's no longer supported on AMD's GPGPU driver stack either. GPU-specific binaries (for example: targeting gfx1010 specifically) are used.

**Comment by franz** [comment]
Documentation has been updated to reflect the current status. PoCL hasn't supported AMD HSA for a some time, only GCC backend with PHSA runtime.

Even when it was still working, it only supported very limited hardware (IIRC, AMD APUs of Kaveri & Carrizo generations) and software (you needed special kernel & libhsa from AMD repositories). If you have that hardware & still want to try PoCL, you could try with older versions (1.0 and older), some of those should have functional AMD HSA support.
