### ISSUE TITLE
Support for AMD Evergreen/Cypress/r600 ?

### ISSUE THREAD

**Issue by erosenst** [pocl/pocl#1039]
Hello, I have bunch of older Radeon HD5870 cards. Is there any(/planned) support for them? if not any guidelines to try own?
HD5870 have 20 compute units and have 2.7Tflops compute capacity. So four of them ~ Radeon VII.. Memory 1GB is low but suitable some small tasks..
(Mesa OpenCL1.2 is flaky, missing features and 50% of compute units)

LLVM 14 seems support Cypress https://llvm.org/docs/AMDGPUUsage.html

Fglrx route seems to bring only two cards at same time usable but I have eight of them..

Any help/ideas?

Thank you

**Comment by franz** [comment]
> Is there any(/planned) support for them

No existing support, and no planned support, at least nobody publicly volunteered. There is a very experimental & unfinished Vulkan driver in PoCL git master, but AFAIK the HD5870 is so old it doesn't support Vulkan.

> LLVM 14 seems support Cypress

LLVM 14 supports a lot of hardware, but unfortunately that's not enough for a working OpenCL.

> Any help/ideas?

I would guess your options are (ordered by least-headache first): 1) use MESA (IIRC it supports OpenCL 1.1 only); 2) use Windows if possible (the AMD Windows drivers of that era were more stable); 3) fglrx (with some old distro).

**Comment by erosenst** [comment]
1) New mesa "support" OpenCL 1.2 (need correct env) but missing lot of functionality. They aim graphics not computation. My CL-program dosn't run in mesa OpenCL. (error: use of type 'double' requires cl_khr_fp64 extension to be enabled)
2) never
3) I use fglrx + amd sdk in ubuntu Jammy kernel 5.3.18. But fglrx.ko only "support" three cards and I have eight.
With fglrx I can run CL program once, second run it segfaults. Need to reload module every time when run CL program. If there is four cards or more fglrx.ko hardlock and module cannot reload, need reboot.
 
How hard it can be to port PoCL direct to radeon.ko driver?

**Comment by pjaaskel** [comment]
> How hard it can be to port PoCL direct to radeon.ko driver?

It's difficult to say without trying. I think you just need to try it out and open a pull request when you have something to review.
