### ISSUE TITLE
AMDGPU not recognised

### ISSUE THREAD

**Issue by guglovich** [pocl/pocl#1073]
I have an RX460 graphics card and a Kaveri 7850K APU, pocl doesn't detect them both. Only the OpenCL CPU is displayed.

Although the project description says HSA, APU Kaveri HSA CPU.

**Comment by pjaaskel** [comment]
The HSA driver is deprecated since there are basically Kaveri and Carrizo that support the HSA spec and the newer ones have diverged from the spec. Proper way to support AMD GPUs nowadays in PoCL would be a layered implementation on top of ROCr. But perhaps rusticl gets there first.
