### ISSUE TITLE
Build issue w.r.t class llvm::AllocaInst | getAlignment()

### ISSUE THREAD

**Issue by abilashcgit** [pocl/pocl#1090]
cmake  -DENABLE_CUDA=ON ..
make && make install

Faced few incremental build issues, and struck at the current issue w.r.t  getAlignment(). 
As per llvm15, the available equivalent signature in getAlign(), but the return value of that is different.
LLVMversion being used in latest (llvm-15)
Which is the recommended LLVM version? AS per Readme i could see, it recommends to use the latest available stable release.
Any solution for this?

Current build issue,
<snip>
/home/abilashc/pocl_git/pocl/lib/llvmopencl/WorkitemLoops.cc: In member function ‘llvm::Instruction* pocl::WorkitemLoops::AddContextRestore(llvm::Value*, llvm::Instruction*, llvm::Type*, bool, llvm::Instruction*, bool)’:
/home/abilashc/pocl_git/pocl/lib/llvmopencl/WorkitemLoops.cc:854:54: warning: ‘llvm::Type* llvm::Type::getPointerElementType() const’ is deprecated: Deprecated without replacement, see https://llvm.org/docs/OpaquePointers.html for context and migration instructions [-Wdeprecated-declarations]
  854 |             alloca->getType()->getPointerElementType(),
      |                                                      ^
In file included from /usr/lib/llvm-15/include/llvm/IR/DerivedTypes.h:23,
                 from /usr/lib/llvm-15/include/llvm/IR/Function.h:29,
                 from /usr/lib/llvm-15/include/llvm/IR/CFG.h:26,
                 from /usr/lib/llvm-15/include/llvm/Analysis/LoopInfo.h:46,
                 from /home/abilashc/pocl_git/pocl/lib/llvmopencl/WorkitemLoops.cc:35:
/usr/lib/llvm-15/include/llvm/IR/Type.h:380:9: note: declared here
  380 |   Type *getPointerElementType() const {
      |         ^~~~~~~~~~~~~~~~~~~~~
/home/abilashc/pocl_git/pocl/lib/llvmopencl/WorkitemLoops.cc: In member function ‘llvm::Instruction* pocl::WorkitemLoops::GetContextArray(llvm::Instruction*, bool&)’:
/home/abilashc/pocl_git/pocl/lib/llvmopencl/WorkitemLoops.cc:976:36: error: ‘class llvm::AllocaInst’ has no member named ‘getAlignment’; did you mean ‘setAlignment’?
  976 |     unsigned Alignment = InstCast->getAlignment();
      |                                    ^~~~~~~~~~~~
      |                                    setAlignment

**Comment by jansol** [comment]
The latest PoCL release only supports up to LLVM 14, which was the latest released LLVM at the time of that PoCL release. LLVM 15 support is still work in progress.

**Comment by pjaaskel** [comment]
This should work now.
