### ISSUE TITLE
CL_INVALID_OPERATION  | clCreateImage returned -59 (with POCL and cuda enabled)

### ISSUE THREAD

**Issue by abilashcgit** [pocl/pocl#1107]
I am hitting the below error while benchmark execution with pocl (cuda backend).
Is image type not supported for now with pocl?

[2022-10-18 07:04:35.907743717]POCL: in fn pocl_create_image_internal at line 104:
  |     ERROR | CL_INVALID_OPERATION There are no devices in context that support this image type + size
....
[1018/070435:ERROR:src/interface/console/consolemain.cpp(808)] Geekbench encountered an internal error and cannot continue. ....

Internal error message: clCreateImage returned -59.

**Comment by franz** [comment]
> Is image type not supported for now with pocl?

images are supported with the CPU backend, but not with the CUDA backend. Documented in `doc/sphinx/source/cuda.rst`
