### ISSUE TITLE
PoCL memory leaks since cl_khr_command_buffer merge

### ISSUE THREAD

**Issue by franz** [pocl/pocl#1108]
Discovered while trying to run OpenCL-CTS on a weaker machine. Some of the CTS tests cause PoCL to eat >10 gigabytes of memory.

After reverting commit 5ddd3c63dbeff3752d3d13aa8f486eafac4e24de and commit 1068c530d889dd0238371ae927ea898cae588366 everything is properly cleaned up:
```
export POCL_ENABLE_UNINIT=1
POCL_DEBUG=all ./examples/example0/example0
.....
[2022-10-21 07:59:02.757466505]POCL: in fn void pocl_llvm_release_context(cl_context) at line 418:
  |      LLVM |  releasing LLVM context
[2022-10-21 07:59:02.858114771]POCL: in fn pocl_check_uninit_devices at line 140:
  | REFCOUNTS |  Zero contexts left, calling pocl_uninit_devices
[2022-10-21 07:59:02.858149971]POCL: in fn pocl_uninit_devices at line 357:
  |   GENERAL |  UNINIT all devices
```

... and `conformance_integer_ops_micro_3` requires about 1.6GB of memory to run. Without those two reverts, 
`conformance_integer_ops_micro_3` eats 10+ gigabytes and the example0 log shows:

```
[2022-10-21 08:14:22.537842048]POCL: in fn POclReleaseContext at line 48:
  | REFCOUNTS |  Release Context 2 (0x55d03f2b3820), Refcount: 4
[2022-10-21 08:14:22.637983686]POCL: in fn pocl_check_uninit_devices at line 148:
  |     ERROR |  Contexts remaining!! 
```
... there are no `Free Event N` messages in the log, so i assume events are not freed at all. @jansol can you take a look ?

**Comment by jansol** [comment]
Hm those commits should not really change anything about the behavior of `clEnqueue*` functions. I also did not spot anything particularly suspicious going over the diff. I'll do some more digging. Meanwhile if you have any hints regarding where events *should* be freed, please let me know.
