### ISSUE TITLE
[Regression 3.0 -> 3.1] `CUDA_ERROR_INVALID_VALUE` on 64-bit pyopencl scan

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#1157]
How to reproduce:
```sh
pip install pyopencl
wget https://raw.githubusercontent.com/inducer/pyopencl/21a5b674b6d94d7da59e912a8b7a989b1f66a083/test/test_{algorithm,array}.py
PYOPENCL_TEST=port:nvi python test_algorithm.py 'test_scan(cl._csc, np.int64, InclusiveScanKernel)' 
```
yields
```
CUDA_ERROR_INVALID_VALUE: invalid argument
```

The error appears to come from within a kernel enqueue. I haven't yet tracked down precisely where.

cc @matthiasdiener

**Comment by inducer** [comment]
Observations:
- This does not appear to happen with `np.int32` instead of `np.int64` in the above command.
- This was observed on ac50b39 (still the current head of `release_3_1`.
- Happens with both LLVM 14 and 15.

**Comment by isuruf** [comment]
https://github.com/pocl/pocl/commit/e1ebad62e96e1bf65fbaf5adb8d838bdc24c918d#diff-953f1cfdd54724e50f8e3a0f47136654634ff0fd926c3c6f3a9de8c7252eab8dL1346-R1398 is the issue here. cc @franz

**Comment by franz** [comment]
Should be fixed now, at least on our CUDA machine it works.
