### ISSUE TITLE
SPIR-V: Program Build Failure with fmin_common Extended Instruction

### ISSUE THREAD

**Issue by bashbaug** [pocl/pocl#1172]
I'm testing SYCL support via the DPC++ compiler and POCL and one of my initial test apps is failing:

https://github.com/bashbaug/simple-sycl-samples/blob/main/samples/04_julia/main.cpp

It looks like POCL is unable to compile the kernel used by this sample due to the calls to `sycl::max()` and `sycl::min()`:

```sh
$ ./julia -p0
Running on SYCL platform: Portable Computing Language
Running on SYCL device: pthread-12th Gen Intel(R) Core(TM) i9-12900K
terminate called after throwing an instance of 'sycl::_V1::compile_program_error'
  what():  The program was built for 1 devices
Build program log for 'pthread-12th Gen Intel(R) Core(TM) i9-12900K':
Error(s) while linking: 
Cannot find symbol _Z11fmin_commonff in kernel library
Cannot find symbol _Z11fmax_commonff in kernel library
Device pthread-12th Gen Intel(R) Core(TM) i9-12900K failed to build the program
 -11 (PI_ERROR_BUILD_PROGRAM_FAILURE)
Aborted (core dumped)
```

The calls to `sycl::max()` and `sycl::min()` are generating the `fmax_common` and `fmin_common` SPIR-V OpenCL extended instructions, respectively.  It looks like these are not supported by POCL.

Here is a simplified test case that demonstrates the problem (can be assembled into a SPIR-V file using `spirv-as`):

```
; SPIR-V
; Version: 1.0
; Generator: Khronos SPIR-V Tools Assembler; 0
; Bound: 24
; Schema: 0
               OpCapability Addresses
               OpCapability Linkage
               OpCapability Kernel
               OpCapability Int64
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %2 "Test" %gl_GlobalInvocationID
               OpDecorate %gl_GlobalInvocationID BuiltIn GlobalInvocationId
               OpDecorate %gl_GlobalInvocationID Constant
               OpDecorate %gl_GlobalInvocationID LinkageAttributes "__spirv_BuiltInGlobalInvocationId" Import
      %ulong = OpTypeInt 64 0
       %uint = OpTypeInt 32 0
    %v3ulong = OpTypeVector %ulong 3
%_ptr_Input_v3ulong = OpTypePointer Input %v3ulong
       %void = OpTypeVoid
      %float = OpTypeFloat 32
%_ptr_CrossWorkgroup_float = OpTypePointer CrossWorkgroup %float
         %21 = OpTypeFunction %void %_ptr_CrossWorkgroup_float
%gl_GlobalInvocationID = OpVariable %_ptr_Input_v3ulong Input
   %float_n1 = OpConstant %float -1
          %2 = OpFunction %void None %21
          %6 = OpFunctionParameter %_ptr_CrossWorkgroup_float
          %7 = OpLabel
         %23 = OpLoad %v3ulong %gl_GlobalInvocationID Aligned 32
          %8 = OpCompositeExtract %ulong %23 0
          %9 = OpUConvert %uint %8
         %10 = OpConvertUToF %float %9
         %11 = OpExtInst %float %1 fmin_common %float_n1 %10
         %12 = OpUConvert %ulong %9
         %13 = OpInBoundsPtrAccessChain %_ptr_CrossWorkgroup_float %6 %12
               OpStore %13 %11 Aligned 4
               OpReturn
               OpFunctionEnd
```

This is roughly the equivalent of this OpenCL C kernel, except the call to `fmin` is replaced by a call to `fmin_common`:

```c
kernel void Test( global float* dst ) {
    uint index = get_global_id(0);
    dst[index] = fmin(-1.0f, index);
}
```

I'm willing to try to fix this myself but I'd appreciate any pointers to get started.  Thanks!

**Comment by franz** [comment]
Thanks, yeah this was on my radar, along with a few remaining SPIRV issues. `fmin/fmax_common` are currently not supported in PoCL. I can see these defined in SPIR-V's ExtInsSet, however i can't find them in OpenCL C specification or the Reference pages. Are these just aliases for OpenCL's `fmin/fmax` functions ? their specification seem slightly different but AFAICT the `*_common` are less strict, so we could just implement them via existing `fmin/fmax`.

**Comment by bashbaug** [comment]
Yeah, the difference between `fmax` and `fmax_common` is pretty subtle, and has to do with handling of NaNs.

The `fmax` extended instruction says:

> Returns y if x < y, otherwise it returns x. If one operand is a NaN, fmax returns the other argument. If both arguments are NaNs, fmax returns a NaN.

So, the behavior with NaNs is well-defined and matches the behavior of the `fmax()` built-in function in OpenCL C.

The `fmax_common` extended instruction says:

> Returns y if x < y, otherwise it returns x. If x or y are infinite or NaN, the resulting values are undefined.

So, the behavior with NaNs (or INFs) is undefined.  This matches the behavior of the `max()` built-in "common function" in OpenCL C.

I agree that `fmax_common` could be implemented using `fmax`, and in fact it seems that my version of the SPIR-V LLVM Translator is compiling both the common function `max()` and `fmax()` to the `fmax` extended instruction, but this is slightly more strict than it needs to be.

**Comment by franz** [comment]
You're right, the implementation can also be done with the ternary operator. Should be straightforward.

1. create `lib/kernel/<builtin-name>.cl` files
2. add implementation with an expression, there is a macro for that (see e.g. `lib/kernel/divide.cl`)
3. the new files have to be added to `SOURCES_WITH_SLEEF` in `lib/kernel/host/CMakeLists.txt`
4. add the builtin names as strings to the `DUAL_ARG` array in `lib/kernel/SPIR/generate_spir_wrapper.py`

that should be all, i think.
