### ISSUE TITLE
What is "--cl-device-info" in cl_offline_compiler.sh?

### ISSUE THREAD

**Issue by TharinduRusira** [pocl/pocl#1186]
Hi,
What is the required file for the argument "cl-device-info". It looks like the path is simply being 'source'-ed in the script so I'm assuming the file is supposed to set some environment variables(?)

Thanks,

**Comment by isuruf** [comment]
It has the same behaviour as the conformance tests scripts. See https://github.com/KhronosGroup/OpenCL-CTS/blob/main/test_common/harness/cl_offline_compiler-interface.txt#L21-L27 for the required env variables. The values can be retrieved from `clGetDeviceInfo`. See https://man.opencl.org/clGetDeviceInfo.html
