### ISSUE TITLE
Error on aarch64 architecture (ARM)

### ISSUE THREAD

**Issue by jandrovins** [pocl/pocl#1196]
I have the following error running `OCL_ICD_VENDORS=/pocl-prefix/etc/OpenCL/vendors ./bin/poclcc -l`: 

> `./bin/poclcc: symbol lookup error: /pocl-prefix/lib64/pocl/libpocl-devices-pthread.so: undefined symbol: pocl_ignore_sigfpe_for_thread`

I am using the Khronos ICD loader (https://github.com/KhronosGroup/OpenCL-ICD-Loader), although I  guess is not very relevant.

Using `grep` I found that the `pocl_ignore_sigfpe_for_thread` function is declared in [lib/CL/pocl_util.h line 63](https://github.com/pocl/pocl/blob/c141fb77ab7e8e219848edcc5576be2bc2ba3213/lib/CL/pocl_util.h#L63)  and defined at [lib/CL/devices/signal_handlers.c line 153](https://github.com/pocl/pocl/blob/c141fb77ab7e8e219848edcc5576be2bc2ba3213/lib/CL/devices/signal_handlers.c#L153). From the last file, this function is inside an `#ifdef __x86_64__` so it makes sense that I do not have it on my ARM installation.

Not sure what to do. Should I just delete the `#ifdef __x86_64__` and expect it to work on my ARM?

**Comment by jandrovins** [comment]
I have just noticed that in known issues (http://portablecl.org/docs/html/conformance.html#known-issues-in-pocl-things-to-be-aware-of) it is mentioned that POCL do not really manages exceptions for integer division by 0 on architectures different from x86. 

I commented line [134 on ../lib/CL/devices/pthread/pthread_scheduler.c](https://github.com/pocl/pocl/blob/c141fb77ab7e8e219848edcc5576be2bc2ba3213/lib/CL/devices/pthread/pthread_scheduler.c#L134) and it is now apparently working. May be this line should be enclosed in a `#ifdef __x86_64__` too.

**Comment by pjaaskel** [comment]
Sounds right. Please send a PR.

**Comment by jandrovins** [comment]
Will do. In a couple of days

**Comment by franz** [comment]
Yep, the ifdef is the correct fix. The SIGFPE code was recently changed and haven't been tested on ARM.
