### ISSUE TITLE
Error running SYCL program using POCL (pthread device) on both X86 and ARM

### ISSUE THREAD

**Issue by jandrovins** [pocl/pocl#1207]
### Description
I have been playing with SYCL using POCL as OpenCL runtime and I have found what seems to be a bug in POCL pthread device implmentation. 

Querying the a SYCL event's 'command_execution_status' gives a value that does not belong to any of the [valid values described in the specification](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.event.command-status).

This is a weird one because it happens on a memcpy operation (generating an event called 'e5') that has a dependency on a kernel execution (with an event called 'e3'), and if you put a `e3.wait()` just before querying e5's 'command_execution_status' with `e5.get_info<sycl::info::event::command_execution_status>()` then the error disappears.

I believe this is an error on the POCL side because it only happens when I use the pthread device. When using the 'basic' device everything works well. 

My code uses USM, which I think is new in POCL so it might be related.

This error occurs on both X86 and ARM platforms.

### How to reproduce
I have encountered this error using the git latest version of [Intel's LLVM (DPC++)](https://github.com/intel/llvm/) which is based on the development branch of llvm 17. POCL was compiled using vanilla (not intel's) LLVM 16 linked statically.

The following code causes the error:

```
#include <CL/sycl.hpp>
#include <assert.h>
#include <iostream>

void axpy(double *h_x, double *h_y, double *d_x, double *d_y, double alpha, long TS)
{
    const long size = TS*sizeof(double);

    sycl::queue q;

    sycl::event e1 = q.memcpy(d_x, h_x, size);
    sycl::event e2 = q.memcpy(d_y, h_y, size);

    sycl::event e3 = q.parallel_for<class C_AXPY>(
        sycl::range<1>(TS), {e1, e2},
        [=](sycl::id<1> i) {
            d_y[i] += alpha * d_x[i];
        });
    //e3.wait();
    // Asynchronous device to host copy  - depends on e3
    sycl::event e5 = q.memcpy(h_y, d_y, size, {e3});
    std::cout << "VVV JUSTO ANTES DE get_info\n";
    auto eret = e5.get_info<sycl::info::event::command_execution_status>();
    if (eret != sycl::info::event_command_status::complete &&
        eret != sycl::info::event_command_status::running &&
        eret != sycl::info::event_command_status::submitted) {
        std::cerr << "VVV ERROR =======> INVALID event.get_info<sycl::info::event::command_execution_status>()\n";
    }
    if (eret == sycl::info::event_command_status::complete) {
        std::cout << "VVV COMPLETED =======> EVENT COMPLETED SUCCESFULLY\n";
    } else if (eret == sycl::info::event_command_status::running) {
        std::cout << "VVV RUNNING =======> EVENT RUNNING SUCCESFULLY\n";
    } else if (eret == sycl::info::event_command_status::submitted) {
        std::cout << "VVV SUBMITTED =======> EVENT SUBMITTED SUCCESFULLY\n";
    }

    e5.wait_and_throw();
}

void multisaxpy(double *h_x, double *h_y, double *d_x, double *d_y,
                const double alpha, long N, long TS, long its)
{
    for (long iteration = 0; iteration < its; iteration++) {
        for (long i = 0; i < N; i += TS) {
            axpy(&h_x[i], &h_y[i], &d_x[i], &d_y[i], alpha, TS);
        }
    }
}


static void initialize(double *data, double value, long N, long TS) {
    for (long i = 0; i < N; i++) {
        data[i] = value;
    }
}

int main(int argc, char *argv[]) {

    const long n = 32;
    const long ts = 32;
    const long its = 1;

    sycl::queue q1;

    double *h_x, *h_y, *check, *d_x, *d_y;
    long size = n * sizeof(double);

    // Allocate host vectors
    h_x = (double *)(malloc(size));
    h_y = (double *)(malloc(size));
    check = (double *)(malloc(size));
    assert(h_x != nullptr && h_y != nullptr && check != nullptr);

    // Allocate device vectors
    d_x = (double *)(sycl::malloc_device<double>(size, q1));
    d_y = (double *)(sycl::malloc_device<double>(size, q1));
    assert(d_x != nullptr && d_y != nullptr);

    const double alpha = 10.0;

    initialize(h_x, 1.0, n, ts);
    initialize(h_y, 0.0, n, ts);
    initialize(check, (double)its * alpha, n, ts);

    // Launch the multisaxpy
    multisaxpy(h_x, h_y, d_x, d_y, alpha, n, ts, its);

    free(h_x);
    free(h_y);
    free(check);
    sycl::free(d_x, q1);
    sycl::free(d_y, q1);

    return 0;
}
```

Compile with `clang++ -fsycl test_error.cpp` and run with `POCL_DEVICES=pthread ./a.out`. To get debug information on SYCL I recommend using `SYCL_PI_TRACE=2`. More variables for debugging SYCL can be found [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#debugging-variables-for-dpc-runtime).

**Comment by pjaaskel** [comment]
Maybe it's CL_QUEUED, which is a valid OpenCL event state? If DPC++ cannot handle that, I believe it's a bug in the SYCL implementation. Since SYCL doesn't seem to have that event state in the specs, it should treat it as 'submitted'.

If it works with basic, it doesn't prove pthread is broken. Basic is a simplified device driver which in this case likely just executes all commands as they come (basically blocking), thus the event just never goes through the CL_QUEUED state.
