### ISSUE TITLE
Local kernel scope variable test failing in CTS

### ISSUE THREAD

**Issue by sasamiyatu** [pocl/pocl#1218]
The local_kernel_scope test from Khronos CTS (part of test_basic) seems to be failing randomly, at least on my machine. Every other test from test_basic is passing. 

Logs from four different runs (using device pthread): 
```
local_kernel_scope...
	Testing with 4 groups, 256 elements per group...
ERROR: Local max validation failed! (expected 4290015211, got 4262452338 for i=1)
local_kernel_scope FAILED
```

```
local_kernel_scope...
	Testing with 4 groups, 256 elements per group...
ERROR: Local max validation failed! (expected 4230681430, got 4290015211 for i=2)
local_kernel_scope FAILED
```

```
local_kernel_scope...
	Testing with 4 groups, 256 elements per group...
local_kernel_scope passed
```

```
local_kernel_scope...
	Testing with 4 groups, 256 elements per group...
ERROR: Local max validation failed! (expected 4290015211, got 4253473385 for i=1)
local_kernel_scope FAILED
```

**Comment by franz** [comment]
wild guess: the code that is supposed to recognize Program-scope variables fails to recognize this case, resulting in the kernels having their own separate variables. I'll take a look.

**Comment by franz** [comment]
I found an issue with `progvar_func_scope` test, but the `local_kernel_scope` works fine here, even repeated runs don't fail. Which LLVM version are were you using, which CPU / OS ?

**Comment by sasamiyatu** [comment]
I just tried running the test a few times with the latest changes from pocl and the CTS and couldn't reproduce the issue myself either...

I'm using LLVM 15.07. The CPU is AMD Ryzen Threadripper 2990WX and the OS is Ubuntu 23.04. 

Maybe this issue can be closed?

**Comment by franz** [comment]
OK, let's reopen if it happens again.
