### ISSUE TITLE
[level0] a couple of regressions

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#1239]
These used to pass from the run_level0_tests:

```
	 49 - kernel/test_sampler_address_clamp_loopvec (Failed)
	141 - regression/test_program_from_binary_with_local_1_1_1_loopvec (Failed
...
  FAIL: Test exited with nonzero code (Segmentation fault):
  /home/pjaaskel/src/pocl/build-l0/tests/kernel/sampler_address_clamp
...
  FAIL: Test exited with nonzero code (1):
  /home/pjaaskel/src/pocl/build-l0/tests/regression/test_program_from_binary_with_local_1_1_1


  STDOUT:



  STDERR:
  
  CL_BUILD_PROGRAM_FAILURE in main on line 101
```

**Comment by franz** [comment]
With PR #1237, both tests pass on my laptop with LLVM 15, and they also pass with dGPU of the [GH runner](https://github.com/pocl/pocl/actions/runs/5141617706) with both LLVM 14 and 15, so seems like something specific to your environment ?

**Comment by pjaaskel** [comment]
I only tested with master.

**Comment by franz** [comment]
Previous master was commit 2a6935fe5 from PR #1231, and that one also [passed](https://github.com/pocl/pocl/actions/runs/5070652587) on the dGPU (LLVM 14+15), and also passes with my laptop's iGPU (LLVM 15). So...  still seems like an issue specific to your environment. Can you reproduce reliably ? which LLVM, driver version, etc ?

**Comment by pjaaskel** [comment]
This was due to me accidentally having an LLVM 16 SPIR-V translator in PATH first.
