### ISSUE TITLE
CTS: c11_atomics/test_c11_atomics crashes

### ISSUE THREAD

**Issue by sasamiyatu** [pocl/pocl#1257]
The C11 Atomics test crashes with the following error on my machine:

```
    global atomic_uint used in function, order_seq_cst, scope_all_svm_devices...
        (thread count 1024, group size 1024)
    gldlopen("/home/tuomas/.cache/pocl/kcache/FD/DHDGHFPCLFLLIACDDOGPFCNCLDFIOMAFLCKNP/test_atomic_kernel/16-1-1-goffs0-smallgrid/test_atomic_kernel.so") failed with '/home/tuomas/.cache/pocl/kcache/FD/DHDGHFPCLFLLIACDDOGPFCNCLDFIOMAFLCKNP/test_atomic_kernel/16-1-1-goffs0-smallgrid/test_atomic_kernel.so: failed to map segment from shared object'.
note: missing symbols in the kernel binary might be reported as 'file not found' errors.
Aborted (core dumped)
```

**Comment by franz** [comment]
Reason for crash: it runs out of virtual memory mappings. On Linux (at least Ubuntu 22.04) by default a process can only create 64k mappings (`cat /proc/sys/vm/max_map_count`).

PoCL's CPU drivers use `dlopen` to load a kernel, after compiling a kernel to a shared library. There is a cache of `dlopen`-ed objects (in `lib/CL/devices/common.c`) that should automatically release unused handles if the cache size exceeds a predefined value.

**Comment by franz** [comment]
should be fixed in `release_4_0` branch now, please reopen if it still fails for you
