### ISSUE TITLE
How can I read PoCL binary files?

### ISSUE THREAD

**Issue by jiefwo** [pocl/pocl#1273]
Hi,

Is there any tool which can disassemble PoCL binary files?

Thanks

**Comment by jansol** [comment]
Which binary files are you referring to, specifically?

**Comment by jiefwo** [comment]
> Which binary files are you referring to, specifically?

POCLCC binary file, generated by poclcc such as:
```shell
./poclcc -o my_kernel.pocl my_kernel.cl
```

**Comment by jansol** [comment]
That would depend on what OpenCL driver it was using (it essentially just dumps the output of `clGetProgramInfo(program, CL_PROGRAM_BINARIES, ...)`). If the driver being used is the default CPU backend of PoCL, the binary is AFAIK just a normal dynamic library, so the usual tools (e.g. objdump) should Just Work.

**Comment by jiefwo** [comment]
Here are the source code and binary file.
[saxpy_kernel.tar.gz](https://github.com/pocl/pocl/files/11950257/saxpy_kernel.tar.gz)

I'm afraid that objdump can't recognize the binary file. I think the binary file contains some metadata and it's not an ELF file.
```shell
$ ../install/bin/poclcc -l                                     
LIST OF DEVICES:
0:
  Vendor:   0x48
    Name:   pthread-0xd01
 Version:   OpenCL 3.0 PoCL HSTR: pthread-aarch64-unknown-linux-gnu-tsv110

$ ../install/bin/poclcc -o saxpy_kernel.cl.pocl saxpy_kernel.cl

$ objdump -D saxpy_kernel.cl.pocl
objdump: saxpy_kernel.cl.pocl: file format not recognized
```

**Comment by jansol** [comment]
Looks like LLVM bitcode. So `llvm-dis should

**Comment by pjaaskel** [comment]
@jiefwo Hi. I think there is currently no command line tool for extracting the binaries. They are close to simple tar files, but PoCL's proprietary format to avoid dependency to tar. Perhaps you can add an extract switch to poclcc and contribute a pull request? This should get you started: https://github.com/pocl/pocl/blob/main/lib/CL/pocl_binary.h#L47
