### ISSUE TITLE
What the difference between api run and submit in struct pocl_device_ops?

### ISSUE THREAD

**Issue by lilh9598** [pocl/pocl#1279]
Is there any functional overlap between submit and run? It look like that both of they will be called by clEnqueueNDRangeKernel. Under what situation will api run and submit be called? I'm confused about that. 

I just know that the submit api is related to out of oder execution. If out of oder execution is supported on my custom device, do I need to implement the run API?

**Comment by franz** [comment]
Hi,

> Is there any functional overlap between submit and run?

No, there isn't. `device->ops->run` is a helper that simplifies implementing `clEnqueueNDRangeKernel` by using `pocl_exec_command`, but this not the only way to implement command execution, and some drivers don't use it (e.g. CUDA, LevelZero).

The `device->ops->submit` is part of the API that does event processing and is mandatory for every driver. It is used by every `clEnqueue*` API  in PoCL (not just enqueueNDRange) via `pocl_command_enqueue`, and is used to notify the driver that an newly created cl_event object has been queued (= appended into a cl_command_queue & status changed to `CL_QUEUED`).

**Comment by lilh9598** [comment]
> Hi,
> 
> > Is there any functional overlap between submit and run?
> 
> No, there isn't. `device->ops->run` is a helper that simplifies implementing `clEnqueueNDRangeKernel` by using `pocl_exec_command`, but this not the only way to implement command execution, and some drivers don't use it (e.g. CUDA, LevelZero).
> 
> The `device->ops->submit` is part of the API that does event processing and is mandatory for every driver. It is used by every `clEnqueue*` API in PoCL (not just enqueueNDRange) via `pocl_command_enqueue`, and is used to notify the driver that an newly created cl_event object has been queued (= appended into a cl_command_queue & status changed to `CL_QUEUED`).

Thanks! I got it.
