### ISSUE TITLE
Crash when entry point contains @

### ISSUE THREAD

**Issue by Snektron** [pocl/pocl#1303]
POCL crashes on the following spir-v (test using https://gitlab.freedesktop.org/Snektron/minimal-spirv-runner):

```
               OpCapability Kernel
               OpCapability Addresses
               OpMemoryModel Physical64 OpenCL
               OpEntryPoint Kernel %func "test@"

       %void = OpTypeVoid
          %F = OpTypeFunction %void

       %func = OpFunction %void None %F
        %blk = OpLabel
               OpReturn
               OpFunctionEnd
```

```
selected platform 'Portable Computing Language' and device 'cpu-AMD Ryzen 7 3700X 8-Core Processor'
/nix/store/rhhll3vwpj38ri72ahrrrvcbkhz4fhh6-binutils-2.40/bin/ld: /home/robin/.cache/pocl/kcache/tempfile_Grgk32.so: version node not found for symbol _pocl_kernel_test@_workgroup
/nix/store/rhhll3vwpj38ri72ahrrrvcbkhz4fhh6-binutils-2.40/bin/ld: failed to set dynamic section sizes: bad value
error: linker command failed with exit code 1 (use -v to see invocation)
Final linking of kernel test@ failed.
fish: Job 1, '../minimal-spirv-runner/minimal…' terminated by signal SIGABRT (Abort)
```

For context, these may be generated by Zig for [behavior tests](https://github.com/ziglang/zig/blob/18b6f9f8a20fc2e1784e203764c4a7f1d0ae2eab/src/codegen/spirv.zig#L1455-L1457) and other symbols, which can contain arbitrary characters except `\0`.

It also seems to happen for `/`.

**Comment by franz** [comment]
Thanks, yeah this is aborting in PoCL. I'm a bit surprised it did not trigger an error much earlier in the compilation pipeline, it aborts in the final step.

**Comment by pjaaskel** [comment]
Is this still failing? Can you retest with latest main (which now passes CTS with SPIR-V) and reopen if it's a problem?
