### ISSUE TITLE
pocl-d: Spurious output about the POCL_DEBUG flags

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#1305]
PoCL-D now prints out the following:
```
** Final POCL_DEBUG flags: 18000000000
```
It should not print anything at all by default, in my opinion.

**Comment by pjaaskel** [comment]
Yep, of course errors should be printed out to stderr.

**Comment by jansol** [comment]
I guess the way to go would be to change the condition of printing that message so it gets printed iff a category other than errors is enabled.

**Comment by pjaaskel** [comment]
Why print even in that case? The user should know what he has set?

**Comment by jansol** [comment]
:shrug: printing the flags predates my involvement
