### ISSUE TITLE
PoCL-D hogs all of the CPU cores even when idle

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#1307]
Does it busy wait / poll for activity on the sockets? Could we use poll() or similar to relieve my poor laptop?

**Comment by pjaaskel** [comment]
Can we have another thread for servicing new connections which are then sent to the active connections that are epolled. IIRC nginx does something like that. This is not high prio, but it's a bit power hungry now.

**Comment by jansol** [comment]
We have that, the problem is telling the active connections that they need to start polling a new socket instead of the old one.

**Comment by pjaaskel** [comment]
Not sure of what you mean. Cannot you just poll all potential connections? There are session ids in the commands which you can use for routing the commands to correct server-side queues?

**Comment by pjaaskel** [comment]
OK, maybe something to add soon for more additional robustness.
