### ISSUE TITLE
Local devices are passed to the remote in clBuildProgram

### ISSUE THREAD

**Issue by kubouch** [pocl/pocl#1321]
When building a program with clBuildProgram containing both local and remote devices, they are both passed to the remote, even though the remote should see only the remote device. It triggers this assert https://github.com/pocl/pocl/blob/00a5c19359959dfeac9c57c41160b2e55e5a8118/pocld/shared_cl_context.cc#L1151 (builtProgramDevices has size 2, binaries has size 1). The solution could be to modify the client code to filter out client-only devices before passing them to the remote.

cc @jansol

**Comment by kubouch** [comment]
Possibly related to / same issue as https://github.com/pocl/pocl/issues/1313

**Comment by jansol** [comment]
This does indeed appear to be the same problem
