### ISSUE TITLE
precision question POCL 4

### ISSUE THREAD

**Issue by twobombs** [pocl/pocl#1335]
Hi All, 
I'm currently on this epic quest to find out if the intermittend crashes we experience on the POCL opencl with Qrack are precision related and was wondering if there are some charts/ideas on the precision on the POCL ICD, version 4 to be exact.

Therefore I ran the [luxmark4](https://wiki.luxcorerender.org/LuxMark_v4) precision benchmark to find out the error percentage rate of the ICD and found the following results:

CPU - `35,5%` - `POCL ICD 4` on Ubuntu 23.10 ( distro package )
![Screenshot from 2023-10-28 12-03-14](https://github.com/pocl/pocl/assets/12692227/78edaea5-c684-4410-b273-27cc9fc81021)
GPU - `13.6%` - `NV ICD 470` on Ubuntu 23.10 ( distro package )
![Screenshot from 2023-10-28 12-09-47](https://github.com/pocl/pocl/assets/12692227/717ac3c2-b050-4382-b0c0-e68f6803c43d)
CPU - `22.49%` - `C++ Native runtime` on Ubuntu 23.10 ( luxmark internal CPU renderer )
![Screenshot from 2023-10-28 12-14-24](https://github.com/pocl/pocl/assets/12692227/250333fe-4886-4778-a3af-afde15f936c2)

Can anyone shed some light on the delta we can see here between the Native CPU renderer and the POCL ICD numbers ?

**Comment by pjaaskel** [comment]
Hi! PoCL 5.0 should be _very_ close to OpenCL 3.0 conformance; there's only a couple of atomic tests that do not pass which we are still trying to debug (it's a strange undeterministic crash), but the artihmetics tests pass. Are you building PoCL in the conformance mode or the default? I'm not sure which the distro builds use by default. Is the Luxmark able to give any further info on which operations cause the differences?

**Comment by franz** [comment]
AFAICT the way Luxmark works is it runs the benchmark for a fixed time (100s ?) and then it measures the amount of different pixels. Due to how raytracing works, slower devices will create a more noisy image in fixed time, and therefore have more different pixels. Have you tried running Luxmark + PoCL on a faster machine ?

**Comment by twobombs** [comment]
@franz thank you for the interesting information, as per requested I've upgraded my Threadripper machine ( 24 threads clipped at 4Ghz ) to Ubuntu 23.10 and it shows the following numbers

CPU - 10,03% - C++ Native runtime on Ubuntu 23.10 ( luxmark internal CPU renderer )
![Screenshot from 2023-11-01 12-20-54](https://github.com/pocl/pocl/assets/12692227/752eae91-a614-428a-a68a-25832e72b30e)

with less-then 100% CPU usage
![Screenshot from 2023-11-01 12-22-20](https://github.com/pocl/pocl/assets/12692227/ba08bce8-17e3-4dbe-bee9-f8ec0520d91e)

CPU - 20.59% - POCL ICD 4  on Ubuntu 23.10  ( distro package )
![Screenshot from 2023-11-01 12-24-30](https://github.com/pocl/pocl/assets/12692227/7e28417b-f93b-4345-88d4-3dbcfb34206d)

GPU - 4.93% - NV ICD 535 - CMP50HX ( GTX2080ti ) on Ubuntu 23.10 ( distro package )
![Screenshot from 2023-11-01 12-28-02](https://github.com/pocl/pocl/assets/12692227/1550da6b-9ed8-4c51-bc3f-2d23ec8f29dd)

for luxmark within a tighter margin as before

@pjaaskel thank you for your response; I saw the announcement but could not find the source to compile the current state of the project. Do you have an URL ? Also, Luxmark leans heavy on FP32 AFAIK; a workload similar to the one Qrack has below 32qubits in that precision isn't a given ; margins for error do exist but too much errors will yield false values and/or crashes will occur

**Comment by pjaaskel** [comment]
The main branch in this repo is the latest one and should be stable (CI-tested). You can use git clone to get it. 

It would be a bit strange if Luxmark refers to as "validation" to what is actually "rendering quality" (what @franz mentioned) as indeed it's very much down to the speed how many samples per pixel one can render. But who knows...

Does Luxmark use some FP relaxation flags in clBuildProgram()?

**Comment by twobombs** [comment]
@pjaaskel thank you for your response. I'll look into integrating and following the main branch
regarding quality and FP relaxation flags I can't answer directly, but I suspect some of the precision comes (also) from architecture
should be able to test the speed vs. architecture when I've received the dual EPYC CPUs and get that machine going

Question answered, thank you all :)
