### ISSUE TITLE
host_ptr alignment and kernal metadata memory issue

### ISSUE THREAD

**Issue by nikhil003** [pocl/pocl#1337]
I am using POCL version 4 compiled with LLVM-12 on my machine. 

The code is compiled with c++11 and here is some information about the machine

```
OpenCL: Version 1.2 supported
OpenCL: Platform 0: Portable Computing Language; OpenCL 3.0 PoCL 4.0  Linux, Debug+Asserts, RELOC, SPIR, LLVM 12.0.0, SLEEF, CUDA, POCL_DEBUG
          Device 0: CPU  [P:ec]; cpu-Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (v4.0)
          Device 1: GPU; Quadro T2000 with Max-Q Design (v4.0)
OpenCL: Platform 1: NVIDIA CUDA; OpenCL 3.0 CUDA 12.2.147
          Device 0: GPU; Quadro T2000 with Max-Q Design (v535.129.03)
OpenCL: Using platform 0, device 1: Quadro T2000 with Max-Q Design
OpenCL: Using platform 0, device 1: Quadro T2000 with Max-Q Design
OpenCL: Using single precision
OpenCL: Platform 0, device 1 maximum workgroup size: 1024
OpenCL: Platform 0, device 1 maximum allocation: 976 Mb
OpenCL: Platform 0, device 1 global memory: 3906 Mb
OpenCL: Platform 0, device 1 local memory: 48 Kb
OpenCL: Platform 0, device 1 maximum workgroup size: 1024
OpenCL: Platform 0, device 1 maximum allocation: 976 Mb
OpenCL: Platform 0, device 1 global memory: 3906 Mb
OpenCL: Platform 0, device 1 local memory: 48 Kb
OpenCL: Host memory limit set to: 7 Gb
OpenCL: Device memory limit set to: 3 Gb
```

I am noticing some *WARNING* messages in the log when I run with `export POCL_DEBUG=1`

![image](https://github.com/pocl/pocl/assets/5336184/ffff8a74-f0ef-4eab-932c-29b574dac625)

and this one

![image](https://github.com/pocl/pocl/assets/5336184/5089bb55-aff0-4a3d-b1a6-7fb221751a9e)

Although the program runs fine. Looking at the code, I can see that these are caused by 

![image](https://github.com/pocl/pocl/assets/5336184/1d834995-877a-4fbd-8a34-c230284cd162)

I encounter these messages in POCL (CPU) and POCL (CUDA). I am wondering if there are recommended ways to go about resolving this.

**Comment by pjaaskel** [comment]
The buffers that are input to the kernels are assumed to have alignment so the contents could naturally align the largest vector datatype of OpenCL C. If you pass a host_ptr to be used as a backing store that is not such nicely aligned, PoCL just uses it and doesn't care if it's not aligned (but can warn about it). It should be fine, if you don't use such large vector datatypes. I don't think we guarantee the alignment to the vectorizer either so the autovectorizer should not assume it either (but I might recall wrongly). To get rid of the warning, you could align your input data at 128B boundary. I don't think OpenCL spec requires this though but likely assumes the driver to copy the data to an aligned space if it's unaligned.

**Comment by nikhil003** [comment]
Thanks @pjaaskel. Closing this for now. I assumed this was causing another issue I am encountering but I will open that separately.
