### ISSUE TITLE
error: /usr/local/lib/../share/pocl/include/opencl-c.h:15178:46: use of type '__read_only image2d_t' requires __opencl_c_images support with LLVM 16

### ISSUE THREAD

**Issue by Oblomov** [pocl/pocl#1339]
Hello all,

I just built the latest `main` with LLVM 16 and when running `clinfo` (that tries to compile a very simple kernel) I get the above error. I suspect this is an bug in the LLVM/Clang headers, that defines the image-related functions without proper fencing to check for `__opencl_c_images`. I'm not sure if this should be worked around in PoCL or not, though.

**Comment by Oblomov** [comment]
Additional information: this happens with the `cuda` device, because image support is false for this still. Still, the functions and types should be properly fenced in the headers, which is an upstream (LLVM) bug, I believe.

**Comment by pjaaskel** [comment]
Oh, OK. Then likely not a regression.

**Comment by Oblomov** [comment]
@pjaaskel I would count it as a regression because I used to be able to run OpenCL code on CUDA‌ devices via PoCL, but I cannot anymore, although I'm not entirely sure where this is coming from, especially since it would seem from the commits that people have been able to run tests with the CUDA device on LLVM 15 and/or 16. I suspect this may be related the the enabling of  3.0 support. I'm currently running a bisection to see if I can identify the culprit.

**Comment by Oblomov** [comment]
Confimed that 1a3d87b806f089f7bfe4f8129c5969b50fdca483 is revealing the issue. The previous commit produces a functioning `cuda` device on my machine, whereas building 1a3d87b806f089f7bfe4f8129c5969b50fdca483 triggers the LLVM header error.

I believe this is due to the fact that `__opencl_c_3d_image_writes` and `__opencl_c_images`  are intentionally excluded from the list of the `CUDA_DEVICE_FEATURES_30`, probably to signal the fact that the device does not support said features, which matches what the spec mentions:
```
The `image2d_t`, `image3d_t`, `image2d_array_t`, `image1d_t`, `image1d_buffer_t`, `image1d_array_t`, `image2d_depth_t`, `image2d_array_depth_t` and `sampler_t` types are only defined if the device supports images, i.e. the value of the [CL_DEVICE_IMAGE_SUPPORT device query](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#opencl-device-queries)) is `CL_TRUE`. If this is the case then an OpenCL C 3.0 or newer compiler must also define the `__opencl_c_images` feature macro.
```

So what happened is that the `cuda` device declaring 3.0 support without images is exposing a bug in the LLVM headers where the image functions are not properly fenced (BTW I checked, and this is the case as far back as LLVM 14 at least). This is probably something that should be reported upstream, but it might be useful to have a workaround in PoCL in the mean time.

**Comment by pjaaskel** [comment]
So, is the workaround to just define those feature macros even though they are not really supported? @isuruf

**Comment by Oblomov** [comment]
Reported upstream. For the record, the issue presents itself also when building with LLVM 14. Also just adding `__opencl_c_images` to the list of supported extensions is NOT sufficient as it leads to a segfault (I haven't examined this more in depth).

**Comment by Oblomov** [comment]
Upstream issue had already been reported [here](https://github.com/llvm/llvm-project/issues/58017), mine was apparently a dupe.

**Comment by Oblomov** [comment]
OK after more testing it seems the segmentation fault is *unrelated*.
Adding the extension to the list IS sufficient to fix this particular issue.
I'll open a separate issue for the LLVM 16 segfault.
