### ISSUE TITLE
Error while building pocl

### ISSUE THREAD

**Issue by suyogchaudhary** [pocl/pocl#1341]
[ 71%] Built target poclu
[ 71%] Building C object bin/CMakeFiles/poclcc.dir/poclcc.c.o
[ 72%] Linking C executable poclcc
CMakeFiles/poclcc.dir/poclcc.c.o: In function `main':
/scratch_ib/suyog/pocl/bin/poclcc.c:364: undefined reference to `clCreateProgramWithIL'
../poclu/libpoclu.a(misc.c.o): In function `poclu_load_program_multidev':
/scratch_ib/suyog/pocl/poclu/misc.c:637: undefined reference to `clCreateProgramWithIL'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/poclcc] Error 1
make[1]: *** [bin/CMakeFiles/poclcc.dir/all] Error 2
make: *** [all] Error 2

**Comment by jansol** [comment]
My educated guess is that it's trying to link against a libOpenCL that only supports OpenCL 1.1 (such as Apple's) but there's not enough information here to tell for sure what's going on. What platform are you building on? Which ICD loader are you using (and which version)? Did you build with ENABLE_ICD on or off?

**Comment by pjaaskel** [comment]
Yep, my guess is that you are linking against an old ICD loader (or even a non-ICD libOpenCL.so) which doesn't recognize the newer symbols like that one. The remedy is to build without ICD support or upgrade your ICD loader (build it against OpenCL 3.0 headers).
