### ISSUE TITLE
Non-flag vaue for POCL_DEBUG_FLAG_REMOTE?

### ISSUE THREAD

**Issue by Oblomov** [pocl/pocl#1349]
I believe the `REMOTE` debug flag was issue the wrong code, as we have
```
#define POCL_DEBUG_FLAG_LEVEL0 0x4000
#define POCL_DEBUG_FLAG_REMOTE 0x6000
#define POCL_DEBUG_FLAG_STREAM 0x8000
```

**Comment by jansol** [comment]
Uhh yeah that is entirely possible. I vaguely remember it coming up in the merge conflicts when upstreaming the remote driver. Brain probably shorted while resolving that.
