### ISSUE TITLE
Sub-Devices do not Retain/Release Parent Devices

### ISSUE THREAD

**Issue by Kerilk** [pocl/pocl#1356]
This is not a problem for sub-devices of root devices, but is an issue with sub-devices of sub-devices.

**Comment by pjaaskel** [comment]
@Kerilk since LLVM 17 got in, we are finally ready to branch PoCL 5.0. Would you like to get this PR in or does it matter? I believe the bug has been there ~always.

**Comment by Kerilk** [comment]
I think it would be safer to have it here. I would also like to delay slightly the branch just to make sure that:
 - `clGetFunctionAddressForPlatformKHR`
 - `clSetPlatformDispatchDataKHR.c`

Shouldn't get renamed to:
 - `clIcdGetFunctionAddressForPlatformKHR`
 - `clIcdSetPlatformDispatchDataKHR.c`

Hopefully I can get some WG time this morning to address the issue.

**Comment by Kerilk** [comment]
This is less critical as the ICD 2 changes are less likely to ship in 5.0 so if this causes trouble we can wait.
