### ISSUE TITLE
POCL 5.0-RC1 on FreeBSD CURRENT: Compiler error: common.c:1682:9: error: initializing 'char *'

### ISSUE THREAD

**Issue by SB211** [pocl/pocl#1373]
OS: FreeBSD 15.0-CURRENT #9 main-n266971-4c9e6ad3205a: Fri Dec 15 15:48:46 CET 2023 amd64
System compiler: FreeBSD clang version 17.0.6 (https://github.com/llvm/llvm-project.git llvmorg-17.0.6-0-g6009708b4367)

```
[...]
FAILED: lib/CL/devices/CMakeFiles/pocl-devices.dir/common.c.o 
/usr/bin/cc -DCL_HPP_TARGET_OPENCL_VERSION=300 -DCL_TARGET_OPENCL_VERSION=300 -DCL_USE_DEPRECATED_OPENCL_1_0_APIS -DCL_USE_DEPRECATED_OPENCL_1_1_APIS -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_USE_DEPRECATED_OPENCL_2_0_APIS -DCL_USE_DEPRECATED_OPENCL_2_1_APIS -DCL_USE_DEPRECATED_OPENCL_2_2_APIS -I/usr/ports/lang/pocl/work/.build -I/usr/ports/lang/pocl/work/pocl-5.0-RC1/include -I/usr/ports/lang/pocl/work/pocl-5.0-RC1/include/hpp -I/usr/ports/lang/pocl/work/pocl-5.0-RC1/lib/CL/devices -I/usr/ports/lang/pocl/work/pocl-5.0-RC1/lib/CL/. -O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DNDEBUG -fPIC -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Wno-ignored-attributes -fvisibility=hidden -MD -MT lib/CL/devices/CMakeFiles/pocl-devices.dir/common.c.o -MF lib/CL/devices/CMakeFiles/pocl-devices.dir/common.c.o.d -o lib/CL/devices/CMakeFiles/pocl-devices.dir/common.c.o -c /usr/ports/lang/pocl/work/pocl-5.0-RC1/lib/CL/devices/common.c
/usr/ports/lang/pocl/work/pocl-5.0-RC1/lib/CL/devices/common.c:1682:9: error: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
 1682 |   char* kernellib_variant = pocl_get_distro_kernellib_variant ();
      |         ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by SB211** [comment]
I was able to fix this problem, since I'm not a developer and the problem might have deeper consequences, pleaese consider:

--- lib/CL/devices/common.c.orig        2023-12-15 17:48:18 UTC
+++ lib/CL/devices/common.c
@@ -1679,7 +1679,7 @@ pocl_init_default_device_infos (cl_device_id dev)
 
   strcat(kernellib, "-");
 #ifdef KERNELLIB_HOST_DISTRO_VARIANTS
-  char* kernellib_variant = pocl_get_distro_kernellib_variant ();
+  const char* kernellib_variant = pocl_get_distro_kernellib_variant ();
   dev->llvm_cpu = pocl_get_distro_cpu_name (kernellib_variant);
   strcat(kernellib, kernellib_variant);
   if (!kernellib_variant)

**Comment by SB211** [comment]
`--- lib/CL/devices/common.c.orig        2023-12-15 17:48:18 UTC
+++ lib/CL/devices/common.c
@@ -1679,7 +1679,7 @@ pocl_init_default_device_infos (cl_device_id dev)
 
   strcat(kernellib, "-");
 #ifdef KERNELLIB_HOST_DISTRO_VARIANTS
-  char* kernellib_variant = pocl_get_distro_kernellib_variant ();
+  const char* kernellib_variant = pocl_get_distro_kernellib_variant ();
   dev->llvm_cpu = pocl_get_distro_cpu_name (kernellib_variant);
   strcat(kernellib, kernellib_variant);
   if (!kernellib_variant)
`

**Comment by SB211** [comment]
`--- lib/CL/devices/common.c.orig        2023-12-15 17:48:18 UTC
+++ lib/CL/devices/common.c
@@ -1679,7 +1679,7 @@ pocl_init_default_device_infos (cl_device_id dev)
 
   strcat(kernellib, "-");
 #ifdef KERNELLIB_HOST_DISTRO_VARIANTS
-  char* kernellib_variant = pocl_get_distro_kernellib_variant ();
+  const char* kernellib_variant = pocl_get_distro_kernellib_variant ();
   dev->llvm_cpu = pocl_get_distro_cpu_name (kernellib_variant);
   strcat(kernellib, kernellib_variant);
   if (!kernellib_variant)
`

**Comment by pjaaskel** [comment]
(Trivial patch in the mailing list.)

**Comment by franz** [comment]
fixed

**Comment by pjaaskel** [comment]
@SB211  can you test RC2 on FreeBSD and add your results to [the wiki](https://github.com/pocl/pocl/wiki/Release-testing-of-pocl-5.0)?
