### ISSUE TITLE
LangOptions error

### ISSUE THREAD

**Issue by ghkareem** [pocl/pocl#1379]
Hi, I hope you can help,
I am trying to compile POCL  from github (i just used master) on almalinux 8.3 with LLVM 18 but I keep running into this error:

-- Checking clang -march vs. -mcpu flag
--   Using -march=
-- Running LLVM link test
-- LLVM link test OK
-- Running Clang link test
...
error: cannot convert 'clang::LangOptions' to 'clang::LangOptions*' in initialization
   24 |        LangOptions *la = pocl_build.getLangOpts();
      |                          ~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                |
      |                                                clang::LangOptions

is anyone familiar with a similar error? I see that it is requesting pointers in the .cc files but the error is asking for LangOptions instead. I hope this doesn't mean editing one by one the .cc files from LangOptions* to LangOptions :( 
Thanks for any advice!

**Comment by ghkareem** [comment]
Thanks for this information!

**Comment by ghkareem** [comment]
I downgraded to LLVM17, but now the error is:

error: base operand of '->' has non-pointer type 'clang::LangOptions'
  517 |   la->CharIsSigned = true;
      |     ^~
 error: base operand of '->' has non-pointer type 'clang::LangOptions'
  520 |   la->OpenCLVersion = cl_std_i;
error: base operand of '->' has non-pointer type 'clang::LangOptions'
  521 |   la->FakeAddressSpaceMap = false;
      |     ^~
error: base operand of '->' has non-pointer type 'clang::LangOptions'
  522 |   la->Blocks = true; //-fblocks
error: base operand of '->' has non-pointer type 'clang::LangOptions'
  523 |   la->MathErrno = false; // -fno-math-errno
error: base operand of '->' has non-pointer type 'clang::LangOptions'
  524 |   la->NoBuiltin = true;  // -fno-builtin
      |     ^~
error: base operand of '->' has non-pointer type 'clang::LangOptions'
  525 |   la->Freestanding = true; // -ffree-standing
      |     ^~
error: base operand of '->' has non-pointer type 'clang::LangOptions'
  526 |   la->AsmBlocks = true;  // -fasm (?)
      |     ^~
 error: base operand of '->' has non-pointer type 'clang::LangOptions'
  532 |     la->setDefaultFPContractMode(LangOptions::FPM_Fast);
error: base operand of '->' has non-pointer type 'clang::LangOptions'
  538 |     la->setDefaultFPContractMode(LangOptions::FPM_On);
      |       ^~
 error: base operand of '->' has non-pointer type 'clang::LangOptions'
  544 |     la->setDefaultFPContractMode(LangOptions::FPM_Off);
      |       ^~
error: base operand of '->' has non-pointer type 'clang::LangOptions'
  550 |   la->setStackProtector(LangOptions::StackProtectorMode::SSPOff);
error: base operand of '->' has non-pointer type 'clang::LangOptions'
  552 |   la->PICLevel = PICLevel::BigPIC;
      |     ^~
 error: base operand of '->' has non-pointer type 'clang::LangOptions'
  553 |   la->PIE = 0;

Thanks for your help!

**Comment by pjaaskel** [comment]
My guess is that it's (still) using a non-intended LLVM (headers).
