### ISSUE TITLE
Question:Are there any plans for RVV1.0 support in PoCL?

### ISSUE THREAD

**Issue by dinyy** [pocl/pocl#1380]
I would like to contribute to POCL's support for RISC-V. I'm interested in knowing the plans regarding POCL's support for RVV1.0.

**Comment by pjaaskel** [comment]
This is in our high wishlist for RISC-V. We hope that RVV Just Works thanks to us delegating most of the vectorization to the standard LLVM vectorizers (which should handle RVV nowadays, right?) after isolating the parallel regions to parallel loops. Perhaps give it a shot?

**Comment by dinyy** [comment]
> This is high in our wishlist for RISC-V. We hope that RVV Just Works thanks to us delegating most of the vectorization to the standard LLVM vectorizers (which should handle RVV nowadays, right?) after isolating the parallel regions to parallel loops. Perhaps give it a shot?

Thank you，I will have a try.
