### ISSUE TITLE
Incorrect behavior with PoCL

### ISSUE THREAD

**Issue by peastman** [pocl/pocl#1390]
I have a kernel that fails on PoCL 4.0 but works correctly on all other OpenCL implementations.  It's a very simple kernel.  Its job is just to scan through an array and find the smallest and largest values it contains.  It is executed as a single workgroup with 256 threads.  Each thread scans a subset of the array, then it performs a reduction in local memory and thread 0 writes the result.

```c++
__kernel void findRange(__global const float* restrict data, uint length, __global float* restrict range) {
    __local float minBuffer[256];
    __local float maxBuffer[256];
    float minimum = MAXFLOAT;
    float maximum = -MAXFLOAT;

    // Each thread calculates the range of a subset of values.

    for (uint index = get_local_id(0); index < length; index += get_local_size(0)) {
        float value = data[index];
        minimum = min(minimum, value);
        maximum = max(maximum, value);
    }

    // Now reduce them.

    minBuffer[get_local_id(0)] = minimum;
    maxBuffer[get_local_id(0)] = maximum;
    barrier(CLK_LOCAL_MEM_FENCE);
    for (uint step = 1; step < get_local_size(0); step *= 2) {
        if (get_local_id(0)+step < get_local_size(0) && get_local_id(0)%(2*step) == 0) {
            minBuffer[get_local_id(0)] = min(minBuffer[get_local_id(0)], minBuffer[get_local_id(0)+step]);
            maxBuffer[get_local_id(0)] = max(maxBuffer[get_local_id(0)], maxBuffer[get_local_id(0)+step]);
        }
        barrier(CLK_LOCAL_MEM_FENCE);
    }
    if (get_local_id(0) == 0) {
        range[0] = minBuffer[0];
        range[1] = maxBuffer[0];
    }
}
```

Running on PoCL, it behaves as if the entire reduction were being skipped.  The values written out are just the minimum and maximum values encountered by thread 0, not the minimum and maximum across all threads.

Here is a possible clue.  If I add this line at the start of the kernel, it magically starts working.

```c++
printf("%d\n", get_local_size(0));
```

Printing out other values such as `get_local_id(0)` does not fix it.  Only printing out the workgroup size makes the error go away.

**Comment by peastman** [comment]
I found a workaround that seems to work: wrap the reduction in a `if (get_local_id(0) < get_local_size(0))` block.

**Comment by pjaaskel** [comment]
Thanks for a relatively small producer with known workarounds. Just for the record, can you also try with `POCL_WORK_GROUP_METHOD=cbs` as well?

**Comment by peastman** [comment]
That improves the behavior a little but doesn't fix it.  The value it stores as the minimum is lower than what thread 0 found, but still not the true minimum.  As if it were doing the reduction over some threads but not all of them.
