### ISSUE TITLE
Should the OpenMP CPU driver be distinct from the pthread/explicit multithreading one?

### ISSUE THREAD

**Issue by Oblomov** [pocl/pocl#1401]
Not much more to say than the title: there are advantages to having them as separate drivers (including simplified testing and slimmer driver code), but also for having them together (much of the code is shared anyway).

**Comment by pjaaskel** [comment]
Yep. It's still unknown if we will keep the OpenMP one as oneTBB seems to outperform it, so the OpenMP experiment might just disappear.

**Comment by Oblomov** [comment]
The advantage of OpenMP is that is fewer dependencies though. How does it fare against the explicit multithreading version?

**Comment by pjaaskel** [comment]
Yes, that's the main advantage. @franz is working on it: do you want to summarize interemediate results at this point?

**Comment by franz** [comment]
The current pthread driver's scheduling is equivalent to OpenMP's dynamic scheduling. On consumer systems the difference between OpenMP/TBB/pthread seems minimal, however on machines with multiple NUMA nodes the difference can be huge, and both OpenMP and TBB drivers can achieve significantly better results than pthread driver. As for TBB vs OpenMP, the difference may not be as high as initial tests suggested.
