### ISSUE TITLE
-I"/foo/bar" still broken?

### ISSUE THREAD

**Issue by AasthaShah1904** [pocl/pocl#1406]
Certain applications such as GROMACS use #include <example.clh> to include multiple sources to build the kernel.
If these .clh files are in different directory, POCL is unable to locate them at runtime.

Here I have given an example of radix sort, where the kernel is included as a #include radix_sort8.clh. in radix_sort8.cl
At runtime, I get the following error

> Input: 
data[0]: 7
data[1]: 6
data[2]: 0
data[3]: 5
data[4]: 4
data[5]: 2
data[6]: 3
data[7]: 1
No. of platforms detected: 1
Selecting platform : Portable Computing Language
Devices found : 1 
Device cpu-minimal-haswell-Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
Selecting : cpu-minimal-haswell-Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
1 error generated.
error: /home/cadl/.cache/pocl/kcache/tempfile_rLgNTU.cl:1:10: 'radix_sort8.clh' file not found
Device cpu-minimal-haswell-Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz failed to build the program

I do not get this error when I use other OpenCL Implementations.
I wanted to know this feature can be added to POCL. 

Thanks!

**Comment by pjaaskel** [comment]
Is this with the latest PoCL? Does GROMACS pass the correct -I options to clBuildProgram()? 

BTW, is there a reason you are using the 'cpu-minimal', not the 'cpu' device? The former is less tested than the latter.

**Comment by AasthaShah1904** [comment]
I am using POCL 5.0
I was only using the CPU as an example device here, facing similar problem with different device as well.

I passed radix_sort8.clh file as a flag
`char *stri="-I\"/home/aastha/xample/radix_sort8/ll\" ";`

My .clh file is present in ll directory and the other files are present in radix_sort8 directory.
I need to keep the .clh and .cl files in different folders as that is also how it is in the GROMACS codebase.

GROMACS compiles and runs properly with other OpenCL implementations.
However, it gives an error with POCL as it is unable to locate the .clh files.

**Comment by pjaaskel** [comment]
OpenCL C doesn't require the "current directory" to be a default search path for the includes. I've fixed some include path issues in e3c126b2662728, but perhaps there are some remaining. Can you try a) removing the (escaped) quotes from the path, it shouldn't need it b) adding your current working directory as another -I?

**Comment by AasthaShah1904** [comment]
Hello
Removing the quotes worked. 
Thank you so much!

**Comment by pjaaskel** [comment]
OK, seems there's still more fixing to do on parsing then.

**Comment by pjaaskel** [comment]
There have been fixes to this spot. Can you test with latest main and see if it fixes the issue and reopen if not?
