### ISSUE TITLE
clCreateProgramWithIL  can not load  printf-kernels.spv, in /pocl/tests/spirv/printf.cc

### ISSUE THREAD

**Issue by yemanxiaotu** [pocl/pocl#1427]
I compile and run the case /build/tests/spirv/spirv_printf,  It fails and reports the following error，Please help analyze the following, thanks very much!

/pocl/build/tests/spirv$ POCL_DEBUG=ALL gdb ./spirv_printf
GNU gdb (Ubuntu 12.1-0ubuntu122.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
https://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./spirv_printf...
(gdb) r
Starting program: /home/yong.gu/u_pocl/pocl/build/tests/spirv/spirv_printf
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2024-02-21 08:47:17.327876452]POCL: in fn pocl_install_sigfpe_handler at line 265:
| GENERAL | Installing SIGFPE handler...
[New Thread 0x7f013f64d640 (LWP 354127)]
[New Thread 0x7f013ee4c640 (LWP 354128)]
[New Thread 0x7f013e52a640 (LWP 354129)]
[New Thread 0x7f013dc08640 (LWP 354130)]
.........
[New Thread 0x7efa857fa640 (LWP 354508)]
[New Thread 0x7efa84ff9640 (LWP 354509)]
[New Thread 0x7efa6ffff640 (LWP 354510)]
[2024-02-21 08:47:17.538291011]POCL: in fn POclCreateCommandQueue at line 103:
| GENERAL | Created Command Queue 3 (0x5579beb4e6a0) on device 0
[2024-02-21 08:47:17.538375559]POCL: in fn void pocl_llvm_create_context(cl_context) at line 587:
| LLVM | Created context 2 (0x5579beb4dc00)
[2024-02-21 08:47:17.538386299]POCL: in fn POclCreateContext at line 232:
| GENERAL | Created Context 2 (0x5579beb4dc00)
binsize = 11368
[2024-02-21 08:47:17.538567315]POCL: in fn POclCreateProgramWithIL at line 142:
| ERROR | CL_INVALID_VALUE The IL provided to clCreateProgramWithIL is not recognized as SPIR-V!
ErrERROR at 102

Thread 1 "spirv_printf" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=139643541817152) at ./nptl/pthread_kill.c:44
44 ./nptl/pthread_kill.c: No such file or directory.
(gdb)

**Comment by yemanxiaotu** [comment]
all logs:
~/pocl/build/tests/spirv$ POCL_DEBUG=ALL gdb ./spirv_printf 
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./spirv_printf...
(gdb) r
Starting program: /home/yong.gu/u_pocl/pocl/build/tests/spirv/spirv_printf 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2024-02-21 08:47:17.327876452]POCL: in fn pocl_install_sigfpe_handler at line 265:
  |   GENERAL |  Installing SIGFPE handler...
[New Thread 0x7f013f64d640 (LWP 354127)]
[New Thread 0x7f013ee4c640 (LWP 354128)]
[New Thread 0x7f013e52a640 (LWP 354129)]
[New Thread 0x7f013dc08640 (LWP 354130)]
.........
[New Thread 0x7efaa4ff9640 (LWP 354502)]
[New Thread 0x7efa87fff640 (LWP 354503)]
[New Thread 0x7efa877fe640 (LWP 354504)]
[New Thread 0x7efa86ffd640 (LWP 354505)]
[New Thread 0x7efa867fc640 (LWP 354506)]
[New Thread 0x7efa85ffb640 (LWP 354507)]
[New Thread 0x7efa857fa640 (LWP 354508)]
[New Thread 0x7efa84ff9640 (LWP 354509)]
[New Thread 0x7efa6ffff640 (LWP 354510)]
[2024-02-21 08:47:17.538291011]POCL: in fn POclCreateCommandQueue at line 103:
  |   GENERAL |  Created Command Queue 3 (0x5579beb4e6a0) on device 0
[2024-02-21 08:47:17.538375559]POCL: in fn void pocl_llvm_create_context(cl_context) at line 587:
  |      LLVM |  Created context 2 (0x5579beb4dc00)
[2024-02-21 08:47:17.538386299]POCL: in fn POclCreateContext at line 232:
  |   GENERAL |  Created Context 2 (0x5579beb4dc00)
binsize = 11368
[2024-02-21 08:47:17.538567315]POCL: in fn POclCreateProgramWithIL at line 142:
  |     ERROR | CL_INVALID_VALUE The IL provided to clCreateProgramWithIL is not recognized as SPIR-V!
ErrERROR at 102

Thread 1 "spirv_printf" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=139643541817152) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb)

**Comment by franz** [comment]
> CL_INVALID_VALUE The IL provided to clCreateProgramWithIL is not recognized as SPIR-V!

That test (`tests/spirv/spirv_printf`) tries to load the SPIR-V binary from PoCL's source directory (`<PoCL-sources>/tests/spirv/printf-kernels.spv`). If you have deleted or changed that file, you could get this error.

**Comment by yemanxiaotu** [comment]
1. I have not change <PoCL-sources>/tests/spirv/printf-kernels.spv
build SPIR-V steps ：
git clone https://hub.nuaa.cf/KhronosGroup/SPIRV-LLVM-Translator
cd SPIRV-LLVM-Translator 
mkdir build; cd build ; cmake .. ; make
#compile the llvm-spirv, then copy it to pocl root directory, compire SPIR-V via this tool:
cd pocl/build/  
cmake -DLLVM_SPIRV=../llvm-spirv -DENABLE_SPIRV=ON -DCMAKE_BUILD_TYPE=Debug .. 
make
#then i build the SPIR-V success, like this:
~/pocl/build/tests/spirv$ ls
CMakeFiles  cmake_install.cmake  CTestTestfile.cmake  Makefile  spirv_printf
~/pocl/build/tests/spirv$POCL_DEBUG=ALL  ./spirv_prinf
#but when I run the  spirv_printf, it run fail at:
| ERROR | CL_INVALID_VALUE The IL provided to clCreateProgramWithIL is not recognized as SPIR-V!

2. I use SPIRV-TOOLS to verify the printf-kernels.spv, and verify log as follows:

/SPIRV-Tools/build/tools$ ./spirv-val printf-kernels.spv 
/SPIRV-Tools/build/tools$ ./spirv-dis printf-kernels.spv 
; SPIR-V
; Version: 1.0
; Generator: Khronos LLVM/SPIR-V Translator; 14
; Bound: 320
; Schema: 0
               OpCapability Addresses
               OpCapability Linkage
               OpCapability Kernel
               OpCapability Int64
               .........

**Comment by yemanxiaotu** [comment]
ctest pass ， Running it directly will cause an error
/pocl/build$ ctest -R spirv
Test project /home/yong.gu/u_pocl/pocl/build
    Start 239: spirv/printf
1/3 Test #239: spirv/printf .....................   Passed    3.87 sec
    Start 241: examples/example0_spirv
2/3 Test #241: examples/example0_spirv ..........   Passed    0.86 sec
    Start 243: examples/example1_spirv
3/3 Test #243: examples/example1_spirv ..........   Passed    0.84 sec

run directly error:
/pocl/build/tests/spirv$ ./spirv_printf 
binsize = 11368
ErrERROR at 102
Aborted (core dumped)

why it coould't run directly

**Comment by yemanxiaotu** [comment]
thanks a lot, I fixed this problem by following step:
1. Add the environment variable of CTestCustom.cmake in the build directory to the terminal and execute it directly.
2. Note that it is the absolute path of llvm-spirv, realpath llvm-spirv
cmake -DLLVM_SPIRV=full_path/llvm-spirv ..
