### ISSUE TITLE
RFE: please provide neve version for LLVM 18.x

### ISSUE THREAD

**Issue by kloczek** [pocl/pocl#1447]
Seems like some updates for new LLVM 18.x are already present on the master.
Is anything else which holds all those changes to be released as new version? 🤔

**Comment by pjaaskel** [comment]
Just the lack of the time combined with more urgent tasks at hand.

**Comment by pjaaskel** [comment]
We'll release as soon as we can, no need for reminder Issues :)

**Comment by kloczek** [comment]
Really .. please do that ASP 😋

**Comment by kloczek** [comment]
And .. thank you 👍

**Comment by pjaaskel** [comment]
Yep, and ASP we will :) Thanks for showing interest.
