### ISSUE TITLE
[RISC-V]error:call to '_cl_min' is ambiguous

### ISSUE THREAD

**Issue by dinyy** [pocl/pocl#1454]
When I run the benchmark  mri-gridding of parboil ,It orrurs this error:

`
[2024-04-29 12:40:27.383870437] PoCL: in fn void appendToProgramBuildLog(cl_program, unsigned int, std::string&) at line 111:
 |     ERROR |  error: /home/sipeed/.cache/pocl/kcache/tempfile_SZhJqE.cl:27:39 <Spelling=/home/sipeed/pocl/include/_builtin_renames.h:142:24>: call to '_cl_min' is ambiguous
`

**Comment by franz** [comment]
Hello,

Could you take a look at the `.cl` source file that PoCL prints (you can tell PoCL to not delete temporary files by env variable: `export POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES=1`). Check the `min` function call arguments (line 27, col 39). My guess is, it's most likely a bug in the benchmark (it is calling `min` with some variables / constants that have different type, and the compiler cannot decide which overload of `min` should it use). Also, have you tried running the same benchmark on other OpenCL platforms (GPU, x86 CPU, ARM) ?

**Comment by dinyy** [comment]
> Hello,
> 
> Could you take a look at the `.cl` source file that PoCL prints (you can tell PoCL to not delete temporary files by env variable: `export POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES=1`). Check the `min` function call arguments (line 27, col 39). My guess is, it's most likely a bug in the benchmark (it is calling `min` with some variables / constants that have different type, and the compiler cannot decide which overload of `min` should it use). Also, have you tried running the same benchmark on other OpenCL platforms (GPU, x86 CPU, ARM) ?

yes,it's because what you have memtoned(it is calling min with some variables / constants that have different type, and the compiler cannot decide which overload of min should it use),I think it's not a problom.
