### ISSUE TITLE
[RISC-V]error: Segmentation fault  in pocl_broadcast func

### ISSUE THREAD

**Issue by dinyy** [pocl/pocl#1455]
![image](https://github.com/pocl/pocl/assets/107465691/b50e0fde-d38c-49d7-a216-03f67cb6673c)
When I run benchmark spmv of parboil , it occurs Segmentation fault  in pocl_broadcast func .
As the pic seen, md->num_deps = 274742877664 , but the size of this dep_ids[] array is only 60.
It‘s unnormal.
![image](https://github.com/pocl/pocl/assets/107465691/cd805ad1-b298-420a-8a61-0b34ffa23cf0)

**Comment by franz** [comment]
this might be fixed in main branch, via commit 1bd1315b9f4b9148ddcf0a5b69fa218a57e134d2
