### ISSUE TITLE
FTBFS on i386

### ISSUE THREAD

**Issue by anbe42** [pocl/pocl#1492]
```
/build/pocl-6.0~rc2/lib/CL/clRemapCommandBufferKHR.c: In function 'POclRemapCommandBufferKHR':
/build/pocl-6.0~rc2/lib/CL/clRemapCommandBufferKHR.c:147:32: error: initialization of 'size_t *' {aka 'unsigned int *'} from incompatible pointer type 'ulong *' {aka 'long unsigned int *'} [-Werror=incompatible-pointer-types]
  147 |           size_t *local_size = cmd->command.run.pc.local_size;
      |                                ^~~
/build/pocl-6.0~rc2/lib/CL/clRemapCommandBufferKHR.c:160:32: error: passing argument 7 of 'pocl_record_ndrange_kernel' from incompatible pointer type [-Werror=incompatible-pointer-types]
  160 |             cmd->command.run.pc.global_offset, global_size, local_size,
      |             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      |                                |
      |                                ulong * {aka long unsigned int *}
```

furthermore there are a few incorrectly named new symbols (without pocl_ prefix), I'll prepare a merge request for that tomorrow

**Comment by anbe42** [comment]
not sure about the proper fix here ... `cmd->command.run.pc` seems to be a 64-bit `pocl_context`, while for calling `pocl_record_ndrange_kernel` one would rather need a 32-bit `pocl_context32` ...

**Comment by pjaaskel** [comment]
Perhaps it's enough to change the size_t to a fixed width 64b type?

**Comment by franz** [comment]
Since the API uses `size_t` consistently, perhaps the runtime code (`struct pocl_context pc`) should be changed to also use `size_t` consistently, and then the drivers would handle converting the the integers to width required by a particular device.

**Comment by franz** [comment]
should be fixed in `release_6_0` branch

**Comment by pjaaskel** [comment]
@anbe42 can you verify the fix? We'll then release 6.0.

**Comment by anbe42** [comment]
OK, trying the fix ...

**Comment by anbe42** [comment]
Looks good so far on i386. I found another exported (but unused) symbol, see separate merge request.

I've just uploaded 6.0-rc2+fixes to Debian/experimental, the package is currently being picked up by the buildds:
https://buildd.debian.org/status/package.php?p=pocl&suite=experimental
All these builds are using LLVM 17.
If nothing else is broken, the architectures `all amd64 arm64 armel armhf i386` should succeed, all others probably fail due to failing tests (no regressions).

**Comment by pjaaskel** [comment]
Excellent. Is LLVM 18 not yet packaged or why LLVM 17? What is the status of the RISC-V port, do you know?

**Comment by anbe42** [comment]
LLVM 18 is packaged but not yet in testing. Default is still 16, but MESA is already built against 17. To avoid having two different llvm versions loaded into a binary that tried both pocl.icd and mesa.icd, I usuallly try to keep the verion in sync with mesa ;-)

------------------------------

on a quick glance over the riscv build log I see

noise on stderr, but seems to be harmless :
```
  Hard-float 'd' ABI can't be used for a target that doesn't support the D
  instruction set extension (ignoring target-abi)
```

and the fatal ones
```
undefined symbol: __gtsf2'.
undefined symbol: __mulsf3'.
undefined symbol: __fixsfdi'.
undefined symbol: __adddf3'.
undefined symbol: __ltsf2'.
undefined symbol: __floatsisf'.
undefined symbol: __eqdf2'.
```

(code generation happens for the default (baseline) target with no -march/-mpcu option specified on the command line, or `dev->llvm_cpu = NULL` in pocl code)
