### ISSUE TITLE
Hombrew formula updated

### ISSUE THREAD

**Issue by dpo** [pocl/pocl#150]
I'm one of the maintainers of the [homebrew/science](https://github.com/Homebrew/homebrew-science) Homebrew tap, which hosts the [formula for POCL](https://github.com/Homebrew/homebrew-science/blob/master/pocl.rb). The formula was just updated to version 0.10. The build instructions are simpler than in [README.OSX](https://github.com/pocl/pocl/blob/master/README.OSX#L54) and should reduce to installing Homebrew (as per http://brew.sh) followed by

```
brew tap homebrew/science
brew install pocl
```

If you are using a version of the command-line tools older than 6.0, it seems that there is an incompatibility with LLVM 3.5 and version 3.4 must be used. For that you might need to

```
brew tap homebrew/versions
```

in addition to the above, but `brew` will indicate whether you need to do so.

Any difficulties can be reported on the [homebrew/science issue tracker](https://github.com/Homebrew/homebrew-science/issues) and possibly here as well.

**Comment by pjaaskel** [comment]
Please use the mailing list for this type of information in the future.
