### ISSUE TITLE
Is it possible to have multiple devices?

### ISSUE THREAD

**Issue by fjarri** [pocl/pocl#1524]
I use `pocl` to test a GPGPU library, and some of the tests require multiple devices to be present (to test work sharing and so on). Is it possible to have `pocl` platform expose multiple devices, even if they are all based on the same CPU?

**Comment by jansol** [comment]
That is quite simple with the [POCL_DEVICES](https://portablecl.org/docs/html/using.html#tuning-pocl-behavior-with-env-variables) env variable.

**Comment by fjarri** [comment]
That seems to create several different devices, is it possible to just make multiple `cpu` ones?

**Comment by jansol** [comment]
You can simply list `cpu` multiple times: `POCL_DEVICES="cpu cpu cpu cpu cpu cpu cpu cpu"`

**Comment by fjarri** [comment]
Oh I see, that works great, thank you! I guess this issue can be closed then.
