### ISSUE TITLE
Creating DBK source code templates

### ISSUE THREAD

**Issue by RABijl** [pocl/pocl#1553]
Looking at the initial DBK source code, a lot of the implementation code is happening in files such as common_utils.c  and pocl_builtin_kernels.c . I'm concerned that once we start adding more DBKs for common devices, these files are going to balloon in size and can become unmaintainable. I'm wondering if it is prudent to start laying out a design pattern for DBKs to follow, similar to what has been done for devices. Or in the very least not add specific implementation code to these files.

**Comment by franz** [comment]
The `common_utils.c/h` has a misleading name, these contain only utils shared between CPU drivers (basic/pthread/tbb etc). The CPU-specific implementation has to go somewhere, but ofc we can separate it if needed.

As for the `pocl_builtin_kernels.c` this only contains "implementation" in the sense of runtime code that is shared among all drivers. DBK definition & metadata setup, driver-independent DBK Attr validation and such. There is no actual implementation of any DBK there. But probably the DBK-specific validation could be moved to a separate file(files) and implemented by function pointers.

Both files are 1K LOC right now. IMO whether introducing a design pattern makes sense depends a lot on what kind of DBKs do we plan to support in the future. There are groups of DBKs (e.g. basic math operations) which could share a lot of validation & possibly execution code, but more complicated DBKs will each need their own separate validation & execution.

**Comment by RABijl** [comment]
> But probably the DBK-specific validation could be moved to a separate file(files) and implemented by function pointers.

This is what I had in mind with regard to `pocl_builtin_kernels.c`.

> The CPU-specific implementation has to go somewhere, but ofc we can separate it if needed.

I was thinking of a `common_dbks` directory with a file for each group of dbk kernels that can be shared by the cpu devices.

I'm currently working on a couple dbks and we can discuss the exact implementation when I make a pr for it.
