### ISSUE TITLE
Raised DBK refactoring changes

### ISSUE THREAD

**Issue by RABijl** [pocl/pocl#1568]
with the DBK prs ( #1567 and #1560) Some refactorings have been suggested and in order to not lose these, I've made a list:
1. remove the xsmm functions from the common_utils, possibly their own file.
2. move the DBK arg validation to pocl_builtin_kernels.c
3. change doxygen documentation to use `/` instead of `@` prefix.
4. bonus: replace C++ style comments with C style ones.

**Comment by pjaaskel** [comment]
Perhaps move this to a personal todo list?
