### ISSUE TITLE
Move cl_half functions out of pocl_utils.c

### ISSUE THREAD

**Issue by RABijl** [pocl/pocl#1587]
there is a bit of work being done to support dbks with the remote driver. This requires the import of pocl_tensor_util.c which in turn requires pocl_util.c only for the float_to_half function. pocl_util.c has a large number of dependencies that are not required by pocld or tensor_util.c so it would be beneficial to split these files up. And as it were, there already exists such a file in poclu: https://github.com/pocl/pocl/blob/main/poclu/cl_half.c , so my suggestion is to see which implementation to keep and create one file.

**Comment by pjaaskel** [comment]
Yes. pocl_util.c has bloated over the years and it's a good idea to spit it to further specific util libs. Just send a PR.
