### ISSUE TITLE
No devices found in platform (Mac Mini M4)

### ISSUE THREAD

**Issue by yves-surrel** [pocl/pocl#1669]
I have already used successfully POCL on Mac Minis M1 and M2, using pyopencl and pocl. Now, I get on a brand new M4:

```
for platform in cl.get_platforms():
    devices = platform.get_devices()
    print(platform, devices)
```
```
<pyopencl.Platform 'Portable Computing Language' at 0x11faede90> []
<pyopencl.Platform 'Apple' at 0x60000141c070> [<pyopencl.Device 'Apple M4' on 'Apple' at 0x6000016095e0>]
```
Is there any hope that POCL can gain access to the CPU? _I know_ that Apple does not support OpenCL any more, no need to tell me.

**Comment by yves-surrel** [comment]
That's Chinese for me... I just installed from a regular
```
mamba install ocl_icd_wrapper_apple "pocl=5.0" 
```
(installing 6.0 does not change anything). Are there options when installing python pocl?

**Comment by isuruf** [comment]
Can you do `export OCL_ICD_ENABLE_TRACE=1` and run your script again?

**Comment by isuruf** [comment]
Also can you send the output of `mamba list` and `mamba info`?

**Comment by isuruf** [comment]
I'm not sure why you don't see any devices. I don't have access to a M4, so can't test.

**Comment by yves-surrel** [comment]
Is there anything else to dig in to try to fix the issue?

**Comment by yves-surrel** [comment]
Good hit! following your suggestion, I could see that the .cache directory had wrong permissions. Fixed now
