### ISSUE TITLE
clinfo (and thus clGetDeviceInfo) reports an empty device type

### ISSUE THREAD

**Issue by rubenvb** [pocl/pocl#168]
When I install pocl 0.11 and run AMD APP SDK's clinfo, the "Device Type" line is bugged:

      Device Type:                                     Vendor ID:                                    0h

It seems pocl is not correctly reporting itself as CPU device. I can also not select it using VexCL's `Context` filtering on `CL_DEVICE_TYPE_CPU`, although I can select it "manually" by not filtering on device type because it is first in the magic OpenCL device list.

**Comment by pjaaskel** [comment]
Are you sure it's not an issue with clInfo. It's a common mistake to assume only a single device type is always returned. It's a bit mask and in pocl's case we OR the CPU type with DEFAULT.

**Comment by rubenvb** [comment]
Yes it is. Thank you, I'll see if I can contact AMD somewhere about this.
