### ISSUE TITLE
Debayer fails on cl_buffer, succeeds with cl_image but result is blank

### ISSUE THREAD

**Issue by boxerab** [pocl/pocl#1722]
Hello,

I have an opencl program to debayer an image. This works fine with AMD gpu on ROCm.

Now I try to run on my cpu under Fedora 41. 

The program has two options, use cl_buffer or use cl_image. The rest of the logic
is the same. 

Running with cl_image succeeds, but result is blank. Running with cl_buffer gives the following error :

```
Selected Platform Vendor : The pocl project
Device 0 : cpu-haswell-AMD Ryzen 9 6900HX with Radeon Graphics
Device ID : 0x547310
Creating program with source debayerBuffer.h
Building program from debayerBuffer.h
Build Options are :  -I ./ -I ../../src  -I ../../src/opencl  -I ./ -I ../../src  -I ../../src/opencl  -D TILE_ROWS=5 -D TILE_COLS=32 -D OUTPUT_CHANNELS=4
Created kernel malvar_he_cutler_demosaic
Error: clEnqueueMapBuffer return CL_INVALID_EVENT_WAIT_LIST.
Error: mapDeviceToHost (CL_QUEUE_CONTEXT) returned CL_INVALID_EVENT_WAIT_LIST.
```

Any ideas would be appreciated, thanks.

**Comment by pjaaskel** [comment]
Quick gut is an application-side error as events are so core and PoCL is a 14 years old now quite a stabilized code base. Which version of PoCL did you test with? If you can share a repro, it would help.

**Comment by pjaaskel** [comment]
Preferably a repro that we can add to the regression test suite (if it's a bug in PoCL), but sure if it's secret I can take a quick look privately.

**Comment by pjaaskel** [comment]
The [Spec](https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/clEnqueueMapBuffer.html) says  _If event_wait_list is not NULL, the list of events pointed to by event_wait_list must be valid and num_events_in_wait_list must be greater than 0._

cl_image could be tested much more and we'd be happy to merge test cases that stress it (and expose&fix bugs in it).

**Comment by franz** [comment]
> I still get blank results if cl_image is used, cl_buffer now works.

Does running your program with `POCL_DEBUG=err` env variable produce anything on stderr ?

> How mature is the POCL cl_image implementation, 

Good enough to pass all image tests in the OpenCL-CTS (official conformance) suite (when PoCL is built in "conformance" mode). There are some additional image formats enabled when PoCL is built in non-conformance mode, and these have some known bugs / failures in the CTS.

**Comment by pjaaskel** [comment]
Perhaps try building PoCL in conformance mode? I believe it's unclear if the issue is in your client code or PoCL. Like you've seen, if it works on other (non-conforming) implementations, it doesn't yet prove the issue is not in the client code. Unfortunately we currently lack the time to debug application code bases we are not familiar with.

Please reopen if you pinpoint the issue to PoCL and not your app code.

**Comment by jansol** [comment]
As far as [the spec](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#built-in-image-read-functions) is concerned your sampler flags are invalid in that case and returning all zeros is well within the range of expected outcomes:

> The read_image{i|ui} calls support a nearest filter only. The filter_mode specified in sampler must be set to CLK_FILTER_NEAREST; otherwise the values returned are undefined.
>
> Furthermore, the read_image{i|ui} calls that take integer coordinates must use a sampler with normalized coordinates set to CLK_NORMALIZED_COORDS_FALSE and addressing mode set to CLK_ADDRESS_CLAMP_TO_EDGE, CLK_ADDRESS_CLAMP or CLK_ADDRESS_NONE; otherwise the values returned are undefined.

Ditto for read_imagef:

> The read_imagef calls that take integer coordinates must use a sampler with filter mode set to CLK_FILTER_NEAREST, normalized coordinates set to CLK_NORMALIZED_COORDS_FALSE and addressing mode set to CLK_ADDRESS_CLAMP_TO_EDGE, CLK_ADDRESS_CLAMP or CLK_ADDRESS_NONE; otherwise the values returned are undefined.

I guess ideally we'd have a vulkan-like validation layer yelling about things like this.
