### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by inferrna** [pocl/pocl#184]
Just seem like some path applied twice.

CMake Error at lib/kernel/host/cmake_install.cmake:44 (FILE):
  file INSTALL cannot find
  "/home/inferno/.dev/OpenCL/pocl/pocl/lib/kernel/host//home/inferno/.dev/OpenCL/pocl/pocl/lib/kernel/host/kernel-x86_64-pc-linux-gnu.bc".
Call Stack (most recent call first):
  lib/kernel/cmake_install.cmake:37 (INCLUDE)
  lib/cmake_install.cmake:39 (INCLUDE)
  cmake_install.cmake:62 (INCLUDE)

**Comment by pjaaskel** [comment]
#183 might be a dupe of this?

**Comment by inferrna** [comment]
Yes, that is it.
