### ISSUE TITLE
longn and ulongn datatypes unknown

### ISSUE THREAD

**Issue by petersupan** [pocl/pocl#191]
Hello, I'm using pocl on an Odroid XU3 lite board (ARM Cortex A15 CPU).
When compiling Kernels which use **ulong4**, **ulong8** or **long4** data types, the compile fails with the message "unknown type name 'ulong4', did you mean 'long'?"
The same  code compiles and runs on the Mali OpenCL.
Are these data types supposed to be supported?

**Comment by pjaaskel** [comment]
Works here on the exact same setup (Ubuntu 14.04, Odroid XU3, LLVM 3.6.1). What is your LLVM version?

**Comment by petersupan** [comment]
Thank you, I had LLVM 3.5. After the update to LLVM 3.6 it works like a charm!
