### ISSUE TITLE
Invalid shufflevector operands

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#193]
Compiling this [piece of CL code](https://gist.github.com/inducer/749383041da3160d9ced), for example by running this snippet:

```shell
python -c 'import pyopencl as cl; ctx = cl._csc(); cl.Program(ctx, open("complex.cl").read()).build()'
```

results in this crash:

```
Invalid shufflevector operands!
  %63 = shufflevector <2 x float> %61, <2 x float> undef, <2 x i64> <i64 0, i64 undef>
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by inducer** [comment]
Should add: pocl from git, LLVM 3.6 from Debian.

**Comment by pjaaskel** [comment]
Can you attach the complex.cl?

**Comment by inducer** [comment]
There's a link to a gist with it in my message:

https://gist.github.com/inducer/749383041da3160d9ced

**Comment by Oblomov** [comment]
I can't seem to reproduce with llvm 3.6 on debian unstable using the current git master of pocl.

**Comment by pjaaskel** [comment]
I managed to find an issue that crashes Clang. Can you verify this is the case for you:
```
// reproduce with:
// clang -x cl test_vec_init.cl -c -emit-llvm -o - -S

typedef float float2  __attribute__((__ext_vector_type__(2)));

float2 func(float2 a) { 
    return a;
} 

kernel void test_vec_init() {
    volatile float2 a = (float2) ( 1.0f, 2.0f );
#if 0
    // This works.
    volatile float2 res = func(a);
    volatile float2 x = 
        (float2) (res.x, res.y);
#else
    // This crashes with:
    // "Constants.cpp:1018: llvm::ConstantVector::ConstantVector(llvm::VectorType*, llvm::ArrayRef<llvm::Constant*>): Assertion `V[i]->getType() == T->getElementType() && "Initializer for vector element doesn't match vector element type!"' failed."
    // Getting confused with the parenthesis in the function call?
    volatile float2 x = 
        (float2) (func(a).x, a.x);
#endif
}
```

**Comment by pjaaskel** [comment]
@inducer are you able to try if the workaround (in #if 0) fixes this issue for you? Maybe these problems are connected.  I got the Clang crash with your complex.cl, it didn't even get to the machine code generation.

**Comment by pjaaskel** [comment]
Crashes with Clang trunk also. Reported it to LLVM: https://llvm.org/bugs/show_bug.cgi?id=23719

**Comment by inducer** [comment]
No, the workaround unfortunately doesn't help me much. Since these complex-ish numbers get initialized in the middle of expressions that come from generated code, I'd have to extensively redo those generators.

**Comment by pjaaskel** [comment]
A Clang issue which at least I don't have time to look at before the release. Likely not a regression, so not a 0.12 blocker.

**Comment by jrprice** [comment]
FYI, a fix for this bug has landed in Clang now (and has been merged onto the release_37 branch too):
http://reviews.llvm.org/rL243851

**Comment by pjaaskel** [comment]
Yeah, the test case above doesn't crash anymore. @inducer can you verify the original issue is gone also with the latest Clang 3.7 revision? Assuming, pls reopen otherwise.
