### ISSUE TITLE
[wishlist] Should use XDG ~/.cache/pocl instead of ~/.pocl/kcache

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#200]
It'd be nice if POCL adhered (at least on Linux) to the XDG spec:

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

That makes it easy to wipe all sorts of caches at once.

**Comment by pjaaskel** [comment]
Sure, a patch doing this would get accepted :) Although I'd prefer some other standard than XDG, if possible, as pocl doesn't imply X nor desktop, even on Linux. Changing the default from .pocl/kcache to .cache/pocl-kcache should not harm in any case, AFAIU.

**Comment by pjaaskel** [comment]
pocl's kcache is closer to the one of 'ccache' in a sense, which stores directly under ~/.ccache, it seems.

**Comment by larsmans** [comment]
I think ccache predates the XDG spec. Don't be confused by the X and D in XDG, it's just a convention for not cluttering homedirs, regardless of the environment. Even SciPy uses the XDG cache directory.

**Comment by pjaaskel** [comment]
Fine for me. Should be trivial to change.
