### ISSUE TITLE
clWaitForEvents does not wait for user events

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#201]
The current stopgap implementation of clWaitForEvents is incorrect in that it waits for all events in the queue that each of the events is associated with. User events have no queue, so they fall through the cracks.

(Low-priority, just figured I'd leave it here since it fails a PyOpenCL test.)

**Comment by pjaaskel** [comment]
Probably will be fixed as a side effect of merging our task scheduler rework hopefully now sooner than later.

**Comment by franz** [comment]
I think this was fixed some time ago.
