### ISSUE TITLE
frexp(0) returns INT_MIN (-2147483648) for exponent

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#202]
Every other CL implementation I've come across returns 0 in this instance.

My `man 3 frexp` says:
> If x is zero, then the normalized fraction is zero and zero is stored in exp.

**Comment by eschnett** [comment]
It seems that the exponent value for `frexp(0)` is not defined in the OpenCL standard. The return value of `ilogb(0)` is specified to be `INT_MIN` or `-INT_MAX`. Given that C specifies that `frexp(0)` return 0 for the exponent, I assume this is an oversight in the OpenCL standard, and we should do the same.

I also notice that `frexp` currently probably doesn't handle this case correctly either -- the mantissa may be wrong as well.

I'll prepare a patch.

**Comment by eschnett** [comment]
I currently don't have time to test, but you'll find my suggestion in the branch `eschnett/frexp`.

**Comment by inducer** [comment]
Results from compiling that branch:
https://gist.github.com/inducer/9bf767ad01e6a8aea71e

**Comment by eschnett** [comment]
I pushed a correction to the branch -- apologies, I still don't have time for testing.

**Comment by inducer** [comment]
Next round:
https://gist.github.com/inducer/2a675cfded680e36dbb0

**Comment by eschnett** [comment]
I pushed a correction. But I'm also re-building pocl now, so if there's an error I should encounter it myself.

**Comment by inducer** [comment]
Sorry for continuing to bother you, and thanks for your patience! :)

**Comment by eschnett** [comment]
@inducer No problem. I'm hoping that pocl will work out for you in the end.

**Comment by inducer** [comment]
Tried you most recent update. The 0 case works now. For 0.1, I get

pocl_significand=1.6
ref_significand=0.8
ref_exponent=-3
pocl_exponent=-4

`man 3 frexp` says

> If the argument x is not zero, the normalized fraction is x times a power of two, and its absolute value is always in the range 1/2 (inclusive) to 1 (exclusive), that is, [0.5,1).

**Comment by eschnett** [comment]
And this should now be corrected on the "eschnett/frexp" branch.

**Comment by inducer** [comment]
Passes on my end. Thanks very much for your help!

**Comment by inducer** [comment]
@pjaaskel Any chance of getting this merged?

**Comment by pjaaskel** [comment]
@inducer eschnett/frexp is merged in already, isn't it?

**Comment by eschnett** [comment]
Yes, the branch is merged.

**Comment by inducer** [comment]
Oops, sorry for the noise.
