### ISSUE TITLE
UNEXPECTED PASS in testsuite

### ISSUE THREAD

**Issue by larsmans** [pocl/pocl#206]
`make check` on a build of 94c8ef9eae8447c19e71afaa6f1dd72801140af3 just reported

```
85. block (testsuite-regression.at:193): UNEXPECTED PASS     (0m0.560s 0m0.102s)
```

and

```
ERROR: 104 tests were run,
1 passed unexpectedly.
251 tests were skipped.
```

Is that bad? (It looks like good news...)

**Comment by pjaaskel** [comment]
Did it fail for you before some recent fixes? It seems to be XFAIL for LLVM 3.4, but there was a recent fix for a const expr cast case.
```
# LLVM 3.4's crashes with an illegal const expr cast. Unresolved.                                                                                                       
AT_XFAIL_IF([grep -q "#define LLVM_3_4" $abs_top_builddir/config.h])
```

**Comment by larsmans** [comment]
I just installed pocl for the first time. I have LLVM 3.4 from Ubuntu, if it matters.

**Comment by pjaaskel** [comment]
My LLVM 3.4 still produces the failure. I suspect it's the mislabeled Ubuntu LLVM 3.4 again (which is really 3.3+some revs, IIRC). This version would need a separate detection which might not be worth it as the latest LLVM versions are recommended with pocl and we might drop LLVM <3.4 support in near releases.
