### ISSUE TITLE
Casting malloc return value to uint32_t?

### ISSUE THREAD

**Issue by larsmans** [pocl/pocl#210]
I notice that in [`pocl_cellspu_run`](https://github.com/pocl/pocl/blob/master/lib/CL/devices/cellspu/cellspu.c#L442), the return value of `malloc` is being cast to `uint32_t`. That doesn't seem safe.

The comment says the code is lifted from `pthreads.c`, but that uses a `void **arguments`.

**Comment by pjaaskel** [comment]
No one seems to care about the CellSPU. It's support was dropped from LLVM after 3.2 and we will drop support for older LLVM versions after the next release has been branched, which drops the CellSPU support too.  Unless, of course, someone jumps up and says he cares about CellSPU and offers to start maintaining it :)
