### ISSUE TITLE
Invalid build options leave cl_program in invalid state

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#212]
If I build a kernel with `-O0` (or, really, any option that pocl doesn't like), it'll return from clBuildProgram with `CL_INVALID_BUILD_OPTIONS` through the `ERROR_CLEAN_OPTIONS` label in `clBuildProgram`. Once that has happened, an attempt to retrieve the build log (or, really, anything that attempts to hit the kernel cache) bombs with the assert

```
python: pocl_cache.c:67: program_device_dir: Assertion `program->build_hash[device_i][0] > 0' failed.
```

Previously, in `clGetProgramBuildInfo`, we hit this code, but  neither of the options really applies, since neither the build hash nor the in-program build logs are initialized:
```c
      if (program->build_log[device_i])
          build_log = strdup(program->build_log[device_i]);
      else
          build_log = pocl_cache_read_buildlog(program, device_i);
```

This patch papers over the issue well enough for me, but I doubt it's what the actual solution should look like:
```diff
--- a/lib/CL/pocl_cache.c
+++ b/lib/CL/pocl_cache.c
@@ -207,6 +207,9 @@ int pocl_cache_write_descriptor(cl_program   program,
 char* pocl_cache_read_buildlog(cl_program program,
                                unsigned device_i) {
     char buildlog_path[POCL_FILENAME_LENGTH];
+    if (program->build_hash[device_i][0] == 0)
+      return NULL;
+
     program_device_dir(buildlog_path, program,
                        device_i, POCL_BUILDLOG_FILENAME);
```

**Comment by pjaaskel** [comment]
@franz is there something better that could be done with this issue?

**Comment by franz** [comment]
Yeah it's not really the solution, i think. Any code that tries to access the build cache, should check that program->build_status for successful build. I'll fix clBuildProgram(), but i don't know what else needs fixing - ideas ?
