### ISSUE TITLE
Handling of Ctrl-C

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#213]
What's pocl's policy regarding handling of Ctrl-C/SIGINT, in particular during kernel execution and during build? I think the current state during LLVM calls is that signals get swallowed and returned as a compiler error.

IMO, it should mostly just leave signal handlers alone.

**Comment by pjaaskel** [comment]
Yes, it should leave them alone. To my understanding pocl doesn't touch the sighandlers (quick grepping didn't find any SIGINT or sigaction strings either), thus what you see must be done internally in LLVM.
