### ISSUE TITLE
HSA device doesn't work with LLVM 3.7

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#218]
Running example1 just fails with a code loading problem while with LLVM 3.6 it works.

**Comment by pjaaskel** [comment]
Fixed to work with HSAIL for now. The native AMDGCN compilation path needs to be fixed in the next release.

**Comment by fabiand** [comment]
What device do you use to test the HSAIL work?

**Comment by pjaaskel** [comment]
A desktop machine with an AMD A10-7850K (Kaveri) APU.

**Comment by fabiand** [comment]
@pjaaskel thanks
