### ISSUE TITLE
clBuildProgram has unimplemented flags

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#226]
At least the warning flags are not implemented.

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clBuildProgram.html

**Comment by franz** [comment]
I believe everything is recognized & passed on, except some options - Program Linking Options in particular - are currently recognized but ignored. Conformance tests on compiler are passing though. 

@pjaaskel  any ideas how to implement it ? Currently at link time everything is compiled to bitcode already, and the only relevant LLC option i see is `--enable-unsafe-fp-math`.

**Comment by pjaaskel** [comment]
Let's focus on conformance test tests flags for now.
