### ISSUE TITLE
Test for whether LLVM was built with assertions doesn't appear to work in LLVM 3.7

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#232]
I just built an LLVM 3.7 in `Release` mode:

```
$ ./pack/llvm-build-release/bin/llvm-config --build-mode
Release
```
and

```
grep ASSERTIONS pack/llvm/build-nondev/CMakeCache.txt
LLVM_ENABLE_ASSERTIONS:BOOL=OFF
```

yet POCL says

```
checking for clang... /home/andreas/pack/llvm-build-release/bin/clang
checking Clang option to specify the target... --target=TARGET
checking for clang++... /home/andreas/pack/llvm-build-release/bin/clang++
checking whether clang++ works... yes
checking if LLVM is built with assertions... yes
```
`pack/llvm/build-nondev` is the build directory, and `pack/llvm-build-release` is where it got installed.

**Comment by inducer** [comment]
There doesn't appear to be an ill effect to this, FWIW, but it may relate to #231.

**Comment by pjaaskel** [comment]
This is likely due to differences between the cmake configured LLVM and autotools one.

**Comment by franz** [comment]
OK so this a misleading message, as in: "checking if LLVM is built with assertions" is misleading, it's not checking for assertions, it's checking if llvm was built wih debugging support (llvm/Support/Debug.h,  llvm::DebugFlag etc). I'll fix the message.
