### ISSUE TITLE
haswell fails test_rotate with LLVM 3.7

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#238]
```
Running test test_rotate...
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000000 res=0x00000101 good=0x00000101
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000001 res=0x00000202 good=0x00000202
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000002 res=0x00000404 good=0x00000404
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000003 res=0x00000808 good=0x00000808
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000004 res=0x00001010 good=0x00001010
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000005 res=0x00002020 good=0x00002020
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000006 res=0x00004040 good=0x00004040
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000007 res=0xffff8080 good=0xffff8080
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000008 res=0x00000101 good=0x00000100
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000009 res=0x00000202 good=0x00000200
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000a res=0x00000404 good=0x00000400
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000b res=0x00000808 good=0x00000800
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000c res=0x00001010 good=0x00001000
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000d res=0x00002020 good=0x00002000
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000e res=0x00004040 good=0x00004000
+FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000f res=0xffff8080 good=0xffff8000
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000000 res=0x00000101 good=0x00000101
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000001 res=0x00000202 good=0x00000202
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000002 res=0x00000404 good=0x00000404
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000003 res=0x00000808 good=0x00000808
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000004 res=0x00001010 good=0x00001010
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000005 res=0x00002020 good=0x00002020
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000006 res=0x00004040 good=0x00004040
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000007 res=0x00008080 good=0x00008080
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000008 res=0x00000101 good=0x00000100
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000009 res=0x00000202 good=0x00000200
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000a res=0x00000404 good=0x00000400
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000b res=0x00000808 good=0x00000800
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000c res=0x00001010 good=0x00001000
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000d res=0x00002020 good=0x00002000
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000e res=0x00004040 good=0x00004000
+FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000f res=0x00008080 good=0x00008000
 OK
```

**Comment by eschnett** [comment]
I fear we should have tested pocl with all the release candidates...

**Comment by pjaaskel** [comment]
Luckily they do point releases now.

**Comment by pjaaskel** [comment]
Do I read this correctly that actually only the ushort16 cases starting from count 0x08 are producing wrong values?

**Comment by eschnett** [comment]
Both `short16` and `ushort16`. I think it's a code generation issue, some bad interaction with the optimizer.

**Comment by pjaaskel** [comment]
But there are entries like `res=0x00002020 good=0x00002020`. Aren't those equal?

**Comment by pjaaskel** [comment]
Ah those were elements, not shift counts. My confusion.

**Comment by ghisvail** [comment]
I encountered the same issue whilst updating the Debian packaging with `pocl-0.13`. The rest of the testsuite succeeds.

**Comment by pjaaskel** [comment]
This must be an LLVM codegen bug as I cannot understand what in pocl would cause such an issue on a single ISA. If you'd want to help to get it fixed please try to minimize the kernel that produces the miscompilation and report to LLVM.

**Comment by pjaaskel** [comment]
Haven't seen this with LLVM 3.8 nor LLVM 3.9 which are now the two officially supported LLVM versions in pocl. If someone cares for the older ones and this issue bothers, please submit a patch.

**Comment by koala6128** [comment]
environment: ubuntu 16.04  pocl-0.13 llvm-3.8 clang-3.8
still has this problem, and I can't fix it , can anyone help?

15/108 Testing: kernel/test_rotate
15/108 Test: kernel/test_rotate
Command: "/usr/bin/cmake" "-Dtest_cmd=/home/ubuntu/Pocl-Test/pocl-0.13/build/tests/kernel/kernel####test_rotate" "-P" "/home/ubuntu/Pocl-Test/pocl-0.13/cmake/run_test.cmake"
Directory: /home/ubuntu/Pocl-Test/pocl-0.13/build/tests/kernel
"kernel/test_rotate" start time: Jan 17 18:48 PST
Output:
----------------------------------------------------------
Running test test_rotate...
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000000 res=0x00000101 good=0x00000101
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000001 res=0x00000202 good=0x00000202
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000002 res=0x00000404 good=0x00000404
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000003 res=0x00000808 good=0x00000808
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000004 res=0x00001010 good=0x00001010
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000005 res=0x00002020 good=0x00002020
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000006 res=0x00004040 good=0x00004040
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000007 res=0xffff8080 good=0xffff8080
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000008 res=0x00000101 good=0x00000100
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000009 res=0x00000202 good=0x00000200
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000a res=0x00000404 good=0x00000400
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000b res=0x00000808 good=0x00000800
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000c res=0x00001010 good=0x00001000
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000d res=0x00002020 good=0x00002000
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000e res=0x00004040 good=0x00004000
FAIL: shift left (<<) type=short16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000f res=0xffff8080 good=0xffff8000
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000000 res=0x00000101 good=0x00000101
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000001 res=0x00000202 good=0x00000202
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000002 res=0x00000404 good=0x00000404
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000003 res=0x00000808 good=0x00000808
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000004 res=0x00001010 good=0x00001010
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000005 res=0x00002020 good=0x00002020
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000006 res=0x00004040 good=0x00004040
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000007 res=0x00008080 good=0x00008080
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000008 res=0x00000101 good=0x00000100
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x00000009 res=0x00000202 good=0x00000200
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000a res=0x00000404 good=0x00000400
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000b res=0x00000808 good=0x00000800
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000c res=0x00001010 good=0x00001000
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000d res=0x00002020 good=0x00002000
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000e res=0x00004040 good=0x00004000
FAIL: shift left (<<) type=ushort16 pattern=0x1 shiftbase=0 shiftoffset=1 val=0x00000101 count=0x0000000f res=0x00008080 good=0x00008000
OK

<end of output>
Test time =   0.11 sec
----------------------------------------------------------
Test Fail Reason:
Error regular expression found in output. Regex=[FAIL]
"kernel/test_rotate" end time: Jan 17 18:48 PST

"kernel/test_rotate" time elapsed: 00:00:00

**Comment by pjaaskel** [comment]
Hi, this can be an LLVM codegen issue which has been fixed in the later versions of LLVM. I saw something similar longish time ago. So please try LLVM 3.9 and pocl master.

**Comment by Oblomov** [comment]
No issue for me with with the LLVM 3.8.1 in Debian unstable. I did a clean build and removed the pocl cache too.

**Comment by ghisvail** [comment]
We investigated this with the ArrayFire guys back in the day, and also found clearing the pocl cache to be the solution.

**Comment by koala6128** [comment]
Hi, thanks everyone. first, I clean the pocl-0.13 cacheI, but it didn't help for me . Then I install LLVM-3.9 and pocl-master, the peoblem dosen't show again.

**Comment by pjaaskel** [comment]
Great!
