### ISSUE TITLE
LLVM Error when using clBLAS

### ISSUE THREAD

**Issue by pavanky** [pocl/pocl#244]
This error propped up when running the OpenCL blas tests in ArrayFire. I am not sure if there is an easy way to narrow it down, but if you guys need any help narrowing it down please let me know.

```
LLVM ERROR: Cannot select: 0x6844ca0: i32 = any_extend 0x6844640 [ORD=10] [ID=199]
  0x6844640: i64 = extract_vector_elt 0x684c3d0, 0x6859b00 [ORD=10] [ID=189]
    0x684c3d0: v2i64 = bitcast 0x68585a0 [ORD=10] [ID=180]
      0x68585a0: v8i16 = X86ISD::PINSRW 0x685bc30, 0x685ba10, 0x68579d0 [ORD=10] [ID=177]
        0x685bc30: v8i16 = X86ISD::PINSRW 0x684cb40, 0x6848240, 0x6843b80 [ORD=10] [ID=167]
          0x684cb40: v8i16 = undef [ID=51]
          0x6848240: i32 = and 0x6857260, 0x68577b0 [ORD=10] [ID=154]
            0x6857260: i32 = X86ISD::SETCC_CARRY 0x6845210, 0x684ae10:1 [ORD=10] [ID=124]
              0x6845210: i8 = Constant<2> [ID=53]
              0x684ae10: i32,i32 = X86ISD::SUB 0x681a440, 0x6858af0 [ORD=5] [ID=94]
                0x681a440: i32,ch = CopyFromReg 0x678f670, 0x685c1a0 [ORD=5] [ID=63]
                  0x685c1a0: i32 = Register %vreg45 [ID=5]
                0x6858af0: i32,ch = CopyFromReg 0x678f670, 0x684d5d0 [ORD=2] [ID=60]
                  0x684d5d0: i32 = Register %vreg132 [ID=2]
            0x68577b0: i32 = Constant<1> [ID=58]
          0x6843b80: i64 = Constant<0> [ID=7]
        0x685ba10: i32 = and 0x68627a0, 0x68577b0 [ORD=10] [ID=153]
          0x68627a0: i32 = X86ISD::SETCC_CARRY 0x6845210, 0x685b4c0:1 [ORD=10] [ID=123]
            0x6845210: i8 = Constant<2> [ID=53]
            0x685b4c0: i32,i32 = X86ISD::SUB 0x68594a0, 0x6858af0 [ORD=4] [ID=93]
              0x68594a0: i32,ch = CopyFromReg 0x678f670, 0x685a290 [ORD=4] [ID=62]
                0x685a290: i32 = Register %vreg46 [ID=4]
              0x6858af0: i32,ch = CopyFromReg 0x678f670, 0x684d5d0 [ORD=2] [ID=60]
                0x684d5d0: i32 = Register %vreg132 [ID=2]
          0x68577b0: i32 = Constant<1> [ID=58]
        0x68579d0: i64 = Constant<4> [ID=24]
    0x6859b00: i64 = Constant<3> [ID=41]
In function: _pocl_launcher_cgemmBlock
```

**Comment by pavanky** [comment]
Also on a side note, POCL passes every other test in ArrayFire :D This is more than what we can say about certain other CPU implementations. Good job POCL team :+1:

**Comment by pjaaskel** [comment]
Seems more like an LLVM (codegen) issue. Is this with 3.7 and latest pocl?

**Comment by pavanky** [comment]
@pjaaskel I did not realize 3.7 was a requirement for pocl. I have been testing with llvm 3.6.2. The test is failing on 3.6.2 with the latest master. I can give it a shot with 3.7 at some point.

**Comment by pavanky** [comment]
Is [this issue](https://llvm.org/bugs/show_bug.cgi?id=22955) relevant ?

**Comment by pjaaskel** [comment]
Not a requirement, but newer LLVMs tend to fix bugs (and introduce new ones), therefore the first thing to do when encountering one is to try the latest version. The issue you pointed out seems to be about a different instruction pattern than in your case.  So if you want to help getting this fixed please test LLVM 3.7.x or even trunk, and if it reproduces, isolate a test case for LLVM X86 maintainers.

**Comment by pjaaskel** [comment]
Assuming not a regression, thus not a 0.12 blocker.

**Comment by franz** [comment]
@pavanky is this still a problem ? can you retry with pocl git master ?

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision and/or the latest LLVM.
