### ISSUE TITLE
Error when used with ASL

### ISSUE THREAD

**Issue by AvtechScientific** [pocl/pocl#246]
POCL v0.10 produces segmentation fault error with ASL ( http://asl.org.il ). It happens on the following line of code (OpenCL C++ bindings 1.2):

`cl_context_properties cps = getContext(queue).getInfo<CL_CONTEXT_PROPERTIES>()[1];`

https://github.com/AvtechScientific/ASL/blob/a14703fa5e4ec933248a5b9ed17ca719570ba6e5/src/acl/aclHardware.cxx#L139

The same happens with Intel's driver. AMD and NVIDIA have no problems with this line.

**Comment by pjaaskel** [comment]
0.10 is quite old, please try with the latest master fevision.
