### ISSUE TITLE
parallel build of AMD SDK tests fails

### ISSUE THREAD

**Issue by kraiskil** [pocl/pocl#25]
Some makefile prerequisite missing:
make[7]: *** No rule to make target `../../../../../samples/opencl/SDKUtil/build/debug/x86_64//libSDKUtil.a', needed by `build/debug/x86_64/SobelFilterImage'. Stop.

Happens when "make -j N" is used. Several (possibly all) tests suffer from this.

**Comment by pjaaskel** [comment]
We now have the 'prepare-examples' rule, thus the examples need to be always rebuilt so this should be less of an issue.
