### ISSUE TITLE
POCL SimpleConvolution speed regression

### ISSUE THREAD

**Issue by franz** [pocl/pocl#252]
There is a speed regression in SimpleConvolution test from AMD SDK 3.0 samples.
```
./SimpleConvolution -q -t -x 512000 -i 40
```
Results:

LLVM  | time
-----------|----------
3.5       |   0.334
3.6       |   0.330
3.7       |   0.406

**Comment by pjaaskel** [comment]
Goes down to 0.35, but also without POCL_BBVECTORIZE. It seems to fluctuate a lot, the very first run was 0.4, but the next ones 0.35. See ad0dc40.
