### ISSUE TITLE
CMake still tries to install pocl.icd when ICD disabled

### ISSUE THREAD

**Issue by jrprice** [pocl/pocl#255]
I'm building the 0.12 RC on OS X, and I tried to disable the ICD by passing `-DENABLE_ICD=OFF`. When running `make install`, CMake is still trying to install the ICD loading point:

    CMake Error at cmake_install.cmake:39 (file):
      file INSTALL cannot copy file
      "/Users/james/projects/pocl-rc012/pocl-0.12/build/obj/pocl.icd" to
      "/etc/OpenCL/vendors/pocl.icd".

Presumably these steps should just be skipped if the user disabled the ICD?

**Comment by franz** [comment]
@jrprice Hi could you please pull & retry

**Comment by jrprice** [comment]
Works as expected now, thanks.
