### ISSUE TITLE
FreeBSD cannot compile cl2.hpp

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#263]
Reported in mailing list: https://sourceforge.net/p/pocl/mailman/message/34536660/

@jrprice do you have ideas for this? Sounds like an issue with the cl2.hpp which comes straight from Khronos, right?

**Comment by jrprice** [comment]
Hmm, looks like it may be a bug in `cl2.hpp`. I'll set up a FreeBSD VM and see if I can reproduce.

**Comment by jrprice** [comment]
OK, I managed to reproduce this when building with FreeBSD's default Clang (3.4). Forcing configure to use Clang 3.6 (`CC=clang36 CXX=clang++36`) fixed the problem.

So this might just be a bug in old Clang, but I'm not 100% sure yet. Haven't encountered any other compilers that can't handle this `cl2.hpp` yet.
