### ISSUE TITLE
CXX flags given an unrecognized command line option '-Wcovered-switch-default'

### ISSUE THREAD

**Issue by kraiskil** [pocl/pocl#264]
building pocl stops at the error:
```g++: error: unrecognized command line option '-Wcovered-switch-default'````
I guess this is because the CXX flags are taken from clang, whereas gcc is used here to build pocl.
The command line option doesn't seem to be implemented in gcc yet:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61864

System: ARM Ubuntu 14. gcc 4.8.4, clang+llvm pre-compiled from llvm.org.
Building pocl with clang seems to fix this.

**Comment by pjaaskel** [comment]
I think it's impossible to cover all of these cases automatically.

**Comment by kraiskil** [comment]
I think we are going the wrong way about this. configure.ac is taking wholesale the flags LLVM was compiled with (with whatever compiler) and applying them to what is used to compile pocl. 
Because the two usually are the same compiler & version of it, it has worked.
Instead, configure.ac should cherry-pick the necessary flags that LLVM passes are picky about (debug, assert).
At the very least, configure.ac should catch this, and make a sensible error message to the user ("you must compile pocl with the same or compatible compiler that was used to build your LLVM")

**Comment by pjaaskel** [comment]
You might be right, but it might be too much effort for corner cases and perhaps should be done in LLVM.
 After all ``--cxxflags        C++ compiler flags for files that include LLVM headers.``. So actually LLVM should not define unneeded flags in "llvm-config --cxxflags", so projects like pocl wouldn't suffer from issues like this?

**Comment by kraiskil** [comment]
Right, this is a LLVM bug. For some reason I was thinking ```llvm-config --cxxflags``` was printing out the flags with which LLVM was compiled, not what the doc says.

**Comment by franz** [comment]
FYI, just tried the other way (gcc-built clang, then clang-built pocl) and clang is also complaining about unknown flags :]

Should i perhaps add a note into documentation, for now ?

**Comment by pjaaskel** [comment]
Yep. In the FAQ or a troubleshooting section.
