### ISSUE TITLE
Data race on packet dispatch writing header field

### ISSUE THREAD

**Issue by markrankilor** [pocl/pocl#266]
The HSA specs state that the packet processor will read the first 32-bits of the packet with a 32-bit atomic read. Hence writing the header field of the packet must include the setup field as the first 32-bits.

In pocl-hsa.c
__atomic_store_n((uint16_t*)(&kernel_packet->header), header, __ATOMIC_RELEASE);

Will cause a data race with the read in the packet processor.

**Comment by franz** [comment]
Hi, nice catch. Definitely needs a fix for 0.12
