### ISSUE TITLE
How to generate LLVM IR using pocl

### ISSUE THREAD

**Issue by adamcavendish** [pocl/pocl#269]
Just using pocl as a frontend, so I can get LLVM IR out of it.

**Comment by eschnett** [comment]
What level of LLVM IR do you need? If you just want to translate C, C++, or OpenCL C into LLVM, then you don't need pocl; clang will do this on its own. However, if you need a representation of e.g. OpenCL's barrier statements, then you could look into pocl's cache to find the LLVM code.

**Comment by pjaaskel** [comment]
Strictly you still need at least the _kernel.h which has the OpenCL C built-in declarations, and if you want to actually run the kernel somewhere, you need to link in the built-in functions from an LLVM IR bitcode library.

**Comment by adamcavendish** [comment]
Thanks. I tried libclc and succeeded.
