### ISSUE TITLE
linking against an version 1.1 ICD causes link error

### ISSUE THREAD

**Issue by kraiskil** [pocl/pocl#27]
Some of the tests (image sampler clamp, I think) fails to link, if an OpenCL 1.1 version ICD is used. This means 'make'  will exit with error. Currently we only warn about tests not working, if ocl-icd not found.
Details missing, as all my ICDs are v. 1.2, and this was a verbal report from an end-user.

This is the same as the old LP bug: https://bugs.launchpad.net/pocl/+bug/1199898

**Comment by pjaaskel** [comment]
Assuming fixed.
