### ISSUE TITLE
Built on a raspberry pi 2 ...

### ISSUE THREAD

**Issue by kif** [pocl/pocl#273]
Hi,
As the raspberry pi 2 is a quad core armv7, I expected *pocl* to build ...  but it is stuck on the hwloc part.

 kieffer@rpi2r ~/workspace/pocl-0.12/build $ ../configure 
 checking build system type... armv7l-unknown-linux-gnueabihf
 checking host system type... armv7l-unknown-linux-gnueabihf
 checking target system type... armv7l-unknown-linux-gnueabihf
 checking for a BSD-compatible install... /usr/bin/install -c
 checking whether build environment is sane... yes
 checking for a thread-safe mkdir -p... /bin/mkdir -p
 checking for gawk... gawk
 checking whether make sets $(MAKE)... yes
 checking whether make supports nested variables... yes
 checking whether make supports nested variables... (cached) yes
 checking for pkg-config... /usr/bin/pkg-config
 checking pkg-config is at least version 0.9.0... yes
 checking for HWLOC... no
 configure: error: hwloc 1.0+ is required
 
 kieffer@rpi2 ~/workspace/pocl-0.12/build $ dpkg -l |grep hwloc
 ii  hwloc                                 1.10.0-3                                  armhf        Hierarchical view of the  machine - utilities 
 ii  libhwloc-plugins                      1.10.0-3                                  armhf        Hierarchical view of the  machine - plugins
 ii  libhwloc5:armhf                       1.10.0-3                                  armhf        Hierarchical view of the machine - shared libs

**Comment by pjaaskel** [comment]
You need the headers from a dev package.
