### ISSUE TITLE
HSA: Waiting on a completion signal should check value and loop

### ISSUE THREAD

**Issue by markrankilor** [pocl/pocl#277]
In lib/CL/devices/hsa/pocl-hsa.c, the hsa_signal_wait_acquire should be in a loop, with sigval checked after each wait has returned. The timeout is purely a hint to the API, and the returned value may not satisfy the specified condition when the wait returns.

From the HSA Runtime spec:
"A wait operation can spuriously resume at any time sooner than the timeout (for example, due to system or other external factors) even when the condition has not been met."

**Comment by franz** [comment]
Hi, there's a fix in  commit 1b295d736e115c56b please check & let me know if you find it OK.

**Comment by markrankilor** [comment]
Looks good to me.
