### ISSUE TITLE
HSA: vpath is picking up the wrong builtins

### ISSUE THREAD

**Issue by markrankilor** [pocl/pocl#278]
In lib/kernel/rules.mk there is:
vpath %.c @top_srcdir@/lib/kernel

The generated lib/kernel/hsail64/Makefile.in contains:
VPATH = @srcdir@

The vpath directive takes precedence and seems to be selecting the generic builtins for HSA instead of the hsail64 ones.

It looks like all the vpath directive lines in rules.mk should have @srcdir@:
vpath %.c @srcdir@ @top_srcdir@/lib/kernel

**Comment by franz** [comment]
I tried autotools build and i don't see this happening. Also the HSA testsuite is currently  autotools-only and i'm quite sure it wouldn't work at all with hsail-compiled host code... Perhaps some automake/autoconf incompatibility ?
