### ISSUE TITLE
Unable to find -lOpenCL

### ISSUE THREAD

**Issue by prashantrar** [pocl/pocl#282]
I am trying to install pocl on the zedboard zynq with arm cortex a9 architecture. Currently ubuntu 12.04 is installed on the board but after compiling pocl, this is the error that i get.

/usr/bin/ld: cannot find -lOpenCL
collect2: ld returned 1 exit status

kindly help.

**Comment by kraiskil** [comment]
libOpenCL is usually the OpenCL ICD loader library, not the implementation library itself.
So either install a ICD loader ('ocl_icd' or the one from Khronos), or link your application against libpocl.so, not libOpenCL.so. Or make a softlink pointing libOpenCL.so to libpocl.so for your system.

**Comment by prashantrar** [comment]
I tried compiling my code with the following command linking it against libpocl as shown below.

<code>
root@localhost:~/Documents/OPENCL/vecadd# gcc vector_addition.c -o vector_addition -lm -L/usr/local/pocl/lib/ -lpocl   
</code>
Im getting the error
<code>
root@localhost:~/Documents/OPENCL/vecadd# ./vector_addition 
./vector_addition: error while loading shared libraries: libpocl.so.1: cannot open shared object file: No such file or directory
</code>

**Comment by pjaaskel** [comment]
You need to add the install location of libpocl.so to your LD_LIBRARY_PATH.

**Comment by prashantrar** [comment]
gcc vector_addition.c -o vector_addition -lm -lOpenCL /root/Documents/pocl/pocl-0.9/lib/poclu/.libs/libpoclu.so -Wl,-rpath -Wl,/usr/local/pocl/lib


This is the command i used to fix it

**Comment by pjaaskel** [comment]
Yes, that's the other way, it records the dynamic path to the binary.

**Comment by prashantrar** [comment]
Thanks for your help @pjaaskel
