### ISSUE TITLE
Making a device detect as an opencl device

### ISSUE THREAD

**Issue by prashantrar** [pocl/pocl#285]
Is it possible to get one of my devices listed under /dev get listed as an opencl device. For example I have an fpga with some logic whose write and read ports are mapped as devices to /dev. Is it possible to make my fpga detect as an opencl device and send kernels to it.

**Comment by pjaaskel** [comment]
You need to write a Linux kernel driver for your device first, then a "user space" pocl driver to communicate with the kernel driver visible in /dev.

Please do not use the issue tracker for questions it's meant for bug reports. The correct forum is the mailing list, the IRC channel (http://portablecl.org/discussion.html)  or  stackoverflow (http://stackoverflow.com/questions/tagged/pocl).

**Comment by prashantrar** [comment]
Sorry, shall use the forms for questions, thanks for the information
