### ISSUE TITLE
configure should pick/check the correct version of LLVM programs

### ISSUE THREAD

**Issue by Oblomov** [pocl/pocl#286]
If the default LLVM programs are not the same version as the llvm-config one (e.g. because one is configuring with LLVM_CONFIG=/usr/bin/llvm-config-3.7 but the default clang is 3.6), compilation may fail due to expected vs effective tool versions. For example, currently on my machine this is failing because atomics are assumed to be available (llvm 3.7) but clang 3.6 doesn't know about them.

configure should thus (1) prefer versioned tools to unversioned ones and (2) check that the unversioned ones are the correct version.

**Comment by pjaaskel** [comment]
Cmake should do this, I believe. Please reopen if fails for you.
