### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [pocl/pocl#296]
I would like to point out that identifiers like "[`__GET_DEVICE_INFO_ERR`](https://github.com/pocl/pocl/blob/18cb17727fbb66c524fe4c9711781265f2e35324/include/CL/cl2.hpp#L727)" and "[`__OPENCL_CL_H`](https://github.com/pocl/pocl/blob/e214d58ce9fd5d5c432a64748ac9a89ff274fce6/include/CL/cl.h#L24)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by pjaaskel** [comment]
These are in cl.h etc. headers, right? The headers are copied straight from Khronos standard ones, so please report these issues with them.

**Comment by elfring** [comment]
Would you like to check if any software evolution will happen which corresponds to [a similar bug report](https://github.com/KhronosGroup/Vulkan-Docs/issues/7 "Improvements around the usage of reserved identifiers?")?
