### ISSUE TITLE
Source build fail

### ISSUE THREAD

**Issue by jhebus** [pocl/pocl#302]
Hi there, 

Trying to play around with pocl -i.e. new to it. I am trying to build from source, but the build is failing using autotools. 

Specifically, i get a compilation error:

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I../../fix-include -I../../include -I/usr/lib/llvm-3.6/include -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -ffunction-sections -fdata-sections -Wcast-qual -fno-rtti -DNDEBUG -g -O2 -MT WorkitemReplication.lo -MD -MP -MF .deps/WorkitemReplication.Tpo -c WorkitemReplication.cc  -fPIC -DPIC -o .libs/WorkitemReplication.o
WorkitemReplication.cc: In member function 'virtual bool pocl::WorkitemReplication::ProcessFunction(llvm::Function&)':
WorkitemReplication.cc:175:55: error: invalid initialization of reference of type 'const llvm::DataLayout&' from expression of type 'const llvm::DataLayout*'
   const DataLayout &TD = F.getParent()->getDataLayout();

Sequence of events:

./autogen.sh  -- fine 

./configure  -- fine

make  -- error

I have included files showing the output from each of the above processes.

I have ubuntu 14.04 and llvm and clang 3.6

[make_output.txt](https://github.com/pocl/pocl/files/144935/make_output.txt)
[configure_output.txt](https://github.com/pocl/pocl/files/144933/configure_output.txt)
[autogen_output.txt](https://github.com/pocl/pocl/files/144934/autogen_output.txt)

**Comment by pjaaskel** [comment]
3.6 is not supported anymore in master. The configure.ac still allows it though, which will be fixed. Please upgrade to 3.7 or 3.8.

**Comment by jhebus** [comment]
thanks
