### ISSUE TITLE
Cmake+LLVM 3.7 single libLLVM.so build broken

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#315]
Something related to LLVM linkage:

```
...
ocl-icd(ocl_icd_loader.c:191): _load_icd: error while dlopening the IDL: '/home/visit0r/src/pocl-public/build-llvm-hsa-3.7/lib/CL/libpocl.so.1.7.0: undefined symbol: _ZN4llvm10CallbackVH6anchorEv',
...
```
Might be a local issue as it works for @franz . It works with autotools here.

**Comment by franz** [comment]
OK so when i search for this symbol in my libpocl, i get

```
$ nm lib/CL/libpocl.so | grep _ZN4llvm10CallbackVH6anchorEv
                 U _ZN4llvm10CallbackVH6anchorEv
```

and it seems present in libLLVMCore.so:

```
$ nm libLLVMCore.so | grep _ZN4llvm10CallbackVH6anchorEv
00000000001b8540 T _ZN4llvm10CallbackVH6anchorEv
```

can you paste the output of ``nm | grep`` on your libLLVM ?
also what does ``ldd lib/CL/libpocl.so`` print

**Comment by pjaaskel** [comment]
The problem is still present in 0.13-rc3. The autotools build works. I don't have .so for libLLVMCore.so, only .a. Maybe that's the problem?

**Comment by pjaaskel** [comment]
Likely an issue with LLVM 3.7 and a static-only lib. As this is not a regression, not blocking 0.13.

**Comment by pjaaskel** [comment]
This is an LLVM build system issue. The workaround is to use -DSINGLE_LLVM_LIB=off in pocl's cmake cmdline. Then it links in the libLLVMCore.so that has the referred symbol.
