### ISSUE TITLE
[i686] kernel/test_printf:  Required regular expression not found.Regex=[Running test test_printf...

### ISSUE THREAD

**Issue by ignatenkobrain** [pocl/pocl#318]
```
 37/108 Test  #31: kernel/test_printf ..................................................................***Failed  Required regular expression not found.Regex=[Running test test_printf...
1
2
3
4
5
         6
0000000007
0000000008
9,9,9,9
1[.]0
2[.]000000
3[.]000000
4
5
  6[.]000000
7[.]0000000000
8[.]0000000000
9[.]000000,9[.]000000,9[.]000000,9[.]000000
[|]a[|]   b[|]c   [|]
[|]aa[|]  bb[|]cc  [|]dddddddddd[|]
[|]0x1[|] 0x2[|]0x3 [|]
OK
]  2.17 sec
```

**Comment by ignatenkobrain** [comment]
Full log: https://kojipkgs.fedoraproject.org//work/tasks/2651/13562651/build.log

**Comment by franz** [comment]
Sadly the full log is not any more useful. Run `ctest` with `--output-on-failure`  and maybe we'll have something better.

Looking at your cmake invokation in the full log.... 
* you realize `-DEXTRA_KERNEL_CXX_FLAGS` only affects a  small portion of the pocl code ?
* you will save your users a ton of trouble with ``-DKERNELLIB_HOST_CPU_VARIANTS=distro`` - this enables runtime detection of CPU

**Comment by ignatenkobrain** [comment]
> you realize -DEXTRA_KERNEL_CXX_FLAGS only affects a small portion of the pocl code ?
yes, I needed to put there because of -std=c++11. Otherwise it says something about isinf is not a macro

> you will save your users a ton of trouble with -DKERNELLIB_HOST_CPU_VARIANTS=distro - this enables runtime detection of CPU
added

> Run ctest with --output-on-failure and maybe we'll have something better.
trying

**Comment by ignatenkobrain** [comment]
```
  Don't know what CPU variants to use for kernel library on this platform.
```

**Comment by franz** [comment]
Can you try this patch

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 9aff256..2dabbdc 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -47,7 +47,7 @@ elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "armv7")
   set(ARMV7 1)
 elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "armv6")
   set(ARMV6 1)
-elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(i386|AMD64|x86_64)")
+elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(i.86|AMD64|x86_64)")
   if(POCL_DEVICE_ADDRESS_BITS MATCHES "32")
     set(I386 1)
   else()
diff --git a/lib/kernel/host/CMakeLists.txt b/lib/kernel/host/CMakeLists.txt
index b08e789..ef49d73 100644
--- a/lib/kernel/host/CMakeLists.txt
+++ b/lib/kernel/host/CMakeLists.txt
@@ -31,7 +31,7 @@ else()
   set(KERNEL_SOURCES ${SOURCES_WITHOUT_VML})
 endif()
 
-if(X86_64)
+if(X86_64 OR I386)
   list(APPEND KERNEL_SOURCES svm_atomics_x86_64.ll svm_atomics.cl)
 elseif(MIPS)
   message(STATUS "OpenCL 2.0 atomics are currently broken on MIPS")
```

if it works i'll push it into github.

**Comment by ignatenkobrain** [comment]
Yup, it works!

**Comment by ignatenkobrain** [comment]
But test is still failing: https://kojipkgs.fedoraproject.org//packages/pocl/0.13/2.fc25/data/logs/i686/build.log

**Comment by franz** [comment]
OK the logs are much more useful now... 

I see
```
Required regular expression not found.Regex=[Running test test_printf...
1
2
3
4
5
         6
0000000007
0000000008
9,9,9,9
1[.]0
2[.]000000
3[.]000000
4
5
  6[.]000000
7[.]0000000000
8[.]0000000000
9[.]000000,9[.]000000,9[.]000000,9[.]000000
[|]a[|]   b[|]c   [|]
[|]aa[|]  bb[|]cc  [|]dddddddddd[|]
[|]0x1[|] 0x2[|]0x3 [|]
OK
]  2.15 sec
```

... and  the actual output is:

```
Running test test_printf...
1
2
3
4
5
         6
0000000007
0000000008
8,-215338336,-143837548,9
1.0
2.000000
3.000000
4
5
  6.000000
7.0000000000
8.0000000000
0.000000,2.500000,-4811255200622669723775721195700224.000000,9.000000
|a|   b|c   |
|aa|  bb|cc  |dddddddddd|
|0x1| 0x2|0x3 |
OK
```

but I have no idea what's going on here. My wild guess is
```
-- The C compiler identification is GNU 6.0.0
-- The CXX compiler identification is GNU 6.0.0
```
it's a pre-release version of gcc, or no ? it possible it miscompiles some code ?

**Comment by ignatenkobrain** [comment]
> it's a pre-release version of gcc, or no ? it possible it miscompiles some code ? 
it's release version (https://gcc.gnu.org/gcc-6/changes.html)

it's possible that there is regression...

**Comment by franz** [comment]
https://gcc.gnu.org/
``Development: GCC 6.0``
.... doesn't look like release version to me.

**Comment by pjaaskel** [comment]
@ignatenkobrain if possible, please try in the exact system but with an older gcc. If this is due to gcc then it's probably indirectly due to miscompilation of LLVM.

**Comment by nponeccop** [comment]
Note that the bug still happens with

```
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
```

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision and/or the latest LLVM.
