### ISSUE TITLE
A set of the pocl tests fail after installation

### ISSUE THREAD

**Issue by fabriceanon** [pocl/pocl#321]
[pocl 0.14-pre] testsuite: 1 9 10 11 12 13 14 20 21 22 23 24 45 46 47 48 49 50 51 52 53 54 55 56 57 62 63 88 90 91 92 93 96 98 99 100 101 102 103 107 109 112 failed, 106 passed unexpectedly‏

I have attached the testsuite log file !

[testsuite.txt](https://github.com/pocl/pocl/files/205681/testsuite.txt)

**Comment by pjaaskel** [comment]
What do you mean by "after installation"? Before running make install, make check passes, but not immediately afterwards?

**Comment by kraiskil** [comment]
Test 1 tests that you are running the testsuite against the pocl just built. If this fails, then your ICD loader has picked up some other OpenCL implementation.
Try setting ```OCL_ICD_VENDORS=/etc/OpenCL/vendors/pocl.icd``` (or wherever pocl got installed to), assuming you are using ocl-icd as your ICD loader.

**Comment by franz** [comment]
@fabriceanon do you still have failures running the tests ?
