### ISSUE TITLE
Segmentation fault when compiling kernels

### ISSUE THREAD

**Issue by neheb** [pocl/pocl#332]
The actual error is: error: <invalid loc>: unknown target CPU 'generic'

It looks to be the same issue as #217 so I tried removing mesa-libOpenCl from my machine. I still get the issue.

edit:  the error got slightly clobbered. it's error invalid loc in parentheses.

edit2: forgot to mention. LLVM 3.8, pocl 0.13, fedora 24.

**Comment by pjaaskel** [comment]
Is this on a virtual machine by any chance?

**Comment by neheb** [comment]
No

**Comment by pjaaskel** [comment]
Please try pocl master, there is no one supporting the older versions.
