### ISSUE TITLE
Segmentation fault while compiling kernel 2

### ISSUE THREAD

**Issue by jsteube** [pocl/pocl#333]
With latest oclHashcat (you can clone it from github if you want to reproduce) I'm getting the following error:

    [2016-04-02 09:03:47.134876262] POCL: in fn llvm_codegen at line 106:
     *** INFO ***  executing [/usr/lib/llvm-3.8/bin/clang++  --target=x86_64-unknown-linux-gnu -    march=bdver1 -shared -lm -o /root/.cache/pocl/kcache/AP/JJEFHIAOKOMADKAGEOHHHMMDDINKIIBIOPONP/m12000_loop/64-1-1/m12000_loop.so /root/.cache/pocl/kcache/AP/JJEFHIAOKOMADKAGEOHHHMMDDINKIIBIOPONP/m12000_loop/64-1-1/m12000_loop.so.o]
    Segmentation fault (core dumped)

Here's GDB output:

    Core was generated by `./oclHashcat -b --opencl-device-types 1 -m 12000'.
    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0x00007f962fdf881c in _pocl_launcher_m12000_loop ()
       from /root/.cache/pocl/kcache/AP/JJEFHIAOKOMADKAGEOHHHMMDDINKIIBIOPONP/m12000_loop/64-1-1/m12000_loop.so
    [Current thread is 1 (Thread 0x7f962afed700 (LWP 7812))]
    (gdb) bt
    #0  0x00007f962fdf881c in _pocl_launcher_m12000_loop ()
       from /root/.cache/pocl/kcache/AP/JJEFHIAOKOMADKAGEOHHHMMDDINKIIBIOPONP/m12000_loop/64-1-1/m12000_loop.so
    #1  0x00007f962fdfae5b in _pocl_launcher_m12000_loop_workgroup ()
       from /root/.cache/pocl/kcache/AP/JJEFHIAOKOMADKAGEOHHHMMDDINKIIBIOPONP/m12000_loop/64-1-1/m12000_loop.so
    #2  0x0000000000000000 in ?? ()

However, if I run the above command from the commandline by utilizing POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES=1 so that the object is not getting deleted:

    $ /usr/lib/llvm-3.8/bin/clang++  --target=x86_64-unknown-linux-gnu -    march=bdver1 -shared -lm -o /root/.cache/pocl/kcache/AP/JJEFHIAOKOMADKAGEOHHHMMDDINKIIBIOPONP/m12000_loop/64-1-1/m12000_loop.so /root/.cache/pocl/kcache/AP/JJEFHIAOKOMADKAGEOHHHMMDDINKIIBIOPONP/m12000_loop/64-1-1/m12000_loop.so.o

It compiles cleanly. Maybe some environment variable causing problems when ran from pocl?

**Comment by pjaaskel** [comment]
Although I didn't get this same crash, there was a problem with the new pocl-binary code which I fixed in c5605a2.

At least this works for me here now:
```
 $ ./hashcat -b --opencl-device-types 1 -m 12000
hashcat (v3.00-beta-58-gd4cc8e3) starting in benchmark-mode...

Device #1: pthread-AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G, 16963/16963 MB allocatable, 3700Mhz, 4MCU

Hashtype: PBKDF2-HMAC-SHA1

Speed.Dev.#1.:    27182 H/s (71.62ms)

Started: Mon May 23 18:34:28 2016
Stopped: Mon May 23 18:34:32 2016 
 $ ./hashcat -b --opencl-device-types 1 -m 12000
hashcat (v3.00-beta-58-gd4cc8e3) starting in benchmark-mode...

Device #1: pthread-AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G, 16963/16963 MB allocatable, 3700Mhz, 4MCU

Hashtype: PBKDF2-HMAC-SHA1

Speed.Dev.#1.:    30268 H/s (90.04ms)

Started: Mon May 23 18:34:34 2016
Stopped: Mon May 23 18:34:38 2016 
 $ 

```

Please reopen if it still breaks for you.
