### ISSUE TITLE
Feature to disable most or all kernel compiler optimizations

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#338]
I'm opening this issue in response to your paper:

https://tutcris.tut.fi/portal/files/5075042/pocl.pdf

First of all, nice job--quite readable and very informative. The reason I'm poking you about it is because I'm interested in a discussion over what types of optimizations I think pocl should attempt. The reason why that's a matter that concerns me is because I would like the
performance I obtained from pocl to be reasonably understandable. The point of
this is that if I apply some sort of transformation to my input source code and
your composure then decides that, no, that was actually not a good idea and
then undoes it, that makes it hard for me to try and do any type of performance
optimization from the source code level. I would therefore like to argue for a
'performance-shallow' compiler that does the best it can in terms of
instruction selection, inlining and register allocation but that does not
perform any 'macro-level' code restructurings.

I'm opening this bug specifically because I read in the paper that pocl will
try to parallelize/ vectorize sequential loops given the opportunity. That's an
example of a type of transformation that I don't particularly like-- I would
prefer if that were made explicit in the input code. One particular reason that
makes me request that is because I am working on a [code transformation tool](https://github.com/inducer/loopy)
whose job it is to put such matters under user control, and thus for my use
case it is best if the code generation layer that follows my tool is as shallow
as possible.

Anyway, I'm putting this out there just to see what you guys think. Obviously
my use case is not the same as everybody else's, but ideally I would at least
like an option for this type of use-case to be available. One example of such a
performance-shallow tool is [ispc](https://ispc.github.io/), just to illustrate
that I'm not completely on my own in wanting this. :)

**Comment by pjaaskel** [comment]
pocl's kernel compiler like any other compiler should attempt all legal optimizations that are expected to improve performance of the end result. What "macro level optimizations" you refer to? Implementing work-items as parallel loops instead of, say, fine grained threads?

**Comment by inducer** [comment]
I guess this will make the most sense to try and figure out with the help of an
example. Suppose I give you code for a matrix matrix multiplication comma
written as simple sequential triple loops.

What type of code transformations would you consider in scope and what type of
code transformations would you consider out of scope in this case?

My point is that opencl is already quite specific in terms of how
parallelization is to be done. Thus I would consider it a bit of a mismatch if pocl
try to apply thread- or vector-level parallelism in this case.

**Comment by eschnett** [comment]
I guess what @inducer is trying to say is that he is working on high-level compiler optimizations that might or might not overlap with optimization passes already implemented in LLVM. If loo.py were to transform a loop in a particular way, and pocl then modifies or undoes this, then @inducer will not be able to understand the performance benefits (if any) of loo.py's transformations.

I would answer this question in terms of the LLVM optimization passes that pocl applies. If the passes are described, and if there is a way to disable some of them (without breaking pocl), then experimenting with additional "passes" (in the sense of source-code transformations to the OpenCL C code) becomes easier.

**Comment by Oblomov** [comment]
FWIW, I agree as a matter of principle with the idea of being able to disable each individual optimization pass when compiling kernels, or at leas the most «upsetting» ones. As an example, Intel's proprietary implementation of OpenCL on CPU autovectorizes; however, it's possible to disable autovectorization by giving a vector_type_hint attribute to the kernel. Something like this for pocl would be nice too.

**Comment by pjaaskel** [comment]
Sure, if you want to add a feature to optionally disable most or all optimizations and/or disable efficient multi-wi execution on CPUs, you are welcome to do so. 

It might make sense in your use case if you are willing to use OpenCL mostly as a software portability layer for a higher-level programming model with its own optimizations. But to claim loudly that by default OpenCL kernel compilers (or any compiler for that matter) should not try to optimize things is plain wrong.

If you see "a bad optimization" (that actually results in a slowdown) then the optimization itself should be fixed, and it is more likely a bug in LLVM as pocl uses its generic optimizations after the parallel loop formation. What pocl does in addition to those is pretty much trying to make originally GPU-optimized multi-wi WGs more efficient also on CPUs/MIMD machines (autovectorization/loop unrolling/pipelining/etc.).

You can start by trying to remove the STANDARD_OPTS in the list in 
https://github.com/pocl/pocl/blob/master/lib/CL/pocl_llvm_api.cc#L1212

Already at clBuildProgram time it might apply -O2, cannot recall, but likely not yet try to autovectorize your kernel loops, if that is what's bothering you.

**Comment by pjaaskel** [comment]
Please send a PR if you wish to add new features.
