### ISSUE TITLE
corrupted .so files in cache break succeeding runs

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#343]
If one, for example, has interrupted pocl while it is producing the .so, it leaves a corrupted .so in the cache which then fails to load when executing the app next time (from the cache). We should try to ensure harder that .so is not corrupted at least in the simple way of ctrl-c interruption e.g. by building to a temporary .so which is then moved to the correct named destination. 

In addition, if loading of the cached .so fails, it might as well delete the .so then a rebuild is attempted the next time.

**Comment by inducer** [comment]
Yep, seen that, too.

**Comment by pjaaskel** [comment]
Let's implement a simple safeguarding scheme for 0.14: build to a temporary file such as ```parallel-temp.so``` and only after a successful return, do a ```mv parallel-temp.so parallel.so```. Similarly for parallel.bc. 

This minimizes the window of time when the parallel.{so,bc} corruption can occur due to ctrl-c or similar process death reason to the run time of the mv which should be really minimal.

The proper safety measure would be to detect the failure to load the .so from the cache and try to rebuild it if fails, but it requires a bit more work as the logic to detect corruption it is not necessarily straightforward as the codegen and loading parts are separated in the code.
