### ISSUE TITLE
Segmentation fault in clEnqueueCopyBufferRect when an event is queried

### ISSUE THREAD

**Issue by sanguinariojoe** [pocl/pocl#349]
clEnqueueCopyBufferRect function is crashing if an event is required. You reproduce the bug in Piglit editing the file tests/cl/api/enqueue-copy-buffer-rect.c to read:

```
    cl_event e;
	err = clEnqueueCopyBufferRect(queue, device_src_buffer, device_dst_buffer,
				src_origin, dst_origin, region, src_row_pitch,
				src_slice_pitch, dst_row_pitch, dst_slice_pitch,
				0, NULL, &e);
	if (!piglit_cl_check_error(err, CL_SUCCESS)) {
		return PIGLIT_FAIL;
	}
```

Other similar functions, like clEnqueueCopyBuffer are working fine

**Comment by Oblomov** [comment]
Found the issue, I think I have a solution, let me check a few things.

**Comment by sanguinariojoe** [comment]
Thanks!

I'm waiting to become merged on master! Then I'll repeat the piglit test and let you know
