### ISSUE TITLE
clEnqueueReadBufferRect causes subsequent failures

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#353]
I haven't debugged this in detail, but if you run (in current PyOpenCL git)

```
PYOPENCL_TEST=portable python  test_enqueue_copy.py "test_enqueue_copy_rect_2d(cl._csc, False)"
```

or

```
PYOPENCL_TEST=portable python  test_enqueue_copy.py "test_enqueue_copy_rect_3d(cl._csc, False)"
```

odd failures occur:

```
PyOpenCL WARNING: a clean-up operation failed (dead context maybe?)
 failed with code -58
terminate called after throwing an instance of 'clerror'
  what():  
[1]    9793 abort      PYOPENCL_TEST=portable python test_enqueue_copy.py 
```

There's an error return from `clWaitForEvents` involved, too. The error path in PyOpenCL probably also isn't great, but I do believe that the root cause is pocl running into an issue. FWIW, AMD, Intel, and Nvidia have no problems with this test.

**Comment by Oblomov** [comment]
Is this with the current master?

**Comment by inducer** [comment]
Sorry, forgot to mention that: 5167ffd.

**Comment by pjaaskel** [comment]
Please try to reproduce with master.

**Comment by inducer** [comment]
Doesn't seem to happen with master.
