### ISSUE TITLE
Build broken with hwloc 2.0

### ISSUE THREAD

**Issue by mnhauke** [pocl/pocl#358]
hwloc 2.0 has incompatible changes in the API.
https://github.com/open-mpi/hwloc/wiki/Upgrading-to-v2.0-API

Here's a buildlog:
[pocl-gitmaster-build-broken-with-hwloc2.0.txt](https://github.com/pocl/pocl/files/322281/pocl-gitmaster-build-broken-with-hwloc2.0.txt)

**Comment by franz** [comment]
This has been fixed
