### ISSUE TITLE
kernel-i686-pc-linux-gnu.bc referenced - incorrect name?

### ISSUE THREAD

**Issue by BeanBagKing** [pocl/pocl#359]
I'm receiving the error "Kernel library file /usr/share/pocl/kernel-i686-pc-linux-gnu.bc doesn't exist."

Searching /usr/share/pocl, it appears that there is a "kernel-x86_64-pc-linux-gnu.bc", so my guess is something is referencing this by the incorrect name. Copying this to the i686 results in an "error: Invalid record"

To replicate:
Try running hashcat32.bin with the --force and -b flag on a 32bit linux VM.

**Comment by franz** [comment]
It's not referencing it by incorrect name; "kernel-i686-pc-linux-gnu.bc" is the correct name for 32bit pocl library bitcode (which you need for 32bit linux VM).

I'm guessing you somehow managed to install 64bit pocl on your 32bit VM. This isn't going to work; you must get a 32bit pocl for that VM.

**Comment by BeanBagKing** [comment]
Wow, yes, I'm an idiot. I don't know how I missed the reference to x64 right in my face.

That said, yes, I'm on a 32bit VM, and am getting the library's directly from the repository. So I'm not sure if this is a problem with pocl, the repository, the distribution..? Output below, if it helps you at all. If you have tips for me it would be much appreciated. 

> root@kali:~# uname -a
> Linux os-18776 4.5.0-kali1-686-pae #1 SMP Debian 4.5.5-1kali1 (2016-06-06) i686 GNU/Linux

I'm getting this from the repository, and just judgeing by the package names, everything seems to be 32-bit

> root@kali:~# apt-get install libpocl1
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following additional packages will be installed:
>   clang-3.7 libclang-common-3.7-dev libclang1-3.7 libhwloc-plugins libhwloc5 libllvm3.7 libpocl1-common llvm-3.7 llvm-3.7-dev
>   llvm-3.7-runtime pocl-opencl-icd
> Suggested packages:
>   gnustep gnustep-devel clang-3.7-doc libhwloc-contrib-plugins llvm-3.7-doc
> The following NEW packages will be installed:
>   clang-3.7 libclang-common-3.7-dev libclang1-3.7 libhwloc-plugins libhwloc5 libllvm3.7 libpocl1 libpocl1-common llvm-3.7
>   llvm-3.7-dev llvm-3.7-runtime pocl-opencl-icd
> 0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
> Need to get 64.8 MB of archives.
> After this operation, 277 MB of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Get:1 http://archive-7.kali.org/kali kali-rolling/main i386 libllvm3.7 i386 1:3.7.1-2 [10.3 MB]
> Get:2 http://archive-7.kali.org/kali kali-rolling/main i386 libclang1-3.7 i386 1:3.7.1-2 [4,453 kB]
> Get:3 http://archive-7.kali.org/kali kali-rolling/main i386 libclang-common-3.7-dev i386 1:3.7.1-2 [285 kB]
> Get:4 http://archive-7.kali.org/kali kali-rolling/main i386 clang-3.7 i386 1:3.7.1-2 [25.2 MB]
> Get:5 http://archive-7.kali.org/kali kali-rolling/main i386 llvm-3.7-runtime i386 1:3.7.1-2 [89.1 kB]
> Get:6 http://archive-7.kali.org/kali kali-rolling/main i386 llvm-3.7 i386 1:3.7.1-2 [1,597 kB]
> Get:7 http://archive-7.kali.org/kali kali-rolling/main i386 llvm-3.7-dev i386 1:3.7.1-2 [16.2 MB]
> Get:8 http://archive-7.kali.org/kali kali-rolling/main i386 libhwloc5 i386 1.11.3-2 [114 kB]
> Get:9 http://archive-7.kali.org/kali kali-rolling/main i386 libhwloc-plugins i386 1.11.3-2 [16.7 kB]
> Get:10 http://archive-7.kali.org/kali kali-rolling/main i386 libpocl1-common all 0.13-2 [680 kB]
> Get:11 http://archive-7.kali.org/kali kali-rolling/main i386 libpocl1 i386 0.13-2 [5,908 kB]
> Get:12 http://archive-7.kali.org/kali kali-rolling/main i386 pocl-opencl-icd i386 0.13-2 [13.4 kB]
> Fetched 64.8 MB in 5s (11.7 MB/s)      
> Selecting previously unselected package libllvm3.7:i386.
> (Reading database ... 371808 files and directories currently installed.)
> Preparing to unpack .../libllvm3.7_1%3a3.7.1-2_i386.deb ...
> Unpacking libllvm3.7:i386 (1:3.7.1-2) ...
> Selecting previously unselected package libclang1-3.7:i386.
> Preparing to unpack .../libclang1-3.7_1%3a3.7.1-2_i386.deb ...
> Unpacking libclang1-3.7:i386 (1:3.7.1-2) ...
> Selecting previously unselected package libclang-common-3.7-dev.
> Preparing to unpack .../libclang-common-3.7-dev_1%3a3.7.1-2_i386.deb ...
> Unpacking libclang-common-3.7-dev (1:3.7.1-2) ...
> Selecting previously unselected package clang-3.7.
> Preparing to unpack .../clang-3.7_1%3a3.7.1-2_i386.deb ...
> Unpacking clang-3.7 (1:3.7.1-2) ...
> Selecting previously unselected package llvm-3.7-runtime.
> Preparing to unpack .../llvm-3.7-runtime_1%3a3.7.1-2_i386.deb ...
> Unpacking llvm-3.7-runtime (1:3.7.1-2) ...
> Selecting previously unselected package llvm-3.7.
> Preparing to unpack .../llvm-3.7_1%3a3.7.1-2_i386.deb ...
> Unpacking llvm-3.7 (1:3.7.1-2) ...
> Selecting previously unselected package llvm-3.7-dev.
> Preparing to unpack .../llvm-3.7-dev_1%3a3.7.1-2_i386.deb ...
> Unpacking llvm-3.7-dev (1:3.7.1-2) ...
> Selecting previously unselected package libhwloc5:i386.
> Preparing to unpack .../libhwloc5_1.11.3-2_i386.deb ...
> Unpacking libhwloc5:i386 (1.11.3-2) ...
> Selecting previously unselected package libhwloc-plugins.
> Preparing to unpack .../libhwloc-plugins_1.11.3-2_i386.deb ...
> Unpacking libhwloc-plugins (1.11.3-2) ...
> Selecting previously unselected package libpocl1-common.
> Preparing to unpack .../libpocl1-common_0.13-2_all.deb ...
> Unpacking libpocl1-common (0.13-2) ...
> Selecting previously unselected package libpocl1:i386.
> Preparing to unpack .../libpocl1_0.13-2_i386.deb ...
> Unpacking libpocl1:i386 (0.13-2) ...
> Selecting previously unselected package pocl-opencl-icd.
> Preparing to unpack .../pocl-opencl-icd_0.13-2_i386.deb ...
> Unpacking pocl-opencl-icd (0.13-2) ...
> Processing triggers for libc-bin (2.22-11) ...
> Processing triggers for man-db (2.7.5-1) ...
> Setting up libllvm3.7:i386 (1:3.7.1-2) ...
> Setting up libclang1-3.7:i386 (1:3.7.1-2) ...
> Setting up libclang-common-3.7-dev (1:3.7.1-2) ...
> Setting up clang-3.7 (1:3.7.1-2) ...
> Setting up llvm-3.7-runtime (1:3.7.1-2) ...
> Setting up llvm-3.7 (1:3.7.1-2) ...
> Setting up llvm-3.7-dev (1:3.7.1-2) ...
> Setting up libhwloc5:i386 (1.11.3-2) ...
> Setting up libhwloc-plugins (1.11.3-2) ...
> Setting up libpocl1-common (0.13-2) ...
> Setting up libpocl1:i386 (0.13-2) ...
> Setting up pocl-opencl-icd (0.13-2) ...
> Processing triggers for libc-bin (2.22-11) ...

When trying to use the library though.

> root@kali:~/Desktop/hashcat-3.00# ./hashcat32.bin --force -b
> hashcat (v3.00-1-g67a8d97) starting in benchmark-mode...
> 
> OpenCL Platform #1: The pocl project
> - Device #1: pthread-Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz, 3031/3031 MB allocatable, 2MCU
> 
> Kernel library file /usr/share/pocl/kernel-i686-pc-linux-gnu.bc doesn't exist.

**Comment by franz** [comment]
I assume you're on Kali linux, derived from Debian ?

If so, i'm wildly guessing the problem is in your distribution, in package "libpocl1-common" to be precise. Looking at its file list: https://packages.debian.org/sid/all/libpocl1-common/filelist  they seem to have included the ``/usr/share/pocl/kernel-x86_64-pc-linux-gnu.bc`` but LLVM bitcode is not platform independent. So this file should definitely not be a part of libpocl1-common. 

So i'm guessing the easiest for you might be to rebuild the debian packages inside your 32bit VM...

**Comment by BeanBagKing** [comment]
Yes to the first comment. 

Thanks for the rest. I'll see what I can do.

**Comment by BeanBagKing** [comment]
It seems to be working. If anyone knows who I should report the repository issue to, or if it's even worth reporting, please let me know.
