### ISSUE TITLE
Automatic buffer migration doesn't always work

### ISSUE THREAD

**Issue by franz** [pocl/pocl#361]
Automatic migration in clEnqueueNDRange seems to depend on ``buffer->owning_device`` being not NULL. It's set up in clEnqueueFill/Map/Copy{Buffer,Image}. But in this case:

    q1 = clCreateCommandQueue(device 1);
    q2 = clCreateCommandQueue(device 2);
    p1 = (malloc pointer & fill the array with some values)
    b1 = clCreateBuffer(p1, CL_MEM_COPY_HOST_PTR);
    output1 = clCreateBuffer(CL_MEM_READ_WRITE);
    output2 = clCreateBuffer(CL_MEM_READ_WRITE);
    set kernel args (kernel, b1, output1);
    clEnqueueNDRange(q1, kernel);
    set kernel args (kernel, output1, output2);
    clEnqueueNDRange(q2, kernel);

``owning_device`` of buffer `output1` never gets set to any value, and it doesn't get migrated before the 2nd enqueue.

**Comment by franz** [comment]
I'm guessing we could either
* set up the first device as owner at clCreateBuffer() and let clEnqueueNDRange() migrate
* setup the owner at clEnqueueNDRange() - buffer owners should not be NULL while the kernel is running..

@visit0r  @vkorhonen ideas ?

**Comment by vkorhonen** [comment]
The first device using the buffer should claim it, because no device has any relevant data in that buffer yet. So that fix is all good.
