### ISSUE TITLE
Building llvm with RTTI for pocl

### ISSUE THREAD

**Issue by noma** [pocl/pocl#363]
Hi, I am trying pocl and followed these instructions:
http://portablecl.org/docs/html/install.html

I used an llvm 3.8.0 source tree, and the
```
make REQUIRES_RTTI=1
```
did not do the trick, neither did putting `REQUIRES_RTTI=1` into the environment. Pocl's CMake scripts kept complaining about llvm not being built with RTTI.

What solved the issue was calling cmake for llvm with `-DLLVM_ENABLE_RTTI=TRUE`. I guess the documentation is outdated on that one.

**Comment by kraiskil** [comment]
Perhaps it is time to remove the documented RTTI requirement completely? It is needed only for the TCE backend.
