### ISSUE TITLE
[pyopencl regression] Inaccurate result from float32*complex64 (single prec) dot product (reduction)

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#370]
Run

```
PYOPENCL_TEST=portable python test_algorithm.py 'test_dot(cl._csc)' 
```

Observe

```
<class 'numpy.float32'> <class 'numpy.float32'>
<class 'numpy.float32'> <class 'numpy.complex64'>
Traceback (most recent call last):
  File "test_algorithm.py", line 971, in <module>
    exec(sys.argv[1])
  File "<string>", line 1, in <module>
  File "test_algorithm.py", line 374, in test_dot
    assert abs(dot_ab_gpu - dot_ab) / abs(dot_ab) < 1e-4
AssertionError
```

Tried to bisect this at (what looked like) the major merge points in the 0.14 cycle. Did not have much luck--here's a log:
- a62d357d94000fb23a306e1093e0417a9e4d3df1 (2016-07-30, current master)           : AssertionError (inaccurate result)
- 698917e8aee1304be5f78dbfda6cc68eba8555c1 (2016-06-01, 'email-fixes')            : AssertionError (inaccurate result)
- 4f140ecbd1575ed7b8caa8a7353b61e4ab0639d7 (2016-05-19, jrprice llvm-trunk)       : symbol lookup error: /opt/pocl-build/lib/libpocl.so.1.7.0: undefined symbol: clReleaseEvent
- 86426a11d04d143ee95fc2be1e8b063415397356 (2016-04-25, Oblomov/device-image-info): symbol lookup error: /opt/pocl-build/lib/libpocl.so.1.7.0: undefined symbol: clReleaseEvent
- 14d9bbdf8a5c69a97ef770407149425f314b02a4 (2016-04-06, fixes franz)              : symbol lookup error: /opt/pocl-build/lib/libpocl.so.1.7.0: undefined symbol: clReleaseEvent
- f24dcb93c0a01d0ea48132d2b01b881f0aecf847 (2016-03-16, OoO_to_publish)           : (build) fatal error: pocl_cl.h: No such file or directory
- c63da64b741eb204bfead8cc46bb0d517e73926e (2016-02-09, various_fixes2 franz)     : (build) clang segfault in svm-atomics
- 9179d6802e3e8914c8b30e05cdb10a78ea259e69 (2015-12-07, LLVM 3.6 fixes?)          : LLVM 3.8 unsupported

This test passes with pocl 0.13.

**Comment by pjaaskel** [comment]
Running test_algorithms.py now crashes with ```static llvm::CastInst* llvm::CastInst::Create(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, const llvm::Twine&, llvm::Instruction*): Assertion `castIsValid(op, S, Ty) && "Invalid cast!"' failed.``` for LLVM 3.7-LLVM 3.8. Building a debug-enabled LLVM to find what's wrong. The .cl doesn't seem to do anything too bold.

**Comment by pjaaskel** [comment]
This is a yet another issue that would be hidden by not using the fake address space map. I isolated the Clang crash to the following snippet:

```OpenCL
typedef unsigned uint4  __attribute__((__ext_vector_type__(4)));
typedef struct { long a; long b; } ctr_t;
typedef uint4 key_t;

ctr_t foobar(ctr_t ctr, key_t key);

uint4 test(key_t *key, ctr_t *ctr) {
  union {
    ctr_t ctr_el;
    uint4 vec_el;
  } u;

  u.ctr_el = foobar(*ctr, *key);
  return u.vec_el;
}
```

```clang -cl-std=CL2.0 -Xclang -ffake-address-space-map -x cl ~/temp/union-arg.cl -emit-llvm -S -o -``` crashes, but if one uses CL1.2 or drops the fake-address-space-map, it generates the code OK.

I'm not going to report this to LLVM, but see if we should still use CL1.2 by default as we are far from CL2.0 compliance and really try to find time to drop the fake-address-space-map early in the next release cycle.

**Comment by pjaaskel** [comment]
Started working on the TAS removal: #394

**Comment by inducer** [comment]
With pocl master (13c9512) with llvm 4.0 (7e59634b25a) and clang 4.0 (870923f42a):

```
/home/andreask/src/env-3.5/lib/python3.5/site-packages/pytest-3.0.6-py3.5.egg/_pytest/assertion/rewrite.py:7: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
<class 'numpy.float32'> <class 'numpy.float32'>
1 warning generated.
2 warnings generated.
/home/andreask/src/pyopencl/pyopencl/cffi_cl.py:1469: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)
1 warning generated.
2 warnings generated.
1 warning generated.
2 warnings generated.
<class 'numpy.float32'> <class 'numpy.complex64'>
1 warning generated.
2 warnings generated.
1 warning generated.
2 warnings generated.
1 warning generated.
2 warnings generated.
1 warning generated.
2 warnings generated.
Traceback (most recent call last):
  File "test_algorithm.py", line 972, in <module>
    exec(sys.argv[1])
  File "<string>", line 1, in <module>
  File "test_algorithm.py", line 390, in test_dot
    assert rel_err < 1e-4, rel_err
AssertionError: 0.713234
```

**Comment by inducer** [comment]
If you're curious, the compiler warnings are all

```
TODO: printf for Clang 4.0+
```

from which I'm concluding they're unrelated.

**Comment by pjaaskel** [comment]
Great news!

**Comment by pjaaskel** [comment]
Wait, I didn't notice the assertion error at the end. You mean that it still fails with 4.0 like it used to? I think the TAS patch took care of this for 3.9 and it should be upstreamed to LLVM 4.0.

**Comment by inducer** [comment]
Yeah, still the same failure as before.

**Comment by inducer** [comment]
(Just retested, with all patches applied, a clean cache, and the pocl 0.13 complex-number workaround in PyOpenCL disabled.)

**Comment by pjaaskel** [comment]
I now get this with LLVM 4.0 with the spirkernabi patch applied:
```
POCL_DEVICES=basic POCL_DEBUG=0 PYOPENCL_TEST=portable python test/test_algorithm.py 'test_dot(cl._csc)' 
<type 'numpy.float32'> <type 'numpy.float32'>
<type 'numpy.float32'> <type 'numpy.complex64'>
<type 'numpy.float32'> <type 'numpy.float64'>
<type 'numpy.float32'> <type 'numpy.complex128'>
Traceback (most recent call last):
  File "test/test_algorithm.py", line 972, in <module>
    exec(sys.argv[1])
  File "<string>", line 1, in <module>
  File "test/test_algorithm.py", line 368, in test_dot
    b_gpu = general_clrand(queue, (200000,), b_dtype)
  File "/home/visit0r/src/pyopencl/test/test_array.py", line 58, in general_clrand
    return clrand(queue, shape, real_dtype) + 1j*clrand(queue, shape, real_dtype)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2016.2-py2.7-linux-x86_64.egg/pyopencl/array.py", line 990, in __rmul__
    common_dtype.type(scalar), self, self.dtype.type(0)))
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2016.2-py2.7-linux-x86_64.egg/pyopencl/array.py", line 210, in kernel_runner
    knl = kernel_getter(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2016.2-py2.7-linux-x86_64.egg/pyopencl/array.py", line 743, in _axpbz
    a.dtype, x.dtype, b.dtype, out.dtype)
  File "<string>", line 2, in get_axpbz_kernel
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2016.2-py2.7-linux-x86_64.egg/pyopencl/tools.py", line 96, in first_arg_dependent_memoize
    result = func(cl_object, *args)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2016.2-py2.7-linux-x86_64.egg/pyopencl/elementwise.py", line 629, in get_axpbz_kernel
    name="axpb")
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2016.2-py2.7-linux-x86_64.egg/pyopencl/elementwise.py", line 178, in get_elwise_kernel
    name=name, options=options, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2016.2-py2.7-linux-x86_64.egg/pyopencl/elementwise.py", line 166, in get_elwise_kernel_and_types
    kernel.set_scalar_arg_dtypes(get_arg_list_scalar_arg_dtypes(parsed_args))
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2016.2-py2.7-linux-x86_64.egg/pyopencl/cffi_cl.py", line 1951, in set_scalar_arg_dtypes
    % (cl_arg_idx, self.num_args))
TypeError: length of argument list (8) and CL-generated number of arguments (7) do not agree
```

**Comment by pjaaskel** [comment]
(I have a local uncommitted fix though for #371)

**Comment by pjaaskel** [comment]
OK now committed. The error sounds like it's still kernel ABI related somehow? Do I need to remove some workaround in pyopencl?

**Comment by pjaaskel** [comment]
This is my PyOpenCL test status now: https://gist.github.com/pjaaskel/725e113345161f3168f4c4b3bc1e1414

**Comment by inducer** [comment]
This crudely disables the workaround:

```
diff --git a/pyopencl/cffi_cl.py b/pyopencl/cffi_cl.py
index c1848a1..314f15a 100644
--- a/pyopencl/cffi_cl.py
+++ b/pyopencl/cffi_cl.py
@@ -1893,7 +1893,7 @@ class Kernel(_Common):
                 else:
                     raise TypeError("unexpected complex type: %s" % arg_dtype)
 
-                if (work_around_arg_count_bug == "pocl"
+                if (work_around_arg_count_bug == "pocliiii"
                         and arg_dtype == np.complex128
                         and fp_arg_count + 2 <= 8):
                     gen(
```

I'll add code to more robustly distinguish 0.13 and 0.14 and only use the workaround when needed.

**Comment by inducer** [comment]
Also, thank you for being receptive towards these bug reports and towards getting them resolved for 0.14!

**Comment by inducer** [comment]
I can confirm that the PyOpenCL test suite runs to completion (and passes) with c9b6bcd4dae4b87327c73befeb676a5bc580f140 and llvm/clang master with the patch from #1. I'll test it on our higher-level stuff later tonight.

I'm super excited about this. Thank you for your help!

cc @mattwala

**Comment by pjaaskel** [comment]
I'm probably even more excited about the fact that I finally found a couple of straight hours to focus on these regressions.Thanks for your patience!

**Comment by pjaaskel** [comment]
Hmm. It still fails here (with the above backtrace) even with that workaround disabled.

**Comment by inducer** [comment]
Did you delete the PyOpenCL cache? `~/.cache/pyopencl/`

**Comment by pjaaskel** [comment]
Yes.

**Comment by inducer** [comment]
Huh, odd. Runs fine for me.

**Comment by pjaaskel** [comment]
I forgot I had installed pyopencl system-wide, and thought I was executing it from the build/source tree. Thus, make install (of the workaround removed version) fixed this.

**Comment by inducer** [comment]
As i think about getting PyOpenCL to be operational with pocl 0.14, I was wondering if there could be a way for me to programmatically determine whether the patch from #1 has been applied. I know I could compile a kernel and check the arg count--any other way that you could suggest (or create, or have me submit a patch for)?

**Comment by pjaaskel** [comment]
Yes, that would be useful for pocl cmake too until the patch has been upstreamed. If a kern func is spir kern cc even for non spir target, the patch has been applied. It shows in the BC.

**Comment by inducer** [comment]
#441
