### ISSUE TITLE
[cygwin64] illegal instructions

### ISSUE THREAD

**Issue by flriancu** [pocl/pocl#379]
Cheers again, I downloaded [pocl 0.13-2](https://cygwin.com/ml/cygwin/2016-07/msg00239.html) under Cygwin 64-bit / GCC 5.4.0 and the [SHOC](https://github.com/vetter/shoc) benchmark suite just to see how the different implementations on my computer behave.

Since pocl was silently failing, I came up with a simple program and went into it with gdb. On calling `clEnqueueReadBuffer` in blocking mode, `clFinish` or `clWaitForEvents`, [this happens](http://pastebin.com/raw/7avfBTH0). In that paste, `kernel_id` is the name of the function from the `.cl` file: `__kernel void kernel_id`.

Now, according to [this discussion](http://stackoverflow.com/questions/38058325/program-received-signal-sigill-illegal-instruction), `vmovss` requires an instruction set which I most certainly do not have (my processor is [this one](http://ark.intel.com/products/41315/Intel-Core-i7-870-Processor-8M-Cache-2_93-GHz)). I recompiled with `-mno-` switches [for everything](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html) AVX-related, then with different `-march`es and `-mtune`s, but they have no effect; the AVX-512 instructions are still there. Is this bug related to gcc, pocl or possibly my program?

**Comment by eschnett** [comment]
How exactly are you setting your CPU flags -- which configure or cmake variables are you setting? Note that there are two kinds of flags; those that define how to compile the C/C++ code, and those that define how to compile the kernel code.

**Comment by flriancu** [comment]
Literally 5 seconds after my post, I commented the body of the `kernel_id` function and pocl finished normally. This is the code:

`__kernel void kernel_id(__global float* output) {`
`	uint gid = get_global_id(0);`
`	uint lid = get_local_id(0);`
`	output[gid] = (float)gid + (float)lid * 0.01f;`
`}`

The last line of code seems to be the problem. The global and local sizes for `clEnqueueNDRangeKernel` are 128 and 32, respectively.

**Comment by flriancu** [comment]
@eschnett if you mean the flags that `clBuildProgram` should optionally receive, there are none.

**Comment by eschnett** [comment]
@flriancu No. You said you "recompiled with `-mno-` switches". How exactly did you do this? I want to find out whether the kernel compiler actually received these switches. The kernel compiler also receives some default switches from pocl, in addition to those you set via `clBuildProgram `.

**Comment by eschnett** [comment]
... put differently: did you try setting any of
```
  CLANG       Program to compile kernels to bytecode
  CLANGXX
  CLFLAGS     Flags to be used when compiling CL sources
  CLANGXX_FLAGS
              Flags to be used when compiling C++ sources with clang
```
?

**Comment by flriancu** [comment]
@eschnett No, I merely used a simple [makefile](http://pastebin.com/raw/1xUTUXyX), since I wanted to keep things as simple as possible. So those flags (surely) never reached the kernel compiler. Where should one set `CLFLAGS`? Should pocl be built in the first place with the desired `-march`, or can I specify it when building my program?

**Comment by eschnett** [comment]
These flags are set via environment variables when calling `./configure`. `./configure --help` should list them, and give further instructions.

**Comment by pjaaskel** [comment]
FYI, autotools are deprecated and is likely removed in the next release cycle, please use/fix cmake instead.

**Comment by eschnett** [comment]
I believe the respective cmake flags are called `EXTRA_KERNEL_CL_FLAGS` (for OpenCL C) and `EXTRA_KERNEL_CXX_FLAGS` (for C++ code).

By way of explanation -- we implement part of the kernel library that is compiled ahead of time in C++ instead of OpenCL C; this is merely a "syntactic" front-end choice and does not influence how OpenCL kernels are generated. If you want to override how the architecture is chosen, then you might need to set both variables.

**Comment by flriancu** [comment]
Please correct me if I'm wrong. So if I do want to override the architecture (e.g. not use some instruction sets), I should set these two variables before building pocl, in the configuration step.
On a related note, if I may ask, since the Cygwin version was build to generate AVX-512 instructions, what CPUs did you use for testing? [As far as I can see](https://en.wikipedia.org/wiki/AVX-512#CPUs_with_AVX-512), it needs some pretty powerful hardware.

**Comment by eschnett** [comment]
The `vmulss` instruction is already part of AVX, which is different from AVX2 and AVX-512. AVX instructions became available in 2011.

**Comment by franz** [comment]
The EXTRA_KERNEL_CL_FLAGS and EXTRA_KERNEL_CXX_FLAGS are not for CPU; there is a specific CMake variable for CPU to be used by kernel compilation, called "LLC_HOST_CPU". Its default value is determined by output of `llc --version`, parsing the line `Host CPU: ....`

It's possible llvm is unable to guess your CPU correctly. In that case simply run CMake with `-DLLC_HOST_CPU=<value>`. You can get the possible values by running `llc -mcpu help`

**Comment by flriancu** [comment]
@eschnett I was referring to `vmovss` which was introduces with [AVX-512](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=vmovss). Meanwhile I built pocl separately for Nehalem using Autotools and it now works. My original issue was with the Cygwin64 version.

**Comment by eschnett** [comment]
Glad to hear that.

`vmovss` was introduced with AVX, not AVX-512. AVX-512 extended the `vmovss` instruction to accept larger vector sizes, but that wasn't used in your code. The web page to which you're pointing searches by C-language intrinsics, not machine instructions, which is why it doesn't find an entry for `vmovss`. The AVX-512 intrinsics it finds only happen to have names that are "similar" to `vmovss`.

**Comment by flriancu** [comment]
@eschnett You learn something new everyday. Thanks! I guess you can mark this issue solved.
As a side question, is there a comprehensive reference for these various machine instruction sets?

**Comment by eschnett** [comment]
Intel's machine instructions are defined [here](http://www.intel.com/content/www/us/en/processors/architectures-software-developer-manuals.html). You want to look at volume 2. This has all the gory details. Thousands of pages. `vmovss` (together with `movss`) is described on pages 1240 - 1243. If you haven't looked at this manual before, then also have a look a volume 2, chapter 1, which contains "instructions" for reading that part of the manual.

AMD has its equivalent reference manuals, and so do IBM (Power), ARM, etc.
