### ISSUE TITLE
Missing symbol when using native_exp with doubles

### ISSUE THREAD

**Issue by pavanky** [pocl/pocl#385]
```
undefined symbol: _Z14_cl_native_expd
```

I have been able to reproduce this on multiple machines all running pocl 0.13

**Comment by pjaaskel** [comment]
I guess it is just unimplemented.

**Comment by jrprice** [comment]
The `native_` math functions are only defined for `float` inputs. The OpenCL spec does not define these functions for double values.

**Comment by pjaaskel** [comment]
Thanks for the info.

**Comment by pavanky** [comment]
@jrprice Any source on this ?

**Comment by pavanky** [comment]
Ok, I went back and looked, the clarification about `native_` functions supporting only floats was made in 2.0 but not earlier. 

If you plan to comply with the spec, shouldn't the error during compilation or downcast doubles to floats ? 

Having a missing symbol error occur during runtime is not normal behavior.

**Comment by jrprice** [comment]
[OpenCL-C 2.0 spec, rev34.](https://www.khronos.org/registry/cl/specs/opencl-2.0-openclc.pdf)

Table 6.9 on page 79 defines the `native_` functions. Just prior to this table, there is this text:

> We use the generic type name gentype to indicate that the functions in table 6.9 can take float, float2, float3, float4, float8 or float16 as the type for the arguments.

This is in contrast to the regular math functions, which also include `double*` types in the list of possible values for `gentype`.

**Comment by jrprice** [comment]
> the clarification about native_ functions supporting only floats was made in 2.0 but not earlier.

I believe this is also the case in the OpenCL 1.2 spec.

> If you plan to comply with the spec, shouldn't the error during compilation or downcast doubles to floats ?

Yes, pocl should probably give a compilation error, I guess it has some auto-generated declarations for these functions that shouldn't be there.

I'm sure there are platforms out there that happen to work with these functions as a developer convenience (I've come across this in the past myself), so the other option would just be to implement them in pocl anyway.

**Comment by pavanky** [comment]
> I believe this is also the case in the OpenCL 1.2 spec.

Not really.. They do not mention differences between `native_func` and `func` from the datatype point of view, but they do mention the differences in precision.

They have a single unified note as can be seen here:
https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/exp.html

> I'm sure there are platforms out there that happen to work with these functions as a developer convenience..

This is what I noticed with other implementations. pocl was the first to throw an error.

@pjaaskel 

Do you want to reopen the issue so atleast the runtime error can be fixed (even if the "feature" is not supported).
