### ISSUE TITLE
In case using Clang 3.9+, use its opencl-c.h instead of our own header

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#388]
See: http://llvm.org/releases/3.9.0/tools/clang/docs/ReleaseNotes.html#opencl-c-language-changes-in-clang

**Comment by pjaaskel** [comment]
There's a switch in clang for this: -finclude-default-header

**Comment by pjaaskel** [comment]
This might be useful to make it more robust and possibly benefit from OpenCL-type specific optimizations etc. added.

**Comment by franz** [comment]
This may be not as simple as it looks like. First i've discovered it broke memfence(), now i found out it completely breaks images (#515). I've looked into opencl-c.h and it seems our friends at LLVM went on a bit of an optimization frenzy, and added a bunch of attributes on pretty much every function in kernel library. This by itself requires "only" fixing the entire pocl's kernel library macros, but there is worse:

```
int __ovld __cnfn get_image_width(write_only image1d_t image);
int __ovld __cnfn get_image_channel_data_type(read_write image2d_t image);
```

all of `get_image_*()` have __cnfn, which is `__attribute__(const)` which AFAICT forbids reading global memory, which is a problem because pocl maps opaque image types to pointers to dev_image_t. I'm not sure why LLVM developers assume these attributes when image types are opaque (unless i'm mistaken) ?

I suggest we comment out the opencl-c.h for now, and deal with this after the upcoming release. @pjaaskel  ideas ?

**Comment by pjaaskel** [comment]
Sure we can disable the opencl-c.h if it seems too much work (this is not a high priority feature by no means), but I'd like to understand why the const attribute breaks the image getters. Why does it "forbid reading global memory"? And why only reading would break constness?

**Comment by franz** [comment]
> why the const attribute breaks the image getters

It doesn't - i used it as an example of how sometimes the header is just incompatible with pocl's implementation. What's actually broken is all of read_image{i,ui,f}*

> Why does it "forbid reading global memory"?

AFAICT that's the defining feature of attribute "const" (and what makes it different from attribute "pure"). Attribute const means the function's return value depend **only** on its arguments, and the compiler is free to optimize it as such. opencl-c.h makes this promise, but then pocl's implementation breaks this promise. This *seems* to work so far with the getters (they pass conformance tests), but lying to the compiler doesn't seem very healthy...

**Comment by pjaaskel** [comment]
> AFAICT that's the defining feature of attribute "const" 

I thought you meant 'global' as in the global address space of OpenCL C. What global state (that is not transferred in the argument objects) do those img function implementations then use that break the promise?

**Comment by franz** [comment]
From [GCC docs on function attributes:](https://gcc.gnu.org/onlinedocs/gcc-6.3.0/gcc/Common-Function-Attributes.html#Common-Function-Attributes)

> const
> Many functions do not examine any values except their arguments, and have no effects except the return value. Basically this is just slightly more strict class than the pure attribute below, since **function is not allowed to read global memory.**
> **Note that a function that has pointer arguments and examines the data pointed to must not be declared const.** Likewise, a function that calls a non-const function usually must not be const. It does not make sense for a const function to return void.

This is GCC but i doubt it's different for Clang / LLVM. So, pocl breaks the promise by casting the image type to _dev_image_t\*_ and then dereferencing it. I don't know which optimization  would possibly break by this, but then again i'm no compiler expert. Do you think it's harmless ?

Anyway, i'd like to leave this bug open for a while as reminder, i'll take a better look at the attributes & constants in the LLVM header, rerun all tests and see if anything else is broken.

**Comment by pjaaskel** [comment]
I don't still understand why the constness promise would be broken by casting the opaque type to the concrete type behind. It's still dealing with the function's input data only? Is there some special casting going on in this case or does LLVM somehow assume the structure of the pointed to data when it shouldn't?

**Comment by Oblomov** [comment]
The concrete type behind the opaque type in this case is essentially a pointer to the image data and metadata, so inspecting that would violate the const attribute.

**Comment by pjaaskel** [comment]
OK, got it.
