### ISSUE TITLE
[pocl_binary] cleanup the 'default_kernels' code

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#390]
For what I could extract from the original author, the default_kernels code was originally meant to be an optimization: When the kernels are implicitly created for serializing the program binary, they could be reused later in clCreateKernel calls. However this was never done and the code was not documented to reflect this idea. Also the default_kernels really would not need to build the kernels itself, but they are needed only for metadata in the binary creation.

A step better way would be to not have a separate default_kernels container, but just use the regular kernel creation code. When needing the kernels for the metadata in the binary building, mark the kernels as "implicit" to differentiate from the kernels explicitly created by the user via clCreateKernel calls. Then this has to be taken in account in clReleaseProgram, which should release the implicitly created kernels to allow the reference count of the program itself to reach zero.  This is currently broken in poclcc because the hidden default kernels do not release the program they retain.

**Comment by franz** [comment]
To clarify on the "optimization": clCreateKernel() calls pocl_llvm_get_kernel_metadata(). If you created a program from binaries, and you didn't have metadata saved somewhere (e.g. "default kernels"), you'd have to reparse the entire binary and find the kernel metadata. This seemed dumb & unnecessary to do on every clCreateKernel call.

OTOH The "default kernels" was a hack to avoid adding a lot more churn to an already big pull request. The proper solution would be an array of "kernel_metadata" structs in program, and have cl_kernel contain just a pointer to this. I suspect this'll require some changes in multiple parts (create kernel/program, pocl_binary.c, pocl llvm api.cc)

**Comment by pjaaskel** [comment]
I would not bother optimizing this spot yet, code clarity and robustness is more important in this case for now. My gut feeling is that not many programs parse the metadata when loading from binaries often enough to make this a bottleneck.

**Comment by franz** [comment]
Pocl needs the metadata, every time :-) you cannot call clSetKernelArg() without knowing types and sizes of kernel arguments (and for programs created from binaries, the only way is to get the metadata from the binary).

But no it's not a bottleneck. If you really want, you can change it to binary parsing at each clCreateKernel.

**Comment by pjaaskel** [comment]
OK. I didn't know it's needed also in clSetKernelArg(), you referred to calling clCreateKernel multiple times. Let's add the kernel_metadata struct or the implicit kernel flag, should work either way.
