### ISSUE TITLE
[benchmarks] pocl does not pass Rodinia/LUD

### ISSUE THREAD

**Issue by flriancu** [pocl/pocl#392]
Cheers, commit [6cfa227](https://github.com/pocl/pocl/commit/6cfa227) (and older, but I didn't test with anything newer) fails with the [LUD](https://github.com/kkushagra/rodinia/tree/master/opencl/lud) benchmark from Rodinia. [Here's](http://pastebin.com/raw/xPUKqcWf) the output from the benchmark, unmodified.
The code was just modified to use the CPU (added `use_gpu = 0` [around here](https://github.com/kkushagra/rodinia/blob/master/opencl/lud/ocl/lud.cpp#L49)). I checked with some proprietary implementations but they seem to pass the verification stage.

**Comment by pjaaskel** [comment]
OK. Please try with LLVM 3.9 and the pocl HEAD. Also, it will be helpful to know if it's a regression or not, that is, is there an older version of pocl with which that passes.

**Comment by flriancu** [comment]
LLVM/Clang 3.9 with [8664f8a](https://github.com/pocl/pocl/commit/8664f8aeef371ca0ee8d7651794f43c69674a110) (current) behaves the same, same goes for Cygwin64 version 0.13-2.

**Comment by pjaaskel** [comment]
Please try with the latest pocl master and LLVM 5.0.

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision and/or the latest LLVM.
