### ISSUE TITLE
[PyOpenCL testsuite] Wrong result in test_subset_minmax

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#398]
Using pocl a2a03108bb1ee0ad8409d8ff63542edb999239ef and llvm ef867d47bfccedd01ff64ebaa702563b384dc863 (3.9 branch), this here:

```
python test_algorithm.py 'test_subset_minmax(cl._csc)'
```

reports

```
Traceback (most recent call last):
  File "test_algorithm.py", line 971, in <module>
    exec(sys.argv[1])
  File "<string>", line 1, in <module>
  File "test_algorithm.py", line 344, in test_subset_minmax
    assert min_a_gpu == min_a
AssertionError
```

i.e. a wrong result. This is a reduction-type workload that uses structs. (But not as kernel arguments.)

**Comment by inducer** [comment]
Clang is ef867d47bfccedd01ff64ebaa702563b384dc863 with the patch from #394.

**Comment by inducer** [comment]
Accidentally built a debug build, so testing this was dog-slow, but it seemed to work. Building a release build now, will report back in a bit.

**Comment by pjaaskel** [comment]
Can you please also check the other pyopencl regressions blocking 0.14: https://github.com/pocl/pocl/milestone/7 thanks.

**Comment by inducer** [comment]
#433 notwithstanding, this appears to work OK now. Thank you for taking care of it!

**Comment by pjaaskel** [comment]
@inducer is this with the no-TAS patch or without?

**Comment by inducer** [comment]
Most of the no-TAS patch seems to have made it into upstream clang at the revision with which I was testing. The only missing bit was a test, which I concluded was not relevant to what I was trying to do. FWIW, I'm testing with just vanilla `release_40` LLVM/clang.

**Comment by inducer** [comment]
Should I be using 3.9 instead?

**Comment by pjaaskel** [comment]
Sorry I meant the other patch that should fix the long standing struct args (Issue #1). Do you have that applied? LLVM 4.0 still has issues to solve. Hopefully Soon they are gone as well if some extra time appears ;)

**Comment by inducer** [comment]
This works with and without the patch from #1. (I added that a while ago, but did not initially have it.)

**Comment by pjaaskel** [comment]
OK, thanks.
