### ISSUE TITLE
 [PyOpenCL testsuite] Wrong result in test_dot

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#399]
Same situation as #398.

```
python test_algorithm.py 'test_dot(cl._csc)'
```

reports

```
<class 'numpy.float32'> <class 'numpy.float32'>
<class 'numpy.float32'> <class 'numpy.complex64'>
Traceback (most recent call last):
  File "test_algorithm.py", line 971, in <module>
    exec(sys.argv[1])
  File "<string>", line 1, in <module>
  File "test_algorithm.py", line 374, in test_dot
    assert abs(dot_ab_gpu - dot_ab) / abs(dot_ab) < 1e-4
AssertionError
```

This is also using structs in a reduction setting. (note the `complex64`)

**Comment by tom-gall** [comment]
Here's the output and a little bit dumping of data for what is being compared in the assertion that fails: 
<type 'numpy.float32'> <type 'numpy.complex64'>
dot_ab_gpu
(39858.6484375+0j)
dot_ab
(49951.7+50042.5j)
Traceback (most recent call last):
  File "test_algorithm.py", line 979, in <module>
    exec(sys.argv[1])
  File "<string>", line 1, in <module>
  File "test_algorithm.py", line 378, in test_dot
    assert abs(dot_ab_gpu - dot_ab) / abs(dot_ab) < 1e-4
AssertionError

Likewise, here's a 'working' pyopencl on OS X using their intel driver:
<type 'numpy.float32'> <type 'numpy.complex64'>
dot_ab_gpu
(49845.2109375+49872.5j)
dot_ab
(49844.9+49872.6j)
vdot_ab_gpu
(49845.2109375+49872.5j)
vdot_ab
(49844.9+49872.6j)
