### ISSUE TITLE
Build fails when LLVM source/build directories are not accessible

### ISSUE THREAD

**Issue by jrprice** [pocl/pocl#403]
If I try and build pocl when I don't have access to the LLVM source/build directories, CMake fails:

    cc1plus: error: /root/src/llvm/3.9/tools/clang/include: Permission denied

This is a result of [these lines in `cmake/LLVM.make`](https://github.com/pocl/pocl/blob/3fef5b58014c40e3e746a7ada281498582d8d569/cmake/LLVM.cmake#L193-L197), which seem to allow for LLVM to be used from the build directory instead of an installed directory. If I get rid of these lines everything works for me, but I guess this would probably break things for anyone who might be using LLVM in a non-installed location.

I don't think my use case is uncommon - the `root` user on this machine built LLVM in their home directory and then installed it to a shared location and now I'm trying to build pocl as an unprivileged user.

**Comment by franz** [comment]
> I don't think my use case is uncommon

TBH i've never run into this problem, nor ever heard of anyone else... possibly because folks don't build software as root :)

That said, these lines were added by elhigu a long time ago, and quite possibly it's dead code - elhigu isn't actively using pocl AFAIK, i never built pocl with non-installed LLVM build tree, also i'm not aware of anybody else who would. It may not actually work.

**Comment by jrprice** [comment]
Maybe I should clarify - I'm using a shared cluster, and LLVM is a package that is used by many users for many different projects. Rather than each user building their own copy of LLVM, it makes much more sense for one of the cluster administrators to provide an LLVM module that we can all use.

I agree that anyone working on a personal machine or just building LLVM in their home directories would never experience this (which is why I never have until just recently). The problem isn't so much that it was built by root, just that it was built by a different user, so I don't have access to the source directory.

I'm all for nuking these lines if no one is using them :)
