### ISSUE TITLE
clFlush shouldn't boil down to clFinish

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#405]
https://github.com/pocl/pocl/blob/release_0_13/lib/CL/clFlush.c

Among other things, this makes queue deletion synchronize.

**Comment by pjaaskel** [comment]
I agree this is not optimal (it's a mere placeholder for better task scheduling we have in works) as there is no overlap/asynch execution by default, but I believe this is not a bug, but fits into the specs definitions regarding clFinish()/clFlush() in the current implementation. Another legal, but inoptimal one would be to implement clFlush() as a no-op.
