### ISSUE TITLE
OpenCL extensions disabled on LLVM 3.9

### ISSUE THREAD

**Issue by kraiskil** [pocl/pocl#409]
Build fails on 32-bit ARM Ubuntu 14.04 with LLVM 3.9.0 (binaries from LLVM.org)
```
In file included from /home/buildbot/pocl/pocl/include/_kernel.h:52:
/home/buildbot/pocl/pocl/include/_enable_all_exts.h:41:28: warning: unsupported OpenCL extension 'cl_khr_fp64' - ignoring
      [-Wignored-pragmas]
#  pragma OPENCL EXTENSION cl_khr_fp64: enable
```
Later the build errors out with:
```
/home/buildbot/pocl/pocl/include/_kernel.h:2254:1: error: use of type 'atomic_long' (aka '_Atomic(long)') requires
      cl_khr_int64_base_atomics extension to be enabled
/home/buildbot/pocl/pocl/include/_kernel.h:2246:43: note: expanded from macro '_CL_DECLARE_ATOMICS2'
  __IF_EA64(_CL_DECLARE_ATOMICS_DECL(MOD, atomic_long, long))
```

This issue does not show up on x86_64 Ubuntu 14.04, LLVM 3.9.0 (binaries from LLVM.org)

**Comment by kraiskil** [comment]
Minimized test case. Error happens also when cross compiling on x86_64.
```
$ echo "#pragma OPENCL EXTENSION cl_khr_fp64: enable" > hello.cl
$ clang  -emit-llvm -x cl -o tmp.bc -c hello.cl
$ clang  -emit-llvm -x cl -o tmp.bc -c hello.cl  --target=armv7-unknown-linux-gnueabihf
hello.cl:1:26: warning: unsupported OpenCL extension 'cl_khr_fp64' - ignoring [-Wignored-pragmas]
#pragma OPENCL EXTENSION cl_khr_fp64: enable
```

**Comment by kraiskil** [comment]
Seems this is expected functionality on clang's part.
Introduced in clang commits `1c20b818` and `c6fb598a`
If I understand correctly, clang 3.9.0 and 3.9.1 do not support OpenCL on ARM, and there is nothing that can be done after clang+llvm are compiled.
Patch for fixing this: [arm-ocl-clang3.9.txt](https://github.com/pocl/pocl/files/678880/arm-ocl-clang3.9.txt)

**Comment by pjaaskel** [comment]
Can you upstream the patch for 4.0? Isn't the workaround to not enable 64b on ARM until it's upstreamed?

**Comment by kraiskil** [comment]
If I understood correctly, this disabled _all_ OpenCL extensions (and their pragmas) on all LLVM targets per default. Seems the nvidia, AMD, x86 and SPIR targets just got them enabled in the same commit.

Disabling 64bit on ARM32 might be a doable work-around, but the clang parser already chokes on e.g. 
`#pragma OPENCL EXTENSION cl_khr_icd: enable` too, so yes, this needs to be upstreamed to LLVM.

**Comment by pjaaskel** [comment]
Did you notice, there's a -cl-ext flag (at least in Clang 4.0)? https://reviews.llvm.org/D28080#

**Comment by pjaaskel** [comment]
-cl-ext works and I've used it to fix TCE for Clang 4.0. It supports fp16, but doesn't support fp64.

**Comment by franz** [comment]
Unfortunately "-cl-ext" doesn't seem to exist on 3.9 and i haven't found a way to enable extensions on 3.9 (getting this error with 3.9 on both 32 and 64bit ARM). Looking at 3.9 release notes:

> Supported extensions are now part of the target representation to give correct diagnostics for unsupported target features during compilation. For example, when compiling for a target that does not support the double precision floating point extension, Clang will give an error when encountering the cl_khr_fp64 pragma.

.. but 1) it disables FP64 on 64bit ARM too, 2) 32bit ARM does support FP64 (not via NEON vectors,  but with the scalar VFP). So i guess the easiest way is to disable pocl+arm+3.9 (4.0 with -cl-ext seems to work on both 32 & 64 ARMs)

**Comment by pjaaskel** [comment]
Agreed.

**Comment by pjaaskel** [comment]
I think this is not an issue with LLVM 4.0/5.0. Please reopen if it is.
