### ISSUE TITLE
Pocl 0.13 (with Clang 3.8.1) unusable on Skylake

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#413]
Due to what appears to be [this LLVM bug](https://llvm.org/bugs/show_bug.cgi?id=29162), running even the simplest pocl kernels on Skylake processors results in an "Illegal Instruction" signal. The root of the issue *may* be that there will ultimatelyl be two versions of Skylake--one without AVX-512 and one with. From the bug log, it's not quite clear whether or not this is fixed in 3.9.

This [workaround](https://github.com/inducer/staged-recipes/blob/pocl/recipes/pocl/work-around-skylake-codegen.patch) suffices to avoid generating illegal instructions. (If you decide to merge it, you should also bump the cache version--if you have such a thing--so that old cached binaries don't get reused.)

cc @mattwala

**Comment by vchuravy** [comment]
We also did run into this for Julia and it is now fixed upstream (see https://reviews.llvm.org/D28221)

**Comment by pjaaskel** [comment]
Please add LLVM 3.8 version checks for your workaround and send a PR. I believe it's fixed in 3.9.

**Comment by inducer** [comment]
Done.
