### ISSUE TITLE
clEnqueueFillBuffer leaks memory in 0.13

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#419]
@mattwala discovered that `clEnqueueFillBuffer` loses a reference to the buffer it's filling, forcing a memory leak. He notes that this code has been rewritten in `master`.

This patch addresses the issue. I'm happy to submit a PR if either you determine that this isn't fixed in master or would after all like this patch for 0.13.

https://gist.githubusercontent.com/mattwala/e8cec37322c2e64a74b847d0458c85a2/raw/36569672eb650e6fb37e43f71db2af199da9b1e0/0001-Fix-clEnqueueFillBuffer-memory-leak.patch

**Comment by pjaaskel** [comment]
I think it was fixed in master and corrected a couple of days ago: https://github.com/pocl/pocl/commit/93d28163b2f6ab83ee60c30dc7bf2fd7dadd261c

If you wish to maintain a 0.13 fixes branch until the master regressions are solved, please do. I don't have the time for it personally.

**Comment by inducer** [comment]
FWIW, I'm effectively doing that by collecting patches here: https://github.com/inducer/staged-recipes/tree/pocl/recipes/pocl

But I don't think there's a need for an "official" maintenance branch...
