### ISSUE TITLE
release more often?

### ISSUE THREAD

**Issue by tjaalton** [pocl/pocl#436]
Hi, you should cut a release for instance every time when you add support for a newer LLVM version. Not doing so causes issues when distros try to migrate Mesa et al to the latest LLVM.

**Comment by pjaaskel** [comment]
Hi, that has been the goal, but unfortunately we have had too little people working on pocl to make this happen, and we had to skip the previous release first time simply because of anyone not having time to fix the regressions and issues with the new LLVM version.
