### ISSUE TITLE
make NEON builds conditional

### ISSUE THREAD

**Issue by ignatenkobrain** [pocl/pocl#437]
In Fedora we have armv7hl (without NEON) and armv7hnl (with NEON). In 46a71e255984967183385c3cc4113a246840259e pocl enforces usage of NEON which we can't do for our armv7hl...

**Comment by kraiskil** [comment]
This was done a while back for Debian. I can't recall the details, but the non-neon build ended up getting a handful of neon instructions which might have been optionally executed. 
This work bitrotted and was never pushed upstream, as nobody with a non-neon hardware platform was available to test this.
Essential parts was just to disable neon from the compilation flags, and not building vecmathlib with neon support.

**Comment by franz** [comment]
I believe pocl doesn't enforce it anymore.
