### ISSUE TITLE
Miscompiles large kernel

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#446]
Consider the two kernels in this gist: https://gist.github.com/inducer/500a8d8fbb0852d8a9f4d58c905d55e9

They produce the same result using pocl 0.13 and other CL implementations. On 9ee526a with a patched LLVM/Clang 4.0 (master), the results don't match.

**Comment by pjaaskel** [comment]
Please provide a host code that launches the kernels and produces the error.

**Comment by inducer** [comment]
https://gist.github.com/inducer/18fbc6f624b2d488c9607061998df328

gives

```
8.19772e-08 (pocl 0.13)
9.9989e-08 (Intel)
9.80323e-08 (AMD)
1.00837e-07 (Beignet)
0.0137821 (pocl 0.14--the actual number varies)
```

**Comment by inducer** [comment]
cc @lcw

**Comment by pjaaskel** [comment]
Fails (at least) as badly with 0.13 and LLVM 3.8 here:
```
visit0r@kaveri:~/temp$ clinfo|grep pocl
pocl warning: encountered incomplete implementation in clGetDeviceInfo.c:209
  Platform Version:                              OpenCL 2.0 pocl 0.13, LLVM 3.8.0
  Platform Vendor:                               The pocl project
  Version:                                       OpenCL 2.0 pocl
visit0r@kaveri:~/temp$ PYOPENCL_CTX=portable python pocl-miscompile.py 
/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py:2078: RuntimeWarning: overflow encountered in multiply
  s = (x.conj() * x).real
inf
visit0r@kaveri:~/temp$ PYOPENCL_CTX=portable python pocl-miscompile.py 
/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py:2078: RuntimeWarning: overflow encountered in multiply
  s = (x.conj() * x).real
inf
visit0r@kaveri:~/temp$ PYOPENCL_CTX=portable python pocl-miscompile.py 
0.0116867
visit0r@kaveri:~/temp$ PYOPENCL_CTX=portable python pocl-miscompile.py 
0.109216


clinfo|grep pocl
pocl warning: encountered incomplete implementation in /home/visit0r/src/pocl-public/lib/CL/clGetDeviceInfo.c:221
  Platform Version:                              OpenCL 2.0 pocl 0.14, LLVM 4.0.0
  Platform Vendor:                               The pocl project
  Version:                                       OpenCL 2.0 pocl HSTR: pthread-x86_64-unknown-linux-gnu-bdver3
(mypy) [llvm-4.0] visit0r@kaveri:~/temp$ python pocl-miscompile.py 
0.0176388
(mypy) [llvm-4.0] visit0r@kaveri:~/temp$ python pocl-miscompile.py 
0.00700009
(mypy) [llvm-4.0] visit0r@kaveri:~/temp$ python pocl-miscompile.py 
0.0176388
(mypy) [llvm-4.0] visit0r@kaveri:~/temp$ python pocl-miscompile.py 
0.0176388
(mypy) [llvm-4.0] visit0r@kaveri:~/temp$ python pocl-miscompile.py 
0.0176388
```

**Comment by inducer** [comment]
Weird. This test has been passing reliably (hundreds of times) on pocl 0.13 for us, across many machines. Maybe it's something that Debian patches in its LLVM 3.8?

**Comment by inducer** [comment]
This is still relevant for us--it's currently one of the things keeping me from switching our production machines over to 0.14.

**Comment by inducer** [comment]
This is still relevant for us--it's currently one of the things keeping me from switching our production machines over to 0.14.

**Comment by pjaaskel** [comment]
That's too bad :I Unfortunately it often takes a lot of time (easily several work days, sometimes weeks if it's a sneaky one) to trace a miscompilation bug in a large kernel. So if you can help isolating it to a smaller test case, I might be able to find the time to help.

**Comment by inducer** [comment]
I understand. I've sat down and simplified this code quite a bit, and in the process noticed that there seems to be an interaction of two features that seems to be related--a call to `pow` and a (in this simplified case, unnecessary) barrier. I've made `#ifdef`s for both--removing either one gives the correct result.

https://gist.github.com/inducer/7f45345c3c4bc74519b41c639bd70fdb

I get a correct answer (i.e. relative error zero, or close to it) from all implementations I've tried (pocl 0.13, beignet, Intel, AMD) except pocl 0.14.

**Comment by pjaaskel** [comment]
Thanks! Looks much more manageable now. The case is affected by some other recent regressions in master. I'll take a look after we fix those and manage to reproduce the actual miscompilation (currently crashes).

**Comment by pjaaskel** [comment]
Getting indeterministic results now, which is very weird:
```
python pocl-miscompile.py.1
Choose platform:
[0] <pyopencl.Platform 'Portable Computing Language' at 0x7f4d50038670>
Choice [0]:
Set the environment variable PYOPENCL_CTX='' to avoid being asked again.
Small error means 'good':
0.0
(pyopencl-env) [llvm-5.0] visit0r@kaveri:~/temp$ python pocl-miscompile.py.1
Choose platform:
[0] <pyopencl.Platform 'Portable Computing Language' at 0x7f4666190670>
Choice [0]:
Set the environment variable PYOPENCL_CTX='' to avoid being asked again.
Small error means 'good':
1.0
(pyopencl-env) [llvm-5.0] visit0r@kaveri:~/temp$ python pocl-miscompile.py.1
Choose platform:
[0] <pyopencl.Platform 'Portable Computing Language' at 0x7f2e29570670>
Choice [0]:
Set the environment variable PYOPENCL_CTX='' to avoid being asked again.
Small error means 'good':
5.17346e-09
```

**Comment by pjaaskel** [comment]
Ah, it uses random input, so hard for me quickly tell if this OK or not. Please check and reopen if it's still an issue in latest master (I pushed some kernel compiler work yesterday).

**Comment by inducer** [comment]
Built it, looks good from my end. I'm a little worried about the 1.0 you got there at some point--FWIW, I consistently got `0.0` over roughly 100 trials. Thanks for working on this!
