### ISSUE TITLE
Missing error detection for when the NDRange-requested local size doesn't match reqd work group size attribute's

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#450]
Run the following in an environment that has PyOpenCL:

```
$ git clone https://github.com/inducer/boxtree.git
$ cd boxtree
$ pip install -e .
$ cd test
$ pip install mako pytest
$ PYOPENCL_TEST=port python -m pytest --capture=no
```

After a non-deterministic amount of time, observe that the program just crashes/stops and prints the following:
```
INFO:boxtree.tree_build:tree build complete
INFO:root:building traversal build kernels
INFO:root:traversal build kernels built
INFO:boxtree.traversal:start building traversal (... or similar program output)
Dynamic WG size binary does not exist
```

This *doesn't seem to happen with:
```
$ PYOPENCL_NO_CACHE=1 PYOPENCL_TEST=port python -m pytest --capture=no
```

**Comment by pjaaskel** [comment]
For me this simply crashes after some time, but doesn't print the Dynamic WG size binary does not exist. For that crashing case I checked that all parameters (including a single struct byval one) are passed correctly to the kernel. Next to check if this fails with LLVM 3.9 + the ABI patch.

**Comment by pjaaskel** [comment]
I look a bit more. The crash happens because of an indirect access box_levels[srcntgt_box_ids[i]]. At least the first element keeps changing over runs and is usually a value that is out of limits. Some printouts that were done in basic.c where it sets the argument in question (not inside the kernel, so it's not a kernel compiler issue unless that input comes from a kernel):

```
ptr arg 3 set to 0x698c900. first int 269488144
ptr arg 3 set to 0x1f54d80. first int -1869574000
```

**Comment by pjaaskel** [comment]
I cannot reproduce your issue with either 0.14&LLVM 4.0 or 0.13&LLVM 3.8, but the crash produces with both. This is either a "deeper" pocl issue if that array produced by another kernel which miscompiles or problem in pyopencl/boxtree. Regardless, it requires more pyopencl/boxtree knowledge to debug further in a reasonable time. If you can reproduce the issue in the original bug report, let me know. If you see the same crash I'm seeing, please open a new bug with some more information/hints how to dig in the pyopencl in this case.

**Comment by inducer** [comment]
Thanks for taking a look, and sorry if this turns out to be our fault after all. We'll investigate and let you know.

**Comment by pjaaskel** [comment]
Well, the one I'm seeing still can be something e.g. related to buffer handling, but seems not to be a regression.

**Comment by mattwala** [comment]
I think the original bug noticed by @inducer is unrelated to the crash observed by @pjaaskel. I can reproduce the "Dynamic WG size binary does not exist" reliably in the following way:

1. Defeat the internal cache used by POCL by applying this patch (this is just for exposing the bug):

```
diff --git a/lib/CL/devices/common.c b/lib/CL/devices/common.c
index 6708f0b..e6144cd 100644
--- a/lib/CL/devices/common.c
+++ b/lib/CL/devices/common.c
@@ -738,7 +738,7 @@ pocl_check_dlhandle_cache (_cl_command_node *cmd)
           return;
         }
     }
-  if (handle_count == 128)
+  if (handle_count == 1)
     {
       ci = pocl_dlhandle_cache->prev;
       //assert (ci->ref_count == 0);
```

2. Run the following example:
```
def f(context):
  import logging
  logging.basicConfig(level=logging.DEBUG)
  import pyopencl as cl
  import numpy as np
  from pyopencl.scan import GenericScanKernel
  from pyopencl.algorithm import ListOfListsBuilder
  for i in range(2):
    builder = ListOfListsBuilder(context, [("mylist", np.int32)], """
        void generate(LIST_ARG_DECL USER_ARG_DECL index_type i)
        {
            int count = i % 4;
            for (int j = 0; j < count; ++j)
            {
                APPEND_mylist(count);
            }
        }
        """, arg_decls=[], complex_kernel=True)
    with cl.CommandQueue(context) as queue:
      result, event = builder(queue, 2000)

import pyopencl as cl
f(cl._csc())```

What's interesting about the code generated by PyOpenCL here is that it contains the attribute `__attribute__((reqd_work_group_size(1, 1, 1)))` while the POCL code seems to be looking for a binary with work group sizes `0, 0, 0`.

**Comment by mattwala** [comment]
Update: After a bit more digging, I think the underlying problem is pyopencl/pyopencl#175, which comes from the fact PyOpenCL seems to be passing a local work size that disagrees with `reqd_work_group_size`.

I can't reproduce the issue when I give it the correct local work size.

**Comment by pjaaskel** [comment]
OK. Thanks for digging. So it's a case of missing error detection.

**Comment by Oblomov** [comment]
I'm doing a cleanup of clEnqueueNDRangeKernel to Oblomov@pocl/ndrange-fixes —the first couple of patches might be a fixes for this issue.

( I haven't created a PR yet because I want to finish some more cleanups first.)

**Comment by inducer** [comment]
Thanks for working on this! Will this find its way into 0.14 or no?

**Comment by pjaaskel** [comment]
Nope.
