### ISSUE TITLE
Segmentation fault while running hashcat with pocl-0.14 on Raspberry Pi

### ISSUE THREAD

**Issue by Zhendong404** [pocl/pocl#451]
I'm trying to run hashcat on Raspberry Pi 2B(ARM Cortex-A7 inside), so I installed pocl-0.14 with LLVM-3.8. But when hashcat execute clGetProgramInfo() and clFinish(), it reported a segmentation fault.

> Program received signal SIGSEGV, Segmentation fault.
> 0x76fd9822 in ?? () from /lib/ld-linux-armhf.so.3

Then I tested pocl with another program, no such problem.
Then I did the same thing on my x86 PC, both hashcat and pocl worked well.
I also tried the same thing on Zynq(Cortex-A9), this time the segmentation fault apearred again.

> Program received signal SIGSEGV, Segmentation fault.
> 0xb1ad4908 in ?? () from /usr/lib/arm-linux-gnueabihf/lib/libLLVM-3.8.so.1

Is this a bug of hashcat or pocl? How can I deal with it?

**Comment by pjaaskel** [comment]
It can be also a bug in LLVM. Please try with a newer LLVM, preferably LLVM 4.0 and see if it makes any difference. If it doesn't help, I think you are on your own unless you find someone supporting your debugging pocl on ARM. Our group currently doesn't have people to do that.

**Comment by pjaaskel** [comment]
Please try with the latest master and LLVM and reopen if still an issue.
