### ISSUE TITLE
Issue with poclcc while compiling kernel with barriers

### ISSUE THREAD

**Issue by rjodin** [pocl/pocl#458]
Hi all,

I have an issue when I run a kernel create from binary that contains barrier.
At the moment I didn't manage to get a simple code that reproduce this bug.

This issue is that the kernel does not produce the outputs expected. The program ends well, but the computation is false.

You can find here attached a tar that contains the kernel and everything to run it.
In my kernel, barriers come from calls to wait_group_events.
As the code is not that simple, it is hard to know where the compiler made an error. But from what I tried to have a simple code, it seems that I need the barrier to be in an if which is in a loop... but I'm not sure.

Does anyone have seen something similar? Any idea on where to look, what to check?
The only difference between compiling offline (with poclcc) and online (as usual) that I'm aware of is that the iterator of the 3 loops (on the 3 dimensions) are variables that are loaded dynamically during kernel execution from pocl_context. Is there anything else?

To run my code, you have to write the path to your pocl and llvm install repositories in the Makefile.
Then you have 4 different targets:
```
make run_bin
make run_bin_no_wait_event
make run_src
make run_src_no_wait_event
```

The only target that fail is "make run_bin" which runs the kernel from binary with barriers (from wait_group_events).
"make run_bin_no_wait_event" runs the kernel from binary but without barriers.
"make run_src" and "make run_src_no_wait_event" runs the kernel from source.

Thanks in advance,
[issue_poclcc_with_barriers.tar.gz](https://github.com/pocl/pocl/files/893272/issue_poclcc_with_barriers.tar.gz)

**Comment by pjaaskel** [comment]
These are the trickiest barrier cases to handle statically so I'm not surprised if you encouter a problem. You can try if switching the work group method (repl vs. loops) makes it fail also online. If it does, you need to dig into the kernel compiler and figure out the failure it creates to the CFG (it that's the case). A way to minimize/expose CFG errors is to use printfs() that output work item ids. This has been used in tests under tests/workgroup/*.cl. The trickiest case is tricky_for.cl which I believe might still fail with one of the WG methods. DebugHelpers.h is useful for visualizing the CFGs before and after the CFG transformations.

**Comment by rjodin** [comment]
Thanks @pjaaskel,
When creating a kernel with poclcc, you cannot choose the work group method. It has to be loops as we don't know the local sizes.
When I run the kernel from source, both work group methods work find.

I did try to puts some printf.
My code is basically (with the printf):
```
for (i) {
   compute(i);
   if (get_global_id() == 13)
       printf("gid %u i %u\n", get_global_id(), i);
   if (i==0) 
       async_work_group_copy();
   else if (i==1)
       wait_group_events();
}
compute2();
async_work_group_copy();
wait_group_events();
```
what I expect is something like that:
```
gid 13 i 0
gid 13 i 1
gid 13 i 2
...
gid 13 i 14
```
and what I get is:
```
gid gid 13 i 13 i0 
gid 13 i 1
0
gid 13 i 2
gid gid 13 i 1
gid 13 i 1
13 i g3
gid 13 i 2
gid id 1313 i 4
gid 13 i 5
gid 13 i  i 3
gid 13 i 4
gid 13 i 5
gid 13 i 6
6
gid g13i di  7
gid 13 i 8
gid 13 i 9
gid 13 i 10
gid 13 i 11
gid 13 i 12
gid 13 i 13
gid 13 i 14
13 i 7
gid 13 i 8
gid 13 i 9
gid 13 i 10
gid 13 i 11
gid 13 i 12
gid 13 i 13
gid 13 i 14
gid 13 i 15
```
It seems to me that there are 2 threads working with (in their point of view) the same global_id, and they are doing twice the loop.

My kernel is run with a local size of "1" (I have only one dimension), so the loops added by the compiler should loop on (1, 1, 1). As their is barriers, compiler must have created severals loops around each continous region without barriers, right?

How do you enable the visualizing of the CFGs before and after transformations?

**Comment by pjaaskel** [comment]
Check WorkitemLoops.cc, there are already some dumpCFG() calls (#if 0'd out).

**Comment by rjodin** [comment]
Thanks @pjaaskel, I managed to have a look at the CFG.
I saw that the loops were peeled. I try to force poclcc not to peel it, and my program worked find after...
I'm looking deeper at the peeling code to see what bad could happen between peeling and offline compiling (WGDynamicLocalSize).

Is peeling necessary theoretically? Could we disable it for offline compilation, or it will break everything?

**Comment by pjaaskel** [comment]
Yes peeling is needed for barriers inside conditional regions. It is used to check which path is taken by the first work item -- the others work items are then assumed to follow the path due to the barrier semantics (all or none of the WIs enter the barrier).

**Comment by rjodin** [comment]
I think I got it.
There is no check on whether we can continue the loop after the first iterator (which has been peeled out). It is like if we expect the local size on the x dimension to be bigger than 1... In my kernel it is not.
I modified the llvm pass to add a check. It seems to work find. I will clean it, and then I'll make a pull request.
