### ISSUE TITLE
OpenGL(mesa)+OpenCL applications segfault due to multiple LLVMs 

### ISSUE THREAD

**Issue by kraiskil** [pocl/pocl#46]
This is one of the problems already recorded in issue #44 and partially fixed in d86c335ea87824385294a0a8247e344d2efdf939.

When an application links against mesa and pocl (even via ICD), and the mesa backend used is LLVMpipe, mesa will jump to the LLVM symbols introduced when LLVM was linked to pocl. 

Commit d86c335ea87824385294a0a8247e344d2efdf939, added -Bsymbolic flag to linker (on GNU systems). This fixed the inverse issue, i.e. libpocl jumped to the LLVM symbols found in mesa.

Sample backtrace:
 #0  0x00007ffff6079475 in *__GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007ffff607c6f0 in *__GI_abort () at abort.c:92
#2  0x00007ffff6072621 in *__GI___assert_fail (assertion=0x7ffff1923ca0 "findOption(Name) == Values.size() && \"Option already exists!\"", file=<optimized out>, line=675, function=0x7

ffff1f77660 "void llvm::cl::parser<DataType>::addLiteralOption(const char_, const DT&, const char_) [with DT = llvm::ScheduleDAGSDNodes\* (_)(llvm::SelectionDAGISel_, llvm::CodeGenOpt:
:Level); DataType = llvm::Sche"...) at assert.c:81
#3  0x00007ffff07cab7c in void llvm::cl::parser<llvm::ScheduleDAGSDNodes* (*)(llvm::SelectionDAGISel*, llvm::CodeGenOpt::Level)>::addLiteralOption<llvm::ScheduleDAGSDNodes\* (*)(llvm::

SelectionDAGISel_, llvm::CodeGenOpt::Level)>(char const_, llvm::ScheduleDAGSDNodes\* (\* const&)(llvm::SelectionDAGISel_, llvm::CodeGenOpt::Level), char const_) [clone .part.609]() fro
m /opt/llvm/3.4//lib/libLLVM-3.4.so
#4  0x00007ffff159618e in llvm::RegisterPassParserllvm::RegisterScheduler::NotifyAdd(char const_, void_ (_)(), char const_) () from /opt/llvm/3.4//lib/libLLVM-3.4.so
#5  0x00007fffeeff8236 in llvm::MachinePassRegistry::Remove(llvm::MachinePassRegistryNode*) () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so

**Comment by pjaaskel** [comment]
The old multiple LLVM issue(s). There's a newer bug with a link to the LLVM bug.
