### ISSUE TITLE
Using OpenCL 2.0 workgroup functions

### ISSUE THREAD

**Issue by ekondis** [pocl/pocl#462]
I tried v.0.14 on a kernel using OpenCL 2.0 workgroup function but the kernel's compilation fails with an error as:

`error xxx: implicit declaration of function 'work_group_reduce_add' is invalid in C99`

AFAIK, v 0.14 supports OpenCL 2.0. Am I missing something?

**Comment by pjaaskel** [comment]
It supports only a small subset of 2.0 so far.
