### ISSUE TITLE
AutomaticLocals pass breaks when local ptr is used in const expression

### ISSUE THREAD

**Issue by jrprice** [pocl/pocl#467]
A kernel that contains something like this:

    local char foo[3];
    results[0] = (ulong)foo; // cast local pointer to integer

Generates LLVM like this:

    @test.foo = internal global [3 x i8] undef, align 1
    ...
    store i64 ptrtoint ([3 x i8]* @test.foo to i64), i64* %results, align 8, !tbaa !6

The `AutomaticLocals` pass then converts `@test.foo` into a kernel argument and replaces uses of `@test.foo` with this new argument. The problem is, a function argument is not a constant, and so it cannot be used in a constant expression like the `ptrtoint` above.

With LLVM built in Debug mode, this shows up as an assertion:

    Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file ../../include/llvm/Support/Casting.h, line 236.

**Comment by xiaoyufish001** [comment]
> A kernel that contains something like this:
> 
> ```
> local char foo[3];
> results[0] = (ulong)foo; // cast local pointer to integer
> ```
> 
> Generates LLVM like this:
> 
> ```
> @test.foo = internal global [3 x i8] undef, align 1
> ...
> store i64 ptrtoint ([3 x i8]* @test.foo to i64), i64* %results, align 8, !tbaa !6
> ```
> 
> The `AutomaticLocals` pass then converts `@test.foo` into a kernel argument and replaces uses of `@test.foo` with this new argument. The problem is, a function argument is not a constant, and so it cannot be used in a constant expression like the `ptrtoint` above.
> 
> With LLVM built in Debug mode, this shows up as an assertion:
> 
> ```
> Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file ../../include/llvm/Support/Casting.h, line 236.
> ```

AutomaticLocals pass breaks when local ptr is used in const expression
the automaticLocals pass breaks means the pass failed ?
