### ISSUE TITLE
CommandLine Error: Option 'enable-value-profiling' registered more than once! 

### ISSUE THREAD

**Issue by znmeb** [pocl/pocl#474]
```
: CommandLine Error: Option 'enable-value-profiling' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
It turns out that if more than one OpenCL vendor's `.icd` file points to an implementation using the same LLVM, you get this error. Debian is statically linking beignet to prevent this - see <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852746>. 

I ran into it with both `pocl` and `opencl-mesa` on an Arch system.

**Comment by inferrna** [comment]
Similar error with blender:
```
: CommandLine Error: Option 'kernel' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

**Comment by pjaaskel** [comment]
Did you try statically linking LLVM also for pocl?

**Comment by pjaaskel** [comment]
This is the long-standing LLVM command line parameter implementation issue, not a pocl bug.

**Comment by pjaaskel** [comment]
The LLVM bugs: https://bugs.llvm.org/show_bug.cgi?id=30587 https://bugs.llvm.org/show_bug.cgi?id=30587  I think further discussion on fixing this belongs to the LLVM bugzilla because it indeed is a wider impact LLVM issue.
