### ISSUE TITLE
Support for using LLVM Project for linking and C++ lib (now relies on system ld, libstdc++ to build kernels)

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#482]
I am trying to ship pocl as infrastructure to my software through conda-forge (and am mostly doing so with reasonable success). One remaining stumbling block is folks who may not have `ld` or `libstdc++` already installed and may lack the privileges to install them--are these dependencies fixable, perhaps by using additional llvm components?

Thanks!

**Comment by pjaaskel** [comment]
Could be! I haven't tried to replace system ld with the LLVM linker or GNU libstdc++ with LLVM project's alternative. It would definitely be useful if someone tested / fixed it to work purely with LLVM Project stack.

**Comment by pjaaskel** [comment]
Please send a PR if contributing features.
