### ISSUE TITLE
Release MemObject on multi-devices platform

### ISSUE THREAD

**Issue by rjodin** [pocl/pocl#486]
I have a question about the mechanism of RetainMemObject and ReleaseMemObject when running a code working on a multi-devices platform.

When using "clCreateBuffer", for each device of the context we are calling "clRetainMemObject".
So when we want to release the buffer, we have to call "clReleaseMemObject" once for each devices of the context. 

I don't know if it is the behaviour that we want.
I was thinking calling "clReleaseMemObject" only once would be enough.
What do you think of it?

**Comment by Oblomov** [comment]
I agree that a single release should be sufficient. A memory object should only be resident on a single device (and optionally the host) at any given time anyway, so it should never happen that it gets leaked when on release.

**Comment by pjaaskel** [comment]
Mem object can be "resident" (mirrored) on multiple devices at the same time. Not sure if it affects anything here though...

**Comment by rjodin** [comment]
As "clReleaseMemObject" does not have the device in argument, when we call it, I understand it as "release the mem object for all the devices". We cannot choose to release it only for one device, because in that case we would have to choose on device, and it would be a bit random, don't you think?

I think "clCreateBuffer" should only Retain once the buffer, no matter the number of devices.

**Comment by pjaaskel** [comment]
Yes, but please keep in mind that you can release a mem object from the user code early, even while it's still being (or going to be) used in execution. In that case, eventually the devices using the buffer should release the buffer after they are done with it.

"After the memobj reference count becomes zero and commands queued for execution on a command-queue(s) that use memobj have finished, the memory object is deleted." https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clReleaseMemObject.html

**Comment by rjodin** [comment]
Of course.
If I'm not mistaken, a call to "clEnqueueNDRange", "clEnqueueRead/WriteBuffer", and all other functions that used a buffer take a ref (by calling RetainMemObject) on it, right?
And so, the ref should be release automatically when the action is completed.

I'll propose a PR for it soon.

**Comment by pjaaskel** [comment]
Yes it should be like that. If it is then there is no problem.
