### ISSUE TITLE
Runtime crash reports for 0.14 on Intel E5-2620

### ISSUE THREAD

**Issue by ChrisCummins** [pocl/pocl#487]
I have been batch testing OpenCL programs and have encountered a number of cases where pocl performs unusually.

The first is when compiling a kernel with undefined symbols. In this case, the compiler should error, however, with pocl, the compilation completes successfully, but the program then crashes due to a symbol lookup error when trying to run the kernel. I have produced a standalone script here with additional version information:

http://paste.ubuntu.com/25031508/ (additional examples below)

Secondly, there are cases where the program silently crashes during kernel execution with an error message. Example:

http://paste.ubuntu.com/25031556/ (additional examples below)

In the above case, the kernel performs a mod zero operation which in the spec is undefined, though the kernel completes on NVIDIA/Intel OpenCL implementations.

This is using pocl built from source (release 0.14 downloaded form the website) compiled against LLVM 3.9. I have only tested on the E5-2620 target.

Cheers,
Chris

Additional examples of undefined symbol errors:

http://paste.ubuntu.com/25031509/ 
http://paste.ubuntu.com/25031510/ 
http://paste.ubuntu.com/25031511/ 
http://paste.ubuntu.com/25031512/ 
http://paste.ubuntu.com/25031513/ 
http://paste.ubuntu.com/25031514/ 
http://paste.ubuntu.com/25031515/ 
http://paste.ubuntu.com/25031516/ 
http://paste.ubuntu.com/25031517/ 
http://paste.ubuntu.com/25031518/ 
http://paste.ubuntu.com/25031519/ 
http://paste.ubuntu.com/25031520/ 
http://paste.ubuntu.com/25031521/ 
http://paste.ubuntu.com/25031522/ 
http://paste.ubuntu.com/25031523/ 
http://paste.ubuntu.com/25031524/ 
http://paste.ubuntu.com/25031525/ 
http://paste.ubuntu.com/25031526/ 
http://paste.ubuntu.com/25031527/ 
http://paste.ubuntu.com/25031528/ 
http://paste.ubuntu.com/25031529/ 
http://paste.ubuntu.com/25031530/ 
http://paste.ubuntu.com/25031531/ 
http://paste.ubuntu.com/25031532/ 
http://paste.ubuntu.com/25031533/ 
http://paste.ubuntu.com/25031535/ 
http://paste.ubuntu.com/25031536/ 
http://paste.ubuntu.com/25031538/ 
http://paste.ubuntu.com/25031539/

Additional examples of runtime crashes:

http://paste.ubuntu.com/25031555/ 
http://paste.ubuntu.com/25031557/ 
http://paste.ubuntu.com/25031558/ 
http://paste.ubuntu.com/25031559/ 
http://paste.ubuntu.com/25031561/ 
http://paste.ubuntu.com/25031562/ 
http://paste.ubuntu.com/25031563/ 
http://paste.ubuntu.com/25031564/ 
http://paste.ubuntu.com/25031565/ 
http://paste.ubuntu.com/25031566/ 
http://paste.ubuntu.com/25031567/ 
http://paste.ubuntu.com/25031568/ 
http://paste.ubuntu.com/25031569/ 
http://paste.ubuntu.com/25031570/ 
http://paste.ubuntu.com/25031571/ 
http://paste.ubuntu.com/25031572/ 
http://paste.ubuntu.com/25031573/ 
http://paste.ubuntu.com/25031574/ 
http://paste.ubuntu.com/25031575/ 
http://paste.ubuntu.com/25031576/ 
http://paste.ubuntu.com/25031577/

**Comment by franz** [comment]
Hello,

Thanks for the report.

* the mod zero bug has been fixed in git master recently
* the undefined symbol crash is a known problem, it just hasn't been filed as bug.

Chris or @pjaaskel, since AFAICT there's only one issue (undefined symbol crash), can you please change the title to something like "crash due to symbol lookup error when trying to run the kernel". We can track any other issues in separate bugreports. Thanks

**Comment by ChrisCummins** [comment]
Hey @franz, sure, I'll switch to 0.14 master before continuing my testing.

I apologise for the code dump, but unfortunately I have very limited time to investigate the specific cause of each crash. However, I do think there may be some additional problems of interest, apart from just the undefined symbol and mod zero problem. Taking a look at the "Additional examples of runtime crashes" links above, I can see:

* http://paste.ubuntu.com/25031555/ appears to be either a barrier in for loop, or WAW race on `a[b]`
* http://paste.ubuntu.com/25031558/ assertion failing when it shouldn't
* http://paste.ubuntu.com/25031565/ i can't see a reason why this should fail
* http://paste.ubuntu.com/25031566/ again, I see no reason. Maybe the implicit int -> float conversion?

Cheers,
Chris

**Comment by ChrisCummins** [comment]
I split the undefined symbols error into it's own issue #488, so that the other reports in this comment thread don't get in the way.

**Comment by pjaaskel** [comment]
Just a quick guess: some of the cases input _only_ a local buffer which does not typically make sense in real world cases, thus it might be an untested feature and the crashes related to it.

**Comment by franz** [comment]
> http://paste.ubuntu.com/25031558/ - assertion failing when it shouldn't

I think it actually should fail, just not the way it's failing. There are is no assert() macro in OpenCL C, there is also no "assert.h" header. I have no idea where the `__assert` your code seems to be using is coming from or what it does, but both assert() and __assert() should fail to compile as undefined symbols.

> What LLVM version do you recommend?

We usually use 4.0 but test pocl with much more, generally back to 3.7. Note that some features are not available with older LLVMs, so pocl will fail more tests with older LLVMs.

**Comment by franz** [comment]
i've compiled CLSmith and run the [four](https://github.com/pocl/pocl/issues/487#issuecomment-313417959) tests again through recent pocl:

> http://paste.ubuntu.com/25031555/ appears to be either a barrier in for loop, or WAW race on

```
[2017-07-15 13:09:57.552449079]POCL: in fn POclSetKernelArg at line 58:
  |   GENERAL | CL_INVALID_ARG_VALUE arg_value != NULl and arg 0 is in local address space
```
... you cannot set a local kernel argument to anything, that is allocated by the runtime / device. You can only set **size** on local mem. See [the documentation of clSetKernelArg](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clSetKernelArg.html): 
`If the argument is declared with the __local qualifier, the arg_value entry must be NULL.`

> http://paste.ubuntu.com/25031558/ assertion failing when it shouldn't

```
  |   GENERAL |  Error(s) while linking: 
Cannot find symbol __assert in kernel library
```
I have no idea where the "__assert" should come from - maybe i got the `--include-path` wrong ? i've set it to <CLSmith_source_dir>/runtime. But pocl can't find it in kernel library, so it properly returns an errors.

> http://paste.ubuntu.com/25031565/ i can't see a reason why this should fail

again trying to set a local mem argument

> http://paste.ubuntu.com/25031566/ again, I see no reason. Maybe the implicit int -> float conversion?

... and again local mem argument.

So the missing symbols @ linking should be fixed, and the rest seems to be problems in CLSmith.
@ChrisCummins  is there some script to run all the tests ?

**Comment by ChrisCummins** [comment]
Hey @franz , thanks for the detailed response. I had missed the `__local` qualifier. I'll fix the host-code and re-run those tests. I'll close this for now since that rules out the results I've gone through so far, and #488 covers the other problem.
