### ISSUE TITLE
Undefined symbols cause symbol lookup crash

### ISSUE THREAD

**Issue by ChrisCummins** [pocl/pocl#488]
The following kernel should produce a compile time error for `__morldNormalided ` but instead compiles fine, then crashes the program during kernel execution:

```
__kernel void entry(__global int* a) {
  int b = __morldNormalided(a);
}
```

Host code and steps to reproduce: http://paste.ubuntu.com/25031508/

Error:
```
symbol lookup error: <pocl-cache>/entry.so: undefined symbol __morldNormalided
```

Expected output: `CL_BUILD_PROGRAM_FAILURE` during compilation.

**Comment by franz** [comment]
This should be now fixed via ab37825d8eaaf547e0d56774864e056f7af9e60f

(reopen if you still find it broken)
