### ISSUE TITLE
optimize-wi-func-calls pass basic/work_item_functions conformance test

### ISSUE THREAD

**Issue by jrprice** [pocl/pocl#509]
Commit 1d161ede1 introduced a pass to optimize calls to work-item functions.

This pass doesn't properly handle cases where the argument to the function call is not constant. There's some logic in there to check for non constant arguments, but only when deciding whether to use a previously moved call. Line 151 seems to unconditionally move the first function call to the start of the function, even if it has variable arguments.

**Comment by pjaaskel** [comment]
Please test and reopen if still broken.

**Comment by jrprice** [comment]
I can confirm this fixes the issue - thanks.
