### ISSUE TITLE
Error building kernel - unknown target CPU 'generic'

### ISSUE THREAD

**Issue by L30nardoSV** [pocl/pocl#512]
Hi,

I have installed pocl 0.14-pre, LLVM 3.9.1, on fedora 25, the machine is AMD Ryzen 5 1600x.
`clinfo` shows that the CPU is correctly recognized as a devices. The problem appears in execution:
`CL_PROGRAM_BUILD_LOG  : error: <invalid loc>: unknown target CPU 'generic'`

There is a [similar issue](https://github.com/pocl/pocl/issues/332) but not sure the suggestion given will work, as I am using the latest pocl. is it because this cpu is not yet supported?

**Comment by franz** [comment]
> is it because this cpu is not yet supported?

Correct, it's supported from [LLVM 4.0.0](https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Clang-znver1-Zen-CPU)

There was a commit to pocl's CMake to [add a fallback to "generic" cpu and print a warning](https://github.com/pocl/pocl/commit/d7f89ad2696a253296a5116bd89fe3031de1fb1c) but it seems "generic" doesn't work at all (although llc does list it in the recognized cpu list). @pjaaskel shall pocl just fail to build if LLVM cannot recognize the CPU and LLC_HOST_CPU wasn't set on the commandline ?

**Comment by pjaaskel** [comment]
Yes, makes sense to me.
