### ISSUE TITLE
WI-loops don't consider alignment for context arrays [was: vload3 is broken]

### ISSUE THREAD

**Issue by franz** [pocl/pocl#516]
SIGSEGV on VMOVAPS with unaligned address.

**Comment by Oblomov** [comment]
Yeah, `vload*` should be implemented as element-by-element fetch since the whole point of them is to work without any alignment constraint (e.g. packed `float3` structures).

**Comment by franz** [comment]
@Oblomov: actually it has been using element-by-element for a while now, that's not the issue.

The problem seems to be not with the vload3 itself, but the vload3 test case. There is a piece of code with a small loop:

```
    __private char sPrivateStorage[ 255 ];
    int tid = get_global_id( 0 );

    for( int i = 0; i < 255; i++ )
    {
        sPrivateStorage[ i ] = src[ i ];
    }
```

and LLVM seems to optimize it in some strange way, to copy the first 128 bytes via AVX and copy the remaining 127bytes one-by-one (AFAICT). For some reason the AVX instructions add the size of sPrivateStorage (255) to the stack pointer (rsp). So `vmovaps XMMWORD PTR [rsp+r11*1+0x20],xmm2` should be `vmovaps XMMWORD PTR [rsp+0x20],xmm2` AFAICT.

git bisect says it's broken by commit 69ea56f3c0bbf01ecee7517dbd0f ( kernel compiler: Apply standard optimations early). @pjaaskel can you take a look ?

**Comment by pjaaskel** [comment]
If there is a WI, loop, it should increment the sp with the WI ID times the private array size to find its copy. Are you sure it is not that? Do you see a problem in the bitcode, which should be very simple in this case?

**Comment by franz** [comment]
> it should increment the sp with the WI ID times the private array size to find its copy. 

And that is the problem. The private array is defined as:

`  %sPrivateStorage = alloca [255 x i8], align 16`

The standard-opts pass then vectorizes the small for loop and uses 16-aligned stores to this array. The WI pass then uses 255 * WI-ID as index, which obviously breaks the 16-aligned store instructions. So WI pass needs to consider both alignment and size, not just size.

**Comment by pjaaskel** [comment]
Yes, that's a clear bug if it doesn't.

**Comment by pjaaskel** [comment]
And it's a good sign -- autovec finally starting to vectorize pocl's output more aggressively.
