### ISSUE TITLE
LLVM assertion "Uses remain when a value is destroyed!" fails on atomic call _only_ when separate function is called

### ISSUE THREAD

**Issue by arghdos** [pocl/pocl#520]
```
llvm-config --version 4.0.1
gcc --version (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
pocl built from bbdf13bc232
```

Consider the following simple mwe:

https://gist.github.com/arghdos/0fa7f554e4bee6c3e81b0004d693f858

If you use the file `kernel_broken.ocl` as `kernel.ocl` in the `compiler` function, I get the following output:

 ```
gcc main.c -o a.out -lOpenCL -I/opt/opencl-headers/ -std=c99
./a.out
>Use still stuck around after Def is destroyed:  %call8.i = tail call i64 @_Z14atomic_cmpxchgPU7CLlocalVlll(i64* <badref>, i64 %1, i64 %3) #6, !noalias !13
>a.out: /home/nick/llvm/lib/IR/Value.cpp:85: virtual llvm::Value::~Value(): Assertion `use_empty() && "Uses remain when a value is destroyed!"' failed.
```
which results on the second call to `clGetProgramInfo` (line 212 of main.c):

```
check_err(clGetProgramInfo(program, CL_PROGRAM_BINARY_SIZES, num_prog * sizeof(size_t), bin_size, NULL));
```

However, if you simply delete the `kernel_call` function (i.e., use `kernel_working.ocl`), the program binary is generated as expected.

Any pointers or suggestions?

**Comment by pjaaskel** [comment]
I think this is borderline case that is likely not defined behavior. It calls another kernel as a subfunction, which is OK, but declaring an automatic local variable in a subfunction (like it is in this case) is less clear:

 _"The __local or local address space name is used to describe variables that need to be
allocated in local memory and are shared by all work-items of a work-group. Pointers to the
__local address space are allowed as arguments to functions (including kernel functions).
Variables declared in the __local address space inside a kernel function must occur at kernel
function scope. "_

_"Kernel functions with variables declared inside the function with the __local or local
qualifier can be called by the host using appropriate APIs such as clEnqueueNDRangeKernel,
and clEnqueueTask."_  I think it misses "only" before "called" though.

**Comment by franz** [comment]
FWIW, just found an explicit answer:

http://www.informit.com/articles/article.aspx?p=1732873&seqNum=11

"The function behaves as a regular function if it is called from a kernel function. The only restriction is that a kernel function with variables declared inside the function with the local qualifier cannot be called from another kernel function"

.... one of the book's authors is Aaftab Munshi, who is the editor of OpenCL standard.

**Comment by arghdos** [comment]
Aaaaah, I had thought the issue was the `volatile` arguments in the subfunction, but the `__local` declaration issue makes sense and is something I can easily deal with on my side -- thanks!
