### ISSUE TITLE
AVX512 support?

### ISSUE THREAD

**Issue by oscarbg** [pocl/pocl#523]
Hi,
I don't know how advanced POCL CPU autovectorizer is or not but using at least float16 double8 operations on kernels should map to AVX512 on processors that support it like new Core i9 7900x and others..
of course LLVM 4.0 supports it so can provide info if POCL supports currently a AVX512 backend..

**Comment by pjaaskel** [comment]
You might want to try LLVM 5.0 and pocl master. If it still fails to produce vector instructions, please optimize and send a pull request. Our group is not currently having it in their roadmap to optimize pocl for Intel ISEs so it's unlikely to happen by us in the near future.

**Comment by jrprice** [comment]
FWIW Intel are currently investing a significant amount of effort into improving LLVM's loop vectorisation capabilities (including adding support for outer loop vectorisation, among other things). If pocl makes use of LLVM's loop vectoriser to vectorize across work-items then hopefully performance will improve as these changes start to land in LLVM (the [first stage of Intel's efforts called VPlan](https://llvm.org/docs/Proposals/VectorizationPlan.html) has recently landed, although this doesn't provide any functional/performance changes yet).

**Comment by pjaaskel** [comment]
Yes, the strategy is to do minimal compilation at pocl side and rely on LLVM autovecs for WG and WI vec. Sounds good!

**Comment by franz** [comment]
If anyone has access to an AVX-512 CPU, please try to compile PR #539 (it's quite likely to fail compilation with AVX-512) and pastebin the full logs. Thanks

**Comment by jeffhammond** [comment]
I will test soon, but [SDE](https://software.intel.com/en-us/articles/intel-software-development-emulator) allows anyone to test AVX-512 without hardware, in case that helps.  If a detailed example is required, please look at the Travis CI testing for `arch=knl` in [BLIS](https://github.com/flame/blis).

**Comment by franz** [comment]
I've tested on MS Azure's AVX512 machines and it's generating code using zmm registers, although there were a few bugs in LLVM that were causing issues. Anyway i think this is done from pocl side.

**Comment by franz** [comment]
BTW when i said "a few bugs in LLVM", i meant in LLVM 5 - LLVM 4 is much more broken with AVX512. Probably it only becomes worthwhile with LLVM 6.
