### ISSUE TITLE
Adding a new device in pocl

### ISSUE THREAD

**Issue by CateCio** [pocl/pocl#531]
Hi,
My research team and I are developing a new architecture and we have already managed to implement a compiler using LLVM. My task now is to enable OpenCL support. The idea is to use as host a PC so an x86 architecture and as host our new architecture.  Since the compiler doesn't have any JIT, I'm aiming to use an offline compilation. However, my question is how can I modify pocl in order to add our architecture as a new device?

**Comment by pjaaskel** [comment]
Hi. Note that you don't strictly need JIT for OpenCL (which compiles while you run the program). The compiler is launched at host program execution time _for the whole kernel_. Thus, if you run on an x86 with Linux you should be able to support OpenCL kernel online compilation with pocl. 

Check lib/CL/devices for different device layer implementations. E.g. 'ttasim' or 'hsa' are good examples of heterogeneous setups. Former interfaces with an instruction set simulator which is nice for testing on a non-fabricated designs. 'basic' is a simple single core single thread CPU device implementation that is also a good starting point.
