### ISSUE TITLE
portablecl.org website is down

### ISSUE THREAD

**Issue by gmholland** [pocl/pocl#532]
As of today I am unable to access POCL's homepage at http://www.portablecl.org/ as it appears to be down.

**Comment by arghdos** [comment]
Looks up here:

http://downforeveryoneorjustme.com/www.portablecl.org

**Comment by Oblomov** [comment]
it's up again, but yesterday it was unreachable for me as well (from Italy, dunno about OP)

**Comment by gmholland** [comment]
Looks like it's back up now
