### ISSUE TITLE
pocl_binaries are not functionnal

### ISSUE THREAD

**Issue by rjodin** [pocl/pocl#537]
Hi everyone,

I updated my version of POCL, and my test-suite fails.
It fails on a test where I compile POCL without LLVM, and I try to run a kernel created from binary.

From what I see, we added the "program.bc" inside the binary. But it seems that you forget to take it into consideration when deserializing.
I found 2 functions in "pocl_binary.c" that seems not to take care of it:
-  pocl_binary_get_kernel_metadata
-  pocl_binary_get_kernel_count

In both of them, we are reading the header and then we try to get information of kernels. But with the current way of serializing the binary, the "program.bc" is just between the header and the kernels. So we would need to increment the buffer accordingly.

And then, I have another issue related.
When my code arrives in "clCreateKernel" (with POCL compiled without LLVM) at line 85 (53ef5e89aa99b5e85ad512ff46aa8f38b36acf4f today's master), it goes into "program->binaries" as now we deserialize "program.bc" in the cache directory (we write "program->binaries" in clCreateProgramWithBinary line 164). But as I do not have LLVM, it does nothing. It would have needed to go into "program->pocl_binaries".

If you agree with all this, I will propose a patch for this issue.

**Comment by pjaaskel** [comment]
Please do. I think offline compile compilation (aka no-LLVM) build is not tested regularly by my test suite so it's no wonder if it fails. If you have tests to share, I can add it to mine so it doesn't regress.

**Comment by rjodin** [comment]
We already have a test that test "clCreateProgramWithBinary" in POCL, but the test uses online compilation.
I don't know how to add a test that will just be run on a build of POCL without compiler. And for this test, we would need to give a static binary that would need to be rebuild each time we are changing the way we serialize/deserialize the binary. But I agree that it is important the improve our testing set on this feature.
How could I make a test that will be run only on a build of POCL without compiler?

**Comment by pjaaskel** [comment]
I don't know if there's any mechanism for that yet. Indeed it's important to have it in the test suite to avoid accidental breakage like this.

**Comment by franz** [comment]
I have one buildbot which is setup to build LLVM-less pocl builds to keep that setup buildable, but it does run any tests with it.

@rjodin

> How could I make a test that will be run only on a build of POCL without compiler?

With current pocl you'll need two buildroots (from the same source) and two tests, one that produces a binary and another that loads it. The test(s) can be not/build on the OCS_AVAILABLE cmake variable The only problem with automating this, is how to tell buildbot about a dependency in two buildroots.

**Comment by rjodin** [comment]
First, is it possible to add a test that will be only be run on the buildroot without LLVM?
Then we can add the binary in the test (and not generated it at each run of the bot). And we would have to update it each time we modify "pocl_binary.c"

**Comment by franz** [comment]
> Then we can add the binary in the test (and not generated it at each run of the bot) 
> update it each time we modify "pocl_binary.c"

I'm not sure it's a good idea. The pocl binary will depend on far more than just pocl_binary.c. At the very least it will depend on LLVM version (.bc in pocl binary - older LLVMs can't read bitcode from newer LLVMs) and the CPU (.so files in pocl binary) and possibly the OS (because the .so are linked to libm). Sounds very fragile.
