### ISSUE TITLE
pocl 0.15-pre w/ LLVM-4.0 on aarch64 reports unexpected caps

### ISSUE THREAD

**Issue by blu** [pocl/pocl#540]
I've just built pocl 0.15-pre natively on an aarch64 linux machine and I've noticed the following when querying the device caps:

```
        CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR:                    1
        CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT:                   1
        CL_DEVICE_NATIVE_VECTOR_WIDTH_INT:                     1
        CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG:                    1
        CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT:                   1
        CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE:                  1
        CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF:                    1
```
Shouldn't the device be NEON-enabled, and thus all vector types be effectively SIMD?

Perhaps I've missed something in the build options? Pocl has been configured as:
```
$ cmake ../pocl -DLLC_HOST_CPU=cortex-a72 -DKERNELLIB_HOST_CPU_VARIANTS=cortex-a72
```
Also, device vendor is reported as `Unknown x86`.

**Comment by franz** [comment]
Hello. No, you did not miss anything in the build options. In fact `-DKERNELLIB_HOST_CPU_VARIANTS=cortex-a72` is redundant, it should build fine with just  `-DLLC_HOST_CPU=cortex-a72`

> Shouldn't the device be NEON-enabled, and thus all vector types be effectively SIMD?

Yes, and quite likely it is. The values reported in *NATIVE are currently based on compile-time detection, and currently it only detects vector sizes on x86.

> Also, device vendor is reported as Unknown x86

We could fix that to "ARM" and "ARM64" or something like that. I don't know of any reliable way to detect ARM vendor or CPU model or anything. Contents of `/proc/cpuinfo` is so variable on ARMs that trying to parse it is futile, LLVM often also gives up and just returns "unknown", and i don't know of anything else.

But the truth is, the problems you describe are the smallest issues with pocl on ARM. The real issues are LLVM-related. I try to keep pocl buildable on ARM, but if you run the tests it's clear how broken pocl+ARM is..

**Comment by blu** [comment]
Hi, franz. Thank you for the reply. Indeed, I've traced the sources of those caps, and they seem rather mundane. Part of the reason is that compile-time detection (i.e. based on build target) looks for `__arm__`, whereas the aarch64 macro is `__aarch64__`. If you'd like I can prepare a reasonably robust patch for the arm detection, as long as we limit ourselves to linux. Re the treatment of vector types by the kernel compiler -- I've tried the poclcc and it does handle vectors as expected on aarch64, at least with the minimal test I've tried. So those caps peculiarities are rather aesthetic, at least for my purposes.

**Comment by franz** [comment]
> If you'd like I can prepare a reasonably robust patch for the arm detection, as long as we limit ourselves to linux.

Yes please. Limited to linux is not an issue.

**Comment by blu** [comment]
I've sent a pull request for a patch that addresses the CL_DEVICE_NAME and CL_DEVICE_VENDOR values.

**Comment by franz** [comment]
i believe this has been resolved in master (the native/preferred vector widths are also resolved, just not yet in master)

**Comment by blu** [comment]
Just FYI, I can confirm that POCL-0.15-pre master from yesterday has all the caps properly reported on aarch64 -- preferred and native vector sizes are all correct. Moreover, master now handles some non-trivial kernels on aarch64, which I had issues compiling before. So I'm a happy POCL user as of yesterday ; )
