### ISSUE TITLE
Build failure on ARM with -DCL_DISABLE_LONG=ON

### ISSUE THREAD

**Issue by tstellar** [pocl/pocl#544]
The build is failing on ARM with -DCL_DISABLE_LONG=ON due to  3877d6316985fdf36a54cfee745952436744ebcc.  The problem is the addition of math.h, which is redefining long.  Here is the error message:

In file included from /builddir/build/BUILD/pocl-53ef5e89aa99b5e85ad512ff46aa8f38b36acf4f/lib/kernel/printf.c:31:
In file included from /usr/include/math.h:37:
/usr/include/bits/types.h:33:18: error: typedef redefinition with different types ('unsigned int' vs 'struct error_undefined_type_long')
typedef unsigned long int __u_long;
                 ^
/builddir/build/BUILD/pocl-53ef5e89aa99b5e85ad512ff46aa8f38b36acf4f/include/pocl_types.h:37:16: note: expanded from macro 'long'
'#' define long error_undefined_type_long
               ^
/builddir/build/BUILD/pocl-53ef5e89aa99b5e85ad512ff46aa8f38b36acf4f/include/pocl_types.h:36:42: note: previous definition is here
typedef struct error_undefined_type_long error_undefined_type_long;
                                         ^

**Comment by pjaaskel** [comment]
This is likely a 32b issue instead of ARM ones, but I'm having troubles finding 32b Intel test boxes anymore. And unfortunately no one has stepped up as a new ARM maintainer yet :I

**Comment by franz** [comment]
yes, it's a 32bit issue (or perhaps a pocl_types.h issue, which breaks a ton of standard headers). Since one cannot call kernel lib's isnan(), possibly the simplest solution is just to implement one in printf.c.

**Comment by franz** [comment]
This should be fixed in c7102b1d347639d12

``CL_DISABLE_LONG`` was removed, because it was a LLVM 3.3 workaround option originally and not doing much these days. There's now a ``-DENABLE_FP64=ON/OFF`` cmake option on ARM platform to build with / without ``cl_khr_fp64``
