### ISSUE TITLE
More barrier fun (conditionals and loops)

### ISSUE THREAD

**Issue by SyamGadde** [pocl/pocl#553]
I have another misbehaving kernel:

```
// Expected output:
//  outer=A inner=B
//  + outer=A inner=B
// for each value of A and B.
// However I see three copies of the second line (starting with +).
// Commenting out any one line marked with YYYY bring it down to two copies,
// and commenting out any one line marked with XXXX gives the expected output.


__kernel void pocltest(int xarg1, int xarg2) {
    int outerend = 1;
    int innerend = 1;
    outerend = 2; // YYYY
    innerend = 2; // YYYY
    int outer = 0;
    int inner = 0;
    int arg1 = 1;
    int arg2 = 1;
    arg1 = xarg1; // XXXX
    arg2 = xarg2; // XXXX
    for (outer = 0; outer < outerend; outer++) // XXXX
    {
	for(inner = 0; inner < innerend; inner++) // XXXX
	{
	    printf("outer=%d inner=%d\n", outer, inner);
	    if (arg2 > arg1) // XXXX
	    {
		barrier(CLK_LOCAL_MEM_FENCE); // XXXX
	    }
	    if (arg1 > 0) // XXXX
	    {
		barrier(CLK_LOCAL_MEM_FENCE); // XXXX
	    }
	    printf("+ outer=%d inner=%d\n", outer, inner);
	}
    }

    if (arg1 > 0) // XXXX
    {
	barrier(CLK_LOCAL_MEM_FENCE); // XXXX
    }
}
```

This is cut down from a version that does actual computation, of course.  The code is two nested loops enclosing two conditionals, and followed by another conditional.  All the conditionals need to be evaluated at runtime because they use parameters sent into the kernel.  The output, using pocl trunk with either LLVM 5.0.0 or LLVM trunk, with a workgroup size of 1, and arguments arg1 and arg2 set to some value greater than zero, is:

```
outer=0 inner=0
+ outer=0 inner=0
+ outer=0 inner=0
+ outer=0 inner=0
outer=0 inner=1
+ outer=0 inner=1
+ outer=0 inner=1
+ outer=0 inner=1
outer=1 inner=0
+ outer=1 inner=0
+ outer=1 inner=0
+ outer=1 inner=0
outer=1 inner=1
+ outer=1 inner=1
+ outer=1 inner=1
+ outer=1 inner=1
```

The printf before the barriers in the inner loop is printed once as expected, but the printf after the barriers is printed three times.  Commenting out any line with XXXX, which means:
- commenting out any one of the barriers, or
- removing any one of the surrounding conditionals/ifs, or
- making any conditional resolvable at compile-time (i.e. replacing arg1 or arg2 with a constant)

fixes the issue.  Also commenting out any line with YYYY, which replaces the stop value of either the inner or outer loop from 2 to 1 (i.e. making it a singleton loop) makes it print only twice (but still incorrectly).

Also a LLVM bug?  And please let me know if these bugs should be directed somewhere else. Thanks again!

**Comment by pjaaskel** [comment]
Seems like a tricky barrier case stressing out the WGF analysis. Might well be pocl's fault this time. I will try to find the time to take a look next week.

**Comment by pjaaskel** [comment]
I spent a work day tracking this, but the resulting CFG analysis becomes so complex it needs more successive days of focus to fix. Unfortunately I don't have much time to spend for pocl's issues that do not concern our group's cases in the foreseeable future.

This indeed is an issue in the pocl's CFG analysis. It's quite a complex barrier usage scenario that stretches the static analysis. It also produces quite a bit of barrier tail duplication code bloat which should be cleaned up first to make more sense out if this case. In that analysis, the loop body should be treated as a separate entitity at which boundaries the BTR also should stop. As it's not a regression (it fails with 0.14/LLVM 4 too), I will set it as a non-blocker for 1.0. If you want to take a stab, I will provide support. Sorry!

**Comment by SyamGadde** [comment]
Thanks for the time you've spent on this!  Given what you've described, and after a quick skimming of the analysis code, I'm not sure I'll have the fortitude to venture further. :-)  But if I do end up having time to look into this, I'll be in touch!
