### ISSUE TITLE
clCreateSubDevices with type CL_DEVICE_PARTITION_BY_COUNTS doesn't respect supplied core count

### ISSUE THREAD

**Issue by arghdos** [pocl/pocl#554]
Migrated from mailing list [see here](https://sourceforge.net/p/pocl/mailman/message/36100200/) for details and example.

**Comment by franz** [comment]
@arghdos PR #571 has the fix (there's also a test for it)

**Comment by arghdos** [comment]
@franz thanks!  Giving this a test shows an increasing runtime (for a problem size of 10^7 in the example from the mailing list), with increasing cores:

>platform: pocl  num cores: 1    elapsed time: 2.722041e+03
platform: pocl  num cores: 2    elapsed time: 2.964494e+03
platform: pocl  num cores: 4    elapsed time: 3.134813e+03
platform: pocl  num cores: 8    elapsed time: 5.078341e+03
platform: pocl  num cores: 16   elapsed time: 4.990547e+03
platform: pocl  num cores: 32   elapsed time: 7.407428e+03
platform: Intel num cores: 1    elapsed time: 2.003667e+03
platform: Intel num cores: 2    elapsed time: 2.509890e+03
platform: Intel num cores: 4    elapsed time: 1.000509e+03
platform: Intel num cores: 8    elapsed time: 8.530500e+02
platform: Intel num cores: 16   elapsed time: 7.983490e+02
platform: Intel num cores: 32   elapsed time: 7.267400e+02

so there is likely more optimization to do in the scheduler, but the CPU usage shown by `top` does correspond to the expected number of cores.

Perhaps we should close this one and open another issue for scheduler performance?  I'd also be willing to take a look at that if you'd like

**Comment by arghdos** [comment]
Also of potentially of note, the SubDev test is failing with a segfault on this system:

>Command: "/home/ncurtis/pocl/build/examples/EinsteinToolkit/EinsteinToolkit" "s"
Directory: /home/ncurtis/pocl/build/examples/EinsteinToolkit
"EinsteinToolkit_SubDev" start time: Nov 24 12:48 EST
Output:
----------------------------------------------------------
<end of output>
Test time =   0.89 sec
----------------------------------------------------------
Test Failed.
"EinsteinToolkit_SubDev" end time: Nov 24 12:48 EST
"EinsteinToolkit_SubDev" time elapsed: 00:00:00

**Comment by pjaaskel** [comment]
> I'd also be willing to take a look at that if you'd like

That would be very much appreciated, thanks. Feel free to open one to track the thread scheduler improvements. Also please open a separate issue for the segfault.

**Comment by franz** [comment]
> so there is likely more optimization to do in the scheduler

Looking at the code you posted on the mailing list, it uses ``reqd_work_group_size(1, 1, 1)`` on a kernel that contains a single instruction, which is probably the worst possible case.

I'm not entirely sure, but i think the ``reqd_work_group_size(1,1,1)`` prevents pocl from vectorizing your kernel in any way, which means you'll see terrible overhead from the scheduler.

Looking at real programs with perf top these days, i don't find the pthread scheduler's overhead to be a big issue, but of course you may try to optimize it, if you wish :)

**Comment by arghdos** [comment]
@franz you were right, converting it to a 16-wide vector:

```
__kernel void __attribute__ ((reqd_work_group_size(16, 1, 1))) knl(__global double *__restrict__ host_ptr, __global double *__restrict__ host_alloc)
{
  int start = (gid(0) / 16) * 16;
  host_alloc[start + lid(0)] = host_ptr[start + lid(0)] + 1;
}
```
shows the expected scaling (at least until large numbers of cores):

>platform: pocl  num cores: 1    elapsed time: 1.173165e+03
platform: pocl  num cores: 2    elapsed time: 8.242200e+02
platform: pocl  num cores: 4    elapsed time: 4.475670e+02
platform: pocl  num cores: 8    elapsed time: 2.580750e+02
platform: pocl  num cores: 16   elapsed time: 2.220630e+02
platform: pocl  num cores: 32   elapsed time: 3.015940e+02
platform: Intel num cores: 1    elapsed time: 1.119206e+03
platform: Intel num cores: 2    elapsed time: 1.523123e+03
platform: Intel num cores: 4    elapsed time: 6.377260e+02
platform: Intel num cores: 8    elapsed time: 3.384320e+02
platform: Intel num cores: 16   elapsed time: 3.809040e+02
platform: Intel num cores: 32   elapsed time: 3.281970e+02
