### ISSUE TITLE
no calling of uninit

### ISSUE THREAD

**Issue by jianbinfang** [pocl/pocl#561]
Hi Guys,

It seems that we forgot calling the uninit APIs in all the target-specific implementations (CUDA, pthread, hsa, etc). This function has a prototype in 'pocl_##__DRV__##_uninit' in ./lib/CL/devices/prototypes.inc:44, and we also have their target-specific implementations such as pocl_cuda_uninit in ./lib/CL/devices/cuda/pocl-cuda.c. I have looked through the code, and note that we forgot calling this function. 

As an solution, I suggest we call the uninit API in clReleaseContext. 

Regards,
Jianbin

**Comment by franz** [comment]
> I suggest we call the uninit API in clReleaseContext.

Calling in clReleaseContext() is not so simple, we must call it after **last** context was released. Then we need some new code to re-init the devices in case some program decides to create a context after releasing all of them.

We haven't forgot calling uninit, it just hasn't been a high priority - and it will require quite a few changes to do properly.
