### ISSUE TITLE
pocl 0.15-pre LLVM-4.0.1 yields suboptimal code from fmin/fmax on arm64

### ISSUE THREAD

**Issue by blu** [pocl/pocl#563]
Hi,

It appears latest pocl produces suboptimal code from fmin/fmax on arm64. The following code
```
__kernel __attribute__ ((vec_type_hint(float4)))
void example(
    __global const float4* const src_a,
    __global const float4* const src_b,
    __global float4* const dst)
{
    const size_t idx = get_global_id(0);
    dst[idx] = fmin(src_a[idx], src_b[idx]);
}
```

produces a sequence of number-of-vector-elements scalar comparisons of the kind (s0 and s16 are lanes from the two inputs):

```
fcmp   s0, s16
fcsel  s24, s0, s16, gt
fcmp   s16, s16
fcsel  s0, s24, s0, vc
...
```

whereas it should produce just an aarch64 vector fminnm/fmaxnm, or fmin/fmax under -cl-finite-math-only. Issue manifests for both float4 and float8 (have not tried other vector dimensions).

Here's the full output from the sample kernel's fmin() emit:

```
0000000000000334 <_cl_fmin(float __vector(4), float __vector(4))>:
 334:   stp     x29, x30, [sp,#-16]!
 338:   mov     x29, sp
 33c:   fcmp    s1, s0
 340:   mov     s2, v0.s[1]
 344:   mov     s3, v0.s[2]
 348:   mov     s4, v0.s[3]
 34c:   mov     s5, v1.s[1]
 350:   mov     s6, v1.s[2]
 354:   mov     s7, v1.s[3]
 358:   fcsel   s16, s0, s1, gt
 35c:   fcmp    s5, s2
 360:   fcsel   s17, s2, s5, gt
 364:   fcmp    s6, s3
 368:   fcsel   s18, s3, s6, gt
 36c:   fcmp    s7, s4
 370:   fcsel   s19, s4, s7, gt
 374:   fcmp    s1, s1
 378:   fcsel   s0, s16, s0, vc
 37c:   fcmp    s5, s5
 380:   fcsel   s1, s17, s2, vc
 384:   fcmp    s6, s6
 388:   fcsel   s2, s18, s3, vc
 38c:   fcmp    s7, s7
 390:   mov     v0.s[1], v1.s[0]
 394:   fcsel   s1, s19, s4, vc
 398:   mov     v0.s[2], v2.s[0]
 39c:   mov     v0.s[3], v1.s[0]
 3a0:   ldp     x29, x30, [sp],#16
 3a4:   ret
```
Please note that not only de-vectorized code is produced, but it also does not inline.

**Comment by pjaaskel** [comment]
Please try with LLVM 5.0 too. Unfortunately, we still miss an ARM maintainer.

**Comment by franz** [comment]
1) are you running cmake with -DLLC_HOST_CPU ?
2) are you using SLEEF or VML for kernel library ?

By default now is pocl builds with SLEEF enabled even on ARMs, and it doesn't look like you have it enabled, because the SLEEF code for fmin() also has one isnan() comparison. If you're using VML i suspect you'll find a lot more cases of suboptimal (and non-conformant) behaviour.

> but it also does not inline.

that also sounds like VML with LLVM 5.0.

**Comment by blu** [comment]
> 1. are you running cmake with -DLLC_HOST_CPU ?

Yep, cortex-a72.

> 2. are you using SLEEF or VML for kernel library ?

Whatever comes by default in cmake. The isnan() is there in the code -- all the fcmp + fcsel w/ vc flag pairs are effectively isnan().

**Comment by franz** [comment]
> Whatever comes by default in cmake. 

Well the default was VML and has changed, so please try a fresh build in an empty directory. Near end of cmake output, there should be a line:

```
-- ENABLE_SLEEF: ON
```

> The isnan() is there in the code -- all the fcmp + fcsel w/ vc flag pairs are effectively isnan().

OK, my guess about that was wrong :) In that case either LLVM somehow manages to replace intrinsics with scalar instructions, or the only other explanation i see is: you're not building with SLEEF. Looking at sources:

https://github.com/pocl/pocl/blob/master/lib/kernel/sleef/arch/helperadvsimd.h#L538

https://github.com/pocl/pocl/blob/master/lib/kernel/sleef/arch/helperadvsimd.h#L473

... all of these should translate to a few instructions at most, AFAICT.

The fmin function is here:
https://github.com/pocl/pocl/blob/master/lib/kernel/sleef/libm/sleefsimdsp.c#L1718

I don't see anything scalar, or any reason why LLVM would convert this to scalars.

**Comment by blu** [comment]
According to CMakeCache.txt my pocl was actually built with SLEEF:
```
ENABLE_SLEEF:BOOL=ON
```
So investigating further based on that.

> In that case either LLVM somehow manages to replace intrinsics with scalar instructions..

I think that's exactly what happens, and I can see a good reason for that:

> The fmin function is here:
> https://github.com/pocl/pocl/blob/master/lib/kernel/sleef/libm/sleefsimdsp.c#L1718

Just to quote the function in question:
```
EXPORT CONST vfloat xfminf(vfloat x, vfloat y) {
  return vsel_vf_vo_vf_vf(visnan_vo_vf(y), x, vsel_vf_vo_vf_vf(vgt_vo_vf_vf(y, x), x, y));
}
```
The problem with the above function is that it is modelled after the semantics of x86_64's instruction minps, which is **not** the semantics of OCL fmin(), at least outside of -cl-finite-math-only. The difference is in the treatment of NaNs. Relevant excerpt from Intel's ISA reference manual:
> If only one value is a NaN (SNaN or QNaN) for this instruction, the second operand (source operand), either a NaN or a valid floating-point value, is written to the result.

In contrast to the semantics of OCL's fmin():
> If one argument is a NaN, fmin() returns the other argument. If both arguments are NaNs, fmin()
returns a NaN.

In its turn, aarch64's has two vector min/max semantics:
1) fminnm/fmaxnm implement precisely OCL's fmin()/fmax() semantics, whereas
2) fmin/fmax implement the common 'return NaN is either arg is NaN'.

Neither of the above matches Intel's minps/maxps semantics, and SLEEF xfminf() is essentially Intel's semantics, LLVM is forced into the suboptimal sequence observed.

Now, the question is, do we want to fix that code into full OCL compliance, potentially penalizing x86, or do we want to keep the status quo, penalizing non-x86 architectures, including those that implement OCL fmin/fmax semantics?

**Comment by blu** [comment]
Pull request sent:
SLEEF xfmin/xfmax/xfminf/xfmaxf adopt OCL fmin/fmax semantics on platforms with built-in OCL-compatible min/max instructions (for now aarch64); original semantics of SLEEF xfmin/xfmax/xfminf/xfmaxf preserved on platforms without such instructions

The non-inlining issue survives the patch, though.

**Comment by blu** [comment]
Apropos, here's a (non-exhaustive) set of very thin functions (as seen in linux perf) that for some reason don't inline on aarch64 (some functions have multiple occurrences due to overloads):

```
   3.55%           641  problem_4  monokernel.so        [.] _cl_fmin                                                                                                                                                            
   3.35%           603  problem_4  monokernel.so        [.] _cl_fmin                                                                                                                                                            
   2.99%           538  problem_4  monokernel.so        [.] _cl_fmax                                                                                                                                                            
   1.94%           349  problem_4  monokernel.so        [.] _cl_fmax                                                                                                                                                            
   1.85%           332  problem_4  monokernel.so        [.] _cl_islessequal                                                                                                                                                     
   1.63%           294  problem_4  monokernel.so        [.] _cl_select                                                                                                                                                          
   1.58%           286  problem_4  monokernel.so        [.] _cl_fmin                                                                                                                                                            
   1.52%           273  problem_4  monokernel.so        [.] _cl_fmin                                                                                                                                                            
   1.31%           237  problem_4  monokernel.so        [.] _cl_isless                                                                                                                                                          
   1.13%           203  problem_4  monokernel.so        [.] _cl_select                                                                                                                                                          
   0.67%           120  problem_4  monokernel.so        [.] _cl_select                                                                                                                                                          
   0.63%           113  problem_4  monokernel.so        [.] _cl_fmax                                                                                                                                                            
   0.36%            64  problem_4  monokernel.so        [.] _cl_fmin                                                                                                                                                            
   0.32%            58  problem_4  monokernel.so        [.] _cl_fmax                                                                                                                                                            
   0.27%            49  problem_4  monokernel.so        [.] _cl_isless                                                                                                                                                          
   0.23%            41  problem_4  monokernel.so        [.] _cl_fmax
```

**Comment by franz** [comment]
> Neither of the above matches Intel's minps/maxps semantics, and SLEEF xfminf() targetting essentially Intel's semantics, LLVM is forced into the suboptimal sequence observed.

Sorry but that makes absolutely no sense. LLVM cannot know and does not care that some function is implemented in a way suitable to Intel. If you look into sources carefully, you'll see that **all** of the helpers like ``visnan_vo_vf`` are using ARM *vector intrinsics* directly. So LLVM is given a small bunch of ARM vector intrinsics - which may implement something the suboptimal way, but that's not a reason to replace them with scalars.

After some fiddling on my Odroid C2, i think i found out what's really going on. I think you have some missing compiler flags - and very likely you'll need to update to LLVM 5.0. I have built pocl git master with LLVM 5, on Cortex A53 (aarch64), and with a small program using fmin(), it both vectorizes and inlines the fmin(). Your LLVM probably (because missing flags) doesn't know if your CPU supports neon, and decides to not use it - and replaces vector intrinsics with scalars. I've also tried a few of those functions you say are not inlined, and all were inlined. So clearly this is not a general ARM64 or SLEEF issue, but rather your system+llvm.

Your PR idea - replacing fmin/fmax with a single instruction - sounds good, but it won't solve your bigger problem. You need to find the proper flags to enable NEON for your CPU, and very likely you'll have to upgrade LLVM to get better results.

**Comment by franz** [comment]
BTW we have already had an issue similar this, for someone compilation failed unless he provided -mfpu=vfp-something flag. This is a general problem with ARM - LLVM has trouble detecting capabilities of ARM CPUs and needs to be told explicitly what features are present.

**Comment by blu** [comment]
> Sorry but that makes absolutely no sense. LLVM cannot know and does not care that some function is implemented in a way suitable to Intel. If you look into sources carefully, you'll see that all of the helpers like visnan_vo_vf are using ARM vector intrinsics directly. So LLVM is given a small bunch of ARM vector intrinsics - which may implement something the suboptimal way, but that's not a reason to replace them with scalars.

You're right, I got carried away -- the de-vectorization cannot be explained by the suboptimal fmin/fmax implementation. Meanwhile I too got pocl + LLVM 5 on a cortex-a53, where LLVM's llc recognizes the host cpu and the non-inlining and de-vectorization went away. But still two problems remain:
1. On a platform where llc does not recognize the host cpu passing a correct LLC_HOST_CPU to pocl does not solve the issue with SLEEF routines. And it's not like all CL code gets de-vectorized -- there's plenty of NEON code generated in other parts of the kernel, so NEON is enabled alright. It seems like some portions of the kernel don't get correct LLVM flags, and that does warrant an investigation beyond 'it must be your system + llvm'. As I'm doing this investigation anyway, any hints to where to look for LLVM passes over SLEEF code would be welcome.
2. On that cortex-a53 with LLVM 5 where things are supposedly alright, the codegen from fmin/fmax is still very far from optimal on aarch64. So please do consider that PR.

**Comment by pjaaskel** [comment]
Might be worth checking pocl_llvm_wg.cc around line 324. We currently call scalarizer in the hopes of being able to work-group vectorizer better. This should be eventually replaced with a better logic inside the loop vectorizer. I haven't checked if it has happened yet. You can try disabling that line to see if the scalarizer breaks your vectors.

**Comment by franz** [comment]
@blu yes you're right, it requires more investigation.

> On a platform where llc does not recognize the host cpu passing a correct LLC_HOST_CPU to pocl does not solve the issue with SLEEF routines.

 .... yes, i think you'll need to pass either ``-mfpu`` or something like ``-march=armv8-a+simd+fp`` flags, and our  current CMake code does not make it possible to pass these flags to all places where they need to be. But i can fix this easily. After that it'll be up to you to find the required flags.

> It seems like some portions of the kernel don't get correct LLVM flags

.. some portions are compiled with -O1 while some are not (because enabling it for everything has broken some stuff), which affects inlining, at least with LLVM 5, not sure about LLVM 4.

If you have time for a small experiment, edit the file ``cmake/bitcode_rules.cmake``, for each function ``compile_X_to_bc`` add an ``-O1``  into the custom command. Recompile pocl, go into ``lib/kernel/host`` dir, run ``llvm-dis kernel-something.bc`` and ``grep -A1 noinline kernel-something.bc``. This gives a list of functions that will NOT be inlined. There's about 10-20 for x86-64 currently, if your list is much longer then something is wrong. Compare this list to one from default pocl build and pls report if -O1 makes any difference.

> So please do consider that PR


Yes, i did say it's a good idea. But only if you're 100% sure those instructions are present on all ARM64 machines; otherwise it'll have to be somehow ifdef-ed / CMake option-ized.

**Comment by blu** [comment]
Thanks for the directions, @pjaaskel, @franz -- I'll follow through and report back.

>Yes, i did say it's a good idea. But only if you're 100% sure those instructions are present on all ARM64 machines; otherwise it'll have to be somehow ifdef-ed / CMake option-ized.

fminnm/fmaxnm are mandatory for aarch64 neon (AKA asimd); instructions are not present in ARMv7 neon, but IIRC lib/kernel/sleef/arch/helperadvsimd.h is just for aarch64, correct?

**Comment by blu** [comment]
I can confirm that the de-vectorization under LLVM4 and unknown host CPU (-DLLC_HOST_CPU=cortex-a72) is caused by the scalarizer pass as suggested by @pjaaskel.

For reference, here's the code emitted from fmin() without scalarizer pass:
```
000000000000032c <_cl_fmin(float __vector(4), float __vector(4))>:
 32c:   stp     x29, x30, [sp,#-16]!
 330:   mov     x29, sp
 334:   fcmge   v2.4s, v1.4s, #0.0
 338:   fcmlt   v3.4s, v1.4s, #0.0
 33c:   fcmgt   v4.4s, v1.4s, v0.4s
 340:   orr     v2.16b, v3.16b, v2.16b
 344:   bsl     v4.16b, v0.16b, v1.16b
 348:   bsl     v2.16b, v4.16b, v0.16b
 34c:   mov     v0.16b, v2.16b
 350:   ldp     x29, x30, [sp],#16
 354:   ret
```
Compare that to the emitted code under LLVM5 **with** scalarizer and known CPU (cortex-a53), and prior to the recent SLEEF PR:
```
...
 398:   ld4     {v0.2s-v3.2s}, [x4], #32
 39c:   subs    x3, x3, #0x2
 3a0:   ld4     {v4.2s-v7.2s}, [x5], #32
 3a4:   fcmge   v16.2s, v4.2s, #0.0
 3a8:   fcmlt   v17.2s, v4.2s, #0.0
 3ac:   fcmge   v18.2s, v5.2s, #0.0
 3b0:   fcmlt   v19.2s, v5.2s, #0.0
 3b4:   fcmge   v20.2s, v6.2s, #0.0
 3b8:   fcmlt   v21.2s, v6.2s, #0.0
 3bc:   fcmge   v22.2s, v7.2s, #0.0
 3c0:   orr     v25.8b, v17.8b, v16.8b
 3c4:   fcmlt   v23.2s, v7.2s, #0.0
 3c8:   fcmgt   v24.2s, v4.2s, v0.2s
 3cc:   fcmgt   v16.2s, v5.2s, v1.2s
 3d0:   fcmgt   v17.2s, v6.2s, v2.2s
 3d4:   orr     v26.8b, v19.8b, v18.8b
 3d8:   fcmgt   v18.2s, v7.2s, v3.2s
 3dc:   bsl     v24.8b, v0.8b, v4.8b
 3e0:   bsl     v16.8b, v1.8b, v5.8b
 3e4:   bsl     v17.8b, v2.8b, v6.8b
 3e8:   orr     v27.8b, v21.8b, v20.8b
 3ec:   bsl     v18.8b, v3.8b, v7.8b
 3f0:   orr     v28.8b, v23.8b, v22.8b
 3f4:   bsl     v25.8b, v24.8b, v0.8b
 3f8:   bsl     v26.8b, v16.8b, v1.8b
 3fc:   bsl     v27.8b, v17.8b, v2.8b
 400:   bsl     v28.8b, v18.8b, v3.8b
...
```
There's apparent workgroup unrolling in the second emit (by a factor of 2), and also all ASIMD code uses the 64-bit D-form ops (vs 128-bit Q-form regs in the first emit), but otherwise the emitted code is the same.

**Comment by blu** [comment]
@franz, re inlining under LLVM4, I checked cl_fmin(<4xfloat>, <4xfloat>) from the examples above -- it does not seem to be `noinline` at default optimization level:

```
$ grep -B1 -e cl_fminDv4_fS kernel-aarch64-unknown-linux-gnu-cortex-a72.ll 
; Function Attrs: norecurse nounwind readnone
define <4 x float> @_Z8_cl_fminDv4_fS_(<4 x float>, <4 x float>) local_unnamed_addr #0 {
```
And SLEEF code appears to be already at -O1 in `cmake/bitcode_rules.cmake`:
```
function(compile_sleef_c_to_bc EXT FILENAME SUBDIR BCLIST)
    get_filename_component(FNAME "${FILENAME}" NAME)
    set(BC_FILE "${CMAKE_CURRENT_BINARY_DIR}/${SUBDIR}/${EXT}_${FNAME}.bc")
    list(APPEND ${BCLIST} "${BC_FILE}")
    set(${BCLIST} ${${BCLIST}} PARENT_SCOPE)
    set(FULL_F_PATH "${CMAKE_SOURCE_DIR}/lib/kernel/${FILENAME}")

    add_custom_command( OUTPUT "${BC_FILE}"
        DEPENDS "${FULL_F_PATH}"
        ${SLEEF_C_KERNEL_DEPEND_HEADERS}
        COMMAND "${CLANG}" ${CLANG_FLAGS} ${ARGN}
        "-I" "${CMAKE_SOURCE_DIR}/lib/kernel/sleef/arch"
        "-I" "${CMAKE_SOURCE_DIR}/lib/kernel/sleef/libm"
        "-I" "${CMAKE_SOURCE_DIR}/lib/kernel/sleef/include"
        "-O1" "-xc" "-o" "${BC_FILE}" "-c" "${FULL_F_PATH}"
        COMMENT "Building SLEEF to LLVM bitcode ${BC_FILE}"
        VERBATIM)
endfunction()
```

So whatever is killing the inlining in LLVM4 is doing it after the `lib/kernel/host/kernel-*.bc` stage.

BTW, I've patched my LLVM4 to return the correct host CPU string by `sys::getHostCPUName()` and pocl now has `#define KERNELLIB_HOST_CPU_VARIANTS "native"` but that does not seem to change anything re inlining.

**Comment by blu** [comment]
BTW, at this stage I consider this ticket effectively fixed. A quick summary, from my perspective:
1. All original issues -- the de-vectorization, non-inlining and unused aarch64 fminnm/fmaxnm -- do not exist in pocl-0.15-pre/LLVM5 with current master; that alone has produced some 3x speedup factor in my tests vs the initial situation.
2. The de-vecotrization under LLVM4 appears to be a side-effect of a deliberate pass -- the scalarizer; the issue there appears to be more of a problem with subsequent passes not getting their effects through, than in the de-vectorization per se. I strongly suspect a relation between the non-inlining and the persistent effect of the scalarizer pass.
3. Making pocl/LLVM4 well aware of the host aarch64 CPU does not solve the non-inlining, so that line of investigation ended up a red herring.
