### ISSUE TITLE
pocl verification -- workgroup order

### ISSUE THREAD

**Issue by jianbinfang** [pocl/pocl#567]
Hey Guys, 

In the OpenCL specification, there is no restriction on the 'execution' order of work-groups. Actually, groups are running concurrently and independently on distinct cores. However, when verifying pocl (e.g., basic_barriers.cl), we use basic_barriers_2_2_2_2.stdout as the 'only' answer for the output. But the point is that workgroup 1 may print the message before workgroup0, rather than after it. In this case, we regard the outputting results are wrong. I assume that this is a bug. 

Regards,
Jianbin

**Comment by pjaaskel** [comment]
This is why we use the 'basic' device driver instead of 'pthread' for these tests with a single thread and guaranteed sequential WG execution order.
