### ISSUE TITLE
conformance_test_micro doesn't work

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#574]
When trying to enable it in the test suites in CMake, it claims it doesn't understand what it is. When this suite is defined, 'make check' should run only the micro / "smoke test suite" that we shall add to Tier-1 tests.

**Comment by franz** [comment]
If by "enabling in cmake" you mean the cmake command line, then the only thing needed is ``-DENABLE_TESTSUITES=conformance``. The code checks subdirectories in ``examples/``.
IIRC the list of all available testsuites is written somewhere at the end of cmake output..

I'm not sure how "make check" works, it's some fancy workaround someone added ages ago, no ? i can take a look, but i have no idea if it's possible to limit it to some specific testsuites.

**Comment by pjaaskel** [comment]
But then "make check" runs the full suite by default, right? Am I supposed to add TESTSUITEFLAGS to filter only the short suite? Is there a nice way to run all the enabled tests, but only the micro tagged ones from the conformance suite?
