### ISSUE TITLE
Memory access violation with clBuildProgram on invalid program

### ISSUE THREAD

**Issue by jszuppe** [pocl/pocl#577]
I'm getting `memory access violation at address: 0x00000000: no mapping at fault address` on `clBuildProgram` when I tried to build a program with invalid code for the second time. We found this problem when testing new exception class that keeps a build log: https://github.com/boostorg/compute/pull/752.

I created a simpler test for that: https://github.com/jszuppe/compute/commits/pocl_bug_on_build_fail (Travis CI: https://travis-ci.org/jszuppe/compute/builds/307320530, failing builds use POCL). The test fails both on `0.13` and `master`. It works fine on AMD, Intel, NVIDIA.

```cpp
BOOST_AUTO_TEST_CASE(two_failed_builds)
{
    const char invalid_source[] =
        "__kernel void foo(__global int *input) { !@#$%^&*() }";

    compute::program invalid_program =
        compute::program::create_with_source(invalid_source, context);

    // First build failure
    try {
        invalid_program.build(); // this calls clBuildProgram
        // should not get here
        BOOST_CHECK(false);
    }
    catch(compute::opencl_error&){
        std::string log = invalid_program.build_log();
        BOOST_CHECK(!log.empty());
    }
    // 2nd build failure
    try {
        invalid_program.build(); // this calls clBuildProgram,
                                 // memory access violation

        // should not get here
        BOOST_CHECK(false);
    }
    catch(compute::opencl_error&){
        std::string log = invalid_program.build_log();
        BOOST_CHECK(!log.empty());
    }
}
```
I can later prepare pure OpenCL example if you care for it.

**Comment by franz** [comment]
> I can later prepare pure OpenCL example if you care for it.

@jszuppe  no need, i've added trivial regression test.

**Comment by jszuppe** [comment]
Thanks for the confirmation. Is the test on GitHub already?

**Comment by franz** [comment]
Not yet. It'll be in next PR together with a fix (this one was quite easy..)

I've tried building your ``compute`` project, and the ``core.program`` test still fails in ``compute_test::create_with_il``

It seems to try building a SPIR kernel despite the fact that pocl doesn't advertise ``cl_khr_spir`` extension unless built with specific clang (and ``clCreateProgramWithIL`` is a 2.1 API call).

**Comment by jszuppe** [comment]
> I've tried building your compute project, and the core.program test still fails in compute_test::create_with_il

You must have used 2.1 OpenCL headers, and I see there's a missing check if device supports 2.1. I'll fix that today, thanks for the info.
