### ISSUE TITLE
lots of "double precision constant requires cl_khr_fp64, casting to single precision" warnings when building PR #580

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#581]
[ 26%] Building CL to LLVM bitcode /home/visit0r/src/pocl/build-llvm-5.0-release/lib/kernel/host/ivybridge/async_work_group_strided_copy.cl.bc
/home/visit0r/src/pocl/lib/kernel/convert_type.cl:37765:30: warning: double precision constant requires cl_khr_fp64, casting to single precision
  return select(res, (float)(0x1.fffffep+30), convert_int(x >= 0x7ffffffc));

**Comment by franz** [comment]
this happens only on TCE-enabled builds, likely because TCE does not build with FP64

**Comment by pjaaskel** [comment]
OK. Enabling of TCE should not affect the host lib build, so there must be something wrong in the build files.
