### ISSUE TITLE
Release 1.0 failing to find platforms

### ISSUE THREAD

**Issue by cdeterman** [pocl/pocl#583]
I have a simple repository to check whether I can use a given pocl release [here](https://github.com/cdeterman/pocl_test).  Updating it to use the 1.0 release my build is now failing with the error 

>Error -1001 in clGetPlatformIDs Call!

The C++ file that is executed is seen [here](https://github.com/cdeterman/pocl_test/blob/master/clDeviceQuery.cpp).  This worked with the previous 0.14 release and I don't know why it isn't working with the 1.0 now.  Any thoughts?

**Comment by pjaaskel** [comment]
At least the clang is too old. 4.0 and 5.0 are supported..

**Comment by cdeterman** [comment]
I just updated the travis.yml to use 5.0.  Still the same error.

**Comment by franz** [comment]
Not a bug in pocl. Just tried that file on my laptop:

```
[franz@fujitsu701 b500]$ g++ -o cldev /tmp/clDeviceQuery.cpp -lOpenCL -pthread
[franz@fujitsu701 b500]$ ./cldev 
clDeviceQuery Starting...

1 OpenCL Platforms found

 CL_PLATFORM_NAME:      Portable Computing Language
 CL_PLATFORM_VERSION:   OpenCL 1.2 pocl 1.0, LLVM 5.0.0
OpenCL Device Info:

 1 devices found supporting OpenCL on: Portable Computing Language

 ----------------------------------
 Device pthread-Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
 ---------------------------------
  CL_DEVICE_NAME:                       pthread-Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
  CL_DEVICE_VENDOR:                     GenuineIntel
  CL_DRIVER_VERSION:                    1.0
  CL_DEVICE_TYPE:                       CL_DEVICE_TYPE_CPU
  CL_DEVICE_MAX_COMPUTE_UNITS:          4
  CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:   3
  CL_DEVICE_MAX_WORK_ITEM_SIZES:        4096 / 4096 / 4096 
  CL_DEVICE_MAX_WORK_GROUP_SIZE:        4096
  CL_DEVICE_MAX_CLOCK_FREQUENCY:        2501 MHz
  CL_DEVICE_ADDRESS_BITS:               64
  CL_DEVICE_MAX_MEM_ALLOC_SIZE:         2048 MByte
  CL_DEVICE_GLOBAL_MEM_SIZE:            5711 MByte
  CL_DEVICE_ERROR_CORRECTION_SUPPORT:   no
  CL_DEVICE_LOCAL_MEM_TYPE:             global
  CL_DEVICE_LOCAL_MEM_SIZE:             32768 KByte
  CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:   32768 KByte
  CL_DEVICE_QUEUE_PROPERTIES:           CL_QUEUE_PROFILING_ENABLE
  CL_DEVICE_IMAGE_SUPPORT:              1
  CL_DEVICE_MAX_READ_IMAGE_ARGS:        128
  CL_DEVICE_MAX_WRITE_IMAGE_ARGS:       128

  CL_DEVICE_IMAGE <dim>                 2D_MAX_WIDTH     8192
                                        2D_MAX_HEIGHT    8192
                                        3D_MAX_WIDTH     2048
                                        3D_MAX_HEIGHT    2048
                                        3D_MAX_DEPTH     2048
  CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>  CHAR 16, SHORT 16, INT 8, FLOAT 4, DOUBLE 8


clDeviceQuery, Platform Name = Portable Computing Language, Platform Version = OpenCL 1.2 pocl 1.0, LLVM 5.0.0, NumDevs = 1, Device = pthread-Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
```

My guess - you have undefined symbols in libpocl.so which results in your ICD unable to load libpocl. This has happened to me before, the undefined symbols were llvm/clang ones, i haven't determined the reason.

**Comment by cdeterman** [comment]
Any recommendations on how to build in the Travis CI environment then (essentially a Ubuntu Trusty image)?

**Comment by franz** [comment]
@cdeterman this *may* actually be a bug in pocl's cmake scripts. Could you try running ``<PATH-TO-LLVM>/llvm-config  --shared-mode`` in your environment ?

**Comment by franz** [comment]
BTW the simple way to find out which symbols exactly are missing, is to build pocl with ```-DENABLE_ICD=OFF``. Without ICD pocl fails to build with error messages, if there are any unresolved symbols.

**Comment by cdeterman** [comment]
@franz The only thing I see when I run the `llvm-config --shared-mode` is `shared` on the line in the build script output [here](https://travis-ci.org/cdeterman/pocl_test/builds/316516778#L1708)

**Comment by franz** [comment]
> llvm-config --shared-mode is shared

@cdeterman  then i think your best bet is to build with ``-DENABLE_ICD=OFF`` and see what error it prints.

**Comment by cdeterman** [comment]
I tried with `-DENABLE_ICD=OFF` but the build still completed with no obvious errors.  You can see the output starting [here](https://travis-ci.org/cdeterman/pocl_test#L7180).

**Comment by franz** [comment]
@cdeterman  i don't see the pocl build anywhere in that log. There's the command that builds the test, but i see no sign of pocl building..

**Comment by cdeterman** [comment]
@franz you may need to click the 'down arrow' at line 713 where the only thing showing is `cd ..`.  Inside there you will find the `cmake` output.

**Comment by franz** [comment]
@cdeterman OK i think i see the problem. You're installing pocl before using it, and you build it with default cmake install dir (which is ``/usr/local``). Which means pocl.icd ends up installed into ``/usr/local/etc/OpenCL/vendors`` and the ICD loader doesn't find it. Pocl will always install the icd file into ``<PREFIX>/etc/OpenCL/vendors``, **except** when prefix is ``/usr`` - then pocl tries to install it directly to ``/etc/OpenCL/vendors``.

You have two options: 1) change the pocl cmake command to:

```
cmake -DWITH_LLVM_CONFIG=${POCL_LLVM_CONFIG} -DCMAKE_INSTALL_PREFIX=/usr ..
```

... or 2) set up an env var: ``export OCL_ICD_VENDORS=/usr/local/etc/OpenCL/vendors/pocl.icd`` before running tests. You'll also want to drop the ``-DENABLE_ICD=OFF`` i suggested before.

**Comment by cdeterman** [comment]
@franz that fixed the issue.  Thanks for your help.  I will close the issue then.
