### ISSUE TITLE
zlib also needed for installation (not mentioned in documentation) on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by Kristian-Popov** [pocl/pocl#585]
Good evening!
I tried to build POCL in a most standard way as described [here](http://portablecl.org/docs/html/install.html#). CMake gave me an error "cannot find -lz".
After installing a package lib64z1-dev everything worked like a charm, this is probably worth adding to documentation. Not really sure if exactly that package is needed though, may be a run time library would be enough.
OS: Ubuntu 16.04.2 AMD64.
POCL source commit: cba079a1351b76c8afc317e740c8a54c8a239bcb (Nov 30 2017)

Regards,
Kristian Popov

**Comment by franz** [comment]
Hello,

> Not really sure if exactly that package is needed though

Actually pocl does not require zlib at all; this is a requirement of LLVM/Clang. But i'll add a note to the documentation
