### ISSUE TITLE
kcache race?

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#586]
There might be a race condition in the kcache which manifests itself as conformance suite failures (possible due to parallel test execution) which work when executed again in isolation.

E.g. conformance_integer_ops_micro_1 failed the first time with

```clGetProgramBuildInfo returned an empty log.
The program we attempted to compile was:
__kernel void sample_test(__global uint *sourceA, __global uint *destValues)
{
  int  tid = get_global_id(0);
  uint8 tmp = vload8( tid, destValues );
  tmp %= ( vload8( tid, sourceA ) );
  vstore8( tmp, tid, destValues );
}
```

When executing it again separately, it works.

**Comment by pjaaskel** [comment]
...it can of course be also a race that is hidden when hitting the cache, thus perhaps even the same as #594.

**Comment by franz** [comment]
@pjaaskel  possible but unlikely. The cache failures manifest with an abort(), in #594 test finishes computation but the results are incorrect.
