### ISSUE TITLE
PyOpenCL segfaults on test_enqueue_task on AMD Kaveri

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#587]
Perhaps a race/locking issue:

```
test_wrapper.py:662: test_enqueue_task[ctx_factory=<context factory for <pyopencl.Device 'pthread-AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G' on 'Portable Computing Language'>] /home/visit0r/src/pocl-1.0-RC2/examples/PyOpenCL/runtest.sh: line 7: 11665 Segmentation fault      (core dumped) py.test -v --tb=native
```

**Comment by franz** [comment]
> Perhaps a race/locking issue:

can you rerun just the PyOpenCL test separately ? ``ctest -L PyOpenCL``

If it segfaults repeatedly, then it's likely not cache locking related. (which i suspect is the case, because cache errors usually end with assertion fails, not segfaults, unless pocl is built with -DNDEBUG)

**Comment by pjaaskel** [comment]
It keeps segfaulting consistently.
