### ISSUE TITLE
`sign` method for `int`?

### ISSUE THREAD

**Issue by cdeterman** [pocl/pocl#591]
I have the following kernel that works with my Intel OpenCL implementation:

```
__kernel void MatSign(
    __global const int *A, __global int *B,
    const int Mdim, const int Pdim, const int MdimPad) {
    
    // Get the index of the elements to be processed
    const int globalRow = get_global_id(0); // C Row ID
    const int globalCol = get_global_id(1); // C Col ID
    
    // Do the operation
    if((globalRow <= Mdim) && (globalCol <= Pdim)){
        
        B[globalRow * MdimPad + globalCol] = sign(A[globalRow * MdimPad + globalCol]);
    }
}
```

However, when I try to run in with `pocl` I get the following error:

>Build Status = -2 ( Err = -11 )
Log: error: /home/travis/.cache/pocl/kcache/tempfile_YEpKEy.cl:12:46 <Spelling=/usr/share/pocl/include/_builtin_renames.h:165:24>: call to '_cl_sign' is ambiguous

This makes it look like `pocl` doesn't have overloads of `sign` for `int` data types.

**Comment by franz** [comment]
> This makes it look like pocl doesn't have overloads of sign for int data types.

Indeed it doesn't. The 1.2 standard doesn't mention sign() for integer types anywhere, at least i don't see it. Looking [here](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/sign.html) and [here](https://www.khronos.org/registry/OpenCL/specs/opencl-1.2.pdf#page=263) i only see halfs, floats & doubles...

We could, in theory, add an overload for integers but then your code might break again later, with some other OpenCL implementation... @pjaaskel ideas?

**Comment by pjaaskel** [comment]
If it's not in the standard, the problem is in the kernel, right?

**Comment by cdeterman** [comment]
Fair enough, I guess Intel implemented it and I didn't consult the OpenCL standards.  I even checked 2.0 now and there was still not mention of an integer overload.

**Comment by eschnett** [comment]
FWIW, the "standard" implementation is a right-shift by 31 bits (for a 32-bit integer).
