### ISSUE TITLE
Provide enough version information to make binary caching safe

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#596]
PyOpenCL caches OpenCL binaries for the user. It uses [every bit of version information](https://github.com/inducer/pyopencl/blob/40d40b89ab79c6e1d68b1b63a2d4bfa489ef55f5/pyopencl/cache.py#L235-L240) it can get its hands on as part of the cache key.

In #594, @franz indicated that that might not be enough, in that at least the following bits of information might be needed but are not included in that currently (as of 1.0):

* ~~LLVM version~~
* Whether pocl was built in distro mode

I'd like to request that these bits of information be included in the platform version.

For posterity, `device.version` for the (conda) distro build:
```
OpenCL 1.2 pocl HSTR: pthread-x86_64-unknown-linux-gnu-haswell
```

And the machine specific build (on a different machine, sorry!):
```
OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-broadwell
```

And `platform.version`:

```
OpenCL 1.2 pocl 1.0, LLVM 5.0.1
```

**Comment by Oblomov** [comment]
FWIW, the LLVM version is available already in the `CL_PLATFORM_VERSION` string. The strings you quote seem to be the _device_ version strings.

**Comment by inducer** [comment]
Good point, sorry about that. Edited.
