### ISSUE TITLE
test_shuffle_half fails on armv7hl

### ISSUE THREAD

**Issue by ignatenkobrain** [pocl/pocl#603]
```
test 25
        Start  25: kernel/test_shuffle_half
25: Test command: /usr/bin/cmake "-Dtest_cmd=/builddir/build/BUILD/pocl-1.0/armv7hl-redhat-linux-gnueabi/tests/kernel/test_shuffle####half" "-P" "/builddir/build/BUILD/pocl-1.0/cmake/run_test.cmake"
25: Test timeout computed to be: 9.99988e+06
25: CMake Error at /builddir/build/BUILD/pocl-1.0/cmake/run_test.cmake:22 (message):
25:   FAIL: Test exited with nonzero code:
25:   /builddir/build/BUILD/pocl-1.0/armv7hl-redhat-linux-gnueabi/tests/kernel/test_shuffle;half
25: 
25: 
25:   STDOUT:
25: 
25:   
25: 
25:   STDERR:
25: 
25:   
25:   /builddir/build/BUILD/pocl-1.0/armv7hl-redhat-linux-gnueabi/tests/kernel/test_shuffle:
25:   symbol lookup error:
25:   /builddir/.cache/pocl/kcache/OF/JJJDNFABAPACAGDJLPCMBPOHKAACIOKLDAJMM/test_shuffle2_2_2/1-1-1/test_shuffle2_2_2.so:
25:   undefined symbol: __gnu_h2f_ieee
25: 
25: 
25: 
  5/121 Test  #25: kernel/test_shuffle_half ............................................................***Failed  Error regular expression found in output. Regex=[FAIL]  5.60 sec
```

**Comment by ignatenkobrain** [comment]
Note that this is latest git code even it says 1.0.

**Comment by punitagrawal** [comment]
I get the following error on a v7 platform with 1.1-RC2 -

25: Test timeout computed to be: 9.99988e+06
25: CMake Error at /home/punit/src/pocl/cmake/run_test.cmake:22 (message):
25:   FAIL: Test exited with nonzero code:
25:   /home/punit/src/pocl/build/tests/kernel/test_shuffle;half
25:
25:   STDOUT:
25:
25:   Error in shuffle half 2 => half 4 :[0, 0, 65472, 0] = shuffle( [0, 1], [4,
25:   2, 69, 4]);
25:
25:   element 2 should be 1 (mask 69), got 29312
25:
25:   Error in shuffle2 half 2 => half 4 :[0, 2, 29312, 0] = shuffle2( [0, 1],
25:   [2, 3], [4, 2, 69, 4]);
25:
25:   Error in shuffle half 2 => half 8 :[0, 0, 60704, 0, 60704, 0, 60704, 0] =
25:   shuffle( [0, 1], [4, 2, 69, 4, 5, 0, 45, 16]);
25:
25:   element 2 should be 1 (mask 69), got 25296
25:
25:   element 4 should be 1 (mask 5), got 0
25:
25:   element 6 should be 1 (mask 45), got 0
25:
25:   Error in shuffle2 half 2 => half 8 :[0, 2, 25296, 0, 0, 0, 0, 0] =
25:   shuffle2( [0, 1], [2, 3], [4, 2, 69, 4, 5, 0, 45, 16]);
25:
25:   element 2 should be 1 (mask 69), got 7
25:
25:   element 4 should be 1 (mask 5), got 7
25:
25:   element 6 should be 1 (mask 45), got 7
25:
25:   element 10 should be 1 (mask 1), got 7
25:
25:   Error in shuffle2 half 2 => half 16 :[0, 2, 7, 0, 7, 0, 7, 0, 0, 2, 7, 2,
25:   0, 2, 2, 0] = shuffle2( [0, 1], [2, 3], [4, 2, 69, 4, 5, 0, 45, 16, 4, 6,
25:   1, 18, 28, 14, 22, 16]);
25:
25:
25:
25:   STDERR:
25:
25:
25:
25: -- OK
1/1 Test #25: kernel/test_shuffle_half .........***Failed  Error regular expression found in output. Regex=[FAIL] 21.42 sec

**Comment by franz** [comment]
Please retry with 1.1 RC3

**Comment by punitagrawal** [comment]
Thanks for updating the shuffle implementation. test_shuffle_half passes with 1.1 RC3 on an ARM v7 board. 

I see new failures with EinsteinToolkit (OTHER_FAULT) but I'll raise that as a separate issue.

Please feel free to close this one.
