### ISSUE TITLE
Buffers underaligned on macOS

### ISSUE THREAD

**Issue by mattwala** [pocl/pocl#604]
I'm using POCL 1.0 on macOS installed via conda. Based on my understanding of OpenCL specification, an allocated buffer should be aligned to the size of the largest native data type (?) However, as running the following code shows, the buffers are only aligned to 16 bytes:

```
import pyopencl as cl

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

mf = cl.mem_flags
buf = cl.Buffer(ctx, mf.READ_ONLY, size=4*8)

prg = cl.Program(ctx, r"""
__kernel void knl(__global double4 *buf) 
{
   // Should print 0, but occasionally prints 16, 32, or 48.
   printf("%d\n", ((unsigned long) buf) & 63);
}
""").build()

prg.knl(queue, (1,), None, buf)
```

Also, it seems like CL_DEVICE_MEM_BASE_ADDR_ALIGN is only 128, whereas on a Linux VM on the same machine it is 1024.

**Comment by inducer** [comment]
Looks like pocl might misdetect the min alignment of a float/double16 on macOS:

https://travis-ci.org/conda-forge/pocl-feedstock/jobs/320069721#L491

**Comment by mattwala** [comment]
> Looks like pocl might misdetect the min alignment of a float/double16 on macOS:

The macOS ABI only requires double16 to be aligned to 16 bytes. OpenCL is stricter ("A data item declared to be a data type in memory is always aligned to the size of the data type in bytes.").

**Comment by franz** [comment]
Yes, pocl uses the host compiler to detect alignment for CPU device, so whatever that returns is the alignment. This should be easy to fix with  a simple max(a, b) in CMake.

Do you plan on having a MacOS bot for building pocl ? Because honestly this is likely the least important  bug pocl has on MacOS...

**Comment by inducer** [comment]
Thanks!
