### ISSUE TITLE
pocl executing wrong kernel from cache

### ISSUE THREAD

**Issue by sudden6** [pocl/pocl#608]
I'm developing a program with OpenCL support using [cl.hpp](https://github.com/KhronosGroup/OpenCL-CLHPP) and POCL and noticed a spurious but somewhat regular error when running the program.

In the program I'm regularly recompiling OpenCL kernels (about once a second) and it seems as if POCL sometimes uses an older kernel than the one specifically recompiled with a constant passed via the `-D` kernel build option. I noticed this by checking the constant via a `printf` in the OpenCL kernel.

Removing the cache directory or slightly changing the kernel source fixes the problem for subsequent runs. I guess both things force a rebuild of the cache. I also did some short tests with `export POCL_KERNEL_CACHE=0` and this seemed to fix the problem too.

POCL Version: Platform Version OpenCL 1.2 pocl 1.0, LLVM 5.0.1

**Comment by franz** [comment]
Unfortunately i couldn't reproduce. Is the code for your program opensource, or could you create some smaller reproducer ?

**Comment by sudden6** [comment]
The program is open source, and the problem occurred around this version: https://github.com/sudden6/m-queens/tree/924d38866f0f79829af010baa10a3923d9567c5f

I'll try to create a small reproducing sample.

**Comment by franz** [comment]
haven't found any big mistakes, but i have some advice/observations:

1) if you run into mysterious bugs, using [POCL_DEBUG](http://portablecl.org/docs/html/env_variables.html) may be helpful.

2) ``clNullRange`` for local size in enqueueNDRange lets the implementation decide. Your global sizes are quite random. If you're developing your program with pocl, you might want to set this instead to ``clNDRange(1)`` - test runs with cold cache will be faster.

3) you're calling this code (``solve_subboard``) in a for loop:
```
clCreateCommandQueue()
clCreateBuffer(input)
clCreateBuffer(output)
clEnqueueNDRange(..)
clEnqueueReadBuffer(output)
clFinish()
... automatic C++ object destruction: buffers, command queue
```

This is quite inefficient. On pocl it's (relatively) cheap to create command queues & buffers, but on GPUs it might not be. Plus your kernels run quickly but you're calling clFinish after each one. So two advices: 1) reuse as much buffers as you can 2) do stuff in big batches before calling clFinish. Something like this, lets say batch of 4:

```
void main() {
    queue = clCreateCommandQueue()
    clCreateProgram / Kernel
    input1..input4 = 4x clCreateBuffer();
    output1..output4 = 4x clCreateBuffer();
    ......

    for () {
        .....
        solve_subboard(kernel, input1, ..., input4, output1, ... output4, args1... args4)
    }
    4x clReleaseBuffer
    clReleaseQueue  / program /kernel 
}

void solve_subboard ( kernel, inputs, outputs, args) {
    4x clEnqueueWriteBuffer(input)
    4x clEnqueueNDRangeKernel()
    4x clEnqueueReadBuffer()
    clFinish() just once
    ... do something with results.
}
```

Your buffers seems <1M & your kernels fast so you could even batch a lot more of them. Oh also, wasn't able to reproduce the bug on pocl 1.1 RC2 (so there's a small hope it's fixed..)

**Comment by sudden6** [comment]
Sorry for the late reply, I could not reproduce the problem anymore.

Thank you for the advice, integrating it in my program made it a lot faster.
