### ISSUE TITLE
[TCE] LLVM 6.0: regression/barrier_between_two_for_loops_LOOPS fails

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#609]

**Comment by franz** [comment]
Haven't found out much yet, but I've come to the conclusion that the problem first appears somewhere in TCE compilation, i.e. after pocl WG codegen. Comparing both program.bc and parallel.bc with LLVM 5 shows they're nearly identical, with the exception of the "convergent" keyword and some metadata IIRC.

But the "program.bc" file generated by ``TCEDevice::tceccCommandLine`` are vastly different between 5 and 6. Possibly ``-O3`` there triggers some new optimization pass (by the convergent keyword), or we're missing something in our parallel.bc bitcode, don't know yet.
