### ISSUE TITLE
inlining static function ...

### ISSUE THREAD

**Issue by kif** [pocl/pocl#617]
Dear POCL developers,

I found a bug in my code which only shows off when using the POCL driver on CPU, it has been tested with various other drivers: Intel, AMD and Apple on CPU, Nvidia, Apple, and Beignet on GPU. Moreover the code passes without warning with oclgrind and tests are OK with POCL when targeting nvidia GPUs.

This code is derived from the bitonic sort described in this book:
https://www.manning.com/books/opencl-in-action

The code is based on a shared function which is called from multiple kernels.
While debugging, I found out that the results are correct when only one kernel calls the function and breaks when multiple kernel call the function. This suggest the function may be inlined in the former case and not in the later.

**Comment by kif** [comment]
As this may be a bit complicated, I created a jupyter notebook self contained (it needs numpy and pyopencl).
https://gist.github.com/kif/b4591ab1dd5cc660d236c4be4a5c91ce

The kernel called "bsort_vertical" is never called. 
If one comments out the line calling  "local_sort", the test passes. 
If one uncomments this line, the code breaks.

**Comment by franz** [comment]
Hello,

Sorry for late reply, been busy with release. I'll try to take a look this week.

**Comment by kif** [comment]
no problem with the delay.

Once this is fixed we can package pyopencl using pocl and use it in continuous integration (which would be great)

**Comment by pjaaskel** [comment]
Assuming fixed since the referenced Debian packaging bug was closed.
