### ISSUE TITLE
kernel/test_fabs ldexp fails on i386 with -DLLC_HOST_CPU=i686 and SLEEF since pow(2.0, 4.0) returns 15.999999999999998

### ISSUE THREAD

**Issue by anbe42** [pocl/pocl#621]
Building pocl for Debian/i386 with `-DLLC_HOST_CPU=i686` `-DFORCE_OCL_KERNEL_TARGET_CPU=ON` (from [FORCE_OCL_KERNEL_TARGET_CPU.patch](https://gist.github.com/anbe42/c386ae497031212f5d991faa6d7b3456), without it there are many more failures due to the more modern cpu being used) and SLEEF causes the kernel/test_fabs test to fail for ldexp.

There is no failure for VECMATHLIB and llvm-3.9

For llvm-4.0 (and newer?), both SLEEF and VECMATHLIB fail.

     46/120 Test  #16: kernel/test_fabs ....................................................................***Failed  Error regular expression found in output. Regex=[FAIL] 24.21 sec
    Running test test_fabs...
    FAIL: ldexp type=float val=-3.4028234663852886e+38 val2=4 res=-5.4445175462164618e+39 good=-inf
    FAIL: ldexp type=double val=-0.10000000149011612 val2=4 res=-1.6000000238418579 good=-1.6000000238418577
    FAIL: ldexp type=double2 val=-0 val2=4 res=-0 good=-0
    FAIL: ldexp type=double2 val=-0.10000000149011612 val2=4 res=-1.6000000238418579 good=-1.6000000238418577
    FAIL: ldexp type=double3 val=-0 val2=4 res=-0 good=-0
    FAIL: ldexp type=double3 val=-0.10000000149011612 val2=4 res=-1.6000000238418579 good=-1.6000000238418577
    FAIL: ldexp type=double3 val=-0.89999997615814209 val2=4 res=-14.399999618530273 good=-14.399999618530272
    FAIL: ldexp type=double4 val=-0 val2=4 res=-0 good=-0
    FAIL: ldexp type=double4 val=-0.10000000149011612 val2=4 res=-1.6000000238418579 good=-1.6000000238418577
    FAIL: ldexp type=double4 val=-0.89999997615814209 val2=4 res=-14.399999618530273 good=-14.399999618530272
    FAIL: ldexp type=double4 val=-1 val2=4 res=-16 good=-15.999999999999998
    FAIL: ldexp type=double8 val=-0 val2=4 res=-0 good=-0
    FAIL: ldexp type=double8 val=-0.10000000149011612 val2=4 res=-1.6000000238418579 good=-1.6000000238418577
    FAIL: ldexp type=double8 val=-0.89999997615814209 val2=4 res=-14.399999618530273 good=-14.399999618530272
    FAIL: ldexp type=double8 val=-1 val2=4 res=-16 good=-15.999999999999998
    FAIL: ldexp type=double8 val=-1.1000000238418579 val2=4 res=-17.600000381469727 good=-17.600000381469723
    FAIL: ldexp type=double8 val=-10 val2=4 res=-160 good=-159.99999999999997
    FAIL: ldexp type=double8 val=-1000000 val2=4 res=-16000000 good=-15999999.999999998
    FAIL: ldexp type=double8 val=-999999995904 val2=4 res=-15999999934464 good=-15999999934463.998
    FAIL: ldexp type=double16 val=-0 val2=4 res=-0 good=-0
    FAIL: ldexp type=double16 val=-0.10000000149011612 val2=4 res=-1.6000000238418579 good=-1.6000000238418577
    FAIL: ldexp type=double16 val=-0.89999997615814209 val2=4 res=-14.399999618530273 good=-14.399999618530272
    FAIL: ldexp type=double16 val=-1 val2=4 res=-16 good=-15.999999999999998
    FAIL: ldexp type=double16 val=-1.1000000238418579 val2=4 res=-17.600000381469727 good=-17.600000381469723
    FAIL: ldexp type=double16 val=-10 val2=4 res=-160 good=-159.99999999999997
    FAIL: ldexp type=double16 val=-1000000 val2=4 res=-16000000 good=-15999999.999999998
    FAIL: ldexp type=double16 val=-999999995904 val2=4 res=-15999999934464 good=-15999999934463.998
    FAIL: ldexp type=double16 val=-3.4028234663852886e+38 val2=4 res=-5.4445175462164618e+39 good=-5.4445175462164612e+39
    FAIL: ldexp type=double16 val=-inf val2=4 res=-inf good=-inf
    FAIL: ldexp type=double16 val=-inf val2=4 res=-inf good=-inf
    FAIL: ldexp type=double16 val=nan val2=4 res=nan good=nan
    FAIL: ldexp type=double16 val=-3.4028234663852886e+38 val2=4 res=-5.4445175462164618e+39 good=-5.4445175462164612e+39
    FAIL: ldexp type=double16 val=-1.1754943508222875e-38 val2=4 res=-1.88079096131566e-37 good=-1.8807909613156598e-37
    FAIL: ldexp type=double16 val=-1.1920928955078125e-07 val2=4 res=-1.9073486328125e-06 good=-1.9073486328124998e-06
    FAIL: ldexp type=double16 val=-0 val2=4 res=-0 good=-0
    OK

**Comment by anbe42** [comment]
worked around in 1.1-RC2 with WILL_FAIL=1, only llvm-3.9 + vml + i686 now fails because the test "unexpectedly" succeeds

not a blocker for 1.1, but I'll try to investigate it a bit further

**Comment by anbe42** [comment]
Let's split the SLEEF and VECMATHLIB instances of this bug and concentrate on the SLEEF one here only.

The problem occurs only if 387 floating point operations are used, not with sse instructions.
Looking only at `double` here:
The reference solution for ldexp is computed as `goodres.s[n] = val.s[n] * pow(2.0, ival2.s[n]);` with `ival2.s[n] = 4`.
Is this `pow()` from libm being called? Does SLEEF set any weird (i.e. non-default) rounding (or other) modes?
The actual problem is that the "good reference solution" `goodres` is not correct since `pow(2.0, 4);` returns `15.999999999999998` (`0x402fffffffffffff`) instead of `16.0` (`0x4030000000000000`). This causes always a 1-ulp difference between `res` (which has the actually exact result) and `goodres`, letting the test fail.
I could not reproduce this weird result with a plain C call to `pow(2.0, 4.0)` on i386 using the 387 fpu.

I think commit f21782ec9 should be reverted, it's not the correct solution to set WILL_FAIL=1 for this problem.

**Comment by franz** [comment]
>  Is this pow() from libm being called? Does SLEEF set any weird (i.e. non-default) rounding (or other) modes?

What is used for a particular kernel library functions can be seen in ``lib/kernel/CMakeLists.txt``, in this case SOURCES_WITH_SLEEF, where you'll see that pow is implemented via ``libclc-pocl/pow.cl`` which is a pure OpenCL implementation from libclc.

> The actual problem is that the "good reference solution" goodres is not correct since pow(2.0, 4);

Since 2^4 is the only ``pow()`` being calculated there, i replaced it with 16.0 (a ``fabs()`` test shouldn't depend on ``pow()`` anyway). This makes the test more robust and it'll likely pass on i386, though obviously doesn't solve the problem with ``pow()``.

> it's not the correct solution to set WILL_FAIL=1 for this problem.

WILL_FAIL is never a solution to anything, it's merely an acknowledgement of a problem. The purpose of setting tests to expected failures is that it's easier to spot any change in tests, because if there's any change it test results, the testsuite will start to fail as a whole.

**Comment by franz** [comment]
Please retry with RC3

**Comment by anbe42** [comment]
Yet, replacing it with 16.0 works, mostly.
There is a weird failure for `floatX` (X >= 2, so not for regular `float`), listing only the relevant failures for `float2`, all other are duplicates:

    FAIL: input=0 iter=8 sign=-1 ldexp type=float2 n=0 val=-3.4028234663852886e+38 val2=4 res=-inf good=-5.4445175462164618e+39
          val=0xff7fffff res=0xff800000 good=0xff800000
    FAIL: input=0 iter=8 sign=+1 ldexp type=float2 n=0 val=3.4028234663852886e+38 val2=4 res=inf good=5.4445175462164618e+39
          val=0x7f7fffff res=0x7f800000 good=0x7f800000
    FAIL: input=0 iter=12 sign=-1 ldexp type=float2 n=0 val=-3.4028234663852886e+38 val2=4 res=-inf good=-5.4445175462164618e+39
          val=0xff7fffff res=0xff800000 good=0xff800000
    FAIL: input=0 iter=12 sign=+1 ldexp type=float2 n=0 val=3.4028234663852886e+38 val2=4 res=inf good=5.4445175462164618e+39
          val=0x7f7fffff res=0x7f800000 good=0x7f800000

This happens for `val=MAXFLOAT` and `good=5.4445175462164618e+39` (`= 16.0 * MAXFLOAT`) is even larger and therefore cannot be represented as `float` ... so we have some excess precision problem here ...

And then there is the weird double infinity case where it also fails with VML, but that is probably a different bug. ... No, it's a similar excess precision thing.

We just need to ensure goodval is read from memory, not from a fpu register ...
since github won't accept the patch file to be attched here, I'll sent it as an email.

---

I don't think there is any problem with pow() since the sleef pow() has an 1.0 ULP error bound (which seems to be needed on 387, but not on sse (at least not for 2.0^4.0)). It's just not appropriate to be used here.

**Comment by anbe42** [comment]
A small C example to demonstrate the x87 excess precision problem, works on both i386 and x86_64. See https://gcc.gnu.org/wiki/x87note for some background.

    /* compile with -mfpmath=387 */
    
    #include <stdio.h>
    #include <stdlib.h>
    
    int main(int argc, char **argv)
    {
      float a = 3.40282347e+38F;
      float b = 16.f;
      if (argc > 1) a = atof(argv[1]);
      if (argc > 2) b = atof(argv[2]);
      float c = a * b;
      volatile float d = a * b;
      printf("a=%.17g b=%.17g c=%.17g d=%.17g\n", a, b, c, d);
      printf("a=0x%08x b=0x%08x c=0x%08x d=0x%08x\n",
             ((int*)&a)[0], ((int *)&b)[0], ((int *)&c)[0], ((int *)&d)[0]);
    }

output with `-O0` (everything goes through memory):

    a=3.4028234663852886e+38 b=16 c=inf d=inf
    a=0x7f7fffff b=0x41800000 c=0x7f800000 d=0x7f800000

output with `-O1`:

    a=3.4028234663852886e+38 b=16 c=5.4445175462164618e+39 d=inf
    a=0x7f7fffff b=0x41800000 c=0x7f800000 d=0x7f800000

- This doesn't work:
even explicit casting does not force rounding to the requested type: `ISEQ((stype)(res.s[n]), (stype)(goodres.s[n]))`
- Expensive solution:
compiling with `-ffloat-store` (performance critical because it affects *all* floating point operations)
- Suggested solution:
in `test_fabs.cl` use

      typedef union {
        vtype v;
        volatile stype s[16];
      } Tvec;

  (affects only accesses via `.s[i]` in this precision-critical but not performance-critical test)
- Alternate solutions:
add some barrier (no, `barrier(CLK_LOCAL_MEM_FENCE)` does not work) between computation of `goodres` and comparing `goodres` with `res`, e.g.

      goodres.s[get_global_id(0)] += (stype)(get_global_id(0));

  (for `global_work_size[1] = { 1 }` this is a noop, but the compiler does not know that)

**Comment by franz** [comment]
Fixed
