### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by geokon-gh** [pocl/pocl#624]
portablecl.org is down

Can't connect (from China, with and without a VPN)

**Comment by geokon-gh** [comment]
https://downforeveryoneorjustme.com/portablecl.org

**Comment by franz** [comment]
Hello,

.. not surprising, sadly. Last week it was displaying outdated version of the page, and the Mailing list wasn't working. This is probably the reason: https://twitter.com/sfnet_ops/status/962041749030952962 

Looking at their status page https://twitter.com/sfnet_ops they're still having problems.

Do you need something from the page, or just letting us know?

**Comment by geokon-gh** [comment]
I came across your project and was just interested in learning more, but it's not time sensitive. Just letting you know - and if anyone else has issues connecting they can see this issue.

**Comment by geokon-gh** [comment]
(website is working now)

**Comment by franz** [comment]
OK, closing. FYI the whole website is static html pages generated from templates, you can see the source in github: https://github.com/pocl/pocl/tree/master/doc/www
