### ISSUE TITLE
OpenCL 1.2 for ARM Cortex A57/A53

### ISSUE THREAD

**Issue by gija92** [pocl/pocl#645]
Hello,

I just built and installed POCL v1.1 on a board with Cortex A57 and A53 CPUs, which was successfull. But by running for example "clinfo"-command the CPUs don't get recogized as OpenCL devices.
The libraries were installed in the "/usr/local"-directory and I copied them to the root-directory. So the libraries are now located at 
```ruby
/etc/OpenCL/vendors/pocl.icd" (changed the directory here)
/usr/lib/libpocl.so.2.1.0 (...)
/usr/share/pocl/(...)
/usr/bin/poclcc
```
But this also doesn't work for me to get the CPUs as OpenCL devices

For more information I build pocl with following steps:
```ruby
mkdir build && cd build
cmake ..
make && make install 
```
Also by running ```make check``` all tests failed cause the executables cannot be found.
The env-variable is ```OCL_ICD_VENDORS=/usr/lib"```

I now re-configured pocl and run ```make -j``` after, which failed cause of "virtual memory exhausted" and clang-6.0 reports errors like this
> clang-6.0: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable

I hope you guys can help me. 
Thank you :)

**Comment by pjaaskel** [comment]
Try unsetting OCL_ICD_VENDORS if you want to run from the default system location. Or set it to /etc/OpenCL/vendors. The latter error is self descriptive: you run out of memory when running clang to build pocl, I cannot help on that.

**Comment by gija92** [comment]
Hi @pjaaskel 
Unsetting OCL_ICD_VENDORS helped, but the error "virtual memory exhausted" refers to low space of the swap-partition, cause I have enough disk space. I just added more space for the swap partition. But the error of clang still occurs. 

You know what I am doing wrong here or do you know another way with pocl to get Cortex A57 as OpenCL devices? 

Thanks

**Comment by franz** [comment]
Hi,

1) don't run ``make -j`` - that launches **all** make jobs at the same time. Use something reasonable like 2-8 jobs, depending on what machine you have.

2) making pocl, installing it somewhere, and copying it elsewhere will not work. The reason is, there are some install paths compiled in (like path to pocl headers) which pocl will look for.

You have two options here:  1) cmake with ``-DCMAKE_INSTALL_PREFIX=/usr`` - after make & make install, pocl will be installed into your **system** paths. Or option 2) you can use pocl without installing it anywhere, just go into pocl's build directory, run make, and then run ``export OCL_ICD_VENDORS=$PWD/ocl-vendors`` This is usually the easiest way for developers.

**Comment by gija92** [comment]
Hi @franz 
alright I just mentioned it in the new build. But building the tests is still failing do you have any idea why?
I run ```ctest -j8 -L internal```

I get errors like "Failed  Required regular expression not found.Regex=[basic|FAIL|..]
I also updated cmake but no chance

**Comment by gija92** [comment]
@franz 
Do you know how to set the Cortex A57 and A53 CPUs as OpenCL devices so I can detect them with the "clinfo"-command?

**Comment by franz** [comment]
@gija92 if the tests fail, try running them directly instead of through ctest. You can find pocl's internal tests with ``find examples/ tests/ -type f -executable`` Or run ctest with ``--output-on-failure`` option.

WRT clinfo, like i said in my previous comment, either ``make install`` pocl into system paths, or run ``export OCL_ICD_VENDORS=$PWD/ocl-vendors`` in pocl's build directory. Do you have build prerequisites installed ?

**Comment by gija92** [comment]
@franz 
I mentioned your advice concerning ```make install``` and the env-variable. I re-installed Pocl by using the install prefix  ```DCMAKE_INSTALL_PREFIX=/usr``` but clinfo didn't show me the ARM CPU ^^

By typing ```ldconfig -p``` the libpocl.so is located at /usr/lib

**Comment by pjaaskel** [comment]
Did you build pocl with ICD support? You need ocl-icd-dev for that, I think. You can check this in the CMake output. Also, do you have ICD libOpenCL.so installed? Sometimes it's easy to overwrite that with another libOpenCL and then it finds only that one. strace can help to locate the issue too.

**Comment by gija92** [comment]
Hi @pjaaskel 
yes I am building with ICD support. I just re-installed LLVM/Clang 6.0 and now building POCL v1.1 again but with errors when it trys to link the kernel bitcode

```` [ 41%] Linking & optimizing Kernel bitcode /home/root/tmp/pocl-1.1/build/lib/kernel/host/kernel-aarch64-unknown-linux-gnu-cortex-a53.bc````

````/usr/bin/llvm-link: "/home/root/tmp/pocl-1.1/build/lib/kernel/host/cortex-a53/abs.cl.bc": error: Could not open input file: No such file or directory````

````/usr/bin/llvm-link: error loading file '"/home/root/tmp/pocl-1.1/build/lib/kernel/host/cortex-53/abs.cl.bc"' ````

Acutally the file is there and I also tried ````chmod 755```` but no chance. 

Thanks

**Comment by gija92** [comment]
Hi @pjaaskel 
I re-built the image and re-installed LLVM/Clang 6.0. Now I'm again into installing POCLv1.1-RC2 (with ICD support). But now I got following error

```[ 41%] Building C to LLVM bitcode /home/root/tmp/pocl-1.1-RC2/build/lib/kernel/host/cortex-a53/mem_fence.c.bc```
```[ 41%] Linking & optimizing Kernel bitcode /home/root/tmp/pocl-1.1-RC2/build/lib/kernel/host/kernel-aarch64-unknown-linux-gnu-cortex-a53.bc```
```/usr/bin/llvm-link: "/home/root/tmp/pocl-1.1-RC2/build/lib/kernel/host/cortex-a53/abs.cl.bc": error: Could not open input file: No such file or directory```
```/usr/bin/llvm-link: error loading file '"/home/root/tmp/pocl-1.1-RC2/build/lib/kernel/host/cortex-a53/abs.cl.bc"' ```

Actually building those files is successfull but by linking the file this erros occurs. The file exists in the directory and I also change permissions with ```chmod 777``` but still got the error.

Thanks

**Comment by franz** [comment]
@gija92 sounds like a filesystem problem. Does it happen with pocl git master ? i haven't seen this problem, so unfortunately i can't help you here.

**Comment by pjaaskel** [comment]
Same here. Unfortunately there's no official pocl ARM maintainer who could help give you more assitance here.

**Comment by gija92** [comment]
@franz 
I am using the v.1.1_RC2-Release version. 

I attached the cmake-configuration maybe there is a detail I am missing through the configuration
[cmake_pocl.txt](https://github.com/pocl/pocl/files/2262438/cmake_pocl.txt)

**Comment by franz** [comment]
Looking at your cmake log, this looks like a problem:

```
--  ########## The command:
-- /usr/bin/clang++ -c -std=c++11 /home/root/tmp/pocl-1.1-RC2/build/compile_test_pnktp.cc
--  ########## Exited with nonzero status: 1
-- STDERR: /home/root/tmp/pocl-1.1-RC2/build/compile_test_pnktp.cc:3:12: fatal error: 'iostream' file not found
  #include <iostream>
           ^~~~~~~~~~
```

either your standard library is borked, or you're missing devel packages, or something else. Either way this looks like a serious issue. Also:

```
-- Checking for module 'ocl-icd>=1.3'
--   No package 'ocl-icd' found
-- ocl-icd not found -> trying fallback ICD implementations
```

I advise you to try building with ``ocl-icd`` first. There's a README.ARM file in pocl, with install requirements for Ubuntu, please install those packages on your distro.

**Comment by JM-Anderson** [comment]
Bump.

I am having the exact same issue with pocl 1.2 and llvm 6. The issue persists even after installing ocl-icd.

Here is the error:
```
Linking & optimizing Kernel bitcode /mnt/ExtSATA/OpenCL/pocl-1.2/build/lib/kernel/host/kernel-aarch64-poky-linux-cortex-a53.bc
/usr/local/bin/llvm-link: "/mnt/ExtSATA/OpenCL/pocl-1.2/build/lib/kernel/host/cortex-a53/abs.cl.bc": error: Could not open input file: No such file or directory
/usr/local/bin/llvm-link: error loading file '"/mnt/ExtSATA/OpenCL/pocl-1.2/build/lib/kernel/host/cortex-a53/abs.cl.bc"'
make[2]: *** [lib/kernel/host/CMakeFiles/kernel_host_cortex-a53.dir/build.make:254: lib/kernel/host/kernel-aarch64-poky-linux-cortex-a53.bc] Error 123
make[1]: *** [CMakeFiles/Makefile2:313: lib/kernel/host/CMakeFiles/kernel_host_cortex-a53.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Here is my cmake output:
[cmake_out.txt](https://github.com/pocl/pocl/files/3522827/cmake_out.txt)

**Comment by franz** [comment]
@JM-Anderson 

Hello, i don't think it's the same issue. The OP managed to build pocl, in your case it seems even the build fails. The cmake output doesn't have anything useful in it (or at least i don't see anything out of the ordinary). Make output should be more useful. Also, pocl 1.2 is fairly old now, 1.3 has been out for a while and 1.4 is coming soon. Unless you have a good reason to use 1.2, it's better to use either 1.3 or git master.

**Comment by JM-Anderson** [comment]
I chose pocl 1.2 here for consistency, but I also tested building pocl 1.3 and git master. All failed with the exact same error. According to pocl 1.3 release notes:
```
Support code for older than LLVM 6.0 will be removed in the beginning of the next release cycle to clean up the code base.
```
LLVM 6.0 should still be supported so I don't think that is an issue.

Not sure if this helps, but I looked at the generated Make files to find the llvm-link command that causes this error. Running it manually allows it to link successfully.

**Comment by franz** [comment]
> LLVM 6.0 should still be supported

Correct, it is, although older have been removed in master already. 6.0 should work.

> Running it manually allows it to link successfully.

That's ... weird. The link command is ran through xargs, and the invokation from CMake feeds the linked file list via shell redirection operator "<", so maybe there's something about this setup that causes a problem with your system.

**Comment by JM-Anderson** [comment]
Well you were right. Thank you.
Turns out I had xargs installed from [BusyBox](https://busybox.net/about.html) which seemed to work fine until that specific step in the build process. I just installed the official GNU findutils package to get the correct version of xargs and everything seems to compile fine now.

**Comment by JM-Anderson** [comment]
Thank you for the suggestion. Turns out I had xargs installed from [Busybox](https://busybox.net/about.html). Switching to the official GNU findutils xargs allowed compilation to complete.
However, when running `poclcc -l` or trying to run an OpenCL program, I get an error message:
```
Unknown OpenCL error -1001 in main on line 283
```

**Comment by franz** [comment]
@JM-Anderson -1001 is from `clGetPlatformIDs`, and it means ICD loader can't find any OpenCL installation. https://github.com/pocl/pocl/blob/master/doc/sphinx/source/using.rst has information on how to use pocl; the short version is, you can either use it from its build directory (without "make install"; you'll need to setup POCL_BUILDING and OCL_ICD_VENDORS env variables) or you can install it somewhere (build with CMAKE_INSTALL_PREFIX and then "make install").
