### ISSUE TITLE
ClReleaseMemObject segfaults when provided an invalid mem object

### ISSUE THREAD

**Issue by nicoTolly** [pocl/pocl#647]
ClReleaseMemObject segfaults when provided an invalid mem object. Indeed, there is no check done when dereferencing memobj at pocl/lib/CL/clReleaseMemObject.c:36

cl_context context = memobj->context;

According to the OpenCl specification (p 119.) it should rather return  CL_INVALID_MEM_OBJECT.

**Comment by pjaaskel** [comment]
I think this was discussed before and the outcome was that no one could come up with a robust solution that would not involve white listing all known good memobj pointers, and even those valid objects could be then corrupted internally.

Shortly put, seamlessly detecting "invalidity" of the mem object might be impossible without introducing overkill complexity and overheads just for the sake of detecting invalid client programs which are not thus likely to recover from the returned error anyways. Sentinels and other kind of tricks only go so far. Thus, it now checks only for NULL against the memobj itself.

For example here memobj could be freed or garbage. To detect that we'd need a white list check of known good memobj pointers. Then the next step is to ensure the memobj itself is not corrupted to get to a valid context obj. Similar handling needed there, etc.

If you have an idea how to detect more of useful invalid memobj cases without ridiculous amount of additional complexity, please let us know.

**Comment by franz** [comment]
@pjaaskel putting invalidity detection aside, the code dereferences (line 36) before the NULL check (line 38). But it's trivial to fix.

**Comment by franz** [comment]
... and IMO there's not much point in adding invalid object detection. Pocl has CMake options to compile with Adress/Thread/UB sanitizers and these work quite well in my experience.

**Comment by nicoTolly** [comment]
Ok, fair enough. I wanted to make sure that this behaviour was intended, even though it does not match the spec (which is probably reasonable in this case, I guess). I am doing a rust interface for a library based on this opencl implementation, and it is a bit annoying to get a segfault because it makes debugging a bit more convoluted (cargo does not unwind properly and I have to rely on gdb to get a backtrace, for example).

**Comment by pjaaskel** [comment]
Yep, I believe it's not the spec's intention to force the implementations to go through abundant hurdles to detect potentially corrupted cl objects.

**Comment by franz** [comment]
@hominhquan  yes that will be fixed, @pjaaskel closed this a bit prematurely.
