### ISSUE TITLE
pocl 1.2-pre + LLVM 7 fails to compile vector-of-3 variant of sin & cos

### ISSUE THREAD

**Issue by franz** [pocl/pocl#648]
running ``math_brute_force/bruteforce -f -3 sin`` from CTS gives:

```
bruteforce: /home/0/LLVM_git/70/lib/Support/APInt.cpp:865: llvm::APInt llvm::APInt::zext(unsigned int) const: Assertion `width > BitWidth && "Invalid APInt ZeroExtend request"' failed.
```

**Comment by pjaaskel** [comment]
Can you isolate a test case and report to LLVM as a regression, if it's due to upstream? Or is the backtrace inside libLLVM or libpocl?

**Comment by franz** [comment]
Bug filed on LLVM [here.](https://bugs.llvm.org/show_bug.cgi?id=38459)

It seems to happen in **X86DAGToDAGISel** even when running plain ``llc -O3``. So it *may* be pocl's fault if it generates invalid bitcode, otherwise seems unlikely.

**Comment by pjaaskel** [comment]
Can you check using gdb which is the exact instruction it explodes at?

**Comment by franz** [comment]
```
868	    return APInt(width, U.VAL);

(gdb) up
2377	APInt DemandedSrc = DemandedElts.zext(NumSrcElts).shl(Idx);

(gdb) up
(gdb) print Op.Node->dump()
t746: v3i32 = extract_subvector t262, Constant:i64<0>

(gdb) up
(gdb) print Op.Node->dump()
t747: v3i64 = zero_extend t746

(gdb) up
(gdb) print Op.Node->dump()
t352: v3i64 = shl t747, t274
```

**Comment by franz** [comment]
Fixed in LLVM, both master & release_70 branches - closing
