### ISSUE TITLE
strdup requires newer _POSIX_SOURCE than declared in 1.2rc1

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#654]
Details here:

https://github.com/conda-forge/pocl-feedstock/pull/19#issuecomment-411067297

cc @isuruf

**Comment by jrprice** [comment]
Happens on one of my boxes as well.

PR #650 fixes this.

**Comment by franz** [comment]
Fixed.

**Comment by inducer** [comment]
Thanks!
