### ISSUE TITLE
Undefined symbol _ZN5clang22FrontendTimesIsEnabledE

### ISSUE THREAD

**Issue by jrprice** [pocl/pocl#655]
When building against LLVM 7.0 and without ICD enabled, I'm getting the following error when preloading `libOpenCL.so`:

```
[james@node23 ~]$ LD_PRELOAD=$HOME/pocl/build-7.0/lib64/libOpenCL.so clinfo
clinfo: symbol lookup error: /nfs/home/james/pocl/build-7.0/lib64/libOpenCL.so: undefined symbol: _ZN5clang22FrontendTimesIsEnabledE
```

Moving `clangCodeGen` to the beginning of the Clang library link order in `cmake/LLVM.cmake` fixes this. I don't know if this is the best solution (picking Clang library link order always seems like voodoo to me).

FWIW, I addressed this same issue in Oclgrind with a [similar fix a few months ago](https://github.com/jrprice/Oclgrind/commit/fa307108de205e76fffbcd8424f3811187cb121d). Looks like Mesa [had the same issue](https://gitlab.freedesktop.org/ajax/mesa/commit/0f9bd67c4bfae58f9befa2464addee3086dcab4c) too.

**Comment by franz** [comment]
Thanks, interesting. I'll have to re-test with older LLVM versions to make sure it doesn't break anything (and yes Clang link order seems a bit voodoo).

**Comment by franz** [comment]
Just an observation: I just built pocl with ``-DENABLE_ICD=0 -DENABLE_ASAN=1`` and it works fine. I'm guessing the reason is that i usually build LLVM with dynamic libraries.

**Comment by franz** [comment]
reproduced & fixed
