### ISSUE TITLE
Adapt Csmith to OpenCL

### ISSUE THREAD

**Issue by eschnett** [pocl/pocl#66]
Csmith tests C99 compilers for correctness by using randomized inputs. We should adapt it to OpenCL.

https://github.com/csmith-project/csmith

This should be straightforward, as the semantic differences between the subset of C99 that Csmith tests and OpenCL are small. It would be interesting, though, to extend Csmith to test vector data types as well.

**Comment by jrprice** [comment]
Not sure if you guys are still interested in this, but some guys at Imperial College London have extended Csmith for fuzz-testing OpenCL  compilers. The project is described here:

http://multicore.doc.ic.ac.uk/projects/clsmith/

They've open sourced the modified version of Csmith here:

https://github.com/ChrisLidbury/CLSmith
