### ISSUE TITLE
Unable to build pocl with CUDA support with LLVM 7 and host GCC 8.2

### ISSUE THREAD

**Issue by Oblomov** [pocl/pocl#671]
The error I get is:

```
[  0%] Building C to LLVM bitcode /home/oblomov/src/opencl/pocl/build/lib/kernel/cuda/BCs/get_work_dim.c.bc
clang: warning: argument unused during compilation: '-fno-stack-protector' [-Wunused-command-line-argument]
In file included from <built-in>:1:
In file included from /home/oblomov/src/opencl/pocl/include/_kernel_c.h:34:
In file included from /home/oblomov/src/opencl/pocl/include/pocl_types.h:12:
In file included from /usr/lib/llvm-7/lib/clang/7.0.0/include/stdint.h:61:
/usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
#include <bits/libc-header-start.h>
```

**Comment by Oblomov** [comment]
The issue essentially stems from clang assuming an “hosted” environment (`__STDC_HOSTED__` is defined) despite the fact that the target is `nvptx64`. Force-undefining `__STDC_HOSTED__` fixes the problem. Assuming the diagnosis is correct, then the issue should be reported upstream to llvm.

**Comment by franz** [comment]
does ``cmake -DEXTRA_KERNEL_C_FLAGS=" -ffreestanding" .....`` fix it for you ? (note the leading space)

**Comment by Oblomov** [comment]
Yes, it does.

I've also tried adding "-ffreestanding" to the `CLANG_FLAGS` in `lib/kernel/cuda/CMakeLists.txt` instead, and it solves the problem as well (with the benefit of being specific to the cuda driver).
