### ISSUE TITLE
Are pipes supported?

### ISSUE THREAD

**Issue by L30nardoSV** [pocl/pocl#673]
Hi, I am using the POCL master branch, but I am not sure if pipes are supported:

```zsh
Kernel compilation flags:                 -cl-std=CL2.0                          
  CL_PROGRAM_BUILD_LOG                         : Error(s) while linking: 
Cannot find symbol __read_pipe_2 in kernel library
Cannot find symbol __write_pipe_2 in kernel library
```
It seems it is not. 

I searched some info in the [CHANGES file](https://github.com/pocl/pocl/blob/master/CHANGES), but I couldn't find anything related to pipes. 

Could you please confirm this ? thanks!

**Comment by franz** [comment]
If you run clinfo, you'll see that pocl reports OpenCL 1.2 on both platform and device(s). There was some limited support for 2.0 features - in particular shared virtual memory - with HSA device, but IIRC pipes were never supported.
