### ISSUE TITLE
Calculation wrong on i386 computers ...

### ISSUE THREAD

**Issue by kif** [pocl/pocl#680]
Hi,
I am the developer of pyFAI which contains OpenCL code. This code is packaged for Debian where they run tests during the build process. It turns out a few tests, related to OpenCL fail on i386 computers whereas they passes on all other architectures (Debian uses POCL driver as default).
https://github.com/silx-kit/pyFAI/issues/974

Those tests are all related to Kahan summation and error compensation while summing many values which did not occur on this platform. Here is the function called by the kernel causing the fault:
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/resources/openCL/kahan.cl

I can help you to reproduce the bug: it is probably related either to a numerical truncation of single precision float or (more likely) an optimization of the error compensation. Is you compiler optimizing the order of the FPU operations ?

Cheers,

Jerome

**Comment by kif** [comment]
On Fri, 21 Dec 2018 08:26:43 -0800
Pekka Jääskeläinen <notifications@github.com> wrote:

> Hi Jerome. It should not order the FPU operations unless any of the OpenCL standard relaxation switches are given at clBuildProgram time. Unfortunately there is no i386 maintainer for pocl at the moment -- would you be interested to pick up this port? 

Hi Pekka,

Thanks for the proposal, but the best I can provide you is a proper and
usable test-case. Please find a simplified version in Python of the test.

I am completely unable to maintain a compiler: I hardly know C,
actually my knowledge is limited to the OpenCL subset. Moreover my main
code never claimed to be running on i386 computer architecture as it
uses often large amounts of memory exceeding the 2GB i386 can allocate.

Cheers,

Jerome

**Comment by franz** [comment]
Hi,

> I am completely unable to maintain a compiler: 

You would not need to maintain a compiler. Pocl uses LLVM internally.

But anyway, IMO the main problem with i386 (and also in this case) is, that most compilers (Clang/LL and GCC including) use the x87 FPU by default. The problem with x87 is, it has extra precision which is present in registers, but disappears when register is written to memory. This means that the numerical error of any algorithm depends on how well the compiler optimizes the code, and obviously it differs between compilers, so it's impossible to get consistent results.

In fact Debian's pocl maintainer has hit one of these bugs with pocl (see last comment from anbe42 in issue #621).

There may be some solution (compiler flags) that would work without losing too much performance and compatibility, but honestly there isn't much interest in i386. If you're really interested in solving this issue, then i'd try to find those compiler flags.

**Comment by kif** [comment]
Thanks for the hint: a properly placed "volatile" stores the x87 register into 32bits memory and solves the issue.
