### ISSUE TITLE
LLVM 8: printing float vectors broken

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#689]
In my (uncommitted) LLVM 8 port, one of the remaining issues is that float vector printing is broken. This looks similar to #682 . Below is a C99 reproducer which shows that the issue appears with LLVM 8, but not with LLVM 7 without any pocl involvement, thus could well be an LLVM regression too. This is to investigate further (when I get more time), I just opened this for possibly helping to track #682.

```
$ cat varargs.c
#include <stdarg.h>
#include <stdio.h>

typedef float float2 __attribute__((__ext_vector_type__(2)));

void print_float2 (const char *restrict fmt, ...)
{
  va_list va;
  va_start (va, fmt);
  float2 f = va_arg(va, float2);
  printf (fmt, f.s0, f.s1);
  va_end (va);
}

int main() {
  float2 x;
  x.s0 = 9.0;
  x.s1 = 12.0;
  print_float2 ("%f %f\n", x);
  return 0;
}
$ ~/local/stow/llvm-7.0-tcepatched/bin/clang -O3 varargs.c -o var && ./var
9.000000 12.000000
$ ~/local/stow/llvm-8.0-tcepatched/bin/clang -O3 varargs.c -o var && ./var
0.000000 2.531250
```

**Comment by pjaaskel** [comment]
Opened https://bugs.llvm.org/show_bug.cgi?id=40491

**Comment by anbe42** [comment]
clang-6.0 on x86_64:
`9.000000 12.000000`

clang-6.0 on i686:
`-nan -nan`

**Comment by pjaaskel** [comment]
@anbe42 if you change the test case to use short2s, do you see the issue of #682?

**Comment by pjaaskel** [comment]
Fixed in LLVM. However, I noted printing double vectors is broken, but it's not a regression. I opened a separate issue #692.
