### ISSUE TITLE
clblas tests abort with !"PIC Level" under pocl

### ISSUE THREAD

**Issue by anbe42** [pocl/pocl#690]
This bug was initially reported in Debian: https://bugs.debian.org/919824

This has been reproduced with pocl 1.2 with both LLVM 6 and LLVM 7.

This is some kind of a caching issue - it passes the first time, but fails subsequently. It disappears under `POCL_KERNEL_CACHE=0`.

To easily reproduce this on a Debian (and probably Ubuntu) system install these packages:
```
# apt-get install python3-pygpu python3-nose python3-scipy libclblas-dev ocl-icd-opencl-dev pocl-opencl-icd
```
and run (twice or more times)
```
$ DEVICE=opencl0:0 python3 /usr/bin/nosetests3 -v pygpu.tests.test_blas
```
to get something like
```
*** Testing for pthread-Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
[...]
pygpu.tests.test_blas.test_gemv((100, 128), 'float32', 'f', False, False, 1, True, False) ... module flag identifiers must be unique (or of 'require' type)
!"PIC Level"
LLVM ERROR: Broken module found, compilation aborted!
```

**Comment by pjaaskel** [comment]
Of course not, but maybe remove the new env, it is not needed for this. Or apply the later commit that makes the env more general?
