### ISSUE TITLE
clblas: *ger out of bounds memory access under pocl

### ISSUE THREAD

**Issue by anbe42** [pocl/pocl#691]
This was initially reported under Debian: https://bugs.debian.org/920497

Reproduced on x86_64 with pocl 1.2 and both LLVM 6 and LLVM 7.
It does not crash every time, but often.

libgpuarray's test_ger (`DEVICE=opencl0:0 POCL_KERNEL_CACHE=0 nosetests3 -v pygpu.tests.test_blas:test_ger`, requires python3-pygpu, python3-nose, python3-scipy, ocl-icd-opencl-dev, libclblas-dev) crashes with memory corruption errors (e.g. "double free" - exact message varies) under clblas+pocl.  Changing the test matrix size (default 4x5) to 64x64 (i.e. a whole number of clblas blocks - 16x64 or 64x16 depending on array order) makes it stop crashing.

```
$ DEVICE=opencl0:0 POCL_KERNEL_CACHE=0 nosetests3 -v pygpu.tests.test_blas:test_ger
*** Testing for pthread-Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
[...]
pygpu.tests.test_blas.test_ger(4, 5, 'float32', 'f', 1, 1, False, True) ... FAIL
free(): invalid next size (normal)
Aborted
```
For details, backtraces, ... see the above bug report.

**Comment by pjaaskel** [comment]
Can you test with master and LLVM 8?

**Comment by anbe42** [comment]
master does not build with LLVM 8, but I could reproduce the problem on master with LLVM 6 and 7.

**Comment by franz** [comment]
one idea worth trying would be to run that program in OCLgrind. If OCLgrind reports memory access errors, the error is likely in the program, otherwise it's likely in pocl.

**Comment by rebecca-palmer** [comment]
I'd tried oclgrind before reporting this: no out of bounds memory access, but several "Controlflow depends on uninitialized value", which possibly points to the kernel having undefined behaviour?
(Not sure what matrix size this is from.)

Controlflow depends on uninitialized value
	Kernel: Sger_R_kernel
	Entity: Global(17,0,0) Local(17,0,0) Group(0,0,0)
	  %call170 = call spir_func float @_Z3madfff(float %175, float %176, float %177) #3, !dbg !399
	At line 126 (column 30) of input.cl:
	  prevA = mad( temp, xReg , prevA);
	

Controlflow depends on uninitialized value
	Kernel: Sger_R_kernel
	Entity: Global(32,0,0) Local(32,0,0) Group(0,0,0)
	  %call143 = call spir_func <4 x float> @_Z3madDv4_fS_S_(<4 x float> %144, <4 x float> %splat.splat142, <4 x float> %146) #3, !dbg !346
	At line 112 (column 26) of input.cl:
	  prevA = mad( temp, xReg , prevA);
	

Controlflow depends on uninitialized value
	Kernel: Sger_R_kernel
	Entity: Global(33,0,0) Local(33,0,0) Group(0,0,0)
	  %call170 = call spir_func float @_Z3madfff(float %175, float %176, float %177) #3, !dbg !399
	At line 126 (column 30) of input.cl:
	  prevA = mad( temp, xReg , prevA);
	

Controlflow depends on uninitialized value
	Kernel: Sger_R_kernel
	Entity: Global(48,0,0) Local(48,0,0) Group(0,0,0)
	  %call143 = call spir_func <4 x float> @_Z3madDv4_fS_S_(<4 x float> %144, <4 x float> %splat.splat142, <4 x float> %146) #3, !dbg !346
	At line 112 (column 26) of input.cl:
	  prevA = mad( temp, xReg , prevA);
	

Controlflow depends on uninitialized value
	Kernel: Sger_R_kernel
	Entity: Global(49,0,0) Local(49,0,0) Group(0,0,0)
	  %call170 = call spir_func float @_Z3madfff(float %175, float %176, float %177) #3, !dbg !399
	At line 126 (column 30) of input.cl:
	  prevA = mad( temp, xReg , prevA);

**Comment by franz** [comment]
It's *possible* that this is fixed in master branch of https://github.com/franz/pocl/

I have tried the C example from debian bug report, it prints:

```
Result:
	4961.000000	2542.000000	4303.000000	4964.000000	5515.000000
	9471.000000	4852.000000	8213.000000	9474.000000	10525.000000
	13981.000000	7162.000000	12123.000000	13984.000000	15535.000000
	18491.000000	9472.000000	16033.000000	18494.000000	20545.000000
	23031.000000	11752.000000	19923.000000	22964.000000	25575.000000
```

valgrind still prints a lot of errors, though.

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision and/or the latest LLVM.
