### ISSUE TITLE
Incorrect SPIR mangled names for renamed bultins

### ISSUE THREAD

**Issue by agozillon** [pocl/pocl#698]
When building a program from SPIR that contains the mangled math function sqrt you get the linking error:

Error(s) while linking: 
Cannot find symbol _Z4sqrtf in kernel library

_Z4sqrtf is the defined SPIR mangled name from: https://github.com/KhronosGroup/SPIR-Tools/wiki/SPIR-1.2-built-in-functions

I believe this is because of the _builtin_renames.h files redefinition of the name which gives you a mangling of _Z8_cl_sqrtf rather than the appropriate spir mangling. Manually swapping out the call to _Z4sqrtf for _Z8_cl_sqrtf in the spir binary yields the right results. 

I imagine the same thing will occur for all the builtin renames. 

I think spir support is still experimental from some of the other issues I've read, but I thought it might be worth opening this up in any case.

**Comment by keryell** [comment]
@agozillon I do not understand what you mean. SPIR support in PoCL is super useful to test a lot of other tools generating SPIR, useful to target with SPIR the various PoCL backends (CPU, CUDA...), etc.
It is not because something is experimental it is not useful anyway... :-)

**Comment by franz** [comment]
I believe this is fixed in git master (for CPU device at least).

**Comment by pjaaskel** [comment]
Please reopen if not.

**Comment by keryell** [comment]
OK, thanks.
