### ISSUE TITLE
error: undefined reference to `floorf()' on Mac

### ISSUE THREAD

**Issue by dwintergruen** [pocl/pocl#706]
I have installed pocl via anaconda:

I get the following error:

OpenCL Build Warning : Compiler build log:
<program source>:23:17: warning: implicitly declaring library function 'floorf' with type 'float (float)'
            y = floorf(i1);
                ^
<program source>:23:17: note: please include the header <math.h> or explicitly provide a declaration for 'floorf'

[CL_DEVICE_NOT_AVAILABLE] : OpenCL Error : Error: Link driver returned (10015)
OpenCL Warning : clLinkProgram failed: could not build program for 0x1024500 (Intel(R) HD Graphics 630) (err:-2)
[CL_BUILD_ERROR] : OpenCL Build Error : Compiler build log:

error: undefined reference to `floorf()'

error: backend compiler failed build.

**Comment by franz** [comment]
Hello,

AFAICT these errors are not coming from pocl. "Intel(R) HD Graphics 630" means you're compiling for the Intel GPU, pocl on Mac only supports the CPU.
