### ISSUE TITLE
LLVM-less fail with null kernel names

### ISSUE THREAD

**Issue by ghost** [pocl/pocl#711]
I'm have an LLVM-less build of pocl for an arm target, and i have compiled binaries using the poclcc method. 

I found that in some of my imported binaries, pocl asserts or fails with segfault because of some kernel names being null after being deserialized from binary.

The places where it fails is:

a segfault here when calculating the hash: https://github.com/pocl/pocl/blob/master/lib/CL/devices/common.c#L1311

```
  char *n = program->kernel_meta[kernel_i].name;
  pocl_SHA1_Update (&hash_ctx, (uint8_t *)program->build_hash[device_i],
                    sizeof (SHA1_digest_t));
  pocl_SHA1_Update (&hash_ctx, (uint8_t *)n, strlen (n));
```

and - if i skip that part - again here with an assertion: https://github.com/pocl/pocl/blob/master/lib/CL/pocl_binary.c#L765

```
 assert (km->name);
```

the name should come from here: https://github.com/pocl/pocl/blob/master/lib/CL/pocl_binary.c#L511, where 

```
kernel->sizeof_kernel_name
````
is 0.

I'm not sure why the kernel name size is 0.

**Comment by pjaaskel** [comment]
I believe this has been fixed, please retry with the latest master and reopen if it still reproduces.
