### ISSUE TITLE
pocl_binary_get_kernels_metadata fails when pocl_binary_deserialize_kernel_from_buffer successfull

### ISSUE THREAD

**Issue by ghost** [pocl/pocl#712]
When this call is successful, the function returns with error CL_INVALID_PROGRAM

https://github.com/pocl/pocl/blob/78e2024b96d629ed2173bc2523e15d535610a1fe/lib/CL/pocl_binary.c#L752

```
      POCL_RETURN_ERROR_ON ((pocl_binary_deserialize_kernel_from_buffer (
                                 &b, &buffer, &k, km, NULL)
                             == CL_SUCCESS),
                            CL_INVALID_PROGRAM,
                            "Can't deserialize kernel %u \n", j);
```

**Comment by michele-vnova** [comment]
there's an additional problem with this function as it reuses the j index in the inner loop

**Comment by franz** [comment]
Fixed in master a while ago
