### ISSUE TITLE
POCL flocks to first node on ARM64

### ISSUE THREAD

**Issue by twobombs** [pocl/pocl#716]
On multinode ARM64 enviroments POCL uses only the first CPU node that is found. Either on one CPU ( when it is defined as one node ) or on the first node on the first CPU, therefore not using all avaliable compute resources.

Also; when starting multiple instances of the OpenCL program that uses the POCL resource the focus remains on that first node.

On c1.large.arm @ Packet - Cavium 128 core dualsocker ARM 64 - Ubuntu 18.04 Docker image of twobombs/qracknet-arm - running ./benchmarks in /qrack/_build/

![Screenshot 2019-04-29 at 11 53 52](https://user-images.githubusercontent.com/12692227/56893567-63d9f800-6a83-11e9-989b-6fab1a6318b3.png)

On c2.large.arm @ Packet - Ampere EMAG 32 core singlesocket ARM 64 - Ubuntu 18.04 Docker image of twobombs/qracknet-arm - running ./benchmarks in /qrack/_build/

![Screenshot 2019-04-29 at 13 30 41](https://user-images.githubusercontent.com/12692227/56893511-32f9c300-6a83-11e9-96a8-b0b7c8e20a43.png)

**Comment by pjaaskel** [comment]
Glad to see it works even that well since we don't currently have an active ARM maintainer.  The pthread driver initialization code is rather simple -- maybe you could take a look and poke a bit things. Immediately I don't have an idea why it doesn't occupy all threads in both nodes. 

Can you try playing with POCL_MAX_PTHREAD_COUNT env? See: https://github.com/pocl/pocl/blob/master/lib/CL/devices/pthread/pthread.c#L217  perhaps the libhwloc detects the number of cores wrongly or the code that calls it is unable to traverse all nodes/sockets?

BTW great terminal colors!

**Comment by twobombs** [comment]
I see that the issue is multiplatform: a dualsocket x86 machine also has this behavior on a m2.xlarge.x86 ( a 2x28 core machine ) https://www.packet.com/cloud/servers/m2-xlarge/ 

![Screenshot 2019-05-09 at 15 45 20](https://user-images.githubusercontent.com/12692227/57458514-ca27fd00-7271-11e9-94f8-277eb89f7f56.png)

![Screenshot 2019-05-09 at 15 45 04](https://user-images.githubusercontent.com/12692227/57458538-d4e29200-7271-11e9-9c26-c43f823e336c.png)

**Comment by franz** [comment]
Hello,

> On multinode ARM64 enviroments POCL uses only the first CPU node that is found

I don't see how you came to this conclusion. The fact that Pocl reports just one CPU device is expected (even on multiple node machine). CPU usage can be much lower than `core_count*100%` for multiple reasons. What does `clinfo` report for the pocl CPU device's "max compute units" ? It should report the total logical cores.

**Comment by twobombs** [comment]
Hi Franz,

Thank you for the answer. Strange that I've not seen this before; it reports 96 devices in clinfo.
I've spawned a c1.large.arm@packet ( dual socket ARM@96 cores ) with a clockspeed of 2000Mhz.
Indeed; this could very well be an application specific reason. I will look into this.



```
root@qracknet-arm-0:/# clinfo
Number of platforms                               1
  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 1.2 pocl 1.1 None+Asserts, LLVM 6.0.0, SLEEF, POCL_DEBUG, FP16
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             POCL

  Platform Name                                   Portable Computing Language
Number of devices                                 1
  Device Name                                     pthread-0x0a1
  Device Vendor                                   Cavium
  Device Vendor ID                                0x13b5
  Device Version                                  OpenCL 1.2 pocl HSTR: pthread-aarch64-unknown-linux-gnu-GENERIC
  Driver Version                                  1.1
  Device OpenCL C Version                         OpenCL C 1.2 pocl
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  **Max compute units                               96**
  Max clock frequency                             200MHz
  Device Partition                                (core)
    Max number of sub-devices                     96
    Supported partition types                     equally, by counts
  Max work item dimensions                        3
  Max work item sizes                             4096x4096x4096
  Max work group size                             4096
  Preferred work group size multiple              8
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             No
    Round to nearest                              No
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              132983042048 (123.9GiB)
  Error Correction support                        No
  Max memory allocation                           34359738368 (32GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        None
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            2147483648 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             32768x32768 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                128
  Local memory type                               Global
  Local memory size                               536870912 (512MiB)
  Max number of constant args                     8
  Max constant buffer size                        536870912 (512MiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_fp16 cl_khr_fp64

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Portable Computing Language
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [POCL]
  clCreateContext(NULL, ...) [default]            Success [POCL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-0x0a1
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-0x0a1
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-0x0a1

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1

```

**Comment by franz** [comment]
OK. Usually the problem is that the kernels are executed on all cores (if there's enough workload), but the other commands (read/copy/fill buffer etc) are not. You'd have to use >=2 queues and interleave kernel execution with memory operations to keep the CPU fully occupied.

Also, keep in mind that pocl is not yet optimized for multi-node NUMA systems, so even if you manage to keep the CPUs busy, the performance can be quite poor. We're aware of this problem and it's on our TODO list, just not done yet.

**Comment by twobombs** [comment]
Hi Micheal,

 

POCL is extremely usefull as a baseline for a project I'm working on because of it's use on docker multiplatform images.

Several manufacturers have released OCL drivers for their hardware, but I'm using POCL on multiplatform CPU-only systems.

I think I've hit some sort of memory throughput limit without knowing;  I'll investigating this more.

 

regards,

Aryan

 

Gesendet: Montag, 13. Mai 2019 um 15:47 Uhr
Von: "Michal Babej" <notifications@github.com>
An: pocl/pocl <pocl@noreply.github.com>
Cc: "Aryan Blaauw" <ablaauw@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [pocl/pocl] POCL flocks to first node on ARM64 (#716)


OK. Usually the problem is that the kernels are executed on all cores (if there's enough workload), but the other commands (read/copy/fill buffer etc) are not. You'd have to use >=2 queues and interleave kernel execution with memory operations to keep the CPU fully occupied.

Also, keep in mind that pocl is not yet optimized for multi-node NUMA systems, so even if you manage to keep the CPUs busy, the performance can be quite poor. We're aware of this problem and it's on our TODO list, just not done yet.

**Comment by twobombs** [comment]
Workaround: deploy multple instances of the application that uses the POCL framework. 
In the example multiple qrack benchmark instances eg. via a screen session.

<img width="1383" alt="Screenshot 2019-09-06 at 11 36 48" src="https://user-images.githubusercontent.com/12692227/64418085-a13a3c00-d09a-11e9-94c8-5a2703410423.png">

In this example I've launched 4 threads that in theory see all the resources displayed in clinfo,times 4; oversubscription of resources helps.

**Comment by pjaaskel** [comment]
Seems this was an issue with the application: Too few work-groups or two few parallel kernels to occupy the cores. We only thread-parallelize with these concepts, and do not spread WIs from a single WG to multiple cores, if that's what you were expecting.
