### ISSUE TITLE
POCL on Power9/TeslaV100

### ISSUE THREAD

**Issue by kif** [pocl/pocl#722]
Hi,
I tested POCL on an IBM server with Power9 and Nvidia Telsa V100 GPU. I had no major issue in getting it working (recompile debian package). The performances are more then decent: the GPU has similar execution times compared to the equivalent x86 setup and the power9 is even a bit faster than the GPU, few times faster compared to a scalable-Xeon from Intel. Kudos to the team !

The only bug I encountered was when running some of my kernel which required the "pown" function. Apparently the  function exists in LLVM but cannot be transformed into assembly, so I had to provide my own implementation of "pown". Shouln't this be done by POCL ?

Cheers,

Jerome

**Comment by pjaaskel** [comment]
Yes of course. Which version of pocl you tried?

**Comment by pjaaskel** [comment]
Which device you target here? The Power9 or the Tesla?

**Comment by kif** [comment]
On Sun, 05 May 2019 10:48:40 -0700
Pekka Jääskeläinen <notifications@github.com> wrote:

> Yes of course. Which version of pocl you tried?

Hi Pekka,

I re-compiled the version from debian10, hence the version 1.2.
https://packages.debian.org/source/buster/pocl

I apologize for not testing the latest release but the computer is on
loan and I had to cut corners to get all tests done, especially that
the version 1.3 is not yet packaged on debian (which could indicate
some complication at the compilation stage).

**Comment by kif** [comment]
On Sun, 05 May 2019 10:56:01 -0700
Pekka Jääskeläinen <notifications@github.com> wrote:

> Which device you target here? The Power9 or the Tesla?

I got the error on Tesla (for sure) but not for the Power9 (I just double checked)

```
[<pyopencl.Device 'pthread-POWER9, altivec supported' on 'Portable Computing Language' at 0x45ec5570>, <pyopencl.Device 'Tesla V100-SXM2-16GB' on 'Portable Computing Language' at 0x45ec5830>, <pyopencl.Device 'Tesla V100-SXM2-16GB' on 'Portable Computing Language' at 0x45ec5af0>]
<pyopencl.Device 'Tesla V100-SXM2-16GB' on 'Portable Computing Language' at 0x45ec5af0>
LLVM ERROR: Cannot select: 0x545a2eb0: i64 = ExternalSymbol'__powisf2'
In function: csr_integrate
```

**Comment by pjaaskel** [comment]
Thanks. OK then this might be simply an unimplemented builtin for the CUDA backend. If @jrprice confirms, then I must just say that pull requests are welcome and will be reviewed happily :)

**Comment by jrprice** [comment]
Yep: https://github.com/pocl/pocl/blob/master/lib/CL/devices/cuda/pocl-ptx-gen.cc#L864

I think the NVVM intrinsics we need are `__nv_powi` and `__nv_powif`. There might be a few different functions that map to these (the error in this issue calls out `__powisf2`, but I'm guessing there might just be a `__powif` as well?). Can probably just deal with them on a case-by-case basis as they come up.

**Comment by kif** [comment]
There are 2 path which are possible:
Either reimplement or reverse-engineer what NVVM is doing, which is probably the _best_ solution but requires know-how in assembly which is rather uncommon, hence it is rather unlikely to see a pull-request popping out from nowhere on this technical subject. I had a look at the assembly for a simple call to *pown* and it is ~500 lines (or instructions). For comparison the naive function is about  100 instructions.

The second option is to provide a set of OpenCL functions implemented in C which can be injected in the code before re-compilation.
```
float naive_pown(float a, int b)
{
    float res = 1.0f;
    for (int i=0; i<b; i++)
    {
        res *= a;
    }
    return res;
}
```

Wouldn't this path be easier ?

**Comment by pjaaskel** [comment]
Yes, I think so, if there's no builtin that helps in NVVM. There are e.g. Sleef implementation already in pocl which can be picked for the CUDA's bitcode library. Also [ROCm-Device-Libs' ocml](https://github.com/pocl/pocl/pull/723) will be an option hopefully soon.

**Comment by jrprice** [comment]
I don't think we need anything so complex. NVVM provides the `__nv_powi` intrinsics as I mentioned above, so we just need to map the `llvm.powi.*` intrinsics to them. I've opened #726 which does exactly this, and verified that this fixes `pown` for me on NVIDIA GPUs.
