### ISSUE TITLE
How to help

### ISSUE THREAD

**Issue by crr0004** [pocl/pocl#727]
Hey,

This project is pretty awesome and I noticed it through a Fedora package because it's allowing opencl to run on my ryzen CPU. I'd love to help the project. Before I drive into the code I thought I'd ask if there are any areas which really need more help in. Is there anything specific that needs help?

Cheers

**Comment by pjaaskel** [comment]
Thanks for offering a hand! You might want to check the issue list and pick ones which might look doable and interest you. Just add a comment that you plan to work on it, so you might get hints and avoid overlapping work.
https://github.com/pocl/pocl/labels/contributions%20welcome

**Comment by crr0004** [comment]
Thanks for that! I'll have a look and see what I can do.
