### ISSUE TITLE
[docs] Intel OpenCL SDK for CPU overwrites libOpenCL.so 

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#729]
This is an issue of the Intel OpenCL SDK installer actually, but seems to affect many pocl users and the reason is not obvious at first. It just overwrites the libOpenCL.so in /usr/lib/x86* with a symlink (through) the alternatives system to its own implementation. The fix is to remove the symlinks manually and reinstall the ICD loader after which both pocl and the Intel SDK can be used through the ICD loader. It's better to make a note of this in the installation/troubleshooting/faq. @shayan-tabatabaei-nikkhah

**Comment by franz** [comment]
Fixed
