### ISSUE TITLE
[docs] add apt example commands for installing the prerequisities

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#730]
At least for the alive LTS Ubuntus.

**Comment by sunfic** [comment]
I suggest these packages:

`apt install libhwloc-dev ocl-icd-dev libclang-dev llvm-dev ocl-icd-opencl-dev clinfo`

tested and working on Ubuntu 18.04 LTS with latest updates for pocl v1.3.
clinfo is not necessary for building but good for testing.

**Comment by franz** [comment]
Fixed

**Comment by sunfic** [comment]
tested with pocl v1.4. addtional package clang needed 

`apt install libhwloc-dev ocl-icd-dev libclang-dev clang llvm-dev ocl-icd-opencl-dev clinfo`
