### ISSUE TITLE
pocl (master branch) fails to build on ARM64 when CUDA is enabled.

### ISSUE THREAD

**Issue by philoteer** [pocl/pocl#741]
When I attempt to build pocl (master branch) on my board, it stops with the following error:

``
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c: In function ‘load_or_generate_kernel’:
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:788:15: error: too many arguments to function ‘pocl_llvm_generate_workgroup_function’
   int error = pocl_llvm_generate_workgroup_function (device_i, device, kernel,
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:35:0:
/home/piloteer/git/pocl/pocl/lib/CL/./pocl_llvm.h:74:5: note: declared here
 int pocl_llvm_generate_workgroup_function (unsigned DeviceI,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:798:3: error: too many arguments to function ‘pocl_cache_work_group_function_path’
   pocl_cache_work_group_function_path (bc_filename, kernel->program, device_i,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:33:0:
/home/piloteer/git/pocl/pocl/include/pocl_cache.h:118:6: note: declared here
 void pocl_cache_work_group_function_path (char *parallel_bc_path,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c: At top level:
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:852:1: error: conflicting types for ‘pocl_cuda_compile_kernel’
 pocl_cuda_compile_kernel (_cl_command_node *cmd, cl_kernel kernel,
 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.h:31:0,
                 from /home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:31:
/home/piloteer/git/pocl/pocl/lib/CL/devices/prototypes.inc:86:8: note: previous declaration of ‘pocl_cuda_compile_kernel’ was here
   void pocl_##__DRV__##_compile_kernel (_cl_command_node *node,               \
        ^
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.h:32:1: note: in expansion of macro ‘GEN_PROTOTYPES’
 GEN_PROTOTYPES (cuda)
 ^~~~~~~~~~~~~~
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c: In function ‘pocl_cuda_compile_kernel’:
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:855:64: error: ‘_cl_command_run {aka struct <anonymous>}’ has no member named ‘device_i’; did you mean ‘device_data’?
   load_or_generate_kernel (kernel, device, 0, cmd->command.run.device_i);
                                                                ^~~~~~~~
                                                                device_data
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c: In function ‘pocl_cuda_submit_kernel’:
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:873:67: error: ‘_cl_command_run {aka struct <anonymous>}’ has no member named ‘device_i’; did you mean ‘device_data’?
       = load_or_generate_kernel (kernel, device, has_offsets, run.device_i);
                                                                   ^~~~~~~~
                                                                   device_data
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:1017:49: error: ‘_cl_command_run {aka struct <anonymous>}’ has no member named ‘local_x’
                            pc.num_groups[2], run.local_x, run.local_y,
                                                 ^
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:1017:62: error: ‘_cl_command_run {aka struct <anonymous>}’ has no member named ‘local_y’
                            pc.num_groups[2], run.local_x, run.local_y,
                                                              ^
/home/piloteer/git/pocl/pocl/lib/CL/devices/cuda/pocl-cuda.c:1018:31: error: ‘_cl_command_run {aka struct <anonymous>}’ has no member named ‘local_z’
                            run.local_z, sharedMemBytes, stream, params, NULL);
                               ^
lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/build.make:62: recipe for target 'lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/pocl-cuda.c.o' failed
make[2]: *** [lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/pocl-cuda.c.o] Error 1
CMakeFiles/Makefile2:913: recipe for target 'lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/all' failed
make[1]: *** [lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
``

It builds fine if I exclude the CUDA option. Also, older versions (v1.1 - v1.3) seem to build fine.

The board in use is NVidia Jetson TX2, running Ubuntu 18.04, stock Clang + llvm (version 6). Version of nvcc is v10.0.166.

**Comment by pjaaskel** [comment]
Ok, cuda needs to be updated to the latest API changes. @jrprice can you take a look? I need to setup a CUDA test env for myself when I find the time.

**Comment by franz** [comment]
Should be fixed in master

**Comment by philoteer** [comment]
Yes, it does seem to build.

`[100%] Built target pocl
`
