### ISSUE TITLE
opencl-c.h lookup fails, CLANG_RESOURCES_DIR determined at compile time

### ISSUE THREAD

**Issue by StefanBruens** [pocl/pocl#747]
The resources dir, containing opnecl-c.h is fixed at compile time:

https://github.com/pocl/pocl/blob/eec41dece31b978da3dfad44ad52c18dd89c2c3c/lib/CL/pocl_llvm_build.cc#L428

If libclang gets a minor version upgrade later (e.g. from 8.0.0 to 8.0.1), the header is still searched for in the old location (e.g. /usr/lib64/clang/8.0.0/include/opencl-c.h). As the SOVERSION is unchanged, is is typically not picked up by the regular dependency mechanisms.

Related Debian bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903822

With LLVM master (> 8.0), the Resources patch can be queried with llvm::driver::Driver::GetResourcesPath(binarydir)
https://github.com/llvm-mirror/clang/commit/8b235351e95f1e66a49532aa86dcead258d77668

**Comment by franz** [comment]
Thanks, i've forward-ported this to master branch.
