### ISSUE TITLE
portabecl.org forces users into using insecure communications because of lack of TLS

### ISSUE THREAD

**Issue by KOLANICH** [pocl/pocl#770]

**Comment by pjaaskel** [comment]
That's true, but I believe there is no secure content in it either so I've thought (so far!) that our group's time has been more efficiently used on other problems.

**Comment by KOLANICH** [comment]
I think that every website should be available via an authenticated connection. There is a group of users who don't visit any website available over an insecure channel only. They even have a special browser addon for it.

**Comment by pjaaskel** [comment]
OK. Let's see what we can do.
