### ISSUE TITLE
POCL Neon

### ISSUE THREAD

**Issue by gregmbi** [pocl/pocl#776]
Hi,

How can i see if a pocl program is utilizing Neon vector instructions on an ARM CPU ?

**Comment by pjaaskel** [comment]
Hi. Inspect the kernel compiler output: http://www.portablecl.org/docs/html/env_variables.html POCL_CACHE_DIR and POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES are useful for this. The *.so is the final binary which you can obj-dump -d.
