### ISSUE TITLE
When double hyperbolic and trigonometric functions are combined in a single kernel the compiler hangs

### ISSUE THREAD

**Issue by KOLANICH** [pocl/pocl#777]
Could you check if compilation hangs on compiling the following code?

```opencl
#pragma OPENCL EXTENSION cl_khr_fp64 : enable

__kernel void testCSin(__global const double *ar, __global double *br){
	unsigned int m = get_global_id(0);
	double s = sin(ar[m]);
	double ch = cosh(ar[m]);
	br[m]=s * ch;
}
```

**Comment by AnastasiaStulova** [comment]
A bug has been submitted to Clang initially https://bugs.llvm.org/show_bug.cgi?id=43444#c3

But Clang doesn't seem to hang and there seems to be nothing strange in the generated IR. It would be good to understand where in the compiler stack the hang happens.

**Comment by pjaaskel** [comment]
Please provide a C++ reproducer and I can test.

**Comment by KOLANICH** [comment]
It also hangs if I try to compile this soutce with poclcc.

**Comment by pjaaskel** [comment]
Can you take a gdb backtrace of the hanging process (gdb --pid)?

**Comment by KOLANICH** [comment]
I can try (I don't have any experience with gdb without GUI frontends), but not now (probably in some hours).

**Comment by pjaaskel** [comment]
Thanks. I cannot guarantee when we have a spot to check this, so your proactive debugging will definitely help squashing this one!

**Comment by KOLANICH** [comment]
pocl is OK. It seems like poclcc just uses mesa runtimes by default (and I haven't managed to make it use another runtime using `-i`).
