### ISSUE TITLE
assert(res) failed in cpu_setup_vector_widths() on non-mainstream architectures

### ISSUE THREAD

**Issue by anbe42** [pocl/pocl#778]
```
clinfo: /<<PKGBUILDDIR>>/lib/CL/pocl_llvm_utils.cc:202: void cpu_setup_vector_widths(cl_device_id): Assertion `res' failed.
```

This happens on several architectures when pocl 1.3 is built with llvm 7 or llvm 8, but not with llvm 6.0. Obviously `llvm::sys::getHostCPUFeatures(features)` does return `false` in the newer llvm versions on these platforms. The build has never been successful on these platforms because some tests were failing (and noone analyzed them deeper, yet) but this type of failure is new.

Build logs showing this issue are available from https://buildd.debian.org/status/package.php?p=pocl&suite=experimental (1.3-8 was built with llvm 8, 1.3-5, ..., 1.3-7 were built with llvm 3.7 and <= 1.3-4 was built with llvm 6.0)

**Comment by franz** [comment]
fixed in master
