### ISSUE TITLE
pocl on riscv

### ISSUE THREAD

**Issue by shamilkhan9** [pocl/pocl#790]
Hello,
        I want to cross compile pocl for RISCV on x86_64 host.
Is it possible to cross compile by modifying the ToolchainExample.cmake file given in the pocl sources.

For example : 
Setting CMAKE_C_COMPILER as riscv-gnu-toolchain/bin/riscv64-unknown-linux-gnu-gcc

**Comment by franz** [comment]
Hello,

No, cross-compilation is currently not supported. It may be easy to cross-compile a LLVM-less build, but there's little point (since LLVM-less builds can run natively even on machines with 512M ram). For cross-compiling LLVM-enabled builds, someone would have to do the necessary work on pocl's CMake files.

**Comment by yingmanwumen** [comment]
> Hello,
> 
> No, cross-compilation is currently not supported. It may be easy to cross-compile a LLVM-less build, but there's little point (since LLVM-less builds can run natively even on machines with 512M ram). For cross-compiling LLVM-enabled builds, someone would have to do the necessary work on pocl's CMake files.

Hello,

Is cross-compile on RISC-V ready now? 

> For example :
> Setting CMAKE_C_COMPILER as riscv-gnu-toolchain/bin/riscv64-unknown-linux-gnu-gcc

Is this possible now? I've tried to compile newlib for riscv, but it told me that `-pie` was not supported in `riscv64-unknown-elf-ld` now. I don't know what to do to cross-compile it.

**Comment by franz** [comment]
> Is cross-compile on RISC-V ready now?

Nobody has done the work to fix the CMake files to cross-compile LLVM-enabled PoCL. So the answer is no, sorry.

**Comment by isuruf** [comment]
I've been cross compiling pocl for `aarch64-linux-gnu`, `powerpc64le-linux-gnu` (from `x86_64-linux-gnu) and `arm64-apple-darwin` (from `x86_64-apple-darwin` for months now and it works just fine as long as you set the correct cmake variables.
However setting up the correct toolchain, setting up a `host` version of LLVM (for eg: aarch64-linux-gnu`) and `build` version of LLVM and setting up a cmake toolchain file is hard and I cannot help you with these basics in cross-compiling. You also need to set `KERNELLIB_HOST_CPU_VARIANTS`, `LLC_HOST_CPU`, `CLANG_MARCH_FLAG` and `LLVM_HOST_TRIPLE` flags when cross-compiling.

**Comment by yingmanwumen** [comment]
> I've been cross compiling pocl for `aarch64-linux-gnu`, `powerpc64le-linux-gnu` (from `x86_64-linux-gnu`) and `arm64-apple-darwin` (from `x86_64-apple-darwin`) for months now and it works just fine as long as you set the correct cmake variables. However setting up the correct toolchain, setting up a `host` version of LLVM (for eg: `aarch64-linux-gnu`) and `build` version of LLVM and setting up a cmake toolchain file is hard and I cannot help you with these basics in cross-compiling. You also need to set `KERNELLIB_HOST_CPU_VARIANTS`, `LLC_HOST_CPU`, `CLANG_MARCH_FLAG` and `LLVM_HOST_TRIPLE` flags when cross-compiling.

I'm curious if there is any done work that could be referred to.
The documentation is ambiguous with some steps for newbies. For example, I can't understand `a host version of LLVM`, does it mean `a LLVM hosts on aarch64-linux-gnu and targets at aarch64-linux-gnu` or just simply `targets at aarch64-linux-gnu`.
