### ISSUE TITLE
plans for generic keyword support OpenCL 2.0

### ISSUE THREAD

**Issue by robbert-harms** [pocl/pocl#791]
Hi POCL developers,

I am a fan or this project and I think it is a very useful basis to further the growth of the OpenCL ecosystem.

Do you have any plans for supporting the generic keyword in OpenCL 2.0? 

Thank you for your attention and time,

Best,

Robbert

**Comment by pjaaskel** [comment]
Thanks Robbert! Generic is not in our group's needs at this moment, so I cannot promise other than pull request reviews from our side, but I will be happy to see any PR landing on towards it and we will give hints to proceed.
