### ISSUE TITLE
pocl 1.4, ppc64le, and c++11 build issue

### ISSUE THREAD

**Issue by branfosj** [pocl/pocl#800]
Building pocl 1.4 on ppc64le (IBM Power9 box) I've hit an issue with the c++11 standard being set as a compiler flag. Using LLVM 9.0.1, GCC 8.3.0 and setting `-DENABLE_ICD=0 -DINSTALL_OPENCL_HEADERS=1` as CMake options. The error message is:
```
/rds/bear-apps/devel/2019b/branfosj-eb-2/EL7/EL7-power9/software/GCCcore/8.3.0/include/c++/8.3.0/cmath:585:31: error: cannot convert int to __vector(4) __bool int in return
   { return __builtin_isinf(__x); }
```
which lead me to https://bugs.freedesktop.org/show_bug.cgi?id=68504#c5 and that suggests a fix.

I've used https://raw.githubusercontent.com/easybuilders/easybuild-easyconfigs/d3f20f575b3c3cf0c839bf249b73ff781c9f1a86/easybuild/easyconfigs/p/pocl/pocl-1.4_remove-c11-std.patch and this fixes the issue.

**Comment by branfosj** [comment]
I've done some more testing and an alternative is the following patch:
```patch
diff -aur pocl-1.4.orig/include/CL/cl_platform.h pocl-1.4/include/CL/cl_platform.h
--- pocl-1.4.orig/include/CL/cl_platform.h      2020-01-03 09:55:56.986465000 +0000
+++ pocl-1.4/include/CL/cl_platform.h   2020-01-03 09:59:18.058173021 +0000
@@ -356,6 +356,8 @@
 /* Define basic vector types */
 #if defined( __VEC__ )
    #include <altivec.h>   /* may be omitted depending on compiler. AltiVec spec provides no way to detect whether the header is required. */
+   #undef bool
+   #undef vector
    typedef __vector unsigned char     __cl_uchar16;
    typedef __vector signed char       __cl_char16;
    typedef __vector unsigned short    __cl_ushort8;
```

**Comment by franz** [comment]
Messing with LLVM_CXXFLAGS is generally a bad idea, so i have merged the second patch. Thanks
