### ISSUE TITLE
How to compile OpenCL kernel for aarch64

### ISSUE THREAD

**Issue by peter197321** [pocl/pocl#803]
I am trying to make Clang compile some simple OpenCL kernel. 

```
__kernel void helloworld(__global char* in, __global char* out)
{
	int num = get_global_id(0);
	out[num] = in[num] + 1;
}

```
I want to use for that the command line ... This code, placed in the file `"helloworld.cl"`, can compile with Clang using the following command line

> clang -S -emit-llvm -o helloworld.ll -x cl helloworld.cl

How to compile for aarch64 a multi-core ARM64  architecture?

**Comment by pjaaskel** [comment]
You best use the standard OpenCL way of building it from a host program via clBuildProgram. Also there's an offline compiler poclcc which you can try. It's described in the manual.

**Comment by Che-Cheng-Chang** [comment]
Hey is there possible to see the build log of poclcc? 
I keep get CL_BUILD_PROGRAM_FAILURE while using poclcc and I don't know why.

thanks

**Comment by pjaaskel** [comment]
Try export POCL_DEBUG=1 before running.
