### ISSUE TITLE
Port POCL library to Android 

### ISSUE THREAD

**Issue by FreemanX** [pocl/pocl#807]
I'm trying to use pocl on Android smartphone but no luck here.  I download the [pocl libs](https://play.google.com/store/apps/details?id=org.pocl.libs) from the play store, but that .so file doesn't work. The sample app ([pocl vector addition](https://play.google.com/store/apps/details?id=org.pocl.sample1)) crushed on launch. 
### Environment
**Smartphone:** OnePlus 6
**OS:** Android 8.1
**SoC:** Snapdragon 845
I follow the instructions using pocl with dlopen, but that doesn't work either.
Here's the output of a [quick test](https://github.com/FreemanX/dyclinfodump-32bit) of mine (querying info and run a kernel):
```
OpenCL lib found: /vendor/lib/libOpenCL.so
dlopen opencl lib: /vendor/lib/libOpenCL.so
dlopen SUCCESS!
Num platform:1
Num devices:1
Platform name: QUALCOMM Snapdragon(TM)
Device name: QUALCOMM Adreno(TM)
CL_DEVICE_MEM_BASE_ADDR_ALIGN: 1024
CL_DEVICE_SVM_FINE_GRAIN_BUFFER
CL_DEVICE_SVM_COARSE_GRAIN_BUFFER
Data size:4MB
Execution time: 0.04096s

OpenCL lib found: /data/local/tmp/libpocl.so.1.4.0
dlopen opencl lib: /data/local/tmp/libpocl.so.1.4.0
dlopen SUCCESS!
Num platform:1
Num devices:0
Platform name: Portable Computing Language
Device name:
CL_DEVICE_MEM_BASE_ADDR_ALIGN: 16163831
CL_DEVICE_SVM_FINE_GRAIN_BUFFER
CL_DEVICE_SVM_COARSE_GRAIN_BUFFER
Bus error
```
As a comparison, I use dlopen to load the OpenCL library for Adreno GPU(works fine). I expect pocl will find at least 1 device (CPU). I notice that pocl library was ported to android a few years ago, I wonder if it's still working on more recent android phones.

**Comment by franz** [comment]
> I notice that pocl library was ported to android a few years ago

That's correct - 2014 per github log. I don't think many people tried it since, and i don't remember any commits that would try to keep it alive, so very likely it's defunct. It might be possible to revive but would likely require some time & effort.

**Comment by FreemanX** [comment]
OK, I'm working on compiling pocl for android (aarch64). I follow the logic from the old script in pocl release 1.3 [pocl/android/build-arm.sh](https://github.com/pocl/pocl/blob/release_1_3/android/build-arm.sh), [pocl-android-prebuilts](https://github.com/krrishnarraj/pocl-android-prebuilts/tree/master/arm) and #71. So far, I'm still dealing with cross-compiling issues (painfully)...    
I build each dependency with android toolchain, then try to compile pocl(1.4):    

### binutils     
- pulled from android OS
- adb pull /system/bin/ld.mc
- mv ld.mc ld
- **Question**: the **ld** binary in pocl-android-prebuilts is a 32-bit arm executable, so I assume I can directly use the one in the smartphone? Is it necessary to have ld executable file building pocl?

### hwloc v2.0.4    
- [0001-Weak-definitions-of-faccessat-getline-for-android.patch](https://github.com/krrishnarraj/pocl-android-prebuilts/blob/master/sources/hwloc/0001-Weak-definitions-of-faccessat-getline-for-android.patch) applied
- build with build_hwloc.sh
- **Question**: cmake build log says hwloc won't be used since I'm not building for Unix or cross-compiling. 
`-- Not on UNIX or cross-compiling -> building without HWLOC`. But the previous android build uses hwloc. Is it still necessary?

### ncurses-6.2
- libtool
- git clone git://git.savannah.gnu.org/libtool.git (commit b9b44533fbf7c7752ffd255c3d09cc360e24183b)

### llvm
- git clone https://android.googlesource.com/toolchain/llvm-project (commit 60aaffe353336fcd5afa08a24133df6673dee3f5), I use llvm from Google instead of from llvm.org. 
- build executable binaries for x86 and copy those files to llvm/bin/ as  [llvm/cross_compiler_for_android/bin](https://github.com/krrishnarraj/pocl-android-prebuilts/tree/master/arm/llvm/cross_compiler_for_android/bin) did, all these executables are x86.
- then build static libraries for aarch64 and put them in llvm/lib/ like [llvm/android/lib](https://github.com/krrishnarraj/pocl-android-prebuilts/tree/master/arm/llvm/android/lib)
- **Question**: to build pocl for Android, only those static libraries are needed when compiling pocl with the compiler provided by the Android toolchain (i.e. aarch64-linux-android-clang++). As for x86 executables, are they are used for passing LLVM checks defined in cmake/LLVM.cmake? Or I got it wrong that pocl must be compiled with these executables?    

Pocl-android build script: https://github.com/FreemanX/pocl-android-dependency/blob/master/build-pocl.sh 

Any help or suggestions are appreciated.

**Comment by franz** [comment]
1) ld is necessary for running pocl (but then it's true for all programs - you have to load them somehow),
2) hwloc is not necessary anymore,
3) ncurses is not necessary (i don't remember it ever being necessary),
4) LLVM is necessary.

Also ltdl (a wrapper around dlopen) is not necessary anymore. The LLVM binaries are indeed used for checks in CMake. In past they were used also at runtime by pocl, but i think that's all gone now and it should use library calls (into libLLVM/libclang) everywhere.

**Comment by FreemanX** [comment]
Thank you.     
After some work, I managed to pass all pre-checks. But I am stuck at linking LibOpenCL.so...  
Build log:   
```
[ 72%] Built target kernellib_hash
Scanning dependencies of target pocl_cache
[ 72%] Building C object lib/CL/CMakeFiles/pocl_cache.dir/pocl_cache.c.o
[ 72%] Built target pocl_cache
Scanning dependencies of target OpenCL
[ 72%] Linking CXX shared library libOpenCL.so
clang90++: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
bionic/libc/arch-arm64/bionic/setjmp.S:199: **error: relocation overflow in R_AARCH64_CONDBR19**
clang90++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/CL/CMakeFiles/OpenCL.dir/build.make:476: lib/CL/libOpenCL.so.2.6.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:541: lib/CL/CMakeFiles/OpenCL.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```
I've searched around, but no luck here...

**Comment by FreemanX** [comment]
I have successfully build pocl for aarch64 android, and I can query OpenCL info. The problem I have above is caused by linking too many static codes(LLVM and CLANG) when generating libOpenCL.so. As long as libOpenCL.so is dynamically linked to LLVM and CLANG, everything works. 
```
Num platform:1                                                                                                                                                            [4/1843]
Platform name: Portable Computing Language
CL_PLATFORM_PROFILE: FULL_PROFILE
CL_PLATFORM_VERSION: OpenCL 1.2 pocl 1.6-pre master-0-g07e70ca6, Debug+Asserts, LLVM 6.0.0svn, RELOC, SLEEF, FP16, POCL_DEBUG
CL_PLATFORM_VENDOR: The pocl project
CL_PLATFORM_EXTENSIONS:
Num devices:1
  CL_DEVICE_NAME:                       pthread-0x803
  CL_DEVICE_VENDOR:                     Qualcomm
  CL_DRIVER_VERSION:                    1.6-pre master-0-g07e70ca6
  CL_DEVICE_TYPE:                       CL_DEVICE_TYPE_CPU
  CL_DEVICE_MAX_COMPUTE_UNITS:          8
  CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:   3
  CL_DEVICE_MAX_WORK_ITEM_SIZES:        4096 / 4096 / 4096
  CL_DEVICE_MAX_WORK_GROUP_SIZE:        4096
  CL_DEVICE_MAX_CLOCK_FREQUENCY:        1766 MHz
  CL_DEVICE_ADDRESS_BITS:               64
  CL_DEVICE_MAX_MEM_ALLOC_SIZE:         2048 MByte
  CL_DEVICE_GLOBAL_MEM_SIZE:            5631 MByte
  CL_DEVICE_ERROR_CORRECTION_SUPPORT:   no
  CL_DEVICE_LOCAL_MEM_TYPE:             global
  CL_DEVICE_LOCAL_MEM_SIZE:             1024 KByte
  CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:   1024 KByte
  CL_DEVICE_QUEUE_PROPERTIES:           CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE
  CL_DEVICE_QUEUE_PROPERTIES:           CL_QUEUE_PROFILING_ENABLE
  CL_DEVICE_IMAGE_SUPPORT:              1
  CL_DEVICE_MAX_READ_IMAGE_ARGS:        128
  CL_DEVICE_MAX_WRITE_IMAGE_ARGS:       128

  CL_DEVICE_IMAGE <dim>                 2D_MAX_WIDTH     8192
                                        2D_MAX_HEIGHT    8192
                                        3D_MAX_WIDTH     2048
                                        3D_MAX_HEIGHT    2048
                                        3D_MAX_DEPTH     2048
  CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>  CHAR 1, SHORT 1, INT 1, FLOAT 1, DOUBLE 1
  CL_DEVICE_PARTITION_MAX_SUB_DEVICES:  8
  CL_DEVICE_MEM_BASE_ADDR_ALIGN:        1024
```
However, the program failed to execute opencl kernels. Here's the debug message:
```
[2020-03-23 02:44:47.546432316310]POCL: in fn cl_command_queue POclCreateCommandQueue(cl_context, cl_device_id, cl_command_queue_properties, cl_int *) at line 42:
  |   GENERAL |  Create Command queue on device 0
[2020-03-23 02:44:47.971665083]POCL: in fn cl_int compile_and_link_program(int, int, cl_program, cl_uint, const cl_device_id *, const char *, cl_uint, const cl_program *, const char **, cl_uint, const cl_program *, void (*)(cl_program, void *), void *) at line 635:
  |   GENERAL |  building from sources for device 0
[2020-03-23 02:44:48.515426273467]POCL: in fn cl_int POclSetKernelArg(cl_kernel, cl_uint, size_t, const void *) at line 73:
  |   GENERAL |  Kernel          vecAdd || SetArg idx   0 ||   float* || Local 0 || Size      8 || Value 0x7fd70eb568 || *Value 0x785a216140 || *(uint32*)Value:        0
[2020-03-23 02:44:48.515426315342]POCL: in fn cl_int POclSetKernelArg(cl_kernel, cl_uint, size_t, const void *) at line 73:
  |   GENERAL |  Kernel          vecAdd || SetArg idx   1 ||   float* || Local 0 || Size      8 || Value 0x7fd70eb558 || *Value 0x785a216280 || *(uint32*)Value:        0
[2020-03-23 02:44:48.515426342582]POCL: in fn cl_int POclSetKernelArg(cl_kernel, cl_uint, size_t, const void *) at line 73:
  |   GENERAL |  Kernel          vecAdd || SetArg idx   2 ||   float* || Local 0 || Size      8 || Value 0x7fd70eb548 || *Value 0x785a216500 || *(uint32*)Value:        0
[2020-03-23 02:44:48.515426352582]POCL: in fn cl_int POclSetKernelArg(cl_kernel, cl_uint, size_t, const void *) at line 73:
  |   GENERAL |  Kernel          vecAdd || SetArg idx   3 ||     uint || Local 0 || Size      4 || Value 0x7fd70eb554 || *Value 0x0 || *(uint32*)Value:      671
CPU Execution time: 0.000001 s
[2020-03-23 02:44:48.515426405811]POCL: in fn cl_int POclEnqueueNDRangeKernel(cl_command_queue, cl_kernel, cl_uint, const size_t *, const size_t *, const size_t *, cl_uint, const cl_event *, cl_event *) at line 240:
  |   GENERAL |  Preferred WG size multiple 8
[2020-03-23 02:44:48.545491184435]POCL: in fn cl_int POclEnqueueNDRangeKernel(cl_command_queue, cl_kernel, cl_uint, const size_t *, const size_t *, const size_t *, cl_uint, const cl_event *, cl_event *) at line 456:
  |   GENERAL |  Queueing kernel vecAdd with local size 128 x 1 x 1 group sizes 8 x 1 x 1...
[2020-03-23 02:44:48.38739366007]POCL: in fn int llvm_codegen(char *, unsigned int, cl_kernel, cl_device_id, _cl_command_node *, int) at line 198:
  |   GENERAL |  Linking final module
#DEBUG message -- cmd_line: /tmp/android-toolchain_r17/bin/aarch64-linux-android-clang
error: unable to execute command: Executable "ld" doesn't exist!
error: linker command failed with exit code 1 (use -v to see invocation)
Final linking of kernel vecAdd failed.
Aborted
```
The problem is that the program invokes an external compiler(https://github.com/pocl/pocl/blob/master/lib/CL/devices/common.c#L208), which in my case is the one comes with android ndk(aarch64-linux-android-clang). To my understanding, everything can be done with function calls from libclang and libLLVM and there's no need to call  aarch64-linux-android-clang right? Thanks.

**Comment by pjaaskel** [comment]
Great progress! It calls libclang and libLLVM directly, and uses their toolchain info for your target _for the linking phase_. Thus, it could be the Clang needs to be patched to use the correct linker? https://github.com/pocl/pocl/blob/master/lib/CL/pocl_llvm_build.cc#L918

**Comment by truboxl** [comment]
Maybe checking https://github.com/termux/termux-packages/pull/1346?

**Comment by FreemanX** [comment]
I can now execute OpenCL kernels with pocl. Here's the output of clpeak:
```
Platform: Portable Computing Language
  Device: pthread-0x803
    Driver version  : 1.6-pre master-0-g07e70ca6 (Android)
    Compute units   : 8
    Clock frequency : 1766 MHz

    Global memory bandwidth (GBPS)
      float   : 13.25
      float2  : 12.94
      float4  : 10.85
      float8  : 10.09
      float16 : 10.32

    Single-precision compute (GFLOPS)
      float   : 5.21
      float2  : 10.39
      float4  : 20.54
      float8  : 36.42
      float16 : 55.13

    Half-precision compute (GFLOPS)                                                                                                                                      
      half   : 5.20
      half2  : 10.37
      half4  : 20.63
      half8  : 40.06
      half16 : 69.66

    Double-precision compute (GFLOPS)
      double   : 5.20
      double2  : 10.37
      double4  : 18.55
      double8  : 28.23
      double16 : 30.08

    Integer compute (GIOPS)
      int   : 11.35
      int2  : 11.39
      int4  : 20.94
      int8  : 33.07
      int16 : 45.41
    Transfer bandwidth (GBPS)
      enqueueWriteBuffer         : 7.49
      enqueueReadBuffer          : 8.00
      enqueueMapBuffer(for read) : 2490.12
      memcpy from mapped ptr   : 8.17
      enqueueUnmap(after write)  : 5347.32
      memcpy to mapped ptr     : 8.23

    Kernel launch latency : 144.00 us
```
Is the Kernel launch latency too high compared to other smartphones in https://github.com/krrishnarraj/clpeak/tree/master/results/Portable_Computing_Language ? (144.00 us vs less than 10 us)

For solving the linking phase problem, I give up using libLLVM and libclang... I compile the ld executable from https://android.googlesource.com/toolchain/binutils/ and use it for linking porcess(from .o to .so). My workaround code in lib/CL/devices/common.c:    
```
  //error = pocl_invoke_clang (device, cmd_line);
  pid_t pid = fork();
  if (pid == 0){
          /* Redirect ld process. Modified*/
          char *cmd_line_ld[16] = {"/data/local/tmp/pocl/ld", "-o", tmp_module, tmp_objfile, "-shared", NULL}; // with -nostartfiles, ld can’t produce .so file
          execv(cmd_line_ld[0], cmd_line_ld);
          exit(0);
  }else{
  wait(NULL);
  if (error)
    {
      POCL_MSG_PRINT_LLVM ("Linking kernel.so.o -> kernel.so has failed\n");
      goto FINISH;
    }
    ...
  } // fork() else
```

Also, dlopen with **RTLD_NOW** flag will cause error: 
```
dlopen failed: "/data/local/tmp/cache/NF/FBJFLNJOFPAGMBOPGFBMLFHPGAMMFCMANIKAJ/vecAdd/128-1-1-goffs0-smallgrid/vecAdd.so": W + E load segments are not allowed
```
This error is caused by Android OS security update since Android O.  Therefore, I make change to this line:
```
ci->dlhandle = dlopen (module_fn, RTLD_LAZY | RTLD_LOCAL);  //ci->dlhandle = dlopen (module_fn, RTLD_NOW | RTLD_LOCAL);
```

**Unsolved problems:**

1. Cannot statically link libLLVM and libCLang. I have to build dynamic libraries and `export LD_LIBRARY_PATH` every time in Android shell.

2.  Not sure if there's better solution for linking phase...

**Other source code modifications made for Android build**
1. lib/CL/pocl_cq_profiling.c : add `#include <strings.h>`
2. lib/CL/devices/pthread/pthread_scheduler.c:       
```
       //pthread_setaffinity_np (td->thread, sizeof (cpu_set_t), &set);
       sched_setaffinity(td->thread, sizeof (cpu_set_t), &set);
```
3. hardcoded cache path in lib/CL/pocl_cache.c:      
```
const char *tmp_path = pocl_get_string_option ("POCL_CACHE_DIR", "/data/local/tmp/cache/");
```

Build with Android ndk_r17b. Android (4691093 based on r316199) clang version 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55536e7d904e0abae47888fc7f) (https://android.googlesource.com/toolchain/llvm 34361f192e41ed6e4e8f9aca80a4ea7e9856f327) (based on LLVM 6.0.2svn)

**Comment by FreemanX** [comment]
> Thank you.
> After some work, I managed to pass all pre-checks. But I am stuck at linking LibOpenCL.so...
> Build log:
> 
> ```
> [ 72%] Built target kernellib_hash
> Scanning dependencies of target pocl_cache
> [ 72%] Building C object lib/CL/CMakeFiles/pocl_cache.dir/pocl_cache.c.o
> [ 72%] Built target pocl_cache
> Scanning dependencies of target OpenCL
> [ 72%] Linking CXX shared library libOpenCL.so
> clang90++: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
> bionic/libc/arch-arm64/bionic/setjmp.S:199: **error: relocation overflow in R_AARCH64_CONDBR19**
> clang90++: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [lib/CL/CMakeFiles/OpenCL.dir/build.make:476: lib/CL/libOpenCL.so.2.6.0] Error 1
> make[1]: *** [CMakeFiles/Makefile2:541: lib/CL/CMakeFiles/OpenCL.dir/all] Error 2
> make: *** [Makefile:163: all] Error 2
> ```
> 
> I've searched around, but no luck here...

It seems that it's a bug in Android NDK for Linux. I rebuilt everything in MacOS then it worked.

**Comment by franz** [comment]
@FreemanX 

> Is the Kernel launch latency too high compared to other smartphones

Hard to tell without knowing what exactly is that measured "latency" - is it worst case ? average ? and how is it measured. FYI pocl's CPU driver does extra compilation on the first clEnqueueNDRange() of a kernel, unless it finds the compiled binary of the kernel in the pocl cache. Anyway i wouldn't put much trust in numbers coming out of clpeak (see pocl's FAQ on why).

**Comment by isuruf** [comment]
For the linker problem, I raised the issue about using `lld` library (not the executable) in https://github.com/pocl/pocl/pull/708#issuecomment-480241119, but there was not much interest.
If there's interest, I can revive that work and send a PR.

**Comment by FreemanX** [comment]
> For the linker problem, I raised the issue about using `lld` library (not the executable) in [#708 (comment)](https://github.com/pocl/pocl/pull/708#issuecomment-480241119), but there was not much interest.
> If there's interest, I can revive that work and send a PR.

That would be great. A standalone libOpenCL.so which can work everywhere with no extra runtime dependency would be perfect in my use case. https://github.com/pocl/pocl/blob/master/lib/CL/devices/common.c#L200-L208 invokes libclang for linking. But libclang eventually invokes external executables with absolute path( same as the path when compiling pocl). That causes problems in cross-compiling or just put libOpenCL.so to another machine. clang and ld executables may not be in that exact path in the runtime environment or may not exist at all(Android).

**Comment by isuruf** [comment]
@pjaaskel, @franz, what do you think? I can add linking to LLD libraries optionally, but let me know if you think it's useful or not.

**Comment by pjaaskel** [comment]
Yes, it would be definitely useful and make the build faster, perhaps allow it finally completely happen in-memory.

**Comment by pjaaskel** [comment]
I think this issue is solved, if someone can improve the linker situation, a pull request is then needed.

**Comment by Saikatsaha1996** [comment]
> I can now execute OpenCL kernels with pocl. Here's the output of clpeak:
> 
> ```
> Platform: Portable Computing Language
>   Device: pthread-0x803
>     Driver version  : 1.6-pre master-0-g07e70ca6 (Android)
>     Compute units   : 8
>     Clock frequency : 1766 MHz
> 
>     Global memory bandwidth (GBPS)
>       float   : 13.25
>       float2  : 12.94
>       float4  : 10.85
>       float8  : 10.09
>       float16 : 10.32
> 
>     Single-precision compute (GFLOPS)
>       float   : 5.21
>       float2  : 10.39
>       float4  : 20.54
>       float8  : 36.42
>       float16 : 55.13
> 
>     Half-precision compute (GFLOPS)                                                                                                                                      
>       half   : 5.20
>       half2  : 10.37
>       half4  : 20.63
>       half8  : 40.06
>       half16 : 69.66
> 
>     Double-precision compute (GFLOPS)
>       double   : 5.20
>       double2  : 10.37
>       double4  : 18.55
>       double8  : 28.23
>       double16 : 30.08
> 
>     Integer compute (GIOPS)
>       int   : 11.35
>       int2  : 11.39
>       int4  : 20.94
>       int8  : 33.07
>       int16 : 45.41
>     Transfer bandwidth (GBPS)
>       enqueueWriteBuffer         : 7.49
>       enqueueReadBuffer          : 8.00
>       enqueueMapBuffer(for read) : 2490.12
>       memcpy from mapped ptr   : 8.17
>       enqueueUnmap(after write)  : 5347.32
>       memcpy to mapped ptr     : 8.23
> 
>     Kernel launch latency : 144.00 us
> ```
> 
> Is the Kernel launch latency too high compared to other smartphones in https://github.com/krrishnarraj/clpeak/tree/master/results/Portable_Computing_Language ? (144.00 us vs less than 10 us)
> 
> For solving the linking phase problem, I give up using libLLVM and libclang... I compile the ld executable from https://android.googlesource.com/toolchain/binutils/ and use it for linking porcess(from .o to .so). My workaround code in lib/CL/devices/common.c:
> 
> ```
>   //error = pocl_invoke_clang (device, cmd_line);
>   pid_t pid = fork();
>   if (pid == 0){
>           /* Redirect ld process. Modified*/
>           char *cmd_line_ld[16] = {"/data/local/tmp/pocl/ld", "-o", tmp_module, tmp_objfile, "-shared", NULL}; // with -nostartfiles, ld can’t produce .so file
>           execv(cmd_line_ld[0], cmd_line_ld);
>           exit(0);
>   }else{
>   wait(NULL);
>   if (error)
>     {
>       POCL_MSG_PRINT_LLVM ("Linking kernel.so.o -> kernel.so has failed\n");
>       goto FINISH;
>     }
>     ...
>   } // fork() else
> ```
> 
> Also, dlopen with **RTLD_NOW** flag will cause error:
> 
> ```
> dlopen failed: "/data/local/tmp/cache/NF/FBJFLNJOFPAGMBOPGFBMLFHPGAMMFCMANIKAJ/vecAdd/128-1-1-goffs0-smallgrid/vecAdd.so": W + E load segments are not allowed
> ```
> 
> This error is caused by Android OS security update since Android O. Therefore, I make change to this line in lib/CL/devices/common.c:
> 
> ```
> ci->dlhandle = dlopen (module_fn, RTLD_LAZY | RTLD_LOCAL);  //ci->dlhandle = dlopen (module_fn, RTLD_NOW | RTLD_LOCAL);
> ```
> 
> **Unsolved problems:**
> 
> 1. Cannot statically link libLLVM and libCLang. I have to build dynamic libraries and `export LD_LIBRARY_PATH` every time in Android shell.
> 2. Not sure if there's better solution for linking phase...
> 
> **Other source code modifications made for Android build**
> 
> 1. lib/CL/pocl_cq_profiling.c : add `#include <strings.h>`
> 2. lib/CL/devices/pthread/pthread_scheduler.c:
> 
> ```
>        //pthread_setaffinity_np (td->thread, sizeof (cpu_set_t), &set);
>        sched_setaffinity(td->thread, sizeof (cpu_set_t), &set);
> ```
> 
> 3. hardcoded cache path in lib/CL/pocl_cache.c:
> 
> ```
> const char *tmp_path = pocl_get_string_option ("POCL_CACHE_DIR", "/data/local/tmp/cache/");
> ```
> 
> Build with Android ndk_r17b. Android (4691093 based on r316199) clang version 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55536e7d904e0abae47888fc7f) (https://android.googlesource.com/toolchain/llvm 34361f192e41ed6e4e8f9aca80a4ea7e9856f327) (based on LLVM 6.0.2svn)

Can you help me how can I solve this error?




pocl/lib/CL/devices/pthread/pthread_scheduler.c:550:11: error: implicit declaration of function 'pthread_setaffinity_np' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          pthread_setaffinity_np (td->thread, sizeof (cpu_set_t), &set));
          ^
1 error generated.

**Comment by jansol** [comment]
@Saikatsaha1996 the solution is right there in the comment you quoted... under "Other source code modifications"

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 the solution is right there in the comment you quoted... under "Other source code modifications"

![Screenshot_2022-05-05-17-50-05-139_com termux](https://user-images.githubusercontent.com/72664192/166929862-5c7d2edd-b705-419e-8395-18ee7f13c38e.jpg)



Which codes I should change ?

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 the solution is right there in the comment you quoted... under "Other source code modifications"

After changing this codes
       //pthread_setaffinity_np (td->thread, sizeof (cpu_set_t), &set);
       sched_setaffinity(td->thread, sizeof (cpu_set_t), &set);


Getting error

![Screenshot_2022-05-05-18-57-51-935_com termux](https://user-images.githubusercontent.com/72664192/166934023-055d611b-e40a-4f21-9862-cd84297c45a6.jpg)
![Screenshot_2022-05-05-19-00-42-306_com termux](https://user-images.githubusercontent.com/72664192/166934048-62b00e94-6a60-4387-b8a1-420efea39ec5.jpg)

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 the solution is right there in the comment you quoted... under "Other source code modifications" @jansol  help wanted !

This problem solved missing one ")"
sched_setaffinity(td->thread, sizeof (cpu_set_t), &set));

But getting new error 

![Screenshot_2022-05-05-19-13-29-642_com termux](https://user-images.githubusercontent.com/72664192/166937370-48e40c9a-3651-4d3e-a664-16704f283d43.jpg)

**Comment by jansol** [comment]
@Saikatsaha1996 if you don't really need poclcc you can disable it in the build options. It should probably be disabled by default or have at least some heuristic to disable it if the OpenCL library that poclcc is being built against does not support clCreateProgramWithIL.

Or you could try updating the version of ocl-icd  that you are building against to one that defines that function.

**Comment by isuruf** [comment]
If you are using a glibc based aarch64 distro on your android, I'd recommend using [Miniforge](https://github.com/conda-forge/miniforge) and then using `conda install pocl-cuda` to install a pre-built binary.

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 if you don't really need poclcc you can disable it in the build options. It should probably be disabled by default or have at least some heuristic to disable it if the OpenCL library that poclcc is being built against does not support clCreateProgramWithIL.
> 
> Or you could try updating the version of ocl-icd that you are building against to one that defines that function.

@jansol 
How to disable this program with cmake option ?

clCreateProgramWithIL

**Comment by Saikatsaha1996** [comment]
> `__android_log_print` [is provided by the android 'log' library](https://stackoverflow.com/questions/4455941/undefined-reference-to-android-log-print) which needs to be added to the list of libraries to link on android.
> 
> The signal handler stuff is defined in `lib/CL/devices/signal_handlers.c` which is only added to the list of sources to be compiled when targeting Linux. Not sure if it would work as-is on Android or if the code trying to call it needs to be disabled in Android builds.

I am trying with

LDFLAGS="-L$/system/lib64 -llog -lz"

Same problem

**Comment by Saikatsaha1996** [comment]
> 
@jansol which code I should change for 
```
undefined reference to pocl_install_sigusr2_handler
undefined reference to pocl_install_sigfpe_handler
```

In here lib/CL/devices/signal_handlers.c which code I should change please help..

**Comment by jansol** [comment]
The code that references those functions should not be built when targeting android. If it is missing an `#ifdef` guard, please add one in the appropriate locations and open a pull request with that change.
