### ISSUE TITLE
subdevice tests fail on (virtual) single-core CPUs

### ISSUE THREAD

**Issue by anbe42** [pocl/pocl#811]
Subdevice creation obviously requires multiple CUs, but if only a single CU is available the test should not fail but rather be skipped.
Test in CMake can have the `SKIP_RETURN_CODE` property. Setting this is useful, if only the test itself can decide whether it can run. Unfortunately this does not work if the test is created with the `add_test_pocl()` macro, only with CMake's `add_test()`. The 'canonical' return code for 'skip' is 77 as it is used by the autotools test framework.

This issue was discovered while making pocl build on Debian GNU/hurd (which needed a small include fix: https://salsa.debian.org/opencl-team/pocl/-/blob/master/debian/patches/hurd.patch) because the virtual machine used for building only had a single core.

I fixed it for Debian by going back to `add_test()` and setting  `SKIP_RETURN_CODE 77`:
https://salsa.debian.org/opencl-team/pocl/-/blob/master/debian/patches/skip-subdevice-tests-on-single-core-cpus.patch
but it would be great if `add_test_pocl()` would support this, too.

**Comment by pjaaskel** [comment]
Was this fixed appropriately in upstream?
