### ISSUE TITLE
Distributing pocl built with cuda

### ISSUE THREAD

**Issue by isuruf** [pocl/pocl#820]
I'd like to build pocl with cuda and distribute it, but would like it to work in machines without cuda with just pthread device. This doesn't work atm because of library not found (`libcuda.so.1`) issues.

What do you think about the following proposal?

1. Create a new library out of `lib/CL/devices/cuda` to `lib/pocl/libpocl-cuda.so`
2. dlopen this library and use the `pocl_cuda_init_device_ops` function.

**Comment by pjaaskel** [comment]
@jrprice any suggestions?

**Comment by pjaaskel** [comment]
We've discussed previously a more generic mechanism for this for distribution purposes, which would add the additional indirection. Your proposal sounds along the lines and does make sense. It could even make sense for 'pthread' so it would be enabled only if libpthread is found.

**Comment by jrprice** [comment]
Yes, dynamically loading the device libraries via `dlopen` sounds sensible to me.

**Comment by franz** [comment]
Another option is to dlopen libCUDA in the "probe" callback and have all CUDA functions as pointers resolved by dlsym. Whatever you find easier to get working
