### ISSUE TITLE
Missed optimizations after unrolling loops

### ISSUE THREAD

**Issue by isuruf** [pocl/pocl#825]
I'm running the GEMM kernel from SHOC benchmark at https://github.com/vetter/shoc/blob/0aea03beba2f09fcb5935cc11737372fe4de9ec0/src/opencl/level1/gemm/gemmN.cl

There are private memory blocks like https://github.com/vetter/shoc/blob/0aea03beba2f09fcb5935cc11737372fe4de9ec0/src/opencl/level1/gemm/gemmN.cl#L69

After unrolling the `i` loops, pocl misses the fact that these private memory blocks are indexed using constant values, that they don't need to be an array and that they can live in registers.

If I compile the kernel using clang with `-O1` I get the same behaviour. If I compile using clang with `-O2`, this optimization is applied.

**Comment by pjaaskel** [comment]
I suppose this affects only CUDA? So, for some reason the standard optimizations of LLVM are not ran for CUDA. The optimization you mean is "scalar replacement of aggregates" and it's one of the standard optimizations in LLVM, thus it needs to be investigated why they are not ran for CUDA.

**Comment by isuruf** [comment]
I see the same issue with pthread device.

**Comment by isuruf** [comment]
I dumped the LLVM IR at https://github.com/pocl/pocl/blob/master/lib/CL/pocl_llvm_build.cc#L605 and here's the output, https://gist.github.com/isuruf/6e597a8ebffac18e061edd298451b84e#file-pocl_gemmn-ll-L62-L63
For the CUDA device I checked the PTX generated.

**Comment by pjaaskel** [comment]
You should take a look at the parallel.bc, it's the final one going into codegen. We don't optimize aggressively in the frontend call on purpose for making life easier for the work-group passes etc. this is why you see not fully optimized code coming out from the frontend (that is called in *build.cc).

In developing the compiler, these envs are useful:

POCL_CACHE_DIR
POCL_DEBUG_LLVM_PASSES    (needs LLVM built with Debug on)
POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES

http://portablecl.org/docs/html/using.html#tuning-pocl-behavior-with-env-variables

**Comment by isuruf** [comment]
Thanks. I ran `program.bc` through `llvm-dis` to get the LLVM IR and here it is, https://gist.github.com/isuruf/0c7c76627896496eed870a9bd1a927c6#file-pocl_gemmn2-ll-L62-L63

I still see the same issue.

**Comment by isuruf** [comment]
Ah, you meant `parallel.bc`. Where is that stored?

**Comment by isuruf** [comment]
Found it. Here's the LLVM IR after running it through `llvm-dis`. https://gist.github.com/isuruf/eb662bfce76d3be4b788c46864648db0#file-pocl_gemmn3-ll-L67-L68. Same issue.

**Comment by pjaaskel** [comment]
OK. Seems like an unfortunate "phase ordering" problem: it applies the work-item loops before the SRoA and then it doesn't apply anymore.  You can try to increase the optimization level in one of the places and see if we can find a way to better optimize it before the work-group function generation to avoid this type of cases.

For PTX this should not apply as it doesn't add the WI loops, but I do not know if it currently runs the standard optimizations either.

**Comment by isuruf** [comment]
For PTX, the standard optimizations are indeed applied. I checked that the program reached https://github.com/pocl/pocl/blob/master/lib/CL/pocl_llvm_wg.cc#L430-L438 and printing the LLVM module before and after tells me that only one of the the two arrays are replaced by scalar. Not sure why one of them is not replaced.

**Comment by pjaaskel** [comment]
OK, there LLVM pass debug printouts might help. Maybe there's a sensible reason.

**Comment by isuruf** [comment]
I get the following. IR before and after are at https://gist.github.com/isuruf/e5c2c24718e4636dadfb97a577248d68
```
SROA alloca:   %c = alloca [16 x float], align 4
  Rewriting FCA loads and stores...
Can't analyze slices for alloca:   %c = alloca [16 x float], align 4
  A pointer to this alloca escaped by:
    %.pre.pre.1 = load float, float* %arrayidx950.phi.trans.insert.phi.trans.insert.1, align 4, !tbaa !19
```

I'm not sure why this happens. If I manually edit the OpenCL kernel to not have an array, it works and I get a 167% performance boost for SHOC GEMM benchmark. I looked at a few benchmarks that have bad performance in http://portablecl.org/cuda-backend.html and they have these array blocks in them.

cc @jrprice

**Comment by isuruf** [comment]
459d0bb5241a62af3b5b607a65dcf5e9a34a01ee fixed the issue
