### ISSUE TITLE
NULL is not defined for OpenCL kernels (use of undeclared identifier 'NULL')

### ISSUE THREAD

**Issue by joanbm** [pocl/pocl#831]
It appears that the macro `NULL` is not defined when building OpenCL kernels. Building this simple program on pocl:

```
__kernel void test(__global int *ptr) {
    if (ptr != NULL)
        *ptr = 123;
}
```

Fails with `CL_BUILD_PROGRAM_FAILURE` and the build log:
```
error: /home/zealcharm/.cache/pocl/kcache/tempfile-c6-2e-ed-9e-fd.cl:1:51:
use of undeclared identifier 'NULL'
```

Reproduced on:
* OpenCL 1.2 pocl 1.2 None+Asserts, LLVM 6.0.1, SLEEF, DISTRO, POCL_DEBUG
* OpenCL 1.2 pocl 1.6-pre master-0-g459d0bb5, Release, LLVM 10.0.0, RELOC, SPIR, SPIR-V, SLEEF, POCL_DEBUG
* OpenCL 1.2 pocl 1.5, Release, LLVM 10.0.0, RELOC, SPIR, SLEEF, POCL_DEBUG

On the other hand, at least on both NVIDIA (`OpenCL 1.2 CUDA 10.2.95`) and Intel (`intel-compute-runtime 20.18.16699`), NULL is defined and the program build correctly.

I can't find much information, but at least on the OpenCL C specification, some examples use `NULL`, so I assume it's expected to be defined (by default and without any header, like `printf` is). At best it would be good to have this clarified since I assume that a lot of kernels rely on `NULL` being defined.

The following works as a workaround:
```
#ifndef NULL
#define NULL 0L
#endif
```

Here's a full standalone program for replicating this behavior:
```
#define CL_HPP_TARGET_OPENCL_VERSION 120
#define CL_HPP_MINIMUM_OPENCL_VERSION 120
#define CL_HPP_ENABLE_EXCEPTIONS
#include <CL/cl2.hpp>

#include <iostream>
#include <cstdlib>
#include <algorithm>
#include <string>

int main() {
    try {
        std::vector<cl::Platform> platforms;
        cl::Platform::get(&platforms);
        if (platforms.empty()) {
            std::cerr << "No OpenCL platforms found\n";
            return EXIT_FAILURE;
        }

        
        auto platformit = std::find_if(platforms.begin(), platforms.end(), [](cl::Platform &platform) {
            return platform.getInfo<CL_PLATFORM_NAME>() == "Portable Computing Language";
        });
        if (platformit == platforms.end())
            std::cout << "POCL platform not found, using " << platforms[0].getInfo<CL_PLATFORM_NAME>() << "\n";
        auto platform = platformit != platforms.end() ? *platformit : platforms[0];

        std::vector<cl::Device> devices;
        platform.getDevices(CL_DEVICE_TYPE_ALL, &devices);
        if (devices.empty()) {
            std::cerr << "No OpenCL devices found\n";
            return EXIT_FAILURE;
        }
        cl::Device device = devices[0];
        cl::Context context({device});

        cl::Program program(context, "__kernel void test(__global int *ptr){ if (ptr != NULL) *ptr = 123; }");
        try {
            program.build({device});
        } catch (const cl::Error &ex) {
            if (ex.err() == CL_BUILD_PROGRAM_FAILURE) {
                std::cerr << "Build log:\n" << program.getBuildInfo<CL_PROGRAM_BUILD_LOG>(device) << "\n";
            }
            throw;
        }
    } catch (const cl::Error &ex) {
        std::cerr << "OpenCL Error: " << ex.what() << " (code " << ex.err() << ")\n";
        return EXIT_FAILURE;
    }

    std::cout << "OK\n";
    return EXIT_SUCCESS;
}
```

**Comment by joanbm** [comment]
It looks like #defining NULL in one of the common kernel headers (`_kernel.h`, `_kernel.c.h`, `pocl_types.h`?) should be enough.

**Comment by AlexeySachkov** [comment]
Hi, @joanbm,

Actually, I think that this is not a bug and everything is correct here:

There is no mention of `NULL` in OpenCL C part of OpenCL 1.2 specification [link](https://www.khronos.org/registry/OpenCL/specs/opencl-1.2.pdf)

OpenCL C is based on C, where `NULL` is just implementation-defined macro, which declared **not** by the compiler, but defined in some standard headers [cppreference](https://en.cppreference.com/w/c/types/NULL), which are not available in OpenCL C mode (per the spec)

OpenCL C 2.0, in turn, explicitly documents `NULL` macro and uses it in code examples [link](https://www.khronos.org/registry/OpenCL/specs/2.2/pdf/OpenCL_C.pdf), see section 6.10. Preprocessor Directives and Macros:

> The NULL macro expands to a null pointer constant. An integer constant expression with the value 0, or such an expression cast to type void * is called a null pointer constant

**Comment by joanbm** [comment]
Thanks, I think this clears it then, if NULL is not actually required to be defined by the OpenCL 1.2 standard, which as far as I can tell pocl implements quite strictly. I’m happy that this issue is here pointing to this though, since I expect that a few people may run into this problem due to the main vendors defining this macro.

I’ll close the issue then, thanks for your time and the clarification.
