### ISSUE TITLE
cl::Error on clGetDeviceIDs whith luxmark 3.1 and pocl 1.4

### ISSUE THREAD

**Issue by illwieckz** [pocl/pocl#845]
If I run the [prebuilt luxmark 3.1](https://github.com/LuxCoreRender/LuxMark/releases) on Ubuntu 20.04 that third-party software crashes at startup, printing this on terminal:

```
terminate called after throwing an instance of 'cl::Error'
  what():  clGetDeviceIDs
./luxmark: line 12: 1965133 Aborted                 ./luxmark.bin "$@"
```

I'm running pocl 1.4 from Ubuntu 20.04 repositories when facing this.

I know that luxmark build is old, so there is a little chance the issue is on its side.

On the other hand, the same old luxmark build does not complain at all with other recent OpenCL implementations like AMD-APP 3110.6 (amdgpu-pro 20.20-1089974-ubuntu-20.04) or Mesa/Clover 20.0.8 (libclc-gcn), so there is another little chance the issue is on pocl side.

In case the issue is on pocl side, you may want to know about it.

**Comment by pjaaskel** [comment]
Thanks for reporting. Does your pocl work otherwise for other applications? Can you try with 1.5 or, better, the latest master revision?

**Comment by franz** [comment]
> terminate called after throwing an instance of 'cl::Error'

That seems like luxmark doesn't handle an opencl error returned from pocl. This is definitely a bug in luxmark, and possibly also a bug in pocl. The pocl side is quite possibly the same old problem we had with luxmark before, namely that your pocl and the prebuilt luxmark were built against different c++ library versions. This causes mysteriously looking errors when trying to run. Try running luxmark from console with `POCL_DEBUG=err,warn /usr/bin/luxmark` and see if there's any error message.

**Comment by illwieckz** [comment]
With Ubuntu 21.10 I get a segfault.

```
$ ( export POCL_DEBUG='err,warn' ; ~/.games/home/Benchmarks/luxmark-v3.1/luxmark )
** Final POCL_DEBUG flags: 1800 
[2022-04-15 23:23:18.563860405]POCL: in fn pocl_cache_init_topdir at line 512:
  |     ERROR |  Could not create top directory (/home/illwieckz/.cache/pocl/kcache) for cache. 

Note: if you have proper rights to create that directory, and still get the error, then most likely pocl and the program you're trying to run are linked to different versions of libstdc++ library. 
This is not a bug in pocl and there's nothing we can do to fix it - you need both pocl and your program to be compiled for your system. This is known to happen with Luxmark benchmark binaries downloaded from website; Luxmark installed from your linux distribution's packages should work.
[2022-04-15 23:23:18.563874161]POCL: in fn pocl_init_devices at line 536:
  |     ERROR | CL_DEVICE_NOT_FOUND Cache directory initialization failed** Final POCL_DEBUG flags: 1800 
3326798 Segmentation fault
```

But I noticed installing pocl from repositories brings old llvm9 as deps, and this is probably an old build anyway.

I rebuilt pocl myself and it works: http://luxmark.info/node/9379

So I guess it's either a bug in the way Ubuntu packages pocl, either a c++ library version mismatch

**Comment by illwieckz** [comment]
I close it as what appears to be occurring on a 2 years old build does not look relevant. We can still reopen this issue if it happens again on relevant builds.
