### ISSUE TITLE
Does cross-compile target need "patch" and "xargs"?

### ISSUE THREAD

**Issue by hdyam** [pocl/pocl#860]
I am trying to cross-compile pocl-1.5 for aarch64 target with "ARM Compiler 6.14" (not a gcc cross-compiler).
In the file `pocl-1.5/CMakeList.txt`, I found the code below.

```
find_program(PATCH_EXEC
  NAMES patch${CMAKE_EXECUTABLE_SUFFIX}
  HINTS ENV PATH
)

find_program(XARGS_EXEC
  NAMES xargs${CMAKE_EXECUTABLE_SUFFIX}
  HINTS ENV PATH
)
```

I think patch and xargs are used only at the "host-side" and those are unnecessary at "target-side" for off-line compile mode.
However, for on-line compile mode, the situation is unclear for me.
Is there any case to call patch or xargs from "target-side"?
My aarch64 target uses non-Linux Real-Time OS and doesn't have patch and xargs.
So I want to confirm the necessity of code modification or porting related with patch and xargs.

**Comment by franz** [comment]
AFAICT patch & xargs aren't used even on "host" side, they're only used in the build system (CMake scripts). They're not used by the compiled libpocl at all (you can check that PATCH_EXEC doesn't end up in generated  `config.h`).
