### ISSUE TITLE
Pocl execution time is unstable？

### ISSUE THREAD

**Issue by easonwang27** [pocl/pocl#862]
hi, recently I was using pocl to learn opencl. When I ran opencl routines, I found that the run time api of clBuildProgram was not very stable. In terms of execution time, I printed the time and found that the unstable execution time was in the pocl_write_tempfile function. The fdataysnc function is used. Do you have any test feedback in this regard?

**Comment by pjaaskel** [comment]
Hi, strangely enough, there is a recent duplicate: #861
 I wonder why users are interested in stable runtimes suddenly.
