### ISSUE TITLE
Debugging using GDB yields invalid/corrupt variables

### ISSUE THREAD

**Issue by cederikhoefs** [pocl/pocl#866]
When debugging a simple test kernel with GDB 8.1 on Ubuntu, (basic thread model, the kernel has only one parameter), GDB is neither able to read the right argument values nor the right locals values.

Can anyone reproduce this, or did I miss anything out?

My command for debugging is:

`export POCL_DEBUG=all && export POCL_DEVICES="basic" && export POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES=1 && export POCL_MAX_PTHREAD_COUNT=1 && cd bin && gdb --args ./test`

**Comment by franz** [comment]
On ubuntu 18.04, both ``info args`` and ``info locals`` work as expected on my machine. Can you provide more details on your setup ? LLVM version, where is it installed from, cmake options used to configure pocl, etc.

**Comment by pjaaskel** [comment]
@cederikhoefs  Did you remember to pass the '-g' option to the CL build?

**Comment by cederikhoefs** [comment]
Yes, I pass `-g` as a compilation parameter. I'll be able to publish a test repo to reproduce the faulty debugging some time, maybe you can take a look to it. I'll post a link and my exact setup then.

**Comment by cederikhoefs** [comment]
Build command (newest version cloned from GitHub): `cmake -DCMAKE_BUILD_TYPE=Debug`
`llvm-config --version` -> 6.0.0
`gdb --version` -> GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git

**Comment by cederikhoefs** [comment]
I just created a repo with a simple vector add kernel: [pomockl](https://github.com/cederikhoefs/pomockl.git)
Still, gdb is not able to correctly retrieve variables from the stack:
![gdb](https://user-images.githubusercontent.com/45330554/94148230-a53c2600-fe76-11ea-8998-b3656aca8d11.png)

**Comment by pjaaskel** [comment]
Please try with a newer LLVM. To be clear, -g must be passed to clBuildProgram() in your OpenCL program.

**Comment by cederikhoefs** [comment]
It is being passed in clhelper.cpp: `prog.build({dev}, "-g -cl-opt-disable");`

**Comment by cederikhoefs** [comment]
Sorry, the test repo contained a typo; I just recreated it, now it should work! Thank your for your time, by the way.

**Comment by cederikhoefs** [comment]
Also, I just checked for my LLVM version, and `apt` tells me, it is up-to-date:

make is already the newest version (4.1-9.1ubuntu1).
ocl-icd-dev is already the newest version (2.2.11-1ubuntu1).
ocl-icd-libopencl1 is already the newest version (2.2.11-1ubuntu1).
ocl-icd-opencl-dev is already the newest version (2.2.11-1ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu2).
zlib1g is already the newest version (1:1.2.11.dfsg-0ubuntu2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2).
clinfo is already the newest version (2.2.18.03.26-1).
dialog is already the newest version (1.3-20171209-1).
libhwloc-dev is already the newest version (1.11.9-1).
ninja-build is already the newest version (1.8.2-1).
apt-utils is already the newest version (1.6.12ubuntu0.1).
cmake is already the newest version (3.10.2-1ubuntu2.18.04.1).
git is already the newest version (1:2.17.1-1ubuntu0.7).
clang is already the newest version (1:6.0-41~exp5~ubuntu1).
libclang-dev is already the newest version (1:6.0-41~exp5~ubuntu1).
llvm is already the newest version (1:6.0-41~exp5~ubuntu1).

**Comment by pjaaskel** [comment]
Yes, but 6.0 is rather old already and this can be fixed in later versions and thus might be an LLVM issue not pocl's.

**Comment by cederikhoefs** [comment]
Cool, I'll then try to build it myself. Is LLVM 12 already supported?

**Comment by pjaaskel** [comment]
No, but 11 should be in master.

**Comment by cederikhoefs** [comment]
I just updated LLVM to 11, and first of all: I had to remove `-dwarf-column-info` as a parameter when using `-g` in pocl_build.c to even be able to use pocl, and still, I can't get debugging to work. Tomorrow, I'll try on a different machine, but is there anything else you'd recommend me to try?

**Comment by pjaaskel** [comment]
I think the issue you mentioned was fixed in yesterday's push. LLVM 11 is still unreleased and will be supported in the next pocl 1.6 release. If it doesn't work for you then it doesn't.

**Comment by cederikhoefs** [comment]
With a freshly pulled pocl repo, LLVM 11 works perfectly. Stil, however, neither GDB nor LLDB seem to be able to resolve variables in kernel code correctly...

**Comment by pjaaskel** [comment]
OK. This could be simply an unimplemented feature of not retaining the debug info of the kernel args across the kernel compiler transformations which recreates the kernel function to make it a WG function. It seems to show the local private 'idx' variable right, which is not for granted since those are transferred to array of values (one copy for each WI) in the WG-func transformation. 

BTW what is the text mode debugger UI you use? Seems nice.

**Comment by pjaaskel** [comment]
When you single step, does the debugger step through the kernel multiple times, once for each WI?

**Comment by InterplanetaryEngineer** [comment]
Can replicate using 
OpenCL 1.2 pocl 1.6-pre master-0-g984525e1, Debug+Asserts, LLVM 10.0.1, RELOC, SPIR, SLEEF, POCL_DEBUG
(I could not try the most recent git version of pocl, as building that currently errors with 
```
/usr/bin/ld: CMakeFiles/poclcc.dir/__/lib/poclu/misc.c.o: in function `poclu_load_program_multidev':
pocl-master/lib/poclu/misc.c:399: undefined reference to `clCreateProgramWithIL'
```
for me, but that is unrelated to this issue)

Is no one else having this issue?

**Comment by cederikhoefs** [comment]
The GDB UI is called [GDB dashboard](https://github.com/cyrus-and/gdb-dashboard). I'll examine the idx variable for another call rather than the first one, and then show you the results.

**Comment by cederikhoefs** [comment]
It turns out that idx / get_global_id(0) is just 0 by chance and equal throughout all calls of the kernel.

**Comment by InterplanetaryEngineer** [comment]
Can replicate using 
OpenCL 1.2 pocl 1.6-pre master-0-g984525e1, Debug+Asserts, LLVM 10.0.1, RELOC, SPIR, SLEEF, POCL_DEBUG
(I could not try the most recent git version of pocl, as building that currently errors with 
```
/usr/bin/ld: CMakeFiles/poclcc.dir/__/lib/poclu/misc.c.o: in function `poclu_load_program_multidev':
pocl-master/lib/poclu/misc.c:399: undefined reference to `clCreateProgramWithIL'
```
for me, but that is unrelated to this issue)

**Comment by pjaaskel** [comment]
The kernel is not called multiple times, but its contents looped over for each WI so you might test this by setting a break point to the line. But OK, the debugging support needs more work.

**Comment by pjaaskel** [comment]
@cederikhoefs Can you test if this is now fixed in the 1.6 branch?

**Comment by cederikhoefs** [comment]
@pjaaskel Unfortunately, only this weekend, I'm sorry. I'll report when I've done it.

**Comment by pjaaskel** [comment]
OK, hopefully it works now. Please reopen or create a new issue if there are still problems. Getting close to release 1.6.
