### ISSUE TITLE
Query regarding executing accel_example 

### ISSUE THREAD

**Issue by shv123** [pocl/pocl#867]
I want to run accel_example to test the example custom accelerator. I am not able to figure out the steps in order to generate the accelerator. According to the TCE Manual, I need to run the generateprocessor in the CLI. How do I do this? 

Any help is appreciated. Thanks.

PS : Trying to build TCE is giving me an error

**Comment by pjaaskel** [comment]
Answered in emails/privately, the current issue cannot be reproduced locally, thus likely a Xilinx FPGA tooling issue.
