### ISSUE TITLE
create_image's implementation

### ISSUE THREAD

**Issue by harishch4** [pocl/pocl#871]
[create_image](https://github.com/pocl/pocl/blob/984525e16cd54732363f1ba147bea14a8877714b/lib/CL/devices/basic/basic.c#L111)'s implementation in basic device is NULL. What this method supposed to do?.
 I can see it is being called in [clCreateImage](https://github.com/pocl/pocl/blob/984525e16cd54732363f1ba147bea14a8877714b/lib/CL/clCreateImage.c#L211), does it mean images doesn't work in basic? 

And out of context question, does pocl is tested against [OpenCL-CTS](https://github.com/KhronosGroup/OpenCL-CTS)?

**Comment by franz** [comment]
> create_image's implementation in basic device is NULL

If you're talking about ``dev->ops->create_image``, that's a driver callback and it's optional (it's NULL for every driver in git master).

> does it mean images doesn't work in basic?

They should work with both pthread and basic drivers. Other drivers don't implement images ATM.

> pocl tested against OpenCL-CTS

Yes it is (the pthread driver). I don't run the full test regularly since it's very time consuming, but there is are several ctest labels to run smaller subsets of CTS tests, and i usually run the whole CTS before pocl release.

**Comment by harishch4** [comment]
> > create_image's implementation in basic device is NULL
> 
> If you're talking about `dev->ops->create_image`, that's a driver callback and it's optional (it's NULL for every driver in git master).
> 
Does  any other branch has this implementation?

> > pocl tested against OpenCL-CTS
> 
> Yes it is (the pthread driver). I don't run the full test regularly since it's very time consuming, but there is are several ctest labels to run smaller subsets of CTS tests, and i usually run the whole CTS before pocl release.

OpenCL-CTS's [samplerlessReads](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/images/samplerlessReads) is falling for basic device. 
Attaching logs for your reference.  [samplerlessReads_results.log](https://github.com/pocl/pocl/files/5254960/samplerlessReads_results.log)

**Comment by franz** [comment]
.... to be more specific, i test CTS on Linux + x86-64 AVX2 cpu; it's very unlikely to pass CTS on anything other than that combination.

We have documentation on conformance status [here](https://github.com/pocl/pocl/blob/master/doc/sphinx/source/conformance.rst); though slightly dated, it has more details & also lists some issues related to CTS.

> Does any other branch has this implementation?

not a public one, but like i said, it's not relevant to CPU image support.

> OpenCL-CTS's samplerlessReads is falling for basic device

I've just tested it on Ryzen and it passes with both pthread and basic:

> PASSED 155 of 155 tests.

Your log says:

> FAILED 31 of 186 sub-tests.

which branch of OpenCL-CTS are you using ? we only test against 1.2 branch.

**Comment by harishch4** [comment]
> 
> Your log says:
> 
> > FAILED 31 of 186 sub-tests.
> 
>which branch of OpenCL-CTS are you using ? we only test against 1.2 branch.

I guess you are correct, I'm using [master](https://github.com/KhronosGroup/OpenCL-CTS) branch for testing. I've created a pull request [#872 ](https://github.com/pocl/pocl/pull/872) which will fix the issue while testing with master branch.
