### ISSUE TITLE
pocl on FreeBSD fails with 'Undefined symbol "clGetPlatformInfo"'

### ISSUE THREAD

**Issue by Orum** [pocl/pocl#877]
I'm seeing a problem identical to the one [reported here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241482) when I try to use pocl on FreeBSD.  I haven't been able to test v1.3 (which supposedly works, but I've yet to get it to build successfully on FreeBSD), but I did test 1.5 in addition to 1.4, and it's an issue with both.

Figured I should report it here as you may not be aware of it.

**Comment by pjaaskel** [comment]
Please retry if you can still reproduce this with the latest master revision and/or the latest LLVM.

**Comment by Orum** [comment]
Thanks.  I can confirm that the issue still occurs on the latest master.

**Comment by isuruf** [comment]
Can you try changing `RTLD_NOW` in https://github.com/pocl/pocl/blob/6b874f7450e77d8c8f1c66c3e6939d7bc102bc92/lib/CL/devices/common.c#L1085 to `RTLD_LAZY`?

**Comment by Orum** [comment]
Just gave that a try, but no change.

**Comment by lherschi** [comment]
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241482
I have also provided a patch there.

**Comment by Orum** [comment]
I know that was meant for an older version, but after applying it by hand to the current master, it's working perfectly for me.  Thank you!
