### ISSUE TITLE
Can't build on NVIDIA Jetson (aarch64 / Ubuntu Bionic / CUDA)

### ISSUE THREAD

**Issue by znmeb** [pocl/pocl#888]
I've got an NVIDIA Jetson AGX Xavier development kit and I'm trying to compile POCL 1.6 RC1 on it. The hardware is an 8-core `aarch64` CPU with an NVIDIA CUDA-compatible GPU. The OS is Ubuntu Bionic for `arm64` with most of the NVIDIA tools, including CUDA 10.2.

The most recent LLVM / CLANG available is 10, so that's what I've installed. The `cmake` step is throwing an error:

```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_WARN_INCOMPATIBLE_POINTER_TYPES
-- Performing Test HAVE_WARN_INCOMPATIBLE_POINTER_TYPES - Success
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- No git and/or not a prerelease -> not adding git commit to version.
-- Host CPU cores: 8
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'hwloc'
--   Found hwloc, version 1.11.9
-- Found Hwloc: hwloc
-- Found hwloc 1.11.9 in :hwloc
-- Hwloc_VERSION 1.11.9
-- Hwloc_LDFLAGS -lhwloc
-- Hwloc_CFLAGS
-- L1D Cacheline size detected: 64
-- Using llvm-config: /usr/bin/llvm-config-10
-- LLVM binaries suffix : -10
-- llvm-config's LLVM_PREFIX is: /usr/lib/llvm-10
-- llvm-config's LLVM_VERSION_FULL is: 10.0.0
-- LLVM_VERSION: 10.0
-- llvm-config's LLVM_CFLAGS is: -I/usr/lib/llvm-10/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- llvm-config's LLVM_CXXFLAGS is: -I/usr/lib/llvm-10/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- llvm-config's LLVM_CPPFLAGS is: -I/usr/lib/llvm-10/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- llvm-config's LLVM_LDFLAGS is: -L/usr/lib/llvm-10/lib
-- llvm-config's LLVM_BINDIR is: /usr/lib/llvm-10/bin
-- llvm-config's LLVM_LIBDIR is: /usr/lib/llvm-10/lib
-- llvm-config's LLVM_INCLUDEDIR is: /usr/lib/llvm-10/include
-- llvm-config's LLVM_SRC_ROOT is: /usr/lib/llvm-10/build/
-- llvm-config's LLVM_OBJ_ROOT is: /usr/lib/llvm-10/build/
-- llvm-config's LLVM_ALL_TARGETS is: AArch64 AMDGPU ARM BPF Hexagon Lanai Mips MSP430 NVPTX PowerPC RISCV Sparc SystemZ WebAssembly X86 XCore AVR
-- llvm-config's LLVM_HOST_TARGET is: aarch64-unknown-linux-gnu
-- llvm-config's LLVM_BUILD_MODE is: RelWithDebInfo
-- llvm-config's LLVM_ASSERTS_BUILD is: OFF
-- llvm-config's LLVM_SYSLIBS is:
-- llvm-config's LLVM_HAS_RTTI is: YES
-- llvm-config's LLVM_LIBS is: -lLLVM-10
-- llvm-config's LLVM_SYSLIBS is:
-- Found clang: /usr/lib/llvm-10/bin/clang-10
-- Found clang++: /usr/bin/clang++-10
-- Found opt: /usr/bin/opt-10
-- Found llc: /usr/bin/llc-10
-- Found llvm-as: /usr/bin/llvm-as-10
-- Found llvm-link: /usr/bin/llvm-link-10
-- Found lli: /usr/bin/lli-10
-- udivmodti4 compiles without extra flags
-- Checking if clang++ works (required by vecmathlib)
-- Checking if LLVM is a DEBUG build
-- DEBUG build
-- Find out LLC target triple (for host aarch64-unknown-linux-gnu)
-- Find out LLC host CPU with /usr/bin/llc-10
-- Autodetected CPU (unknown) overriden by user to aarch64
-- Checking clang -march vs. -mcpu flag
CMake Error at cmake/LLVM.cmake:731 (message):
  Could not determine whether to use -march or -mcpu with clang
Call Stack (most recent call first):
  CMakeLists.txt:459 (include)


-- Configuring incomplete, errors occurred!
See also "/usr/local/src/pocl-1.6-RC1/build/CMakeFiles/CMakeOutput.log".
The command '/bin/sh -c $SCRIPTS/pocl-cuda.sh #> $LOGS/pocl-cuda.log 2>&1' returned a non-zero code: 1
```

[CMakeOutput.log](https://github.com/pocl/pocl/files/5662909/CMakeOutput.log)

**Comment by franz** [comment]
`-- Autodetected CPU (unknown) overriden by user to aarch64`

This is the problem. Trying clang on my arm64 machine with `aarch64` i get this:

```
root@odroid64:~# /home/LLVM_110/bin/clang --target=aarch64-unknown-linux-gnu -march=aarch64 -o /tmp/test.o -c /tmp/test.c
clang-11: error: the clang compiler does not support '-march=aarch64'
root@odroid64:~# /home/LLVM_110/bin/clang --target=aarch64-unknown-linux-gnu -mcpu=aarch64 -o /tmp/test.o -c /tmp/test.c
clang-11: error: the clang compiler does not support '-mcpu=aarch64'
```

"aarch64" is not a CPU name that LLVM recognizes. As README.ARM in pocl says:

```
* LLVM will likely not recognize your cpu, and running cmake will give you a warning.
  run cmake with -DLLC_HOST_CPU=<yourcpu>. "yourcpu" must be something LLVM recognizes, 
  usually it's simply "cortex-aXX" like cortex-a15 etc. You can get the full list by
  running `llc -mcpu=help`.
```

Some quick googling suggests that the correct CMake option for your system is: `-DLLC_HOST_CPU=carmel`

**Comment by znmeb** [comment]
Well ... partial success. `llc-10 -mcpu=help` doesn't work, but I got `-mcpu=help` to work with LLVM 6. It doesn't list `carmel` so I went with `generic` and it builds.

For future reference, this page has some details on the Tegra line. The two I have are the Jetson Nano and the Jetson AGX Xavier. I haven't tried building `pocl` on the Nano yet but will be testing it later today.

AGX Xavier: https://en.wikipedia.org/wiki/Tegra#Devices_8

Nano: https://en.wikipedia.org/wiki/Tegra#Devices_6

**Comment by franz** [comment]
Apparently with newer LLVMs, you need:
 `llc -mtriple=aarch64-unknown-linux-gnu -mcpu=help`

And `carmel` is only available since LLVM 11. `generic` or `cortex-a53` should work on most 64bit ARM boxes.

**Comment by znmeb** [comment]
> 
> 
> Apparently with newer LLVMs, you need:
> `llc -mtriple=aarch64-unknown-linux-gnu -mcpu=help`
> 
> And `carmel` is only available since LLVM 11. `generic` or `cortex-a53` should work on most 64bit ARM boxes.

Ah ... I think I want generic anyhow. I don't really need OpenCL on the CPU; it's the CUDA piece I'm after in the application(s). There are a couple of R packages I want to run that only have OpenCL code for the GPU.

I have the build working; it passes all 69 of the CUDA tests so I'm about to write some R tests.

**Comment by pjaaskel** [comment]
If CUDA is only what you want, did you notice there's a CMake option 'ENABLE_HOST_CPU_DEVICES' which you can set to OFF so it shouldn't try to build the CPU devices (pthread and basic)? But good that you got it working.

**Comment by znmeb** [comment]
@pjaaskel I'm still testing things - it failed most of the CUDA tests on the Nano but they all work on the AGX Xavier. Is there a minimum GPU compute capability for `pocl`? The Nano is now something like four generations old.

I'll probably set it to GPU-only on the Xavier and CPU-only on the Nano - the R software I'm using it with can detect OpenCL devices.

**Comment by pjaaskel** [comment]
@isuruf might be able to answer that (unless docs answer it), he is the CUDA driver maintainer.

**Comment by isuruf** [comment]
Nano is a Maxwell chip right? I've tried GeForce Titan X and it works fine there. What's the error that you are getting?

**Comment by znmeb** [comment]
@isuruf Yep - it's a Maxwell and the Xavier is a Volta

Here's the first part of the failures - the one it starts after that runs a very long time or maybe forever.

```
running CUDA tests
Using OCL_ICD_VENDORS: /usr/local/src/pocl-1.6-RC1/build/ocl-vendors
Test project /usr/local/src/pocl-1.6-RC1/build
      Start   1: pocl_version_check
 1/69 Test   #1: pocl_version_check ................................................................   Passed    0.07 sec
      Start  26: kernel/test_shuffle_char
 2/69 Test  #26: kernel/test_shuffle_char ..........................................................***Failed  Error regular expression found in output. Regex=[FAIL]  0.65 sec
      Start  27: kernel/test_shuffle_short
 3/69 Test  #27: kernel/test_shuffle_short .........................................................***Failed  Error regular expression found in output. Regex=[FAIL]  0.64 sec
      Start  28: kernel/test_shuffle_ushort
 4/69 Test  #28: kernel/test_shuffle_ushort ........................................................***Failed  Error regular expression found in output. Regex=[FAIL]  0.64 sec
      Start  30: kernel/test_shuffle_int
 5/69 Test  #30: kernel/test_shuffle_int ...........................................................***Failed  Error regular expression found in output. Regex=[FAIL]  0.67 sec
      Start  31: kernel/test_shuffle_uint
 6/69 Test  #31: kernel/test_shuffle_uint ..........................................................***Failed  Error regular expression found in output. Regex=[FAIL]  0.65 sec
      Start  32: kernel/test_shuffle_float
 7/69 Test  #32: kernel/test_shuffle_float .........................................................***Failed  Error regular expression found in output. Regex=[FAIL]  0.64 sec
      Start  33: kernel/test_shuffle_long
 8/69 Test  #33: kernel/test_shuffle_long ..........................................................***Failed  Error regular expression found in output. Regex=[FAIL]  0.65 sec
      Start  34: kernel/test_shuffle_ulong
 9/69 Test  #34: kernel/test_shuffle_ulong .........................................................***Failed  Error regular expression found in output. Regex=[FAIL]  0.66 sec
      Start  36: kernel/test_sizeof_uint
10/69 Test  #36: kernel/test_sizeof_uint ...........................................................   Passed    3.08 sec
      Start  37: kernel/test_shuffle_double
11/69 Test  #37: kernel/test_shuffle_double ........................................................***Failed  Error regular expression found in output. Regex=[FAIL]  0.65 sec
      Start   2: kernel/test_as_type
^C
```

I have the R tests coded and they work on both Jetsons in both the CPU and GPU, so it looks like I can ship with `pocl`! I've got one more piece of coding to do - I want to see if the `stan` OpenCL code works on a Jetson.

**Comment by znmeb** [comment]
[AGX-Xavier-clinfo.txt](https://github.com/pocl/pocl/files/5684047/AGX-Xavier-clinfo.txt)
[Nano-clinfo.txt](https://github.com/pocl/pocl/files/5684049/Nano-clinfo.txt)

Here's the `clinfo` logs for the two devices.

**Comment by isuruf** [comment]
what do you get with `ctest --verbose`?

**Comment by znmeb** [comment]
[cuda_tests_verbose.log](https://github.com/pocl/pocl/files/5684231/cuda_tests_verbose.log)

**Comment by isuruf** [comment]
can you try running,
```
export POCL_DEVICES=CUDA
export OCL_ICD_VENDORS=/usr/local/src/pocl-1.6-RC1/build/
export POCL_BUILDING=1
gdb /usr/local/src/pocl-1.6-RC1/build/tests/kernel/test_shuffle short 
```
and get a backtrace where it is failing?

**Comment by znmeb** [comment]
> 
> 
> can you try running,
> 
> ```
> export POCL_DEVICES=CUDA
> export OCL_ICD_VENDORS=/usr/local/src/pocl-1.6-RC1/build/
> export POCL_BUILDING=1
> gdb /usr/local/src/pocl-1.6-RC1/build/tests/kernel/test_shuffle short 
> ```
> 
> and get a backtrace where it is failing?

Yeah - it'll take a while for me to get `gdb` on the image

It looks like in both machines it's using the "basic" device by default, not the GPU

**Comment by isuruf** [comment]
the error is `CUDA_ERROR_NOT_SUPPORTED: operation not supported`. so it's definitely running on the GPU. Some cuda operations that are not supported on Nano are supported on Xavier. So, we need to figure out which command is throwing this error and figure out if there's a workaround.

**Comment by isuruf** [comment]
can you also run `POCL_DEBUG=1 ctest --verbose` and post the output?

**Comment by znmeb** [comment]
> 
> 
> the error is `CUDA_ERROR_NOT_SUPPORTED: operation not supported`. so it's definitely running on the GPU. Some cuda operations that are not supported on Nano are supported on Xavier. So, we need to figure out which command is throwing this error and figure out if there's a workaround.

OK ... rebuilding the image now

**Comment by isuruf** [comment]
https://github.com/pocl/pocl/pull/890

**Comment by znmeb** [comment]
> export POCL_DEVICES=CUDA
> export OCL_ICD_VENDORS=/usr/local/src/pocl-1.6-RC1/build/
> export POCL_BUILDING=1
> gdb /usr/local/src/pocl-1.6-RC1/build/tests/kernel/test_shuffle short

```
root@3524705308a8:/usr/local/src/pocl-1.6-RC1/build# export POCL_DEVICES=CUDA
root@3524705308a8:/usr/local/src/pocl-1.6-RC1/build# export OCL_ICD_VENDORS=/usr/local/src/pocl-1.6-RC1/build/
root@3524705308a8:/usr/local/src/pocl-1.6-RC1/build# export POCL_BUILDING=1
root@3524705308a8:/usr/local/src/pocl-1.6-RC1/build# gdb /usr/local/src/pocl-1.6-RC1/build/tests/kernel/test_shuffle short
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/src/pocl-1.6-RC1/build/tests/kernel/test_shuffle...done.
/usr/local/src/pocl-1.6-RC1/build/short: No such file or directory.
(gdb) quit
```

**Comment by znmeb** [comment]
> 
> 
> can you also run `POCL_DEBUG=1 ctest --verbose` and post the output?

[verbose-pocl-debug-nano.txt](https://github.com/pocl/pocl/files/5684260/verbose-pocl-debug-nano.txt)

**Comment by isuruf** [comment]
Can you try the change in https://github.com/pocl/pocl/pull/890 ?

**Comment by znmeb** [comment]
> 
> 
> Can you try the change in #890 ?

`git clone https://github.com/isuruf/pocl` then `git checkout cuMemHostRegister`, right?

That's what I'm running now ... takes about 20 minutes on the Nano

**Comment by znmeb** [comment]
```
[545/697] Building C object lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/pocl-cuda.c.o
FAILED: lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/pocl-cuda.c.o
/usr/bin/cc -DCL_TARGET_OPENCL_VERSION=220 -DCL_USE_DEPRECATED_OPENCL_1_0_APIS -DCL_USE_DEPRECATED_OPENCL_1_1_APIS -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_USE_DEPRECATED_OPENCL_2_0_APIS -DCL_USE_DEPRECATED_OPENCL_2_1_APIS -DCUDA_TOOLKIT_ROOT_DIR=\"/usr/local/cuda-10.2\" -Dpocl_devices_cuda_EXPORTS -I../include -I. -I../lib/CL/devices -I../lib/CL/. -I../lib/CL/../llvmopencl -I/usr/local/cuda-10.2/include -I../lib/CL/devices/cuda/../../../llvmopencl -g -fPIC   -Werror=implicit-function-declaration -Wincompatible-pointer-types -MD -MT lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/pocl-cuda.c.o -MF lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/pocl-cuda.c.o.d -o lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/pocl-cuda.c.o   -c ../lib/CL/devices/cuda/pocl-cuda.c
../lib/CL/devices/cuda/pocl-cuda.c: In function 'pocl_cuda_finalize_command':
../lib/CL/devices/cuda/pocl-cuda.c:1389:40: error: 'event->command' is a pointer; did you mean to use '->'?
       cl_kernel kernel = event->command.run.kernel;
                                        ^
                                        ->
../lib/CL/devices/cuda/pocl-cuda.c:1390:48: error: 'event->command' is a pointer; did you mean to use '->'?
       pocl_argument *arguments = event->command.run.arguments;
                                                ^
                                                ->
../lib/CL/devices/cuda/pocl-cuda.c:1392:23: error: 'meta' undeclared (first use in this function); did you mean 'getw'?
       for (i = 0; i < meta->num_args; i++)
                       ^~~~
                       getw
../lib/CL/devices/cuda/pocl-cuda.c:1392:23: note: each undeclared identifier is reported only once for each function it appears in
[546/697] Building C object lib/poclu/CMakeFiles/poclu.dir/cl_half.c.o
[547/697] Building C object bin/CMakeFiles/poclcc.dir/poclcc.c.o
[548/697] Building CXX object lib/CL/CMakeFiles/lib_cl_llvm.dir/pocl_llvm_wg.cc.o
[549/697] Building CXX object lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/pocl-ptx-gen.cc.o
[550/697] Building CXX object lib/CL/CMakeFiles/lib_cl_llvm.dir/pocl_llvm_build.cc.o
ninja: build stopped: subcommand failed.
```

**Comment by znmeb** [comment]
[pocl-cuda.c.txt](https://github.com/pocl/pocl/files/5684325/pocl-cuda.c.txt)

**Comment by isuruf** [comment]
@znmeb, added a new commit. Can you check now?

**Comment by znmeb** [comment]
OK ... running it now

**Comment by znmeb** [comment]
It compiled - all the R stuff worked. It looks like your tests are working too. I'll post a log when it finishes.

**Comment by znmeb** [comment]
[patched-pocl-tests.log](https://github.com/pocl/pocl/files/5685471/patched-pocl-tests.log)

Looks like only one test failed

**Comment by znmeb** [comment]
Same test failed on the Xavier

[test-cuda-xavier.log](https://github.com/pocl/pocl/files/5685586/test-cuda-xavier.log)

**Comment by isuruf** [comment]
Can you try pulling in https://github.com/pocl/pocl/pull/891 too?

**Comment by znmeb** [comment]
> 
> 
> Can you try pulling in #891 too?

OK - what's the `git` command to merge the two pull requests? I'm not a `git` aficionado yet :-)

**Comment by znmeb** [comment]
I think I figured the `git` stuff out - logs attached. There's now another test which passes but the same one still fails.

[pocl-build.log](https://github.com/pocl/pocl/files/5686679/pocl-build.log)
[pocl-git-source.log](https://github.com/pocl/pocl/files/5686680/pocl-git-source.log)
[test-cuda.log](https://github.com/pocl/pocl/files/5686681/test-cuda.log)

**Comment by znmeb** [comment]
You can close this as _fixed in 1.6_.

Final score - 71 tests, all passed!

By the way, if you want my Docker context, let me know. It's a bit different from the way your Docker contexts work because it has to integrate into my end-user image, but it's fully functional on its own.
