### ISSUE TITLE
[1.6 RC1, PPC64le] Building SLEEF to LLVM bitcode host/pwr9/c_sleef_glue_auto.c.bc

### ISSUE THREAD

**Issue by kif** [pocl/pocl#894]
The error is independent of LLVM 10 or 11 but rather related to the change in sleef
```
In file included from /home/kieffer/workspace/pocl/lib/kernel/sleef/libm/sleef_glue_auto.c:3:
/home/kieffer/workspace/pocl/lib/kernel/sleef/include/sleef_cl.h:85:8: error: conflicting types for 'Sleef_sin_u35'
double Sleef_sin_u35 (double);
       ^
/home/kieffer/workspace/pocl/lib/kernel/sleef/include/sleef.h:148:21: note: previous declaration is here
IMPORT CONST double Sleef_sin_u35(double);

```

and many other like this...

**Comment by pjaaskel** [comment]
@isuruf is this power9 specific?

**Comment by isuruf** [comment]
Isn't this the same as https://github.com/pocl/pocl/issues/876 ?

**Comment by pjaaskel** [comment]
True, looks like it.

**Comment by kif** [comment]
I forgot about #876. Indeed it is the same.
I confirm that this bug does not show up on AMD64 (same operating system, debian11 testing )

Apparently there is a difference when defining CONST in:
```
#if (defined(__GNUC__) || defined(__CLANG__)) && !defined(__INTEL_COMPILER)
#define CONST const
#else
#define CONST
#endif
```
`CONST` should equally be equal to `const` on amd64 and on ppc64le
