### ISSUE TITLE
CI on various architectures

### ISSUE THREAD

**Issue by kif** [pocl/pocl#897]
Travis-CI offers AMD64, ARM64 and PPC64le machines for continuous integration. Does it make sense to test POCL on them ? at least the CPU part ?

**Comment by pjaaskel** [comment]
For AMD64 and PPC64 we have maintainers, for ARM we are still lacking one, but otherwise, yes CI is always a good idea so please go ahead and setup for Intel CPU and PowerPC.

**Comment by znmeb** [comment]
> 
> 
> For AMD64 and PPC64 we have maintainers, for ARM we are still lacking one, but otherwise, yes CI is always a good idea so please go ahead and setup for Intel CPU and PowerPC.

Travis does have access to arm64 (AWS Graviton) machines FWIW. But I've been hearing they're shutting down free access for open source projects and a lot of folks are migrating to GitHub actions.

**Comment by franz** [comment]
Pocl currently has Travis CI (though only MacOS X, and it's been quite unmantained), and Drone CI (i try to maintain this one), which has AMD Ryzens and some ARM64 machines (i think Cavium ThunderX).

So x86-64 + ARM64 are already covered by CI. You should be able to get pocl's Travis / Drone CI for your own github account by signing up with them.

PPC / MacOS X would be nice, but someone would have to maintain the CI (which means mainly keeping the LLVM reasonably up2date in those environments).

**Comment by pjaaskel** [comment]
We have setup our own system to test some envs. Maybe adding more later.
