### ISSUE TITLE
Strange type of values when printing variables in gdb

### ISSUE THREAD

**Issue by muks** [pocl/pocl#907]
With locally built pocl-1.6, llvm-11.0.0-1.fc33.x86_64 on Fedora 33, and the following env:

```sh
$ export POCL_MAX_PTHREAD_COUNT=1
$ export POCL_EXTRA_BUILD_FLAGS="-g -cl-opt-disable"
$ export POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES=1
```

Debugging a program under `gdb`, setting a breakpoint on a function within the OpenCL kernel and running the program, here is what I get:

```
Thread 2 "kit" hit Breakpoint 1, KitGPU ()
    at /home/muks/.cache/pocl/kcache/tempfile-a3-e9-6a-31-7c.cl:207
207         const int gid = get_global_id(0);
(gdb) next
208             const unsigned width = config->width;
(gdb) p gid
$1 = {{{0 <repeats 4096 times>}}}
(gdb) 
```

But `gid` is an int here, so why isn't its value printed as an integer? Same with `width`, but if I print `config->width`, I get the right type:

```
(gdb) step
209             const unsigned height = config->height;
(gdb) p width
$2 = {{{1278, 0 <repeats 4095 times>}}}
(gdb) p config->width
$3 = 1278
```

**Comment by franz** [comment]
This is by design. The simplified idea of how pocl deals with workgroups, is 1) it creates a `for (i=0; i < workgroup_size;++i)` loop around the kernel code; 2) the LLVM optimizer then tries to vectorize that loop. For this to work, variables in private address space must be "replicated" for the entire workgroup. IOW one copy is created for each workitem in the workgroup; that's why `gid` is an array.

**Comment by muks** [comment]
Thank you for answering. And it's fair.. I'll get used to looking into the array.

You may want to update the docs at with an explanation, so that it is expected by readers who follow the docs:
http://portablecl.org/docs/html/debug.html#debugging-with-gdb

The example there prints `gid` as an `int` currently.

**Comment by sunshineywz123** [comment]
> With locally built pocl-1.6, llvm-11.0.0-1.fc33.x86_64 on Fedora 33, and the following env:
> 
> ```shell
> $ export POCL_MAX_PTHREAD_COUNT=1
> $ export POCL_EXTRA_BUILD_FLAGS="-g -cl-opt-disable"
> $ export POCL_LEAVE_KERNEL_COMPILER_TEMP_FILES=1
> ```
> 
> Debugging a program under `gdb`, setting a breakpoint on a function within the OpenCL kernel and running the program, here is what I get:
> 
> ```
> Thread 2 "kit" hit Breakpoint 1, KitGPU ()
>     at /home/muks/.cache/pocl/kcache/tempfile-a3-e9-6a-31-7c.cl:207
> 207         const int gid = get_global_id(0);

i can't break point here
What is the reason for this?
