### ISSUE TITLE
AMD GPU support

### ISSUE THREAD

**Issue by CaiusTSM** [pocl/pocl#927]
Hello, I went through some previous issues regarding AMD support, and i'm not sure, but is this a blocker on AMD's part? Will pocl ever have AMD GPU support? I would like to distribute an application leveraging OpenCL (on the GPU), right now pocl seems to be the closest thing to making that a reality. When searching for answers on how to distribute an OpenCL application I more or less got the answer of "you don't". Maybe i'm missing something here.

**Comment by pjaaskel** [comment]
Hi, there used to be some support for AMD Kaveri and Carrizo APUs through the HSA, but it has now bitrotted. I do not know of anyone working on AMD GPU support but I do not see technical obstacles there, someone just has to do it. This is a community project thus I cannot predict what contributions will desire to do with it in the future. I can answer only from my research group's perspective: We currently have no such project ongoing or being planned.
