### ISSUE TITLE
standard printf in basic

### ISSUE THREAD

**Issue by harishch4** [pocl/pocl#928]
Is there a way to use standard libc's print instead of PoCL printf implementation in CPU devices like basic and pthread?

**Comment by franz** [comment]
Hi,

Sorry for late reply.

PoCL (with basic/pthread) devices currently has two implementations of OpenCL printf, one (the default) uses device-side code with `snprintf` and writes into in-memory buffer, the other way uses purely device-side code (without snprintf) and the same in-memory buffer. The in-memory buffer is written to STDOUT after each workgroup iteration is run.

There is a minimalist implementation that just uses printf, but it's only for TCE device. The problem with using libc's printf is that it's insufficient - it can't handle OpenCL vector arguments. What are you trying to achieve?

**Comment by harishch4** [comment]
My understanding of CPU devices is where the device code runs on host CPU( has OS environment). If so can't just use the libc's printf?

**Comment by Oblomov** [comment]
As @franz mentioned, `printf` in OpenCL C and in C99 accept different formatting specifiers (e.g. for vector types) so no, it's not possible to map them directly.

**Comment by harishch4** [comment]
Thanks for the clarification @franz @Oblomov
