### ISSUE TITLE
Ubuntu 18.04 LTS + LLVM 12 (binary distribution for 16.04) fails

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#941]
The binary distribution for LLVM 12 is only available for 16.04 and 20.04, so I assumed [16.04 ](https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz )should work also for 18.04 (might not be true).

It, however, fails at Cmake time with at least two issues:

- Lack of libLLVM-12.so. It seems to be not included in the distribution.
- Clang++ cannot compile C++ codes required for the vecmathlib (again issue with llvm::DisableABIBreakingChecks and also some other symbols, perhaps a mangling issue)?

**Comment by franz** [comment]
For ubuntu, binary packages are available here: https://apt.llvm.org/ for 18.04 and newer, and they work (have been using them). 

> so I assumed 16.04 should work also for 18.04 (might not be true).

I'm fairly certain i've had issues before with LLVM tarballs not working on other OS releases. Something to do with libstdc++ changes, don't remember exactly what.
