### ISSUE TITLE
Error trying to build pocl on zedboard host in petalinux

### ISSUE THREAD

**Issue by stzogas** [pocl/pocl#943]
Hi! I get the following error when i run in petainux the command cmake -DOCS_AVAILABLE=0 -DENABLE_ACCEL_DEVICE=1 -DENABLE_HOST_CPU_DEVICES=0 ..
in build directory of pocl-master
-- The C compiler identification is GNU 9.2.0

-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_WARN_INCOMPATIBLE_POINTER_TYPES
-- Performing Test HAVE_WARN_INCOMPATIBLE_POINTER_TYPES - Success
-- Setting build type to 'Debug' as none was specified.
-- Pocl source Git commit: dec40b5f7dbe0b625e07aa7d02f0d68a3f367ad9
-- Pocl source Git branch: * master
-- Pocl source Git describe: master-0-gdec40b5f
-- Host CPU cores: 2
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'hwloc'
--   No package 'hwloc' found
CMake Warning at CMakeLists.txt:386 (message):
  hwloc package not found

CMake Warning at CMakeLists.txt:435 (message):
  Unable to detect cacheline size - assuming 64byte cacheline, override with
  -DHOST_CPU_CACHELINE_SIZE=<number> (Note: this is merely used for
  optimization, at worst pocl will be slightly slower)

-- Looking for fork
-- Looking for fork - found
-- Looking for fsync
-- Looking for fsync - found
-- Looking for sleep
-- Looking for sleep - found
-- Looking for getrlimit
-- Looking for getrlimit - found
-- Looking for utime
-- Looking for utime - found
-- Looking for futimens
-- Looking for futimens - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for fdatasync
-- Looking for fdatasync - found
-- Looking for mkdtemp
-- Looking for mkdtemp - found
-- Looking for mkstemps
-- Looking for mkstemps - found
-- Looking for vfork
-- Looking for vfork - found
-- Looking for mkostemps
-- Looking for mkostemps - found
-- Looking for dladdr
-- Looking for dladdr - found
-- Relocation not available
-- libdl found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'lttng-ust>=2.7'
--   No package 'lttng-ust' found
-- Checking for module 'ocl-icd>=1.3'
--   No package 'ocl-icd' found
-- ocl-icd not found -> trying fallback ICD implementations
-- Checking for module 'OpenCL>=1.2'
--   No package 'OpenCL' found
-- No ICD loader of any kind found (or its OpenCL version is <1.2)
-- Using an ICD loader : 0
-- Run tests with ICD: 0
-- OpenCL.h not found, installing our headers
-- Failed to find tcecc or tce-config, disabling TCE
-- TCE support : 0
-- Building the following device drivers:  accel
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
CMake Error at lib/CL/CMakeLists.txt:53 (list):
  list sub-command INSERT requires at least three arguments.

-- CPACK_DEBIAN_LIB_PACKAGE_BREAKS
-- CPACK_DEBIAN_LIB_PACKAGE_DEPENDS
-- CPACK_DEBIAN_LIB_PACKAGE_NAME
-- CPACK_DEBIAN_LIB_PACKAGE_RECOMMENDS
-- CPACK_DEBIAN_LIB_PACKAGE_REPLACES
-- OPENCL_LIBS: Threads::Threads;OpenCL;
-- OPENCL_CFLAGS: 
-- POCLU LINK OPTS: poclu;Threads::Threads;OpenCL;-lm
-- CPACK_DEBIAN_LIB_PACKAGE_BREAKS
-- CPACK_DEBIAN_LIB_PACKAGE_DEPENDS
-- CPACK_DEBIAN_LIB_PACKAGE_NAME
-- CPACK_DEBIAN_LIB_PACKAGE_RECOMMENDS
-- CPACK_DEBIAN_LIB_PACKAGE_REPLACES
-- CPACK_DEBIAN_POCLCC_PACKAGE_DEPENDS
-- CPACK_DEBIAN_POCLCC_PACKAGE_NAME
--  
-- *********************** SUMMARY ***************************
--  
-- ******* Directories:
--  
-- CMAKE_INSTALL_PREFIX: /usr/local
-- POCL_INSTALL_CMAKE_CONFIG_DIR: /usr/local/lib/pocl
-- POCL_INSTALL_ICD_VENDORDIR: /usr/local/etc/OpenCL/vendors
-- POCL_INSTALL_OPENCL_HEADER_DIR: /usr/local/include/CL
-- POCL_INSTALL_PKGCONFIG_DIR: /usr/local/lib/pkgconfig
-- POCL_INSTALL_PRIVATE_DATADIR: /usr/local/share/pocl
-- POCL_INSTALL_PRIVATE_HEADER_DIR: /usr/local/share/pocl/include
-- POCL_INSTALL_PRIVATE_LIBDIR: /usr/local/lib/pocl
-- POCL_INSTALL_PUBLIC_BINDIR: /usr/local/bin
-- POCL_INSTALL_PUBLIC_HEADER_DIR: /usr/local/include
-- POCL_INSTALL_PUBLIC_LIBDIR: /usr/local/lib
--  
--  
-- ******* Various Flags:
--  
-- CL_DISABLE_HALF: 
-- HAVE_CLOCK_GETTIME: 1
-- HAVE_GLEW: 
-- HAVE_LTTNG_UST: 0
-- HOST_AS_FLAGS:  -mfloat-abi=soft 
-- HOST_CLANG_FLAGS:  -mfloat-abi=soft 
-- HOST_LD_FLAGS: -shared 
-- HOST_LLC_FLAGS: -relocation-model=pic -mtriple= -float-abi=soft 
-- 
-- LIB_API_VERSION: 2
-- LIB_BUILD_VERSION: 2.7.0
-- ICD_LD_FLAGS: -Wl,-Bsymbolic
-- EXTRA_KERNEL_FLAGS: 
-- EXTRA_KERNEL_CXX_FLAGS: 
-- EXTRA_KERNEL_CL_FLAGS: 
-- EXTRA_KERNEL_C_FLAGS: 
-- final KERNEL_CXX_FLAGS: -xc++ -std=c++11 -fno-stack-protector -fPIC 
-- final KERNEL_CL_FLAGS: -xcl -fno-stack-protector -fPIC 
-- final KERNEL_C_FLAGS: -xc -std=c11 -D__CBUILD__ -fno-math-errno -fno-stack-protector -fPIC 
-- MAX_EXTENDED_ALIGNMENT: 128
-- OCL_KERNEL_TARGET: 
-- OCL_KERNEL_TARGET_CPU: 
-- HOST_DEVICE_ADDRESS_BITS: 32
-- 
-- ******* Enabled features:
--  
-- DEVELOPER_MODE: OFF
-- ENABLE_CONFORMANCE: ON
-- ENABLE_FP64: ON
-- ENABLE_ICD: 0
-- ENABLE_TCE: 0
-- ENABLE_TCEMC: 0
-- ENABLE_HSA: OFF
-- ENABLE_CUDA: OFF
-- ENABLE_ASAN (address sanitizer): OFF
-- ENABLE_LSAN (leak sanitizer): OFF
-- ENABLE_TSAN (thread sanitizer): OFF
-- ENABLE_UBSAN (UB sanitizer): OFF
-- ENABLE_POCL_FLOAT_CONVERSION: OFF
-- ENABLE_RELOCATION: OFF
-- ENABLE_SLEEF: ON
-- ENABLE_SPIR: OFF
-- ENABLE_SPIRV: OFF
-- ENABLE_POCL_BUILDING: ON
-- INSTALL_OPENCL_HEADERS (Install our headers): 1
-- OCL_DRIVERS (Drivers built):  accel
-- OCL_TARGETS (Targets built): 
-- OCS_AVAILABLE: 0
-- POCL_ICD_ABSOLUTE_PATH: ON
-- POCL_ASSERTS_BUILD: 1
-- TESTS_USE_ICD: 0
-- Available testsuites: AMD;AMDSDK2.9;AMDSDK3.0;ASL;arrayfire;clBLAS;CLBlast;clFFT;conformance;w
-- Enabled testsuites:           +-----------------------------+
-- Disabled testsuites: AMD;AMDSD|                             |BLAS;CLBlast;clFFT;conformance;Cw
-- Testsuites are built from git |  Cannot open /dev/ttyACM0!  |
-- Kernel caching: ON            |                             |
-- Kernel library CPU variants: n+-----------------------------+
-- Kernel library distro build: 0
-- Use pocl custom memory allocator: OFF
-- L1d cacheline size: 64
-- Configuring incomplete, errors occurred!
See also "/home/pocl/build/CMakeFiles/CMakeOutput.log".
See also "/home/pocl/build/CMakeFiles/CMakeError.log".

ANy ideas please?

**Comment by franz** [comment]
Can you try with this patch: https://github.com/pocl/pocl/commit/2390f6d34f3f419b0c91afb432ab1c210f1c447e

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision.

**Comment by stzogas** [comment]
Hi to all
 it is all ok I finally managed to build it on Arm by disabling 'hwloc' package...
