### ISSUE TITLE
CUDA PTX target codegen exceeds max constant space on Jetson AGX Xavier (Volta 512-core)

### ISSUE THREAD

**Issue by blu** [pocl/pocl#944]
Hi,

Compiling a mid-sized OCL kernel here on a Jetson AGX Xavier I got a `CUDA ERROR INVALID PTX: a PTX JIT compilation failed` error from `cuModuleLoad` call.

After refactoring the `cuModuleLoad` invocation into a `cuModuleLoadDataEx` and checking the JIT error log, I got:

`too much global constant data (0x10018 bytes, 0x10000 max)`

Indeed, the llvm had generated 65536 bytes of `_constant_memory_region_`, followed by my 24 bytes of auto constants.

I had to patch PoCL's `fixConstantMemArgs` as follows (cumulative patch with `cuModuleLoadDataEx` changes) to get the kernel to compile:

```patch
diff --git a/lib/CL/devices/cuda/pocl-cuda.c b/lib/CL/devices/cuda/pocl-cuda.c
index 766bb1b6..dc51c426 100644
--- a/lib/CL/devices/cuda/pocl-cuda.c
+++ b/lib/CL/devices/cuda/pocl-cuda.c
@@ -42,6 +42,11 @@

 #include <cuda.h>

+#include <sys/types.h>
+#include <sys/stat.h>
+#include <unistd.h>
+#include <fcntl.h>
+
 typedef struct pocl_cuda_device_data_s
 {
   CUdevice device;
@@ -851,12 +856,42 @@ load_or_generate_kernel (cl_kernel kernel, cl_device_id device,
         POCL_ABORT ("pocl-cuda: failed to generate PTX\n");
     }

+  struct stat st;
+  stat(ptx_filename, &st);
+
+  const int fd = open(ptx_filename, O_RDONLY);
+  assert(fd != -1);
+
+  char *buffer = (char *)malloc(st.st_size + 1);
+  const ssize_t r = read(fd, buffer, st.st_size);
+  assert(r == st.st_size);
+
+  buffer[r] = '\0';
+  close(fd);
+
   /* Load PTX module */
   /* TODO: When can we unload the module? */
   CUmodule module;
+#if 0
   result = cuModuleLoad (&module, ptx_filename);
   CUDA_CHECK (result, "cuModuleLoad");

+#else
+  const size_t log_size = 1 << 11;
+  char *log = (char*)malloc(log_size);
+
+  CUjit_option opt[] = { CU_JIT_ERROR_LOG_BUFFER, CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES };
+  void* val[] = { log, (uintptr_t)log_size };
+  result = cuModuleLoadDataEx(&module, buffer, sizeof(opt) / sizeof(opt[0]), opt, val);
+
+  fprintf(stderr, "log:\n%s\n", log);
+  CUDA_CHECK (result, "cuModuleLoadDataEx");
+
+  free(log);
+
+#endif
+  free(buffer);
+
   /* Get kernel function */
   CUfunction function;
   result = cuModuleGetFunction (&function, module, kernel->name);
diff --git a/lib/CL/devices/cuda/pocl-ptx-gen.cc b/lib/CL/devices/cuda/pocl-ptx-gen.cc
index f8b416ab..9fb89176 100644
--- a/lib/CL/devices/cuda/pocl-ptx-gen.cc
+++ b/lib/CL/devices/cuda/pocl-ptx-gen.cc
@@ -751,7 +751,7 @@ void fixConstantMemArgs(llvm::Module *Module, const char *KernelName) {
   // TODO: Does allocating the maximum amount have a penalty?
   llvm::Type *ByteArrayType =
       llvm::ArrayType::get(llvm::Type::getInt8Ty(Module->getContext()),
-                           65536 - TotalAutoConstantSize);
+                           65536 - 16384 - TotalAutoConstantSize);
   llvm::GlobalVariable *ConstantMemBase = new llvm::GlobalVariable(
       *Module, ByteArrayType, false, llvm::GlobalValue::InternalLinkage,
       llvm::Constant::getNullValue(ByteArrayType), "_constant_memory_region_",
```

Issue manifests in `release_1_6` and `release_1_8` as well.

In all cases `llvm-8` was used.

**Comment by blu** [comment]
Issue reproduces with `llvm-9` as well.

**Comment by Oblomov** [comment]
Sorry for the question barrage, but:
* What's so special about 16384? Does it work with more/less?
* Do you get the same issue on other CUDA architectures? If you don't have more for testing, do you have a minimal repro? (I can try testing on a variety of archs and LLVM combos).

It would be also useful to understand why. Isn't the point of subtracting `TotalAutoConstantSize` avoiding precisely the situation you ended up in?

**Comment by blu** [comment]
Yep, `TotalAutoConstantSize` clearly fails its purpose here, but I didn't investigate how and why. I just wanted to see this one kernel up and running as part of new hw evaluation; that kernel was a variation of an older kernel where I didn't have the issue on the predecessor hw and pre-1.6 PoCL.

There's nothing special about 16384 -- just 16K I deemed I could safely subtract from the `_constant_memory_region_` without consequences. For this particular kernel I could've subtracted as little as 24 bytes.

I haven't tried this kernel with PoCL and other CUDA hw as it's normally the Jetson lineup that doesn't have OCL in their factory stack, and where I use PoCL with PTX. I can try it on other machines as well. But I'd rather investigate what causes `TotalAutoConstantSize` to malfunction on this setup.

**Comment by Oblomov** [comment]
I agree that debugging the `TotalAutoConstantSize` issue is crucial here. So I would guess printing the actual address space of the supposed constants and their size would be what needs to be done? (to see if it gets incremented correctly).

(Also: I don't know enough about how LLVM describes things, but does the size computation as done around line 745 work with arrays?)

**Comment by blu** [comment]
I think I know what the problem is, but I don't know yet how to solve it.

The crux of the issue is that `fixConstantMemArgs` gets called *before* all auto constants have been introduced, particularly before `linkLibDevice` has been called to link the CUDA libdevice bitcode, which is where the 24 bytes of auto constants originate from.

Here's what a `fixConstantMemArgs` instrumented to print all considered-for-evaluation global vars does when called **before** `linkLibDevice` (columns read: index, address_space_code, initializer_size, `TotalAutoConstantSize` accumulated); last two lines are the log and result from `cuModuleLoadDataEx`:

```
fixConstantMemArgs: 741
0: 0, 0, 0
1: 0, 0, 0
ptxas error   : File uses too much global constant data (0x10018 bytes, 0x10000 max)
CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed
```

And here is how it looks when called **after** `linkLibDevice`

```
fixConstantMemArgs: 741
0: 0, 0, 0
1: 0, 0, 0
2: 1, 11, 0
3: 4, 24, 24

CUDA_ERROR_NOT_FOUND: named symbol not found
```

In the second case the 24 bytes have appeared in the constant address space (code `4`), and `TotalAutoConstantSize` has been adjusted, but another problem occurs later on during JIT compilation -- some symbol is missing. Here's what the PTX global declarations looks in the two cases from above:

```asm
.extern .global .align 4 .u32 _global_offset_x;
.extern .global .align 4 .u32 _global_offset_y;
.const .align 1 .b8 _constant_memory_region_[65536];
.global .align 1 .b8 $str[11] = {95, 95, 67, 85, 68, 65, 95, 70, 84, 90, 0};
.const .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};
```

```asm
.extern .global .align 4 .u32 _global_offset_x;
.extern .global .align 4 .u32 _global_offset_y;
.global .align 1 .b8 $str[11] = {95, 95, 67, 85, 68, 65, 95, 70, 84, 90, 0};
.const .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};     
.const .align 1 .b8 _constant_memory_region_[65512];
```
Note the properly-sized `_constant_memory_region_` in the second case.

For posterity, here's the patch producing the above (with reordered `fixConstantMemArgs` and `linkLibDevice`, so its the second case from above):

```patch
diff --git a/lib/CL/devices/cuda/pocl-cuda.c b/lib/CL/devices/cuda/pocl-cuda.c
index 766bb1b6..5220e883 100644
--- a/lib/CL/devices/cuda/pocl-cuda.c
+++ b/lib/CL/devices/cuda/pocl-cuda.c
@@ -42,6 +42,11 @@

 #include <cuda.h>

+#include <sys/types.h>
+#include <sys/stat.h>
+#include <unistd.h>
+#include <fcntl.h>
+
 typedef struct pocl_cuda_device_data_s
 {
   CUdevice device;
@@ -854,9 +859,36 @@ load_or_generate_kernel (cl_kernel kernel, cl_device_id device,
   /* Load PTX module */
   /* TODO: When can we unload the module? */
   CUmodule module;
+
+#if 0
   result = cuModuleLoad (&module, ptx_filename);
   CUDA_CHECK (result, "cuModuleLoad");

+#else
+  struct stat st;
+  stat(ptx_filename, &st);
+
+  const int fd = open(ptx_filename, O_RDONLY);
+  assert(fd != -1);
+
+  const size_t log_size = 1 << 12;
+  char *buffer = (char *)malloc(st.st_size + 1 + log_size);
+  const ssize_t r = read(fd, buffer, st.st_size);
+  assert(r == st.st_size);
+
+  buffer[r] = '\0';
+  close(fd);
+
+  CUjit_option opt[] = { CU_JIT_ERROR_LOG_BUFFER, CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES };
+  void* val[] = { buffer + r + 1, (void *)(uintptr_t)log_size };
+  result = cuModuleLoadDataEx(&module, buffer, sizeof(opt) / sizeof(opt[0]), opt, val);
+
+  fprintf(stderr, "%s\n", buffer + r + 1);
+  CUDA_CHECK (result, "cuModuleLoadDataEx");
+
+  free(buffer);
+
+#endif
   /* Get kernel function */
   CUfunction function;
   result = cuModuleGetFunction (&function, module, kernel->name);
diff --git a/lib/CL/devices/cuda/pocl-ptx-gen.cc b/lib/CL/devices/cuda/pocl-ptx-gen.cc
index f8b416ab..9e474410 100644
--- a/lib/CL/devices/cuda/pocl-ptx-gen.cc
+++ b/lib/CL/devices/cuda/pocl-ptx-gen.cc
@@ -86,12 +86,12 @@ int pocl_ptx_gen(const char *BitcodeFilename, const char *PTXFilename,

   // Apply transforms to prepare for lowering to PTX.
   fixPrintF(Module->get());
-  fixConstantMemArgs(Module->get(), KernelName);
   fixLocalMemArgs(Module->get(), KernelName);
   handleGetWorkDim(Module->get(), KernelName);
   addKernelAnnotations(Module->get(), KernelName);
   mapLibDeviceCalls(Module->get());
   linkLibDevice(Module->get(), KernelName, LibDevicePath);
+  fixConstantMemArgs(Module->get(), KernelName);
   if (pocl_get_bool_option("POCL_CUDA_DUMP_NVVM", 0)) {
     std::string ModuleString;
     llvm::raw_string_ostream ModuleStringStream(ModuleString);
@@ -738,13 +738,19 @@ void convertPtrArgsToOffsets(llvm::Module *Module, const char *KernelName,
 // CUDA doesn't allow constant pointer arguments, so we have to convert them to
 // offsets and manually add them to a global variable base pointer.
 void fixConstantMemArgs(llvm::Module *Module, const char *KernelName) {
+  fprintf(stderr, "%s: %d\n", __FUNCTION__, __LINE__);

   // Calculate total size of automatic constant allocations.
-  size_t TotalAutoConstantSize = 0;
+  size_t TotalAutoConstantSize = 0, i = 0;
   for (auto &GlobalVar : Module->globals()) {
     if (GlobalVar.getType()->getPointerAddressSpace() == 4)
       TotalAutoConstantSize += Module->getDataLayout().getTypeAllocSize(
           GlobalVar.getInitializer()->getType());
+    fprintf(stderr, "%lu: %d, %lu, %lu\n",
+      i++,
+      GlobalVar.getType()->getPointerAddressSpace(),
+      GlobalVar.hasInitializer() ? Module->getDataLayout().getTypeAllocSize(GlobalVar.getInitializer()->getType()) : 0,
+      TotalAutoConstantSize);
   }

   // Create global variable for constant memory allocations.
```

**Comment by Oblomov** [comment]
Oh, that's an interesting chicken-and-egg problem. Yes, the CUDA internal library includes some constant stuff that is used by trig functions (not sure if only when using fastmath or in general, but it's likely going to be included regardless anyway), so they should be considered in the reservation, but their size isn't known programmatically until after linking, at which point it's too late to do the transformation.

The easy way out is the one you presented in the beginning: just reserve a certain amount that might come from linking the CUDA library (of course it doesn't need to be 16KiB, since we know the amount is small and it's unlikely to get much larger, so you can probably go with something like 64 or 128 bytes if we want to be safe).

OTOH, I've actually been pondering about the need to do this kind of transformation this way. Pinging @jrprice price since he's the maintainer of this code.

So, my issue with the way this is done currently is that CUDA devices has several (11, IIRC) banks of constant memory: the first bank is conventionally used for statically-allocated constant data (i.e. module-wide global constants), whereas the other 10 banks can be used for dynamic allocations, in 64KB chunks each. So an alternative solution might be to declare the constant memory arg to be in banks 1 to 10 rather than in the default bank. This would allow usage of the full 64KiB for each constant memory argument. The big question here is: is it possible to tell LLVM to specify a different const bank?

**Comment by blu** [comment]
It does seem like a chicken-n-egg problem indeed. One thing that puzzles me is that missing-symbol error when `fixConstantMemArgs` comes last -- I can't figure out what that symbol is, and `cuModuleLoadDataEx` does not seem to report it either. From what I can tell the generated PTX code is not missing anything along the CUDA library routines -- in my case sinf, cosf and sqrtf. The apparent difference in the PTX's is that in the original `fixConstantMemArgs`-first case the lib fns have what appears to be forward-declarations at the start of the PTX module, while their definitions come after the user kernel. In the `fixConstantMemArgs`-last case, the forward declarations are omitted altogether, and the fn definitions precede the user kernel. Clearly I need to extract further logs from `libnvidia-ptxjitcompiler`.

**Comment by blu** [comment]
Ok, I got the problem with the reordered case with some help from friends -- it was an overlook on my end all along. The reported `CUDA_ERROR_NOT_FOUND` is actually *not* from `cuModuleLoadDataEx` JIT compilation, but from the subsequent `cuModuleGetFunction`. While in both cases the user kernel is present in the PTX module, in the original case it's declared as a kernel:
```asm
.visible .entry monokernel(
```
but in the reordered case it's declared as a function
```asm
.visible .func monokernel(
```
So what might cause the demotion of `monokernel` from user kernel to a regular function?

**Comment by Oblomov** [comment]
The problem happens because `convertPtrArgsToOffsets` (called by `fixConstantMemArgs`) re-creates the function, and apparently doesn't copy over the kernel annotation. You can check if moving the call to `addKernelAnnotations` to after the call to `fixConstantMemArgs`.

Even if this fixes the issue, though, I still think that a proper fix would be to move the constant arguments to the non-default constant memory bank.

**Comment by blu** [comment]
Keeping `addKernelAnnotations` invocation after the `fix*Args` bunch does fix the `CUDA_ERROR_NOT_FOUND`, but introduces warnings
```
ptxas warning : Unresolved extern variable '_global_offset_x' in whole program compilation, ignoring extern qualifier
ptxas warning : Unresolved extern variable '_global_offset_y' in whole program compilation, ignoring extern qualifier
```
and leaves a dangling `_shared_memory_region_` which is not used at all by this kernel.

The above do not seem critical and the compiled kernel works as expected. This is all FTR, as I don't have the capacity to tell which is the best approach in this particular aspect of PoCL/PTX. Thank you for the hints, @Oblomov, I'll leave it to @jrprice and you from here.

If there's interest I can prepare a pull request with the modifications for reporting PTX JIT error log as seen above, not that it's much of a change.

**Comment by Oblomov** [comment]
I'm sure that a PR that introduced improved output in case of warnings/errors will be appreciated, although I suspect the feature might be better hidden behind some `POCL_DEBUG` value (e.g. `ptx`).  @pjaaskel or someone else among the core developers might have more information on the preferred way to handle this within pocl.

**Comment by pjaaskel** [comment]
That warning could be fixed with an LLVM pass that cleans up unused magic variables. In the default CPU LLVM pass run they get cleaned up as a side effect when we generate the WG functions, which are not needed for CUDA. Global dead code elimination could do it after marking the variables static. Anyhow, I'd just try to suppress that warning since it's harmless and CUDA likely just ignores them.
