### ISSUE TITLE
[Regression 1.6->1.7] CL1.1 atomic operations with CUDA lead to linker error

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#955]
Running [this script](https://gist.github.com/inducer/a2064316b8890356a03596fdd35f21e5) with 2359701 (`release_1_7`) and 
```
VERSION: OpenCL 2.0 pocl 1.7, Release, LLVM 12.0.1, RELOC, SPIR, SLEEF, CUDA, POCL_DEBUG
```
against an Nvidia device (Titan V, driver 460.73.01, CUDA 11.2.162) gives this error:
```
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'TITAN V' on 'Portable Computing Language' at 0x1d79f58>:

Error(s) while linking: 
Cannot find symbol _Z14_cl_atomic_addPU3AS1Vii in kernel library
```
This works OK with 9b8e620 (`release_1_6`) and LLVM 11.0.1 on an otherwise unmodified setup.

**Comment by isuruf** [comment]
b3e616e2b81689755f7f310dc48191d3208317fb is the culprit. Even though this rename affects C and CL files, the LLVM IR files in https://github.com/pocl/pocl/tree/fdb536e19a8bd9f2cbf7af43258c72b06b1e3b58/lib/kernel/cuda were not fixed.

**Comment by isuruf** [comment]
PR at #963
