### ISSUE TITLE
Build POCL 1.7 on OSX

### ISSUE THREAD

**Issue by rgioiosa78** [pocl/pocl#958]
Good morning everyone and thank you for your work on POCL!

We are working on a dynamic runtime and programming model for extremely heterogeneous systems in HPC (MCL - https://minos-computing.github.io) and heavily rely on POCL for many devices (indeed we have an internal fork with OpenCL and POCL extensions).

For OSX we've been using the default Apple OpenCL installation so far but that is going away, so we're considering suggesting our users to install POCL on OSX instead of relying on other software that seat above Metal. However, we're encountering various issues with the building process:

1. Looks like the LLVM installation provided from Apple (11.0) and MacPorts (11.0) do not have all the features required. This is well explained in the POCL documentation.
2. using a custom built LLVM 12.0 we can make quite a some progress. A few things to notice it that clang requires including `-I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include` otherwise the clang compiler can't find the system `stdlib.h`. We pass this option with `EXTRA_HOST_CLANG_FLAGS`.

It looks like the POCL building process still relies on the system OpenCL framework:

```
[ 70%] Linking C executable poclcc
cd /Users/gioi152/workspace/builds/pocl-1.7/bin && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/poclcc.dir/link.txt --verbose=1
/Users/gioi152/workspace/bin/clang -O3 -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/poclcc.dir/poclcc.c.o CMakeFiles/poclcc.dir/__/lib/poclu/misc.c.o -o poclcc  -framework OpenCL
Undefined symbols for architecture x86_64:
  "_clCreateProgramWithIL", referenced from:
      _poclu_load_program_multidev in misc.c.o
ld: symbol(s) not found for architecture x86_64
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

The parameter `-framework OpenCL` is generally invoked to link against the Apple OpenCL implementation, which only supports OpenCL 1.1 (and, for some devices even just 1.0), thus the library doesn't provide `clCreateProgramWithIL' (which is another reason why we would like to use POCL instead of the native Apple OpenCL library version).

It looks like there isn't much updated documentation on building POCL on OSX and we couldn't locate the old README.OSX. Is there still support for POCL on OSX and will there be support moving forward? Ideally, it would be great if POCL builds with the default Apple compiler from Xcode but we understand that might not be possible....

Thanks for your help!

Roberto

Fore reference, we're testing this on OSX 10.14.6, here are some additional information:

Custom built LLVM 12
```
clang version 12.0.0 (https://github.com/llvm/llvm-project.git d28af7c654d8db0b68c175db5ce212d74fb5e9bc)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
```

Apple LLVM
```
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

MacPorts LLVM
```
clang version 11.1.0
Target: x86_64-apple-darwin18.7.0
Thread model: posix
```

**Comment by isuruf** [comment]
@rgioiosa78, yes, pocl 1.7 is supported on OSX. (There are 3 tests failing on 1.7 due to an error in the tests, but not pocl itself)
I only test the variant with ` -D ENABLE_ICD=on` and I use the OpenCL ICD loader from https://github.com/KhronosGroup/OpenCL-ICD-Loader. LLVM 11.1.0 works perfectly fine for me.

If you want a pre-built pocl installation, you can use conda package manager for macOS-x86_64 or macOS-arm64 (or even linux)
```
curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
bash Mambaforge-$(uname)-$(uname -m).sh
```
After that restart the shell and do,
```
conda install pocl
```

**Comment by pjaaskel** [comment]
@rgioiosa78 MCL looks interesting! Is it (going to be) open sourced?

**Comment by franz** [comment]
> Ideally, it would be great if POCL builds with the default Apple compiler from Xcode 

The Apple compiler is Clang with some extra features ? The main issue is probably that pocl has LLVM passes, which have `#ifdef LLVM_VERSION ... #else` code to compile with various upstream LLVM versions. If the Apple clang doesn't define the proper clang version macros it would be a problem. Also pocl needs to link to full versions of libClang and libLLVM.

> Is there still support for POCL on OSX and will there be support moving forward?

There used to be support, we had a Travis CI setup with some OS X configurations, but i think hasn't been updated for newer LLVM versions for a while, and none of the main developers uses Mac as their main machine. But in principle it shouldn't be too hard.

**Comment by franz** [comment]
> Ideally, it would be great if POCL builds with the default Apple compiler from Xcode 

AFAIK The Apple compiler is Clang with some extra features ? The main issue is probably that pocl has LLVM passes, which have `#ifdef LLVM_VERSION ... #else` code to compile with various upstream LLVM versions. If the Apple clang doesn't define the version macros with the same meaning (e.g. it would define Clang version to be 11 but the actual compiler is from a different commit than upstream LLVM 11 release branch), it could be a problem. Also pocl needs to link to full versions of libClang and libLLVM (that means libclang-cpp in newer LLVM versions).

> Is there still support for POCL on OSX and will there be support moving forward?

There used to be support, we had a Travis CI setup with some OS X configurations, but i think hasn't been updated for newer LLVM versions for a while, and none of the main developers uses Mac as their main machine. It would be helpful if someone updated this. But in principle OS X support should be relatively easy, there isn't that much OS-specific code in PoCL, mostly an issue of people stepping up to do the work.

**Comment by rgioiosa78** [comment]
> @rgioiosa78 MCL looks interesting! Is it (going to be) open sourced?

Yes, indeed, we're trying to sort out a good way for user to install MCL on OSX, write some decent documentation, and then we'll populate the repository. I'll keep you posted.

**Comment by rgioiosa78** [comment]
> @rgioiosa78, yes, pocl 1.7 is supported on OSX. (There are 3 tests failing on 1.7 due to an error in the tests, but not pocl itself)
> I only test the variant with ` -D ENABLE_ICD=on` and I use the OpenCL ICD loader from https://github.com/KhronosGroup/OpenCL-ICD-Loader. LLVM 11.1.0 works perfectly fine for me.
> 

Thanks for the info! could you post your cmake configuration command? Also, which OSX version have you tested?

**Comment by isuruf** [comment]
It's at https://github.com/conda-forge/pocl-feedstock/blob/master/recipe/build.sh

**Comment by isuruf** [comment]
I've checked 10.9, 10.15, 11.0

**Comment by rgioiosa78** [comment]
I was able to use POCL, both compiling from source and using the binary from condo! Thank you very much for your help!

I'm now try to see if I can use the AMD GPU on the Mac.... but that's a different issue :)
