### ISSUE TITLE
Quotes in the compiler options are being ignored

### ISSUE THREAD

**Issue by jsteube** [pocl/pocl#962]
I've tested this with latest POCL 1.7, but it occurs with older POCL versions, too.

Some users have space characters in their user name or installation folder of my application. My application puts the path to the applications' OpenCL include folder in quotes. This work well with all OpenCL runtimes (ROCm, AMD legacy, Intel OneAPI, NVIDIA OpenCL, Apple OpenCL) except POCL.

Example compiler options string:

```
-D KERNEL_STATIC -I OpenCL -I "/root/space test/hashcat/OpenCL" -D LOCAL_MEM_TYPE=2 -D VENDOR_ID=64
```

Received error string:

```
clCompileProgram(): CL_INVALID_COMPILER_OPTIONS

Invalid build option: test/hashcat/OpenCL"
```

Wild guess: There's a function somewhere in POCL which splits the string naively only with space, but ignores if strings put in quotes.

**Comment by LionNatsu** [comment]
FYI: https://www.gnu.org/software/libc/manual/html_node/Argp.html

`error_t argp_parse (const struct argp *argp, int argc, char **argv, unsigned flags, int *arg_index, void *input)`

**Comment by matrix** [comment]
Hi @pjaaskel, any update on this issue? do you need help?

Thanks!

**Comment by pjaaskel** [comment]
Hi @matrix, yes helping hands are appreciated. Please fix and send a pull request. Since our group's work is not affected by this issue, we work on more urgent issues within the team.

**Comment by matrix** [comment]
Hi @pjaaskel, I finished the patch :) Thanks

**Comment by pjaaskel** [comment]
@matrix merged in, thanks. @jsteube can you test with the HEAD and close if it works?

**Comment by matrix** [comment]
> @matrix merged in, thanks. @jsteube can you test with the HEAD and close if it works?

you can close, I did the test for him

**Comment by pjaaskel** [comment]
Thanks!
