### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [pocl/pocl#964]
I'm trying to package pocl for the gentoo overlay guru but the majority of the tests fails with:
`Failed  Error regular expression found in output. Regex=[FAIL]`

Logs:
https://800073.bugs.gentoo.org/attachment.cgi?id=721122
https://800073.bugs.gentoo.org/attachment.cgi?id=721125
https://bugs.gentoo.org/show_bug.cgi?id=800073

**Comment by isuruf** [comment]
Looks like `ENABLE_POCL_BUILDING` is turned off which is turned on by default.
I don't think tests work with this option turned off.

**Comment by Alessandro-Barbieri** [comment]
I`ve added that option but 126 tests still fails for me

**Comment by franz** [comment]
You can get more useful log if you run at least one test with `POCL_DEBUG=all` like this:

```
POCL_DEBUG=all ctest -V -R kernel/test_shuffle_char
```
