### ISSUE TITLE
Enable cl_khr_subgroups in POCL

### ISSUE THREAD

**Issue by kakulo** [pocl/pocl#970]
Hi, I was trying to enable cl_khr_subgroups in POCL by changing the include/CL/cl2.hpp file, but could not find it in the Device Extensions after installation. Could you please let me know the correct way to enable the cl_khr_subgroups support in POCL? Thank you very much :P

**Comment by pjaaskel** [comment]
Hi. I don't think any of the upstream devices support the subgroups at this moment. Thus, the correct way to enable it would be to send a pull request that implements it in one.
