### ISSUE TITLE
pocl reports "variables in the local address space can only be declared in the outermost scope of a kernel function"

### ISSUE THREAD

**Issue by pdhahn** [pocl/pocl#978]
I have just started using pocl for an implementation of OpenCL on CPU. I use the NVidia OpenCL 1.2 implementation on GPU.

In many of my kernsls, I have OpenCL variables declared local that are not in the kernel outermost scope. Consequently, when the kernel is built, I get this error message:

`error: ... : variables in the local address space can only be declared in the outermost scope of a kernel function`

where the ellipses "..." after `error:` lists a temporary file name (differs from run to run).

Indeed, when I move the variable declarations to the required location in outermost scope, the build works.

However, I have not seen this problem until now using other OpenCL implementations. To resolve it will mean a lot of relations of the local variable definitions in my kernels (lots of kernels!).

Did I not configure pocl right when I built it from github source?

**Comment by pjaaskel** [comment]
https://www.khronos.org/registry/OpenCL/specs/opencl-1.2.pdf 6.5.2 specifically disallows this case. Lifting that standard restriction might require kernel compiler updates, unless already implemented in upstream LLVM. I'm surprised other SDKs allow that without errors (do they even produce a warning?). Maybe this is something to ask Khronos' OpenCL group to fix in their conformance suite instead? Anyhow, pull requests are welcome to add such a feature to PoCL. I think it could work as a vendor-specific clBuildProgram() switch.
