### ISSUE TITLE
Pocl cross compile Question

### ISSUE THREAD

**Issue by hsung607** [pocl/pocl#983]
Hi, I working on integrating POCL on Petalinux ( Zilinx) these days.

FWI, petalinux is ARM architecture system. ( zync board)
 
so I just see information on POCL official site

==============================
Cross-compile pocl
It’s now possible to cross-compile POCL on x86-64 to run on ARM/MIPS/etc, There is a ToolchainExample.cmake file; copy it under a different name, then follow the instructions in the file.
=============================

and also I checked “ToolchainExample.cmake file”

but, I cannot understand some points.

As you can see on ToolchainExample.cmake file, 

# 2) On your board, install libltdl, ocl-icd and libhwloc + their development headers
# 3) copy the entire root filesystem of the board somewhere on your host,
#    then set CMAKE_FIND_ROOT_PATH below to this path

Is it means that I have to install onboard directly?

Why I questions about this,

AFAIK, there two petalinux systems. 

One way to run only executable files (compiled example files)  on petalinux (system without linux command)

Another way is you can compile directly on petalinux (a system that can use the linux command).

As your guide to using pocl-cross compile arm, it looks like that this can work on 2nd way. Is that right what I understand? 

If this is right, I have to reinstall petalinux which can use Linux command.
I'd like to know exactly where the POCL compilation is worked on the host pc or on the device (petinux) in this case.

and I want to know a more specific cross_compile information guide about this one.

I already read “ToolchainExample.cmake” but, I do not understand…

thank you!

**Comment by panyan928** [comment]
I have same problem. Did you solve it? Please.

**Comment by franz** [comment]
> it looks like that this can work on 2nd way. Is that right what I understand?

Yes, that is correct. PoCL doesn't support  running on "bare metal" (without Linux OS). 

I can copypaste here a Dockerfile + toolchain file that was used for cross-compile testing. This is a build **without** LLVM. `RPI4_ROOT.tar.xz` file contains the root filesystem of the board (raspberry 4).

Dockerfile:

```
FROM amd64/ubuntu:20.04

LABEL vendor=pocl distro=Ubuntu version=1.0

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt upgrade -y
RUN apt install -y build-essential cmake git pkg-config make ninja-build zlib1g zlib1g-dev python3-dev libpython3-dev python3-pip
RUN apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu cpp-aarch64-linux-gnu binutils-aarch64-linux-gnu

ENV PATH_TO_ARM_ROOT=/home/RPI4_ROOT
ENV CROSS=/home/cross.cmake

# cross-compiling for pocl
COPY cross.cmake RPI4_ROOT.tar.xz /home/
RUN cd /home ; tar xJf /home/RPI4_ROOT.tar.xz

RUN cd /home ; git clone https://github.com/pocl/pocl.git
RUN cd /home/pocl ; mkdir build
RUN cd /home/pocl/build && cmake -DHOST_DEVICE_BUILD_HASH=1234 -DENABLE_LLVM=0 \
         -DCMAKE_TOOLCHAIN_FILE=/home/cross.cmake \
         -DLLC_TRIPLE=aarch64-unknown-linux-gnu \
         -DLLC_HOST_CPU=cortex-a72 \
         /home/pocl && make -j4
```

cross.cmake:

```
SET(CMAKE_SYSTEM_NAME Linux)

# specify the cross compiler
SET(CMAKE_C_COMPILER   /usr/bin/aarch64-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/aarch64-linux-gnu-g++)


SET(CMAKE_SYSROOT /home/RPI4_ROOT)
SET(CMAKE_FIND_ROOT_PATH /home/RPI4_ROOT)
SET(CMAKE_LIBRARY_PATH /home/RPI4_ROOT/usr/lib/aarch64-linux-gnu)

# search for programs in the build host directories
# but for libraries and headers only in the target directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

```

**Comment by bojle** [comment]
Why do we need the copy of rootfs of target board?

**Comment by franz** [comment]
because libpocl needs to be linked to the target environment's libraries (which ones, depends on your build configuration).
